### ISSUE TITLE
page wiki serveur osm-fr

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#10]
nettoyer la page wiki pour
- archiver les serveurs eol
- rajouter les os pour se faire une idée de ce qu'il faudrait mettre à jour
- localisation du serveur rendu fr (de mémoire a disparu de la page)

**Comment by cquest** [comment]
osm13 mis à jour

**Comment by MaelREBOUX** [comment]
Est-ce que je peux modifier le wiki car il est indiqué ça :

![screenshot140](https://user-images.githubusercontent.com/6370443/39181956-89692fc8-47bb-11e8-8c4d-71ba10e3676d.png)

?

Or osm202 c'est le tuileur "langues minoritaires".

**Comment by Marc-marc-marc** [comment]
je signalais dans #14 que le serveur de tuile bzh ne s'appelle apparemment pas osm202 mais bzh202 d'après les infos que tu as posté de son hostname
J'ai fais hier quelques clarifications à ce sujet sur le wiki mais n'hésites pas à compléter si tu le souhaites

**Comment by MaelREBOUX** [comment]
Ok : désolé : un quiproquo qui traîne depuis le début.
C'est bien bzh202.osm25   

Donc c'est plus conforme à ce que j'en savais : sur une la machine osm25 avec proxmox.
Du coup faut faire un sous-tableau dans cette ligne ? Avec une ligne pour la vm rendu "fr" et une ligne pour le rendu "br" ?

![image](https://user-images.githubusercontent.com/6370443/39186074-91354cf6-47c9-11e8-8a1e-6f8ee0223b89.png)

**Comment by MaelREBOUX** [comment]
Je pense que l'on peut fermer ce ticket car https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France est à jour.

**Comment by Cyrille37** [comment]
Je ferme ce vieux ticket. Si besoin en créer un nouveau
