### ISSUE TITLE
rendu limite admin ko sur tile

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#100]
sur https://tile.openstreetmap.fr/ la surcouche limite admin fr est ko

**Comment by jocelynj** [comment]
https://layers.openstreetmap.fr/ marche correctement, lui.

**Comment by cquest** [comment]
Semble corrigé, pas de problème visible sur tile (couche Route500 qui inclut les limites admin d'Admin-Express, etc).

Je ferme
