### ISSUE TITLE
api overpass : Erreur avec 'area' et maj pour fonctionalité 'nwr'

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/infrastructure#101]
Hello,

j'ai souvent des erreurs en utilisant l'API Overpass d'OSM-FR.

Par exemple:
la [requête suivante](http:////overpass.openstreetmap.fr/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A350%5D%3Barea%5B%22wikidata%22%3D%22Q142%22%5D%2D%3E%2Efrance%3B%28way%5B%22amenity%22%3D%22fast%5Ffood%22%5D%5B%22brand%3Awikidata%22%3D%22Q839466%22%5D%28area%2Efrance%29%3B%29%3Bout%20meta%3B%0A) me renvoie actuellement:
```
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: runtime error: The dispatcher (i.e. the database management system) is turned off. 
```

Je pense aussi qu'on ne doit pas utiliser la dernière version, car la syntaxe `nwr` (pour ne pas répéter les trois types d'objets) ne fonctionne pas. La [requête suivante](http:////overpass.openstreetmap.fr/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A350%5D%3Barea%5B%22wikidata%22%3D%22Q142%22%5D%2D%3E%2Efrance%3B%28nwr%5B%22amenity%22%3D%22fast%5Ffood%22%5D%5B%22brand%3Awikidata%22%3D%22Q839466%22%5D%28area%2Efrance%29%3B%29%3Bout%20meta%3B%0A) renvoie:
```
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: line 1: parse error: Unknown type "nwr"

Error: line 1: static error: For the attribute "type" of the element "query" the only allowed values are "node", "way", "relation" or "area". 
```

Les deux exemples de requêtes sont ok avec l'api `overpass-api.de/api` à la place de la nôtre.

**Comment by Marc-marc-marc** [comment]
> la [requête suivante](http:////overpass.openstreetmap.fr/api/interpreter?data=%5Bout%3Axml%5D%5Btimeout%3A350%5D%3Barea%5B%22wikidata%22%3D%22Q142%22%5D%2D%3E%2Efrance%3B%28way%5B%22amenity%22%3D%22fast%5Ffood%22%5D%5B%22brand%3Awikidata%22%3D%22Q839466%22%5D%28area%2Efrance%29%3B%29%3Bout%20meta%3B%0A) me renvoie actuellement:
> ```
> Error: runtime error: The dispatcher (i.e. the database management system) is turned off. 
> ```

La construction des "index" des aires termine en timeout, problème causé par le fait qu'overpass prod tourne sur un disque mécanique à cause d'une erreur lors de la création de la vm). j'autre vm overpass a été améliorée, je dois vérifier si tout est en ordre pour basculer la prod. je vais regarder s'il est possible d'augmenter le timeout en attendant.

> on ne doit pas utiliser la dernière version, car la syntaxe `nwr` (pour ne pas répéter les trois types d'objets) ne fonctionne pas.

c'est exact. parce que nos patch n'ont pas été repris dans l'upstream,il faut donc les réadapter légèrement pour la "nouvelle" version. je m'en occuperai après le point précédent.

**Comment by jocelynj** [comment]
@Marc-marc-marc : Est-ce que ce ticket est toujours d'actualité ?

**Comment by naomap** [comment]
Le serveur //overpass.openstreetmap.fr/api/ n'utilise toujours pas la version 0.7.55. C'est bien dommage car cette version ajoute plein d'éléments de syntaxe intéressants. Je répondrais donc bien oui à la question de @jocelynj :-)

**Comment by Marc-marc-marc** [comment]
suite dans https://github.com/osm-fr/infrastructure/issues/19
