### ISSUE TITLE
extract/download : pas à jour selon le timestamp du fichier state.txt

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#102]
le fichier [state.txt pour la France](http://download.openstreetmap.fr/extracts/europe/france.state.txt) renseigne 

> timestamp=2019-03-24T12\:09\:02Z

suggestion : faire une sonde monit pour alerter si le timestamp a + de 36h par ex

**Comment by Marc-marc-marc** [comment]
extrait du crontab d'osmbin
> #2 0 * * * (cd /data/project/osmbin/osm/osc_modif && ./update_pbf_all.sh)

**Comment by jocelynj** [comment]
On Thu, Apr 04, 2019 at 09:45:19AM +0000, Marc-marc-marc wrote:
> extrait du crontab d'osmbin
> > #2 0 * * * (cd /data/project/osmbin/osm/osc_modif && ./update_pbf_all.sh)

Je l'ai commenté volontairement, pour mettre à jour les extracts manuellement à
partir d'un nouveau planet - il nous manquait certaines relations.

Désolé - j'aurais du informer tech@ de la pause de la génération des extracts.

**Comment by Marc-marc-marc** [comment]
à réactiver ou la reconstruction est en cours ? rien vu de spécial sur le serveur

**Comment by jocelynj** [comment]
La mise à jour est réactivée.
