### ISSUE TITLE
Forcer https ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#104]
Bonjour,
sur sotm2019.openstreetmap.fr, ne peut-on pas forcer sur le https ?
je ne sais pas comment on peut "forcer" sur le https mais je crois que c'est une bonne pratique non ?
à fermer si cela n'a pas de sens :)

**Comment by joker234** [comment]
Peut-on aussi forcer HTTPS pour umap.openstreetmap.fr, surtout si les mots de passe sont affectés?

**Comment by vinber** [comment]
Petit up juste pour savoir si c'est ou pas une bonne pratique ? et ensuite on verra pour la mise en oeuvre :)

**Comment by Marc-marc-marc** [comment]
oui c'est une bonne pratique qui devrait être générale sur toute l'infra
cela peux se faire un http redirect dans la config de la vm ou dans la config du cluster

**Comment by jocelynj** [comment]
Je ne suis pas tellement fan de forcer https pour tout ce qui est affichage d'information, sans login, comme sotm2019, le site de l'asso, ou encore les tuiles (rien que pour pouvoir cacher dans un proxy).

Pour umap, ça a sûrement plus de sens - à voir avec @yohanboniface ce qu'il en pense.

**Comment by Marc-marc-marc** [comment]
rien n'interdit à un proxy de mettre en cache du contenu consulté en https (c'est ce que fait le cdn osm.org).
l'avantage de l'https aujourd'hui est triple : permet d'ensuite activer http/2, pris en compte par le référencement d'au moins un moteur de recherche, de + en + nécessaire pour l'annexe (ex geolocalisation dans le navigateur)

**Comment by jocelynj** [comment]
Je ferme le ticket, parce que c'est à voir au cas par cas: en tout cas, l'infra permet de forcer https sur certains sites sur les proxy.
