### ISSUE TITLE
Certificat HTTPS des vhost *.openstreetmap.fr du cluster ovh expiré (16 avril 2019)

### ISSUE THREAD

**Issue by yannicka** [osm-fr/infrastructure#105]
Le certificat HTTPS du siteumap.openstreetmap.fr a expiré le mardi 16 avril 2019 à 23:17:23 :

![image](https://user-images.githubusercontent.com/22885898/56274868-e36cdc00-60ff-11e9-8ea9-6012cfb8717a.png)

**Comment by Marc-marc-marc** [comment]
regen force des certificats du cluster ovh
test ok
ticket ouvert pour vérifier pq le fichier signed.crt daté du 21 mars <> certif périmé le 16 avril <> certif valable 3 mois

**Comment by lhirlimann** [comment]
vous avez pas un script (genre dans un nagios pour vérifier les certificats) un truc du genre https://exchange.nagios.org/directory/Plugins/Network-Protocols/HTTP/check_ssl_cert/details ça prévient 21 jours avant.

**Comment by Marc-marc-marc** [comment]
niveau monitoring, il n'y a pour le moment pas grand chose d'opérationnel (munin, monit)
mais ce serrait en effet une bonne chose à mettre en place

**Comment by cquest** [comment]
Etait-ce le certificat qui n'était pas à jour ou nginx qui ne l'avait pas rechargé ?

J'ai constaté qu'un reload nginx ne suffisait pas toujours, et que pour les certificats un restart était préférable.

**Comment by cquest** [comment]
comme le problème se situe un cran au dessus sur les hosts et pas dans la VM umap, je ferme.

**Comment by jfoucry** [comment]
Hello, 
Je suis d'accord sur le redémarrage de nginx.
Certes les problèmes ne sont pas les mêmes au niveau infra, mais Exodus Privacy utilise ce tout petit script :

`#!/bin/bash

mkdir /tmp/letsencrypt-auto
letsencrypt renew --webroot -w /tmp/letsencrypt-auto
service nginx reload
`

**Comment by Cormoran96** [comment]
> niveau monitoring, il n'y a pour le moment pas grand chose d'opérationnel (munin, monit)
> mais ce serrait en effet une bonne chose à mettre en place

Je sais pas ce que vous pensez mais je pense que se serait pas mal de mettre en place un monitoring. Je veux bien prendre en charge le projet

**Comment by vinber** [comment]
@Cormoran96 Merci pour cette proposition, je  suis pour ma part incapable d'orienter sur ces questions? @Marc-marc-marc @cquest 
Il y a aussi d'autres canaux (liste tech et/ou irc) pour faire ta proposition.
Si tu fais cette proposition, c'est que tu es à l'aise avec ces outils je suppose ?

**Comment by Marc-marc-marc** [comment]
@Cormoran96 très bonne idée. pour éviter de refaire la roue depuis 0, tu peux regarder ce que @RoPP avait commencer à faire.
tu voyais cela comment ? un module monit pour commencer, qlq chose de local sur le cluster ou qlq chose centralisé qui teste une série d'url ?

**Comment by jocelynj** [comment]
Vu que la régénération du certificat SSL marche maintenant (celui sur umap date du 25 avril), je vais fermer ce ticket.

Le sujet du monitoring est sur #110.
