### ISSUE TITLE
Mise à jour du PeerTube OSM

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#106]
Bonjour à l'équipe Tech !

Le PeerTube d'OSM est dans une très vieille version (1.0.0 beta 9). Ce serait pas mal de passer en version stable 1.2.1 pour bénéficier des nouveautés :
- francisation
- abonnement aux chaînes (notamment pour le SOTM 2019)
...

Merci :+1:

**Comment by jocelynj** [comment]
C'est mis à jour, merci pour le rappel !

**Comment by bristow** [comment]
Bonjour,

Je me permets de relancer cette issue pour mettre à jour en version 1.3.1. En effet, l’interaction avec Mastodon semble ne pas fonctionner et du coup, mon commentaire n'est pas arrivé sur la vidéo de Nomad Maps :( (https://framapiaf.org/@Bristow_69/102305708509461742)

Merci :)

**Comment by bristow** [comment]
Je relance l'issue pour un passage en 2.0.0, une grosse release :)

https://github.com/Chocobozzz/PeerTube/releases/tag/v2.0.0

Merci !

**Comment by jocelynj** [comment]
Merci pour le rappel - je suis en train de procéder à la mise à jour.

**Comment by jocelynj** [comment]
Mise à jour effectué, sans souci après avoir copié les nouvelles entrées dans la config production.yaml.

Je n'ai pas mis grand chose sur la page https://peertube.openstreetmap.fr/about/instance. Tu aurais une idée de quoi mettre ?

**Comment by bristow** [comment]
Super rapide la mise à jour, merci !

Pas vraiment d'idées, éventuellement (à voir avec le bureau) : 

# Qui sommes-nous
Association Openstreetmap France

# Description
Cette instance est maintenue par des bénévoles de l'association française OpenStreetMap.

# Conditions d'utilisation
Les inscriptions sont closes. Toutefois, si vous avez des vidéos en lien avec OpenStreetMap et que vous souhaitez les partager, merci de nous contacter par le formulaire pour disposer d'un compte sur cette instance PeerTube.

# Informations matérielles
AMHA, inutile de faire afficher cette partie

**Comment by bristow** [comment]
Je relance l'issue pour un passage en 2.4.0, une grosse release avant le live prévu pour bientôt :)

https://github.com/Chocobozzz/PeerTube/releases/tag/v2.4.0

Mais attention, cette instance est en 2.1.1, il y a eu entre temps la 2.2.0 et la 2.3.0.

Merci !

**Comment by frodrigo** [comment]
@bristow c'est clot ici, faut en ouvrir une nouvelle.
