### ISSUE TITLE
osm28: /run sature

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#108]
depuis environ 1 semaine /run augmente constament en taille utilisée jusqu'à être quasi saturation depuis hier

**Comment by Marc-marc-marc** [comment]
fichier /run/pacct_source > 3Go
systemctl restart atoppacct + atop : ok

**Comment by jocelynj** [comment]
C'est du coup un fichier généré par atop ?

On peut l'empêcher de générer ce fichier ?

**Comment by Marc-marc-marc** [comment]
c'est pour l'account des processus, on peux évidement s'en passer si on juge que la fonction n'est pas utile. voir carrément coupé atop et ne le lancer qu'en interactif (cependant parfois c'est bien pratique d'avoir les stats d'atop sur une période passée).
pas sur que cela soie utile de le couper parce qu'il a planté une unique fois
