### ISSUE TITLE
remettre visu sur tile.openstreetmap.fr

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#11]
Visualisation avec Leaflet des couches produites par OSM-FR

**Comment by MaelREBOUX** [comment]
@cquest ça vous intéresserait une version pure OpenLayers 3 ? 

On est parti sur ça pour http://kartenn.openstreetmap.bzh/
https://github.com/osm-bzh/osm-bzh-kartenn/

Vu les fonctionnalités sur tile.openstreetmap.fr, je pense que c'est 100 % compatible.

**Comment by cquest** [comment]
La visu est ok, et j'ai rajouté les nouvelles couches br/oc/eu :)

**Comment by MaelREBOUX** [comment]
Trugarez dit.
