### ISSUE TITLE
certificat osm25 promox autosigné et mauvais hostname

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#112]
Voir si on peux le signer version let's encrypt
ajouter ou remplacer les osm25 par osm25.openstreetmap.fr

**Comment by jocelynj** [comment]
Il y a juste à copier les certificats générés comme décrit ici:
https://pve.proxmox.com/wiki/HTTPS_Certificate_Configuration_(Version_4.x,_5.0_and_5.1)#Install_certificate_chain_and_key

**Comment by cquest** [comment]
Fait, par contre, on ne peut pas faire de lien symbolique, mais juste un cp
Quid des mises à jour... on ajoute un cron ?

**Comment by jocelynj** [comment]
J'ai testé la procédure sur osm26, mais sans succès: l'interface web n'est plus accessible dès que je mets le certificat dans les fichiers pveproxy-ssl.pem/pveproxy-ssl.key, sans message d'erreur sans les logs.

@cquest: tu te souviens de ce que tu avais fait exactement ?

**Comment by cquest** [comment]
le certificat pour osm25.openstreetmap.fr est généré par certbot, pour nginx

Il faut le recopier dans la config de proxmox et relancer le service pour qu'il soit pris en compte

```
cp /etc/letsencrypt/live/osm25.openstreetmap.fr/privkey.pem /etc/pve/nodes/osm25/pveproxy-ssl.key
cp /etc/letsencrypt/live/osm25.openstreetmap.fr/fullchain.pem /etc/pve/nodes/osm25/pveproxy-ssl.pem
systemctl restart pveproxy

```
Ajouté en cron quotidien sur /data/project/letsencrypt/certbot2proxmox.sh

Je propose de fermer.
