### ISSUE TITLE
envisager l'ajout de CAA pour la robustesse de la chaine des certificats ssl

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#113]
https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum

**Comment by jocelynj** [comment]
Intéressant comme fonctionalité. Et ça a l'air super simple à mettre en place.

Il faut bien juste rajouter ça dans le DNS ?
```
. CAA 128 issue "letsencrypt.org"
```

**Comment by Marc-marc-marc** [comment]
oui, avec un ttl ultra faible pour commencer au cas oü on a un certificat d'un autre CA qlq part hors du cluster dont personne ne se souvient

**Comment by jocelynj** [comment]
C'est ajouté sur Gandi:

`openstreetmap.fr.	1800	IN	CAA	0 issue "letsencrypt.org"`
