### ISSUE TITLE
lien pour rapporter un bug ou une suggestion

### ISSUE THREAD

**Issue by althio** [osm-fr/infrastructure#114]
Sur la page [OSM-FR/Groupes_de_travail/Technique](https://wiki.openstreetmap.org/wiki/WikiProject_France/OSM-FR/Groupes_de_travail/Technique#Rapporter_un_bug_ou_une_suggestion_.C3.A0_un_des_outils)
Le texte et le lien qui pointe vers http://trac.openstreetmap.fr/ devrait être remplacé par https://github.com/osm-fr/infrastructure/issues/new ... Vrai ou Faux ?

**Comment by Marc-marc-marc** [comment]
vrai :)

**Comment by althio** [comment]
modifié
et toiletté la page
https://wiki.openstreetmap.org/w/index.php?title=WikiProject_France/OSM-FR/Groupes_de_travail/Technique&diff=1869534&oldid=1783389

**Comment by Marc-marc-marc** [comment]
merci
