### ISSUE TITLE
Africa PBF ko

### ISSUE THREAD

**Issue by althio** [osm-fr/infrastructure#115]
les PBFs africa.osm.pbf ne sont pas mis à jour
http://download.openstreetmap.fr/extracts/africa.state.txt

> #Thu Apr 25 07:41:34 CEST 2019
sequenceNumber=3466636
timestamp=2019-04-25T05\:38\:02Z

**Comment by jocelynj** [comment]
J'ai retélécharge l'extract africa de geofabrik, et on va vérifier que la mise à jour se passe bien dans les jours qui viennent.

**Comment by jocelynj** [comment]
C'est à jour maintenant:
```
#Wed Jul 03 09:40:58 CEST 2019
sequenceNumber=3565918
timestamp=2019-07-03T07\:20\:03Z```
