### ISSUE TITLE
Vietnam pbf 

### ISSUE THREAD

**Issue by thucnc** [osm-fr/infrastructure#117]
May you provide Vietnam osm file because I found some unreliable data (missing osm tags) from another source ? 
Hence it would be great that I can find an alternative.

Thanks.

**Comment by Marc-marc-marc** [comment]
https://download.geofabrik.de/asia/vietnam.html
an additional need not satisfied by this one?

**Comment by jocelynj** [comment]
A way was incorrectly missing a tag oneway=yes on Geofabrik extract. @thucnc already informed Geofabrik team about this, and it seems that the way is now correct on their extract.

So, there is now no need to generate an extract on osm-fr servers.
