### ISSUE TITLE
Live is dead, 502 Bad Gateway

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#118]
Bonjour,
quand on va sur http://live.openstreetmap.fr/, il  a un 502 Bad gateway, nginx/1.10.3
je ne sais pas ce que cela veut dire mais cela ne colle pas avec le live :)

**Comment by Marc-marc-marc** [comment]
cela veux dire :
- nginx sur le cluster ovh fonctionne (c'est lui qui te répond)
- live lui même ne répond pas quand la requête lui est envoyé (c'est le "bad gateway"), la vm était coupé, je l'ai relancée

**Comment by jocelynj** [comment]
@Marc-marc-marc Une idée de pourquoi la VM était coupée ?

**Comment by Marc-marc-marc** [comment]
non je n'ai pas regardé durant le we. vérifications basiques faite à l'instant:
les dernières lignes avant coupure dans /var/log/syslog date du 13 juin 02:24 et concernent 54 kill pour oom dont des composants systèmes.
je laisse ouvert si tu veux investiguer +.
pour ma part celui peux être fermé, en faveur d'un ticket global sur la consommation mémoire
