### ISSUE TITLE
monit trop ancien sur bzh202

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#119]
Bonjour,

Je suis en train de finir (enfin…) la config de monit sur bzh202.
Histoire d'être tranquille avant l'été et les congés.

Mais j'ai un problème que je ne rencontre pas sur debian 8 ou 9 et donc je pense que le monit 1.5.16 qui correspond à la version max sur Xenial (Ubuntu 16.04) me bloque sur une fonctionnalité.

A votre avis est-ce que je peux désinstaller monit et faire une installation depuis les sources sans risque ?
Reformulation : est-ce que ça se compilera bien sur cette 16.04 ? Vu que je suis pas développeur…

https://mmonit.com/wiki/Monit/Installation

https://bitbucket.org/tildeslash/monit/src/master/

Merci d'avance pour un avis éclairé.

**Comment by Marc-marc-marc** [comment]
> monit 1.5.16 qui correspond à la version max sur Xenial (Ubuntu 16.04) me bloque sur une fonctionnalité.

Ubuntu 18.04 a Monit version 5.25.1
je crois que c'est l'occasion de mettre à jour vers 18.04.2 LTS ou 19.04 :)

> est-ce que ça se compilera bien sur cette 16.04 ?

perso je l'ignore, mais tu peux le tester avec ton compte utilisateur sans l'installer pour autant

**Comment by MaelREBOUX** [comment]
> je crois que c'est l'occasion de mettre à jour vers 18.04.2 LTS ou 19.04 :)

Ça ça fait qqs temps que je me pose la question mais je vais :
1. recueillir l'avis de @cquest sur ce sujet. Dans l'esprit d'être synchro avec le tuileur principal.
2. je testerai dans ma VM clone avant

Hier j'en ai profité pour installer tous les patches de sécurité via `unattended-upgrades --verbose`

> mais pour ma part en tant que sysadmin, c'est ce que j'évite à tout prix

Pareil mais ça vaut le coup amha pcq ça ne bougera plus de version pour monit sur cette distribution. Je vais tester dans ma VM clone (vu que je me suis souvenu après que j'en avais une…)

**Comment by MaelREBOUX** [comment]
Fait dans ma VM de test.

```bash
sudo -s

apt-get remove monit

mkdir /data/tmp/monit
cd /data/tmp/monit
wget https://bitbucket.org/tildeslash/monit/downloads/monit-5.25.3.tar.gz
tar zxvf monit-5.25.3.tar.gz
cd monit-5.25.3
./configure

# erreur 1
configure: error: PAM enabled but headers or library not found, install the PAM development support or run configure --without-pam
# erreur 2
checking for SSL include directory... Not found
Couldn't find your SSL header files.
Use --with-ssl-incl-dir option to fix this problem or disable
the SSL support with --without-ssl


# donc
./configure --without-pam --without-ssl

Monit Build Information:

                Architecture: LINUX
              Compiler flags: -Wno-address -Wno-pointer-sign -g -O2 -Wall -Wunused -Wno-unused-label -funsigned-char -D_GNU_SOURCE -std=c99 -D _REENTRANT
                Linker flags: -lz -lpthread -lcrypt -lresolv -lnsl 
           pid file location: /run
           Install directory: /usr/local

+------------------------------------------------------------+
| License:                                                   |
| This is Open Source Software and use is subject to the GNU |
| AFFERO GENERAL PUBLIC LICENSE version 3, available in this |
| distribution in the file COPYING.                          |
|                                                            |
| By continuing this installation process, you are bound by  |
| the terms of this license agreement. If you do not agree   |
| with the terms of this license, you must abort the         |
| installation process at this point.                        |
+------------------------------------------------------------+
| Monit has been configured with the following options:      |
|                                                            |
|   Compression:                                  ENABLED    |
|   PAM support:                                  DISABLED   |
|   SSL support:                                  DISABLED   |
|   Large files support:                          ENABLED    |
|   IPv6 support:                                 ENABLED    |
|   Optimized:                                    DISABLED   |
|   Profiling:                                    DISABLED   |
+------------------------------------------------------------+

# pour finir
make && make install

monit --version
This is Monit version 5.25.3
Built without ssl, with ipv6, with compression, without pam and with large files
Copyright (C) 2001-2019 Tildeslash Ltd. All Rights Reserved.
```

# on crée un fichier de config
nano /etc/monitrc
chmod 0700 /etc/monitrc

mkdir /etc/monit
mkdir /etc/monit/conf.d
mkdir /etc/monit/conf-enabled

# pour que ça marche…
mkdir /var/lib/monit
monit
/etc/monitrc:295: Include failed -- No such file or directory '/etc/monit/conf.d/*'
/etc/monitrc:296: Include failed -- No such file or directory '/etc/monit/conf-enabled/*'
 New Monit id: 8a5b873bef8294c9445f2288fff9e3b5
 Stored in '/var/lib/monit/id'
Starting Monit 5.25.3 daemon with http interface at [*]:2812
```

J'arrive bien à voir le monitoring de la taille de /data/ 

![Capture d’écran 2019-06-30 à 11 17 36](https://user-images.githubusercontent.com/6370443/60394683-bccc1800-9b28-11e9-8491-619d2319e65d.png)

Cool. Je vais donc appliquer sur le serveur.

**Comment by MaelREBOUX** [comment]
Installation sur bzh202…

YES !  \o/

![Capture d’écran 2019-06-30 à 20 29 50](https://user-images.githubusercontent.com/6370443/60400564-e7908d80-9b75-11e9-81e0-cdf9c7f531d4.png)

Plus qu'à configurer le script à exécuter en plus de l'alerte.

**Comment by MaelREBOUX** [comment]
Suite de la configuration à cause de #139 

comment définir monit comme un démon.

```
monit quit

nano /etc/init.d/monit

#DAEMON=/usr/bin/monit
DAEMON=/usr/local/bin/monit

systemctl daemon-reload

# on bouge la config
mv /etc/monitrc /etc/monit/

# on démarre le démon
service monit start
```
