### ISSUE TITLE
bzh202 : cron ne fonctionne pas / pas bien ?

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#120]
Depuis que j'ai configuré le SMTP je reçois des mails pour root à propos des tâches cron.
Et je m'aperçois que des tâches cron ne sont pas appliquées / lancées.

Exemple d'une tâche super basique : 
```
# redémarrage de apache 1x par jour à 5h00
5 5 * * * service apache2 restart
```

Par mail je reçois :
```
subject : Cron <root@bzh202> service apache2 restart
/bin/sh: 1: service: not found
```

Et je vois bien via monit que apache n'est pas relancé comme demandé.

Je n'ai jamais été confronté à une _défaillance_ de cron. Qqn a une idée de l'origine du pb ?
Sachant que ça fonctionnait sans doute il y a encore qqs semaines.

**Comment by Marc-marc-marc** [comment]
soit tu met le path complet genre /usr/sbin/service
soit tu modifie PATH pour inclure ce que tu as besoin
soit tu corriges le problème que tu contournes en redémarant apache aussi souvent :)

**Comment by MaelREBOUX** [comment]
Ce que je comprend pas c'est que ça fait 1 an 1/2 que ça fonctionne et visiblement ça disfonctionne depuis qqs semaines.

C'est pas tant le apache qu'il faut redémarrer que le mysql pour les stats.

Bon cron changer : on verra demain si ça change qqch.

`0 23 * * * /usr/sbin/service mysql restart`

**Comment by jocelynj** [comment]
J'ai eu un souci un peu similaire sur une autre machine, où j'avais oublié de mettre l'user après le temps. Ce format est celui utilisé par /etc/cron.d/:
0 23 * * * <user> <commande>

**Comment by MaelREBOUX** [comment]
Ha ben justement : tous les crons avec un user indiqué ne fonctionnent plus non plus. Ex : 

```
# maj quotidienne des tuiles style osm-br à 03h00 tous les jours
0 3 * * * www-data /data/styles/br/scripts/calculer_tiles_br_13-18.sh

/bin/sh: 1: www-data: not found
```

Tout ça a tourné pendant des mois. Jamais vu ça. Je viens de vérifier dans htop. Apache2 est toujours bien géré par l'utilisateur www-data.

Je met quoi là du coup. Une idée ?

**Comment by MaelREBOUX** [comment]
Par contre : pour le redémarrage de apache et mysql c'est OK maintenant après avoir mis le chemin complet /usr/sbin/service
```
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by jocelynj** [comment]
Normalement, la logique, c'est de mettre le "user" uniquement dans les scripts de /etc/cron*/. Les scripts de `crontab -e` n'ont pas besoin de user.

**Comment by MaelREBOUX** [comment]
Comme ça ne refonctionne toujours pas je vais mettre ce cran dans le crontab de l'utilisateur www-data

**Comment by jocelynj** [comment]
Problème cron résolu a priori.
