### ISSUE TITLE
overpass osm-fr usage limits

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/infrastructure#121]
I know about 

> You are welcome to use that API for any purpose but not for any number of query by day. Not every query consumes the same ressources, but above 1.000 queries per day per "project" you might get banned. (By "project" I mean if you use this API in a smartphone app and you have 10.000 customer querying once per day then you are above the limit) 

https://wiki.openstreetmap.org/wiki/Servers/overpass.openstreetmap.fr

Is it possible to get special permission for greater use in something directly improving OSM, like an OSM editor?

--------

I am asking about StreetComplete ( https://github.com/westnordost/StreetComplete ).

Alternative Overpass servers will be used since the next version for bypassing censorship in Russia. Currently only server operated by Kumi Systems is available as an option, and it would be useful to have more than one alternative.

For that use it will be probably less than 1000/queries day anyway as it is useful only for people in Russia (and other countries with blocked main overpass instance), but I am not sure.

See https://github.com/westnordost/StreetComplete/issues/1389 for more info.

For censorship status (caused by attempts to block Telegram in Russia) see https://isitblockedinrussia.com/?host=http%3A%2F%2Foverpass.openstreetmap.fr%2Fapi%2F (not blocked) and https://isitblockedinrussia.com/?host=https%3A%2F%2Foverpass-api.de%2Fapi%2F (blocked)

Would it be OK to give overpass.openstreetmap.fr as an additional option?

------

Second possible use of overpass osm-fr instance is for initial task scan, what is likely to be causing usage heavier than 1000 calls/day, especially in case of many new users appearing in short time - https://github.com/westnordost/StreetComplete/issues/1457 (but this one is just proposal for feature).

Would it be OK to use overpass.openstreetmap.fr also in this case?

**Comment by Marc-marc-marc** [comment]
on the principle: yes of course, SC can use the osm-fr instance as a fallback
but in practice: if SC were to make a much higher volume than expected, osm-fr could not do nothing if it impacts other services.
does SC plan to inform a &contact in the url? and/or has a recognizable user agent?
Is the list of servers in the application code or retrieved when it is launched?
any idea why osm-ru instance is down ?

**Comment by matkoniecz** [comment]
Thanks for the answer! Hopefully SC will not consume too many resources.

> does SC plan to inform a &contact in the url?

Yes, PR adding osm-fr server to available ones would also add &contact parameter as requested at https://wiki.openstreetmap.org/wiki/Servers/overpass.openstreetmap.fr .

>  and/or has a recognizable user agent?

Yes - set for example at https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/data/OsmModule.java#L71

> Is the list of servers in the application code or retrieved when it is launched?

in the application code

>  any idea why osm-ru instance is down ?

I have no idea

**Comment by matkoniecz** [comment]
BTW, is upgrading overpass version to new version planned in the near future? (if yes then I would be able to wait instead of checking compatibility of syntax of all quests)
