### ISSUE TITLE
Serveur mail pour l'envoi d'email @openstreetmap.fr

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#123]
Le but est de pouvoir envoyer des emails depuis @openstreetmap.fr, de façon à ce que les emails soient acceptés par tout le monde. DKIM/DMARC/SPF parait un minimum.

**Comment by jocelynj** [comment]
La VM osm158 a été configuré avec proxmox mail gateway, et modifiée pour générer des signature DKIM. DMARC et SPF, ainsi que la clé publique DKIM, ont été mis dans le DNS.

Cette VM est sur mail.openstreetmap.fr

**Comment by MaelREBOUX** [comment]
Superbe.

Quelles infos pour pouvoir utiliser le SMTP ?

**Comment by jocelynj** [comment]
> Quelles infos pour pouvoir utiliser le SMTP ?

J'aurais effectivement bien besoin d'un cobaye :)

Quel est ton adresse email en @openstreetmap.fr ?
Je t'y enverrais le mot de passe à utiliser.

Concernant les paramètres de connexion pour une addresse en
toto@openstreetmap.fr, ça devrait être:

 - serveur SMTP = mail.openstreetmap.fr
 - login        = toto@openstreetmap.fr
 - password     = <password>

**Comment by MaelREBOUX** [comment]
> Quel est ton adresse email en @openstreetmap.fr ?

Heu : je n'ai pas de boîte mail avec ce domaine. Comment ça marche pour en avoir une ? C'est lié à l'asso ?

Comme c'est pour le monitoring : je verrais bien osm-bzh@openstreetmap.fr

**Comment by MaelREBOUX** [comment]
@jocelynj : j'ai besoin d'une boîte mail pour la VM stats et le matomo.

**Comment by jocelynj** [comment]
Serveur en place depuis quelques années - je ferme le ticket.
