### ISSUE TITLE
Le serveur de réplication semble planté.

### ISSUE THREAD

**Issue by phiphou** [osm-fr/infrastructure#124]
Bonjour. 

Le serveur de réplication semble planté. [http://download.openstreetmap.fr/replication/europe/france/minute/state.txt](http://download.openstreetmap.fr/replication/europe/france/minute/state.txt) est bloqué au 5 août 20h13, c'est normal ?

**Comment by Marc-marc-marc** [comment]
semble être entrain de se résorber avant même que je regarde http://munin.openstreetmap.fr/osm12.openstreetmap.fr/osm108.openstreetmap.fr/osm_replication_lag_osmbin.html
cause primaire inconnue.
il faudrait vraiement se faire une alerte automatique, genre en cas de lag > 4h, à la fois pour réagir + tôt et pour rechercher les causes récurrentes et inclure des actions automatiques pour certains d'entre eux.

**Comment by Marc-marc-marc** [comment]
depuis hier 18h, nouveau coup de lag (maj en cours non planté). les problèmes de perf sont peut-être du à #125

**Comment by cquest** [comment]
Aucune idée de ce qui bloque, et malheureusement je ne connais vraiment pas ce qui tourne sur ce container (osmbin).

Container relancé, mais pas d'amélioration constatée, il va falloir attendre sur @jocelynj en prenne soin...

**Comment by jocelynj** [comment]
En fait, une grosse relation a été modifiée plusieurs fois - il s'agit d'une relation contenant tous les pays de l'Union Européenne. Le traitement n'est pas optimisé dans ce cas, et chaque génération de diff vérifie si cette relation est dans son poly ou pas.

C'est reparti maintenant:
http://munin.openstreetmap.fr/osm12.openstreetmap.fr/osm108.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by frodrigo** [comment]
Tout le retard n'a pas été rattrapé et c'est reparti à la hausse.

**Comment by jocelynj** [comment]
La relation UE a encore changé sur le dernier diff en cours de traitement:

    <relation id="2668952" version="103" timestamp="2019-08-12T19:45:11Z" uid="3335899" user="GBAB" changeset="73281426">


J'ai commencé à tester des moyens d'accélérer ce genre de relation pour le
futur, en stockant une info pour la relation compléte. Pour le moment, j'ai mis
la liste de tous les nodes, mais ça ralentit le traitement. Peut-être que je
devrais stocker le polygone engloblant, et considérer que si le polygone du
pays est dans ce polygone engloblant, alors on garde la relation.

Ça aurait comme effet de bord de conserver plus de relations que ce qu'on fait
actuellement, et ces relations seront incomplètes.

**Comment by frodrigo** [comment]
J'ai repensé à ça, et il faut mettre les nœuds de la relation dans un r-tree pour accélérer le contrôle.

**Comment by jocelynj** [comment]
On a récupéré le retard: http://munin.openstreetmap.fr/osm12.openstreetmap.fr/osm108.openstreetmap.fr/osm_replication_lag_osmbin.html

Il reste toujours à trouver un moyen d'accélérer ce genre de grosses relations dans le futur.

**Comment by jocelynj** [comment]
J'ai mis un fix temporaire, en dumpant systématiquement dans tous les diffs générés les grosses relations modifiées: https://github.com/jocelynj/osm/commit/f7d3275ffd43d678eb86a1b7726366e31a348ade

Ça ne devrait pas avoir d'impact sur les extracts qui ne devraient pas avoir cette relation, parce que ces extracts n'auront alors aucun node/way/relation associé à cette relation, et ne pourront donc pas la placer sur la carte.
