### ISSUE TITLE
/data/project/osm2pgsql/import-base-osm/render_list.sh multiple et longue durée

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#125]
sur osm105 : 
- plusieurs occurrences du script, au point de saturer les io du raid meca sdc -> il faudrait rajouter un lock pour ne s'exécuter qu'une fois
- la plus veille instance du script tourne depuis le 29 juillet -> il faudrait rajouter un temps maxi avec alerte si on le dépasse pour ne pas subir ce lag sans le réaliser
amélioration à déployer idéalement sur toutes les serveurs de rendus

**Comment by cquest** [comment]
J'ai rajouté un flock

**Comment by jocelynj** [comment]
J'ai commité le flock dans le repo osm2pgsql-import-tools, en changeant le nom du fichier de lock.

Concernant le temps maxi avec alerte, je pense que ça devrait être géré via munin.

**Comment by Marc-marc-marc** [comment]
@cquest
> J'ai rajouté un flock

sur tous les serveurs de rendu ? comment as-tu déployé la modif ? ils étaient tous différents.

@jocelynj 
> Concernant le temps maxi avec alerte, je pense que ça devrait être géré via munin.

solliciter un admin pour juste faire un kill et voir si le problème a disparu, ce n'est pas très utile comme besoin d'intervention humaine par rapport à "réparation automatique+notification"
