### ISSUE TITLE
wms.openstreetmap.fr : problèmes Orthophoto Nancy 2012

### ISSUE THREAD

**Issue by the-knife** [osm-fr/infrastructure#126]
Bonjour,

il semble y avoir un problème avec la couche d'orthophoto GrandNancy 2012.

Les images sont floues (pixellisées) et des messages d'erreurs apparaissent de manière intermittente ("Erreur http 500 lors du chargement des tuiles").

**Comment by cquest** [comment]
Corrigé !

**Comment by grischard** [comment]
C'est re-cassé.
