### ISSUE TITLE
Live is dead :D

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#127]
http://live.openstreetmap.fr/ / On arrive à la page mais rien ne bouge.

**Comment by Marc-marc-marc** [comment]
cron était coupé, je l'ai relancé
monit qui surveille cron était coupé, je l'ai relancé
en passant frontend/fetch-changeset-meta.py utilisait encore http://api.openstreetmap.fr coupé depuis... longtemps... j'ai modifié directement sur le serveur en https://api.openstreetmap.org
vu que le [précédent PR](https://github.com/cstenac/osm-livechanges/pull/22) n'est mergé. j'ai mis un commentaire sur celui-ci pour voir si on peux resynchroniser serveur & dépot
