### ISSUE TITLE
Erreurs HTTP 504 aléatoires

### ISSUE THREAD

**Issue by don-vip** [osm-fr/infrastructure#130]
De temps en temps l'URL https://www.openstreetmap.fr/bdortho/ renvoie un HTTP 504.

On monitore cette URL depuis le Jenkins de JOSM. Dernier exemple en date le job qui a démarré à cette date:
29 sept. 2019 18:57:00

**Comment by jocelynj** [comment]
Est-ce que ça arrive encore ?

Est-ce que tu pourrais donner une date plus récente si possible ?

**Comment by don-vip** [comment]
Visiblement ça ne s'est pas reproduit récemment: https://josm.openstreetmap.de/jenkins/job/JOSM-Imagery-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.imagery/ImageryPreferenceTestIT/testImageryEntryValidity_fr_ign_bdortho_/history/

**Comment by jocelynj** [comment]
Merci, je vais fermer du coup.
