### ISSUE TITLE
fr.osm.social - suivre

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/infrastructure#132]
Impossible de suivre un profil de `fr.osm.social` depuis `pouet.chapril.org`.  
Erreur affichée :

    Malheureusement, il y a eu une erreur en cherchant les détails du compte distant

**Comment by Marc-marc-marc** [comment]
info dans la console : 
`Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »).`

**Comment by Marc-marc-marc** [comment]
@cquest c'est voulu la config dupliquée osm28+osm143 ?
Mastodon ne gère-t-il pas lui-même depuis quelques version le CSP ? il y a de nombreux tickets/commit en ce sens.

**Comment by jocelynj** [comment]
Suite à la mise à jour de mastodon faite par @cquest, est-ce ce souci est toujours là ?

**Comment by deuzeffe** [comment]
Hello,
À partir d'un autre instance que fr.osm.social, désabonnement/réabonnement réussis sans souci à l'instant.
HTH

**Comment by jocelynj** [comment]
Merci !

**Comment by adrienandrem** [comment]
Je crois que je retrouve le problème.
Quelqu'un d'autre ? @deuzeffe ?

**Comment by Marc-marc-marc** [comment]
idem depuis en.osm.town

**Comment by jocelynj** [comment]
fr.osm.social est maintenant désactivé.

**Comment by adrienandrem** [comment]
[fr.osm.social](https://fr.osm.social) est réactivé, il reste impossible de suivre le compte [@osm_fr](https://fr.osm.social/@osm_fr).

Voir https://piaille.fr/@A_d_r_i/109299106772005561
