### ISSUE TITLE
commune manquante dans extrait France

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#133]
fichier http://download.openstreetmap.fr/extracts/merge/france_metro_dom_com_nc.osm.pbf
https://github.com/osm-fr/osm-vs-fantoir/issues/65
https://github.com/osm-fr/bano/issues/159
exemple commune de Torreilles, code INSEE 66212
https://www.openstreetmap.org/relation/74993

**Comment by vdct** [comment]
@jocelynj est-ce qu'on peut considérer ce ticket comme clos ? Les données reconstruites la semaine dernière sont ok, ma question concerne surtout les outils derrière ces données : est-ce que le process que tu as joué avec succès la semaine dernière est commité, pérène ? Il y a des tickets ouverts côté BANO en référence au présent ticket, je ne les fermerai qu'une fois celui-ci fermé :)

**Comment by jocelynj** [comment]
Normalement, ça devrait être bon, même si je ne me rappelle plus du fix exact - je crois que j'ai regénéré l'extract de merge avec les extracts normaux, que j'avais regénéré il y a quelques mois avec la bonne option.

Si il y a de nouveau une commune manquante, on peut ouvrir un nouveau ticket.

**Comment by vdct** [comment]
Merci
Il me semble que tu as changé d'outil (abandon d'osmosis pour osmium ?)

**Comment by jocelynj** [comment]
Oui, sur ce commit: https://github.com/jocelynj/osm/commit/bd2cf44902956e371889a7c6c3117ad44fe03f87
Mais je ne suis pas persuadé à 100% que ça explique tous les soucis.

**Comment by vdct** [comment]
Ok. Piste complémentaire : un souci de tri des objets dans le merge

**Comment by jocelynj** [comment]
Ça me parle, mais je ne retrouve plus si j'avais lancé une commande différente du merge habituel pour générer le pbf.
