### ISSUE TITLE
rendu alsacien manquant  pour compléter les versions en breton , occitan, basque

### ISSUE THREAD

**Issue by DHSTR67** [osm-fr/infrastructure#134]
Afin de faire la promotion de la libération et de la diffusion des toponymes alsaciens par les collectivités locales et les organismes publics en charge du bilinguisme, il est nécessaire de disposer d'un outil de démonstration valorisant et facilement accessible  pour les acteurs publics et le citoyen.
Il faut donc un rendu des toponymes taggés en name:gsw.

**Comment by jocelynj** [comment]
@MaelREBOUX: tu peux gérer la génération du style pour l'alsacien ?

**Comment by MaelREBOUX** [comment]
oui. voir https://github.com/osm-bzh/osmbr-mapstyle/issues/26 également pour le suivi.

**Comment by jocelynj** [comment]
Le rendu alsacien (gsw) est dispo depuis quelque temps sur le serveur de rendu, mais je ne suis pas sûr si on a un site web permettant d'y accéder.
@MaelREBOUX : est-ce que tu aurais un lien pour ces tuiles alsaciennes ?

**Comment by MaelREBOUX** [comment]
"quelque temps" => oui effectivement :D

Le service est accessible via l'url : https://tile.openstreetmap.bzh/gsw/

OSM-BZH n'a pas vocation a fournir un visualiseur. C'est à chaque communauté locale de s'organiser.

**Comment by jocelynj** [comment]
Merci, je ferme le ticket.
