### ISSUE TITLE
Mastodon - Impossible de joindre un média

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/infrastructure#135]
Lorsqu'on tente de joindre un média (image PNG) à un pouet, on obtient l'erreur :

    Oops ! Une erreur inattendue s'est produite

Journal du navigateur :

    Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). 4 utils.js:35:9
    The VAPID public key is not set. You will not be able to receive Web Push Notifications. registerer.js:56:16
    Impossible d’inscrire/mettre à jour un service worker pour la portée « https://fr.osm.social/ » : l’accès au stockage est limité dans ce contexte en raison des paramètres de l’utilisateur ou du mode de navigation privée. runtime.js:11:47
    SecurityError: The operation is insecure. application-93c929e75d0c677aeee2.chunk.js:1
    error { target: img, isTrusted: true, srcElement: img, currentTarget: img, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }    alerts.js:60:12
    Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à blob:https://fr.osm.social/877e0042-3cd2-4ecc-ba14-2824b2ad6889 (« img-src »). resize_image.js:29:4

**Comment by jocelynj** [comment]
Suite à la mise à jour de mastodon faite par @cquest, est-ce que ça plante encore ?

**Comment by deuzeffe** [comment]
@jocelynj voir https://fr.osm.social/@deuz_osm/103385036438110547 si ça répond à ta question ;)

**Comment by jocelynj** [comment]
Super, merci :)
