### ISSUE TITLE
Ortho 2018 hauts de France

### ISSUE THREAD

**Issue by jvanoost** [osm-fr/infrastructure#136]
Bonjour,

l'ortho 2018 hauts de france est disponible ici : https://www.geo2france.fr/ckan/dataset/orthophotographie-des-hauts-de-france-2018-rayonnement-visible
https://www.geo2france.fr/geonetwork/srv/fre/catalog.search#/metadata/b78820de-0104-4369-b4c5-7ff715b1a34e

Bonne journée
Jérôme

**Comment by cquest** [comment]
Elle a été ajoutée sur wms.openstreetmap.fr dans les couches orthohr_2018, orthohr et tous_fr
