### ISSUE TITLE
Transfert de MapContrib sur les serveurs de l'association

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#137]
Aujourd'hui l'hébergement de l'instance mapcontrib.xyz est "dépendant" de @guillaumeamat et moi.

Afin de péréniser l'instance mapcontrib.xyz, je propose de :
- transférer cette instance sur les serveurs de l'association
- transférer le ou les (fr, com, ...) noms de domaines également

Suis-je au bon endroit pour cela ? sachant que le principe avait plus ou moins été validé je crois en CA mais je ne retrouve pas de traces !!!

**Comment by Marc-marc-marc** [comment]
oui tu es au bon endroit pour la partie technique :)
quelle os ?
vous avez un ansible à exécuter ou vous vous chargez de l'install "à la main" ?
quelle caract (cpu/ram(/disque) ? vous avez des stats munin ou autre pour se faire une idée ?
si vous n'avez pas encore de clef ssh sur l'infra, faudra les transmettre

pour la confirmation du ca, je te laisse voir sur la ml sur ca :)

**Comment by GuillaumeAmat** [comment]
Toujours à faire @frodrigo

**Comment by vinber** [comment]
toujours vrai :) d'autant plus maintenant que l'instance est tombée avec Ovh.

Si cela doit être remonté, que cela soit de préférence remonté sur les serveurs de l'association

**Comment by Marc-marc-marc** [comment]
> quelle os ?
> vous avez un ansible à exécuter ou vous vous chargez de l'install "à la main" ?
> quelle caract (cpu/ram(/disque) ? vous avez des stats munin ou autre pour se faire une idée ?
> si vous n'avez pas encore de clef ssh sur l'infra, faudra les transmettre

ces questions techniques sont toujours ouvertes :) difficile d'avancer sans savoir l'os voulu par ex :)

**Comment by frodrigo** [comment]
C'est du docker, ça retreint les choix du host. Coté place je ne sais pas, @vinber essaye de récup les sauvegardes.
Je ne pense pas que ce soit trop gros, vm de 50 Go je pense.
Coté mémoire aucune idée.

**Comment by jocelynj** [comment]
Le docker est obligatoire ?

Parce qu'on ne sait pas faire de backups d'un docker actuellement. Mais si vous n'avez pas besoin de backup, et que ça se remonte facilement, on peut partir sur ça.

**Comment by frodrigo** [comment]
Avec docker, on peut mettre des données dans une volume docker, ou directement sur le fs de la vm, ce n'est pas un problème.

**Comment by GuillaumeAmat** [comment]
> quelle os ?

Effectivement il y a une image Docker prête à l'emploi. C'est ce que j'utilisais et ça serait plus simple de faire la même chose.

> vous avez un ansible à exécuter ou vous vous chargez de l'install "à la main" ?

Pas d'Ansible (ou autre) aujourd'hui, et je n'aurai malheureusement pas le temps de le faire... Si c'est moi qui installe, ça sera à la main.

> quelle caract (cpu/ram(/disque) ? vous avez des stats munin ou autre pour se faire une idée ?

Pas de data non, mais ça demande "pas grand chose". De mémoire ça prenait moins de 2 Go de RAM, pour le disque un 50 Go laisserait une bonne marge. 

> si vous n'avez pas encore de clef ssh sur l'infra, faudra les transmettre

Il faut que j'en renvoie une, dis-moi où @jocelynj 


Et merci pour le coup de main !

**Comment by jocelynj** [comment]
@GuillaumeAmat : envoie moi la clé sur mon email jjaubert@openstreetmap.fr

**Comment by frodrigo** [comment]
Une instance docker tourne sur mapcontrib.vm.openstreetmap.fr port 8080
C'est possible de faire pointer mapcontrib.openstreetmap.fr dessus (temporairement) ?

L'instance tourne mais est inutilisable pour l'instant. On ne peut pas se connecter dessus, je n'ai trouvé comment configurer correctement l'OAuth et il ny' a aucune carte de déjà crée.

https://github.com/mapcontrib/mapcontrib/issues/374

**Comment by frodrigo** [comment]
L'instance est maintenant bien configurer.

**Comment by jocelynj** [comment]
Le site est maintenant accessible sur http://mapcontrib.openstreetmap.fr. Pas de https pour le moment, mais ça arrivera sous peu.

**Comment by vinber** [comment]
vous êtes énormes :D

**Comment by jocelynj** [comment]
https est aussi en place maintenant. On peut fermer le ticket ?

**Comment by frodrigo** [comment]
Ok, merci.

Non, l'idée c'est d'avoir mapcontrib.xyz, avec les ces sauvegardes.

**Comment by vinber** [comment]
oui, attendons de voir ce que peut nous dire @GuillaumeAmat 

pour le nom de domaine, comment cela se passe-t-il ? j'en suis proprio, je transfère à l'asso ? comment les noms de domaines sont gérés d'ailleurs ? (j'ouvre une autre issue ?)

**Comment by Marc-marc-marc** [comment]
avant le transfert, modifie deja www.mapcontrib.xyz en CNAME vers mapcontrib.openstreetmap.fr (je ne me souviens plus si un tranfert entre 2 identifiants gandi conserve toute la config dns mais je l'espère)

**Comment by cquest** [comment]
CNAME ou redirect ?

Comme ce n'est pas la même instance (contenu remis à zéro, non ?), une page avec un lien pour aller sur l'instance OSM-FR me semblerait plus adapté.

**Comment by jocelynj** [comment]
@vinber: pour le DNS, il y a deux questions différentes.
  - pour la configuration technique, tu peux ajouter le groupe "OpenStreetMap France", configuré avec l'email "admin@listes.openstreetmap.fr", avec l'onglet "Partage" sur Gandi.
  - pour la paiement du DNS, je ne sais pas comment on procède par contre, vu que openstreetmap.fr est gracieusement payé par Gandi. On gère ça par facture et remboursement ?

**Comment by cquest** [comment]
Gandi ne facture pas, tout simplement.

**Comment by frodrigo** [comment]
Ne pas faire pointer mapcontrib.xyz.
Je pense que l'on va supprimer le ceontenu par celui de la sauvegarde, non ?

**Comment by vinber** [comment]
oui l'idée cela serait de rajouter la dernière sauvegarde, risque d'avoir perdu des choses mais au moins quelques années de sauvegardées.
Je ne sais pas si @GuillaumeAmat a pu regardé (c'est pas de la pression @GuillaumeAmat pas pressé il n'y a pas non plus des demandes folles au portillon :) )

en fait aujourd'hui il n'y a qu'un seul nom de domaine et c'est openstreetmap.fr, aucun autre nom de domaines n'est la propriété de l'association ?

**Comment by cquest** [comment]
Il y a osm-fr.org utilisé en principe pour les noms courts... u.osm-fr.org = umap.openstreetmap.fr
J'avais aussi enregistré osm.social, utilisé pour le fr.osm.social de mastodon (et pour pas se faire squatter)

**Comment by vinber** [comment]
bon je reprends et j'avoue je ne comprends pas.
Ce que j'aimerai aujourd'hui à minima c'est que lorsque les gens tapent mapcontrib.xyz ils arrivent sur la nouvelle instance (même si elle est vide).
- Et plus tard si on arrive à remonter la sauvegarde, quand ils tapent https://www.mapcontrib.xyz/t/ae8f8d ils arrivent sur leur thème mapcontrib.

les 2 sont-ils compatibles ?



>     * pour la configuration technique, tu peux ajouter le groupe "OpenStreetMap France", configuré avec l'email "[admin@listes.openstreetmap.fr](mailto:admin@listes.openstreetmap.fr)", avec l'onglet "Partage" sur Gandi.

@jocelynj c'est fait à l'instant avec les droits de configuration.



>     * pour la paiement du DNS, je ne sais pas comment on procède par contre, vu que openstreetmap.fr est gracieusement payé par Gandi. On gère ça par facture et remboursement ?

cela va continuer à être ma participation, à voir plus tard car j'avais aussi pris le fr, le com, ... moins important cette question pour l'instant

**Comment by frodrigo** [comment]
> les 2 sont-ils compatibles ?

Je ne sais pas dire si c'est faisable ou pas (facile ou non) d'ensuite fusionner deux instances). En plus c'est dans un base mongodb.

On peut soit remonter une deuxième instance vide pour mapcontrib.xyz ou juste une page d'explication.

**Comment by GuillaumeAmat** [comment]
Ça va être compliqué de fusionner deux instances oui... Je regarde si j'ai de vieilles sauvegardes dimanche et je vous dis ça.

**Comment by Marc-marc-marc** [comment]
> > ```
> > * pour la configuration technique, tu peux ajouter le groupe "OpenStreetMap France", configuré avec l'email "[admin@listes.openstreetmap.fr](mailto:admin@listes.openstreetmap.fr)", avec l'onglet "Partage" sur Gandi.
> > ```
> 
> @jocelynj c'est fait à l'instant avec les droits de configuration.

j'ai validé la proposition d'accès dns du domaine et j'ai modifié `www cname gerard.mapcontrib.xyz.` par `www cname mapcontrib.openstreetmap.fr.`
reste pour cette partie là : 
- [ ]  choisir quel domaine  (ou les 2) doit s'afficher (=faire une redirection de l'un vers l'autre ou accepter les 2)
- [ ] certificat https tant pour mapcontrib.openstreetmap.fr que pour www.mapcontrib.xyz

**Comment by Marc-marc-marc** [comment]
certif https généré (timeout dns résolu en ajoutant des serveurs alternatifs dans /etc/resolv.conf sur osm14)

**Comment by GuillaumeAmat** [comment]
Pour mémoire, je viens d'envoyer mon dernier backup dispo (19 décembre 2019) à @jocelynj @vinber et @frodrigo

**Comment by frodrigo** [comment]
J'ai remonté le backup sur une seconde stack sur la même machine. Quelqu'un peut faire pointer le reverse proxy de mapcontrib.xyz vers le post 8081, svp ?

**Comment by vinber** [comment]
alors moi il y a peu de chances :) mais normalement si cela se gère coté nom de domaine, j'ai transmis les droits pour ces modifs à marc, jocelyn et christian

**Comment by Marc-marc-marc** [comment]
> Quelqu'un peut faire pointer le reverse proxy de mapcontrib.xyz vers le post 8081, svp ?

fait à la main en attendant de voir un peu plus clair sur ce qu'on met comme vversion définitive dans ansible

**Comment by frodrigo** [comment]
Reste à faire:
- [ ] Supprimer ou pas la version mapcontrib.openstreetmap.fr, 3 thèmes ont été cré dessus
- [ ] Dumper et sauver la base
- [ ] Ajouter les crons de maintenance

**Comment by vinber** [comment]
en faisant une recherche sur "e  " j'en vois 6.
1 sans requête
la requête la plus complexe c'est pour restaurant et pizza
le nombre de couches le plus élevé c'est 6 différenes avec des requêtes simples à chaque fois

J'aurai tendance à dire que l'on supprime

**Comment by frodrigo** [comment]
J'ai stopé `mapcontrib.openstreetmap.fr`

Dump journalier de la base dans `/home/fred`, pas sur que ce soit le bon endroit pour faire ça.

**Comment by frodrigo** [comment]
Sauvegarde à mettre dans /data/project/mapcontrib

**Comment by lmagreault** [comment]
Je viens de constater une erreur CORS dans les appels au geocodeur lors de la saisie d'une adresse.

**Comment by frodrigo** [comment]
> Je viens de constater une erreur CORS dans les appels au geocodeur lors de la saisie d'une adresse.

Reported here https://github.com/mapcontrib/mapcontrib/issues/377

**Comment by GuillaumeAmat** [comment]
Corrigé dans MapContrib v1.18 :+1:

**Comment by frodrigo** [comment]
@GuillaumeAmat j'ai fait marche arrière avec 1.18 (docker hub), la page d’accueil ne marche pas.

```
Uncaught 
Object { fileName: "https://www.mapcontrib.xyz/js/commons.bundle.js", lineNumber: 541, name: "Error", message: "An \"el\" undefined must exist in DOM", stack: "" }
​
fileName: "https://www.mapcontrib.xyz/js/commons.bundle.js"
​
lineNumber: 541
​
message: "An \"el\" undefined must exist in DOM"
​
name: "Error"
​
stack: ""
​
<prototype>: Object { urlRoot: "http://marionettejs.com/docs/v2.4.7/", constructor: constructor(message, options), captureStackTrace: captureStackTrace()
, … }
backbone.marionette.js:436
```

**Comment by GuillaumeAmat** [comment]
Damned... Je revert un truc et je publie une nouvelle version dès que possible :/

**Comment by GuillaumeAmat** [comment]
Ok c'est corrigé dans la v1.18.1. Tu peux pull la dernière image Docker @frodrigo

**Comment by frodrigo** [comment]
C'est bon. Merci.
