### ISSUE TITLE
osm25/bzh202 : oom quasi toutes les nuits

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#138]
@MaelREBOUX oom quasi toutes les nuits vers 1h10
te faut-il plus de mémoire ou il y a une conf qui n'est pas bonne dans la maintenance ?

**Comment by MaelREBOUX** [comment]
oom = Out Of Memory j'imagine ?

Ça se voit au bleu qui sature sur ces graphiques ?
http://munin.openstreetmap.fr/osm25.openstreetmap.fr/bzh202.osm25/memory.html

Je remarque que je n'arrive plus à joindre http://monit.openstreetmap.bzh/ poke @jocelynj 

À 1h00 chaque nuit est lancée l'analyse des logs apache par Matomo. Rien n'a changé depuis 1 an 1/2.

**Comment by Marc-marc-marc** [comment]
> oom = Out Of Memory j'imagine ?

oui

> Ça se voit au bleu qui sature sur ces graphiques ?
> http://munin.openstreetmap.fr/osm25.openstreetmap.fr/bzh202.osm25/memory.html

ce qui m'étonne le plus c'est le graphe de la semaine, particulièrement la ligne "active".
tu as plus de 3Go de différence entre avant et après le reboot du 24 décembre au soir.
il semble qu'il y avait quelque chose bloqué en mémoire, au point de manquer de ram pendant la maintenance.
le graphe annuel donne l'impression d'une fuite mémoire, cela a augmenté en continu depuis juillet.  
 
> À 1h00 chaque nuit est lancée l'analyse des logs apache par Matomo. Rien n'a changé depuis 1 an 1/2.

ce n'est pas nécessairement une modif. au vu du graphe c'est peut-être simplement la goute qui fait débordé le vase.
vu le graphe depuis 5 jours, je clos le ticket. on rouvrira si la fuite mémoire réapparait, histoire d'avoir quelque chose à regarder

**Comment by MaelREBOUX** [comment]
> il semble qu'il y avait quelque chose bloqué en mémoire

À part renderd : je vois pas trop quoi. Lui je le redémarre jamais. Apache redémarre tous les jours. Il reste mysql éventuellement.

> vu le graphe depuis 5 jours, je clos le ticket. on rouvrira si la fuite mémoire réapparait, histoire d'avoir quelque chose à regarder

On est d'accord. Merci.
