### ISSUE TITLE
502 Bad Gateway sur http://monit.openstreetmap.bzh/

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#139]
Bonjour @jocelynj 

Je ne sais pas de quand ça date mais il n'y a plus de redirection depuis osm25 vers bzh202 pour le domaine monit.openstreetmap.bzh

Merci de le rétablir.

A+

**Comment by jocelynj** [comment]
Hum, la config de osm25 n'a pas changé. Je vois que ça pointe vers http://10.1.0.202:2812, mais rien n'écoute sur le port 2812 sur bzh202, parce que monit n'est pas démarré.

Par contre, je ne comprends pas pourquoi monit est installé dans /usr/local/bin/monit, et pas via un paquet debian. Tu te souviens de la raison ?

**Comment by MaelREBOUX** [comment]
> Par contre, je ne comprends pas pourquoi monit est installé dans /usr/local/bin/monit, et pas via un paquet debian. Tu te souviens de la raison ?

oui : version paquet 16.12 bcp trop vieille. Donc installation par compilation des sources. Y'a un ticket qui traîne qq part sur ça.

Si le monit n'est pas actif... forcément... Par contre il devrait l'être.
Je regarde ça demain.

**Comment by MaelREBOUX** [comment]
Pour mémoire : https://github.com/osm-fr/infrastructure/issues/119#issuecomment-507021183

En fait : monit ne démarre pas comme un service (systemd ?). Je viens de le lancer avec un simple ’monit’ et c'est lancé.

Donc au reboot : monit n'est pas relancé avec le reste des services.

**Comment by MaelREBOUX** [comment]
J'ai trouvé comment définir monit comme un démon.

```
monit quit

nano /etc/init.d/monit

#DAEMON=/usr/bin/monit
DAEMON=/usr/local/bin/monit

systemctl daemon-reload

# on bouge la config
mv /etc/monitrc /etc/monit/

# on démarre le démon
service monit start
```

Reste à savoir si ça résiste à un reboot.

**Comment by jocelynj** [comment]
Du coup, ça marche maintenant avec une version à jour de monit ?

**Comment by MaelREBOUX** [comment]
Il faut que je teste un reboot encore avant de fermer ce ticket.

**Comment by MaelREBOUX** [comment]
ça résiste au reboot. cool.
