### ISSUE TITLE
configuration pour osm.bzh

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#14]
Bonjour,

J'ai accès à osm202 depuis octobre mais comme je ne suis pas sudo je ne peux pas faire grand chose ;)

ci-dessous ma liste au père-noël (c'est bientôt la période…) :
- [X] compte user 
- [x] compte -> sudousers
- [x] nginx frontal sur osm25 : router *openstreetmap.bzh  -> 10.1.0.202 , http + https
- [x] postgresql : créer rôle osmbr pour USAGE et SELECT
- [x] postgresql : autoriser accès depuis machine osm202
- [x] certificat ssl pour tile.osm.bzh
- [ ] Real IP pour les stats

**Comment by jocelynj** [comment]
Je suis un peu perdu: osm202 est sur osm20 d'après [la page du wiki](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France). Est-ce qu'il s'agirait d'une autre VM ?

@cquest, tu peux confirmer ?

**Comment by MaelREBOUX** [comment]
Bonjour,

Je me permet un petit up.
(et promis je vous fais une carte en basque hyper vite ;) )

**Comment by jocelynj** [comment]
@MaelREBOUX Est-ce que tu peux préciser si la VM qui tu utilises n'est pas plutôt osm131 ?

**Comment by MaelREBOUX** [comment]
cat /etc/hostname  --> bzh202
ifconfig  --> 10.1.0.202

Comment en savoir plus quand on est DANS la VM ?

**Comment by MaelREBOUX** [comment]
suis joignable en DM si nécessaire : https://twitter.com/mael_reboux_ig

**Comment by jocelynj** [comment]
Ok, j'avais mal lu - il s'agit d'une VM sur osm25, mais qui n'est pas sur la page de [wiki](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#VMs). On a apparemment une autre VM pour bzh, appelée osm131.

Comment est-ce que tu te connectes sur la VM 202 ?

Je te mets un accès sudo;

**Comment by MaelREBOUX** [comment]
> Comment est-ce que tu te connectes sur la VM 202 ?

Par rebond depuis osm25.

J'aurais pu commencer par regarder /etc/hosts…… Désolé.   10.1.0.202 bzh202.osm25 bzh202

Je confirme que je suis sudo. Merci @jocelynj 

Maintenant je vais faire pointer un sous-domaine de openstreetmap.bzh vers  88.191.250.205. C'est toi qui gères ça aussi ?

**Comment by jocelynj** [comment]
Plutôt 46.105.110.145 pour le DNS, non ?   Ou un CNAME osm25.openstreetmap.fr. L'ip que tu as donné est celle d'osm13, qui est hébergé ailleurs.

Tu veux quoi comme redirection ?  teol.openstreetmap.bzh ? Et aussi [abc].teol.openstreetmap.bzh pour les tuiles ?

Je peux aussi gérer le certificat letsencrypt pour le https si tu veux.

**Comment by MaelREBOUX** [comment]
A ou CNAME : juste me dire quoi mettre. J'ai fais un ping sur tile.openstreetmap.fr et j'ai mis l'IP que j'ai trouvé.

Va pour le CNAME alors ?

Si tu ne peux pas faire une redirection globale *.openstreetmap.bzh alors il faut prévoir :
- tile.
- teol.  (pour tests sinon laisse tomber)
- api
- stats

Et oui pour le https. @cquest en avait parlé que c'était géré au niveau du frontal.

**Comment by MaelREBOUX** [comment]
Je viens de mettre un CNAME osm25.openstreetmap.fr pour teol.openstreetmap.bzh

**Comment by jocelynj** [comment]
@MaelREBOUX, il faudrait mettre osm25.openstreetmap.fr pour teol, pas 88.191.250.205, vu que ta VM est sur osm25.

**Comment by MaelREBOUX** [comment]
Rhha : modif du début d'après-midi pas enregistrée. Ce coup-ci c'est bon. Propagation dans moins d'une heure.

**Comment by jocelynj** [comment]
Le proxy est à jour, et ça tourne sur http://teol.openstreetmap.bzh/ et https://teol.openstreetmap.bzh/

**Comment by MaelREBOUX** [comment]
Je confirme que teol.osm.bzh arrive bien sur le apache osm25 --> bzh202.osm25 en http et https

Peux-tu d'emblée rajouter les domaines tile.openstreetmap.bzh  api.openstreetmap.bzh et stats.openstreetmap.bzh  STP ?

**Comment by jocelynj** [comment]
Les redirections sont ajoutés - il ne te reste plus qu'à changer les DNS.

**Comment by MaelREBOUX** [comment]
Trugarez / merci.

Je suis en train de mettre en ordre les clés RSA pour SSH. 

Pb : /home/mael/.ssh/authorized_keys  est réservé pour root sur osm25.

Je voulais ajouter la clé depuis mon serveur perso. Ce sera plus simple que je passe par lui pour m'identifier.

Donc : **peux-tu STP ajouter la clé   id_rsa_breizhpovh1.pub  à .ssh/authorized_keys**

**Comment by jocelynj** [comment]
C'est fait: j'ai changé les permissions sur ce fichier, et rajouté les clés demandées.

**Comment by MaelREBOUX** [comment]
OK : c'est mieux en effet. je passe au travers de osm25 mais je dois encore fournir mon mdp sur osm202. Faut que je revoie ça. Merci.

**Comment by jocelynj** [comment]
Tu pourras me prévenir quand les DNS seront à jour, afin que je génère les certificats https ?

**Comment by MaelREBOUX** [comment]
Pour tile. ce sera possible quand j'aurais fini d'installer mon bazar. cf #18 

Je suis en déplacement cette semaine. Je vais essayer d'avancer ça demain. Sinon we prochain. j'ai pas besoin de bcp de temps. Il me reste juste à configurer renderd et apache. Ça devrait pas être très long car je ne fais que dérouler mon tuto d'install qui pour le moment n'est pas pris en défaut.

**Comment by MaelREBOUX** [comment]
accès base réglé à l'instant avec christian

**Comment by MaelREBOUX** [comment]
Je rouvre car j'avais oublié que ce ticket est toujours actifs tant que j'aurais pas basculé le sous-domaine tile.osm.bzh vers le nouveau serveur.

**Comment by MaelREBOUX** [comment]
@cquest : je n'accède plus à la base de données OSM monde.

```
psql -h 10.0.0.25 -d osm -U osmbzh
psql: FATAL:  aucune entrée dans pg_hba.conf pour l'hôte « 10.1.0.202 », utilisateur « osmbzh »,
base de données « osm », SSL actif
FATAL:  aucune entrée dans pg_hba.conf pour l'hôte « 10.1.0.202 », utilisateur « osmbzh »,
base de données « osm », SSL inactif
```

Je m'y suis connecté avant-hier pourtant. Tu peux vérifier STP ?

**Comment by MaelREBOUX** [comment]
Bonjour @jocelynj  je prépare la mise en prod et je me suis aperçu hier que le serveur apache ne recevait les requêtes qu'avec l'IP interne du frontal web (10.0.... 5 de mémoire).

Pourrais-tu reconfigurer le vhost pour que les IP publiques parviennent jusque osm202 ?
En cherchant 2 min ça ressemblerait à ```ngx_http_realip_module```

Merci d'avance.

**Comment by MaelREBOUX** [comment]
Up @jocelynj ?

**Comment by jocelynj** [comment]
Je vais vérifier la configuration de cette machine, mais sur un autre proxy, osm26, on a configuré nginx avec ça:
```
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
```
Du coup, le serveur récupére l'IP sur X-Real-IP, ce qu'on utilise sur forum.openstreetmap.fr

Je regarde le paramètre ngx_http_realip_module.

**Comment by jocelynj** [comment]
Le paramètre en question est à mettre sur le serveur visé par le proxy, d'après http://nginx.org/en/docs/http/ngx_http_realip_module.html

Il doit y avoir un paramètre équivalent sur apache.

**Comment by MaelREBOUX** [comment]
Ok : je vois. Ce doit être pas loin de ça : https://buzut.fr/apache2-recuperer-ip-derriere-reverse-proxy/

Je suis habitué à avoir un tomcat derrière un proxy apache mais là c'est la première fois que j'ai un apache derrière un proxy nginx. Je vais essayer ce soir.
On apprend :D

PS : je pense basculer en prod ce soir ou demain soir = bascule DNS

@Marc-marc-marc je ne demande pas mieux mais j'avoue qu'il me manque un vrai schéma d'architecture logique de l'infra OSM FR pcq c'est super dur de s'y retrouver en tentant de reconstruire par bribes et la page wiki ça a ses limites. Je suis prêt à aider mais difficile sans se caler 2 x 3 h de réunion pour aboutir.

**Comment by MaelREBOUX** [comment]
```bash
a2enmod remoteip
service apache2 restart

# pour vérifier
apachectl -M

nano /etc/apache2/conf-available/remoteip.conf
…
a2enconf remoteip
service apache2 restart
```

Contenu de remoteip.conf
```
#RemoteIPHeader X-Forwarded-For
RemoteIPHeader X-Real-IP

# ici les adresse distantes auxquelles on fait confiance pour présenter une valeur RemoteIPHeader
RemoteIPTrustedProxy 10.0.0.25
```

N'a pas marché : j'ai tjs 10.0.0.25 en IP d'origine dans les logs.
Une idée ?

J'ai trouvé ça aussi : https://gist.github.com/patrocle/43f688e8cfef1a48c66f22825e9e0678

**Comment by MaelREBOUX** [comment]
> Tu pourras me prévenir quand les DNS seront à jour, afin que je génère les certificats https ?

@jocelynj  :  Voilà c'est effectif. C'est bizarre : c'est passé du premier coup pour stats.osm.bzh  et là ça renvoie vers la page par défaut apache Ubuntu. Bizarre.

Faut pas que je laisse ça cassé trop longtemps : ça consulte bcp à cause de la Redadeg qui va bientôt commencer.

**Comment by jocelynj** [comment]
Pour les IPs, tu es sûr qul ne faudrait pas utiliser `RemoteIPHeader X-Forwarded-For` plutôt ?

Quel DNS veux-tu que je configure ?

**Comment by MaelREBOUX** [comment]
sur tile.openstreetmap.bzh
Tout est OK mais ça part en erreur car certificat non valide. A toi de jouer ;)

J'ai aussi essayé RemoteIPHeader X-Forwarded-For mais pareil

**Comment by jocelynj** [comment]
Les certificats https sont créés.

Je vois qu'on a aussi `api.openstreetmap.bzh` sur la config du proxy. Je l'enlève, ou tu comptes l'utiliser ?

**Comment by MaelREBOUX** [comment]
J'ai suivi ça en direct  ;)  Merci @jocelynj  pour ta disponibilité.

Je compte bien que ce sous-domaine serve. Notamment pour des outils de suivi de saisie.
Donc je préfère que tu laisse pour le moment. Merci.

**Comment by MaelREBOUX** [comment]
La suite sur #34 . Il est temps de fermer ce ticket.
