### ISSUE TITLE
osm26 : certificat incomplet pour id-editor

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/infrastructure#141]
Hello,

Le certificat LE sur osm26 contient beaucoup de sous-domaines (cf plus bas) mais pas id-editor. Y a moyen de moyenner ?

Merci d'avance pour la réponse, quelle qu'elle soit.

Non critique
Nom DNS: api-pic4carto.openstreetmap.fr
Nom DNS: api.openstreetmap.fr
Nom DNS: backup.umap.openstreetmap.fr
Nom DNS: bato.openstreetmap.fr
Nom DNS: beta.osmose.openstreetmap.fr
Nom DNS: buildbot2.osmose.openstreetmap.fr
Nom DNS: dev.analyser.openstreetmap.fr
Nom DNS: dev.bano.openstreetmap.fr
Nom DNS: dev.comcommaker.openstreetmap.fr
Nom DNS: dev.forum.openstreetmap.fr
Nom DNS: dev.taginfo.openstreetmap.fr
Nom DNS: dev.tile.openstreetmap.ma
Nom DNS: dev.umap.openstreetmap.fr
Nom DNS: educosm.openstreetmap.fr
Nom DNS: forum.openstreetmap.fr
Nom DNS: fr.osm.social
Nom DNS: josm-dev.openstreetmap.fr
Nom DNS: layers.openstreetmap.fr
Nom DNS: live.openstreetmap.fr
Nom DNS: maposmatic.openstreetmap.fr
Nom DNS: monitor.openstreetmap.fr
Nom DNS: munin.openstreetmap.fr
Nom DNS: next.openstreetmap.fr
Nom DNS: nextcloud.openstreetmap.fr
Nom DNS: opendata.osmose.openstreetmap.fr
Nom DNS: openstreetmap.fr
Nom DNS: osm26.openstreetmap.fr
Nom DNS: osm27.openstreetmap.fr
Nom DNS: osm28.openstreetmap.fr
Nom DNS: osmma.openstreetmap.fr
Nom DNS: osmose.openstreetmap.fr
Nom DNS: overpass.openstreetmap.fr
Nom DNS: peertube.openstreetmap.fr
Nom DNS: petitereine.openstreetmap.fr
Nom DNS: prev.openstreetmap.fr
Nom DNS: sotm2018.openstreetmap.fr
Nom DNS: sotm2019.openstreetmap.fr
Nom DNS: sotm2020.openstreetmap.fr
Nom DNS: taginfo.openstreetmap.fr
Nom DNS: tile.openstreetmap.ma
Nom DNS: umap.openstreetmap.fr
Nom DNS: www.openstreetmap.fr

**Comment by jocelynj** [comment]
@Marc-marc-marc : tu pourrais pusher sur osm-fr/ansible-scripts l'ajout de la VM pour id-editor ?

**Comment by jocelynj** [comment]
Le certificat de id-editor est maintenant généré.
