### ISSUE TITLE
Pb munin sur bzh202

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#143]
Depuis tout début janvier il n'y a plus de graphiques sur 
http://munin.openstreetmap.fr/osm25.openstreetmap.fr/bzh202.osm25/index.html 

poke @Marc-marc-marc ou @jocelynj

**Comment by Marc-marc-marc** [comment]
dans osm127:/var/log/munin/munin-update.log (le master, celui qui collecte les données), il y a : 
2020/01/23 18:15:21 [INFO] node bzh202.osm25 advertised itself as bzh202 instead.
2020/01/23 18:15:21 [WARNING] Config node bzh202.osm25 listed no services for bzh202.osm25, (advertised as bzh202).  Please see http://munin-monitoring.org/wiki/FAQ_no_graphs for further information.

 peut-être qu'une modif été perdue par la maj récente du fichier contenant les hosts

**Comment by Marc-marc-marc** [comment]
ajout de host_name bzh202.osm25 dans bzh202:/etc/munin/munin-node.conf + restart munin-node
effet : 
2020/01/23 19:55:34 [INFO]: Munin-update finished for node osm25.openstreetmap.fr;bzh202.osm25 (14.56 sec)
les graphs sont réapparus, avec un gros trou
je te laisse confirmer que c'est bon et si oui fermer le ticket

**Comment by MaelREBOUX** [comment]
Ca a l'air ok.
