### ISSUE TITLE
Osmose est en 503 Service unavailable

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#144]

**Comment by vinber** [comment]
cela semble revenu mais rien d'affiché en terme de'erreurs

**Comment by cquest** [comment]
Pour info, uptimerobot donne un taux de dispo pour osmose de 94%

**Comment by vinber** [comment]
à priori tout fonctionne parfaitement (j'ai du tomber sur les 6%)
Je ferme :)

**Comment by cquest** [comment]
94% de dispo c'est pas vraiment bon... il y a bien un problème régulier sur le front d'osmose car ça va, ça vient.

**Comment by vinber** [comment]
ah pardon, je pensais que c'était plutôt c'est bon :) je laisse ouvert alors ?

**Comment by jocelynj** [comment]
@frodrigo parlait de souci de lock entre des DELETE des marqueurs utilisant des requêtes un poil compliqué, et l'autovacuum.

J'ai désactivé l'autovacuum pour voir si ça améliore.

**Comment by jocelynj** [comment]
J'ai aussi passé le CT osmose-frontend osm153 sur osm28 de 2 à 4 cpus.

Mais il y a surement un truc à vérifier, parce qu'on continue à plafonner à 100% de cpus

**Comment by frodrigo** [comment]
Non le problème d'autovacuum n'est pas liée au DELETE. Quand c'est bloqué c'est plutôt avec des INSERT, Mais je ne suis pas sur qu'il faille faire un line direct, on fait des INSERT tout le temps.

**Comment by cquest** [comment]
Le load-average monte régulièrement depuis un an... http://munin.openstreetmap.fr/osm28.openstreetmap.fr/osm153.openstreetmap.fr/load.html

On était à 2 et maintenant à 8 (environ).

Il y a effectivement beaucoup de lock sur postgresql. Les INSERT sont faits record par record ou sur des paquets de records ?

**Comment by frodrigo** [comment]
Un par un, depuis peu c'est des upserts.
https://github.com/osm-fr/osmose-frontend/blob/master/tools/update.py#L268-L276

On en fait environ 50 000 000 par jour.

Ça déjà réduit les autovacuum (décembre):
http://munin.openstreetmap.fr/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=osm28.openstreetmap.fr/osm153.openstreetmap.fr/postgres_autovacuum&size_x=800&size_y=400&start_epoch=1546014467&stop_epoch=1580574467

Ça a aussi réduit les écritures disque, mais je ne sais as retrouver bon graphe.

**Comment by cquest** [comment]
Un peu de tuning de postgres ne ferait pas de mal. L'autovacuum récupère une partie des trous dans le data, mais je ne pense pas que ça joue beaucoup ici.

La table markers est l'essentiel de la base et sa mise à jour permanente force à mettre à jour les index (il y en a 8).
Il n'y a que 512Mo alloués en shared_memory, là où PG va en priorité conserver les pages d'index, alors que le container a 10Go d'alloués mais à peine 1 d'utilisé... et sur le host, on a 20Go de RAM de libre.

Je monterai shared_memory à 4Go pour commencer, ensuite voir si work_mem ne mériterai aussi pas plus (actuellement à 6Mo ce qui est peu).
