### ISSUE TITLE
taginfo à mettre à jour pour export vers josm

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#145]
mettre à jour pour inclure ce commit https://github.com/taginfo/taginfo/pull/267
la dernière fois il y avait quelques soucis :) je ne sais pas si le correctif était définitif ou si le problème risque de se reproduire

**Comment by Codain** [comment]
Je ne sais pas si c'est lié mais à ce jour pas moyen de charger des données vers JOSM depuis taginfo FR : JOSM écoute le port 8111 alors que taginfo envoi les données sur le 8112.

Par exemple la page suivante https://taginfo.openstreetmap.fr/tags/maxspeed=walk envoi les données sur https://localhost:8112/import?url=https%3A%2F%2Foverpass-api.de%2Fapi%2Fxapi_meta%3F*%5Bmaxspeed%253Dwalk%5D

**Comment by Marc-marc-marc** [comment]
oui c'est lié : il y a eu des modifis côté josm (ne plus écouter en https sur localhost) qui ont été [reprise](https://github.com/taginfo/taginfo/commit/9878b55faef008070a5f5b771a8655956737b58f) dans taginfo en octobre 2019 (ne plus envoyer vers https://localhost mais uniquement http://localhost)

**Comment by Marc-marc-marc** [comment]
@jocelynj maj possible ?

**Comment by jocelynj** [comment]
J'ai mis à jour le git sur taginfo, et relancé, mais ça ne marche pas - j'ai lancé 20_update.sh pour voir si ça suffit.

**Comment by jocelynj** [comment]
En fait, il faudrait mettre à jour ruby pour une version >= 2.5. Pour cela, il faudrait surement mettre à jour la VM vers un OS plus récent. Je n'ai pas le temps tout de suite, mais je devrais pouvoir lancer la mise à jour vers 21h.

**Comment by jocelynj** [comment]
taginfo remarche après mise à jour de la VM vers buster, et modif de la config lxc avec:
`features: nesting=1`

**Comment by jocelynj** [comment]
Je ferme le ticket - merci de réouvrir si josm ne fonctionne toujours pas.

**Comment by Codain** [comment]
Merci @jocelynj mais malheureusement si cela fonctionne cela ne fonctionne pas encore bien. Je pense que c'est un soucis lié à Taginfo ou à sa conf, je m'explique plus loin. J'ai comparé les liens  pour charger les données dans JOSM depuis taginfo ORG, FR et FR GEOFABRIK : ce sont maintenant les mêmes et JOSM s'active bien quand on clique. Parfait. Sauf que intrigué par des erreurs de timeout sur par exemple deux occurrences de [maxspeed=25 mph dans le Taginfo FR](http://taginfo.openstreetmap.fr/tags/maxspeed=25%20mph) et bien cela cache un autre souci.

Explication : ce lien semble ne pas considérer le périmètre géographique des données de l'instance Taginfo et interroge l'instance Overpass mondiale indifféremment. En conséquence là où sur Taginfo FR il y a deux ways avec `maxspeed=25 mph` (donc Taginfo active l'affichage du lien JOSM) il y en a en fait 850897 dans le Taginfo ORG (le lien JOSM est désactivé car trop de données). D'où le timeout étant donné qu'il charge 850897 résultats au lieu de 2. Idem sur le bouton XAPI. Le lien Overpass Turbo sur Taginfo FR et FR GEOFABRIK inclut un `in France` qui semble faire l'affaire (même si en chipotant on pourrait dire que "France" ne garanti pas de restreindre aux données chargées dans cette instance Taginfo "France métropolitaine").

Question : est-ce possible d'associer les boutons JOSM et XAPI (et accessoirement OverPass) aux données strictement chargées dans le Taginfo en question ? Cela nécessiterait peut-être une instance Overpass par Taginfo... A minima une rustine consisterait à inclure ce fameux "in France" dans les liens JOSM et XAPI. Sauf que si Geofabrik ne le fait c'est peut-être parce que ce n'est pas possible ?

Nota : je ne peux pas rouvrir le ticket, pb de droit surement.

**Comment by Marc-marc-marc** [comment]
c'est le bug/fonctionnalité manquante dont parle ce [ticket](https://github.com/osm-fr/infrastructure/issues/65)
il faudrait vérifier auprès du projet principal si c'est un bug/manque dans le code ou une mauvaise configuration.
d'ici là je me demande si ce ne serrait pas mieux de couper le lien xapi.
l'export vers josm est toujours possible et fonctionnel avec le lien overpass / export / josm
