### ISSUE TITLE
Relation analyser dead

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#147]
Repport de l'issue Osmose https://github.com/osm-fr/osmose-frontend/issues/165

> The "Relation analyser" link point to http://analyser.openstreetmap.fr/cgi-bin/index.py that doesn't work.

> The other link ("analyse2") : http://polygons.openstreetmap.fr/~osmbin/analyse-relation-open.py is dead as well (error 403)

**Comment by maro-21** [comment]
The link is still dead, can we remove it from the menu?

**Comment by frodrigo** [comment]
First links removed.
Second now pointing to http://polygons.openstreetmap.fr/
Open to better suggestion.
