### ISSUE TITLE
live en panne suite à remplissage ram par les journaux sur /run/log

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#149]
http://live.openstreetmap.fr est en panne.

À ce que je vois, la VM utilise 100% de la ram, mais je ne vois aucun process l'utilisant.

**Comment by jocelynj** [comment]
/run/log/journal/ explique le remplissage de la ram:

$ df /run/log/journal/
Filesystem     1K-blocks   Used Available Use% Mounted on
tmpfs           16417796 491664  15926132   3% /run

**Comment by jocelynj** [comment]
Et ça vient d'ici:

$ sudo journalctl --disk-usage
Archived and active journals take up 480.0M in the file system.

J'ai redémarré la VM, et je modifierai cette config.

**Comment by jocelynj** [comment]
Pour référence; `journalctl --flush` doit permettre de vider ces logs.

**Comment by Marc-marc-marc** [comment]
journalctl --flush pour éviter le reboot :)
avoir un tmps de taille < ram dispo pour éviter la saturation de la ram

**Comment by Marc-marc-marc** [comment]
osm132 est en valeur par défaut pour journald.conf donc Storage=auto donc préférence au disque si le répertoire existe, sinon ram... et le répertoire /var/log/journal n'existe pas, donc tout reste en ram (et oom puisque la limite maxi du tmpfs est erroné).
donc double cause : 
- la préférence (probablement involontaire) à la ram alors que la resource la + critique/saturée sur le serveur est la ram. suffit de créer le répertoire.
- la limite de sécurité qui ne protège rien :ajuster la limite du tmpfs et/ou changer la valeur dans journald.conf

**Comment by jocelynj** [comment]
Est-ce que ce souci de journal pourrait être lié à https://lwn.net/Articles/812238/ ?

De ce que je comprends, sur Debian, `/run/log/journal` est créé, mais pas `/var/log/journal` pour le moment, ce qui fait que les logs ne sont jamais déplacé de la ram vers le disque.

Je me demande si on ne devrait pas créer `/var/log/journal/` sur toutes les machines.

**Comment by jocelynj** [comment]
J'ai créé /var/log/journal sur toutes les machines, et j'ai vu que l'utilisation disque du ramfr /run/ a bien baissé sur plein de machines.

**Comment by frodrigo** [comment]
On peut fermer ?
