### ISSUE TITLE
antispam sur Sympa

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#15]
mettre/activer un antispam sur Sympa
https://www.sympa.org/manual/antispam
attention c'est gandi qui forwarde les emails à liste... faudra donc configurer correctement le smart_host

**Comment by Marc-marc-marc** [comment]
gandi : un spam reçu avait comme destinataire sotm@openstreetmap.fr recu par gandi et transféré en sotm@listes.openstreetmap.fr

**Comment by Cyrille37** [comment]
Salut. Pas de nouveau, je ferme ce ticket :-)
