### ISSUE TITLE
Certificat expiré sur les serveurs tile.openstreetmap.fr

### ISSUE THREAD

**Issue by gegeweb** [osm-fr/infrastructure#150]
Bonjour,

le certificat utilisé sur les serveurs de tuiles tile.openstreetmap.fr a expiré hier soir et n'a pas été renouvelé automatiquement.
Du coup les tuiles ne s'affichent plus, avec une erreur CORS pour OpenLayer et l'erreur SEC_ERROR_EXPIRED_CERTIFICATE pour LeafLet.

Merci pour le travail au passage.

**Comment by deuzeffe** [comment]
C'est même pas sur tile.openstreemap.fr (certif valide jusqu'en mai 2020) mais sur cachelyon.openstreetmap.fr et ça cascade...

**Comment by gegeweb** [comment]
Je pensais à ces serveurs car voici le code que j'utilise (OpenLayers 3), du coup ça me fait penser qu'il faut que je pense à mettre à jour "attributions" pour mentionner OSM France : 

```
		new ol.layer.Tile({
			title: 'OSM France',
			type: 'base',
			preload: Infinity,
			visible: false,
			source: new ol.source.OSM({
				url: 'https://{a-c}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png'
			})
		}),
```

**Comment by deuzeffe** [comment]
@gegeweb regarde ce que donne une navigation directe sur https://a.tile.openstreetmap.fr et affiche le certif. Idem sur tile.openstreetmap.fr : c'est pas pareil :/

**Comment by Marc-marc-marc** [comment]
@cquest je n'ai pas d'accès sudo à osm23 pour regarder le soucis

**Comment by cquest** [comment]
Le certificat d'osm23 qui sert pour a/b/c.tile.openstreetmap.fr court du 17 janvier au 17 avril, donc ce n'est pas lui qui est en jeu ici.

tile.openstreetmap.fr est sur osm13... et le certificat va du 10/2 au 10/5.

Je ne vois pas d'où sort ce certificat périmé au 16/02 !

@Marc-marc-marc j'ai ajouté ta clé si besoin

**Comment by Marc-marc-marc** [comment]
@gegeweb sur https://tile.openstreetmap.fr (qui comme son nom ne l'indique pas est l'rul pour accéder au OpenLayers montrant les différentes couches) le certificat date du 10 février et est valable jusqu'au 10 mai
sur https://a.tile.openstreetmap.fr https://btile.openstreetmap.fr https://c.tile.openstreetmap.fr il date du 17 janvier valide jusqu'au 17 avril
ex de tuile https://a.tile.openstreetmap.fr/osmfr/19/265560/180371.png
Une url de tuile posant un problème de certificat ?

**Comment by gegeweb** [comment]
Je suis au boulot, donc plus sur le même réseau que ce matin.
Je suis chez K-Net, RIP Covage derrière.
Je vais reterser ce soir. 
Mais j'ai eu le problème avec les trois sous domaines a, b, c ou tile directement.

Si ça aide…

**Comment by gegeweb** [comment]
À noter que j'ai eu la même chose avec OpenLayer ou Leaflet.
OpenLayers provoquait une erreur CORS.
Leaflet avec l'url https://{s}.tile.openstreetmap.fr remontait l'erreur certificat expiré quel que soit le serveur (a, b ou c) qui remontait la tuile. 
Navigateur Firefox à jour.
En prod avec OL3 (pas touché au code depuis un moment) sur le site de prod.
En dev avec la dernière version OpenLayer ou LeafLet.

**Comment by jocelynj** [comment]
Je vois que nginx a été redémarré ce matin sur osm23 (=cachelyon).

Est-ce qu'on n'aurait pas eu nginx utilisant encore l'ancien certificat avant redémarrage ?

**Comment by jocelynj** [comment]
Je n'ai rien vu sur nginx dans /etc/letsencrypt/. Du coup, j'ai suivi cette doc: https://blog.arnonerba.com/2019/01/lets-encrypt-how-to-automatically-restart-nginx-with-certbot

Un fichier dans /etc/letsencrypt/cli.ini avec:
```ini
renew-hook = systemctl reload nginx
```

**Comment by gegeweb** [comment]
@jocelynj erreur que j'ai déjà faite à mes dépens… ça pas marche le reload pour recharger les certificats (même avec un lien symbolique). Un restart est obligatoire.

**Comment by deuzeffe** [comment]
@gegeweb je confirme que dans les mêmes conditions que https://github.com/osm-fr/infrastructure/issues/150#issuecomment-586860708 je ne reproduis pas l'erreur.

@jocelynj ah, il y avait quand même un loup :/

**Comment by cquest** [comment]
Par principe j'ai relancé nginx/cerbot sur osm23, mais je ne m'explique pas d'où peut sortir un certificat valide jusqu'au 16.

**Comment by jocelynj** [comment]
@cquest: je pense qu'on tournait toujours avec le certificat généré le 17 novembre, expirant le 16 février. Et nginx n'a pas du être relancé depuis, pour le forcer à utiliser un certificat généré après le 17 novembre.

**Comment by gegeweb** [comment]
Voici une des tuiles qui posait problème ce matin : 
https://a.tile.openstreetmap.fr/osmfr/8/125/88.png

Rien à signaler ce soir.

Le certificat est valide et expire en avril.

Je ferme le ticket.

Par contre, je vous conseille `systemctl restart nginx` et non `reload` après le renouvellement.
J'utilise dehydrated sous FreeBSD, la conf pointe vers un lien symbolique et je suis obligé de faire un `service nginx restart` pour que le nouveau certificat soit pris en compte, avec reload ça reste sur l'ancien.
Et j'ai du mettre à jour dehydrated après les changements récents chez Let's Encrypt.
