### ISSUE TITLE
Acces-Control-Allow-Origin manquant sur {s}.tile.cyclosm.openstreetmap.fr

### ISSUE THREAD

**Issue by gegeweb** [osm-fr/infrastructure#151]
Bonsoir,

l'entête Acces-Control-Allow-Origin manquante sur les serveurs de {s}.tile.cyclosm.openstreetmap.fr qui servent les tuiles de la carte Cyclo OSM.

Observé depuis plusieurs connexions/réseaux différents et avec Chrome et FF.
Du coup les tuiles ne sont pas affichées.
J'utilise Open Layer 3 avec le code suivant : 

```
		new ol.layer.Tile({
			title: 'Cyclo OSM',
			type: 'base',
			preload: Infinity,
			visible: false,
			source: new ol.source.OSM({
				url: 'https://{a-c}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png',
				attributions: [
					ol.source.OSM.ATTRIBUTION,
					new ol.Attribution({
						html: ' | <a href="https://github.com/cyclosm/cyclosm-cartocss-style/releases" title="CyclOSM - Open Bicycle render">CyclOSM</a>.'
					})
				],
			})
		}),
```

<img width="1438" alt="Capture d’écran 2020-02-18 à 18 42 21" src="https://user-images.githubusercontent.com/9108457/74762841-ee901b80-527e-11ea-90fb-2c406d21bd6a.png">

**Comment by jocelynj** [comment]
@Phyks: c'est pour toi :)

**Comment by cquest** [comment]
Le plus simple est de le traiter sur le proxy nginx (si il y en a un).

**Comment by Phyks** [comment]
Il suffit probablement d'ajouter

```
Header set Access-Control-Allow-Origin "*"
```

dans `/etc/apache2/sites-available/tileserver_site.conf` sur osm166, mais je n'ai pas les droits.

**Comment by jocelynj** [comment]
J'ai fait la modif proposé par @Phyks sur osm166.

**Comment by gegeweb** [comment]
C'est nickel. ;)

merci.
