### ISSUE TITLE
Ajouter IPv6 sur cache de tuiles de Lyon (tilecache.openstreetmap.fr) ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#152]
L'IPv6 d'osm23: 2a03:9180:0:100::8

**Comment by jocelynj** [comment]
Ça me parait une très bonne idée.

Tu t'occupes de rajouter l'entrée du DNS qui va bien ?

**Comment by cquest** [comment]
Ajouté à l'instant sur l'IP que j'ai indiqué, je n'arrive pas à faire un ping6 sur la seconde.
J'ai vérifié localement avec mon /etc/hosts que c'était bon avant de modifier le DNS.

**Comment by jocelynj** [comment]
C'est peut-être la config DNS d'osm23 qu'il faut mettre à jour dans ce cas ?

Je vois que http vers l'ipv6 marche, mais est-ce que le ssh -6 devrait marcher aussi ?

**Comment by jocelynj** [comment]
J'ai corrigé le DNS ipv6 d'osm23, et également activé le sshd depuis ipv6.
