### ISSUE TITLE
qui est derrière contact @

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#154]
Nous nous sommes posés la question lors d'un dernier CA, sait-on qui est derrière l'adresse et de fait qui répond ?

@cquest @Cyrille37 @jocelynj @nlehuby

**Comment by Marc-marc-marc** [comment]
7 personnes recoivent : bfournier cquest jocelyn noémie 2xvdct sylvain.maillard
a répondu avec copie à conctact : en février cquest, en janvier personne, en décembre Jocelyn

**Comment by vinber** [comment]
merci, je t'envoie un maill :)
