### ISSUE TITLE
bug certificat LE

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#155]
https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864
certifs impactés : 
- [x]  cluster ovh - affecté et regen
- [x] cluster free (osm11) - non affecté
- [x] osm13 - non affecté
- [x] tilecache de lyon - non affecté
- [x] différentes VM - regen

**Comment by cquest** [comment]
J'ai fait le nécessaire sur osm23 après réception d'un mail à ce sujet.

**Comment by jocelynj** [comment]
Tous les certificats concernés ont été regénérés.
