### ISSUE TITLE
Sur @contact, on nous signale que cela ne fonctionne pas :http://export.openstreetmap.fr/contours-administratifs/communes/ 

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#156]
http://export.openstreetmap.fr/contours-administratifs/communes/

**Comment by Marc-marc-marc** [comment]
renseigné comme coupé sur le wiki
https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#Liste_des_services_web_sur_le_domaine_openstreetmap.fr
j'évoquais justement hier le fait qu'on devrait mettre un message "service coupé" ou une redirection vers la page du wiki au lieu que l'utilisateur ai une erreur qui ne dit pas si c'est volontaire ou pas, temporaire ou pas, je viend d'en faire un ticket https://github.com/osm-fr/infrastructure/issues/157
du coup je te laisse voir si on ferme ce ticket ou si qlq veux rétablir export

**Comment by vinber** [comment]
non, ok on ferme !
