### ISSUE TITLE
La synchro nextcloud ne fonctionne pas depuis mon ordi 

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#158]
cela fonctionne pour 4 autres nextcloud, donc je pense que c'est du coté d'osm-fr
![Capture d’écran de 2020-03-11 09-42-57](https://user-images.githubusercontent.com/890869/76398192-bad77b80-637c-11ea-914f-65ac6cde71c9.png)

**Comment by cquest** [comment]
Je viens de faire une synchro depuis mon client: aucun problème pour moi.

**Comment by vinber** [comment]
ok, je relance mon client alors

**Comment by vinber** [comment]
cela semble ok, merci :)
