### ISSUE TITLE
trac.openstreetmap.org est injoignable

### ISSUE THREAD

**Issue by pamputt** [osm-fr/infrastructure#159]
Bonjour, il semble que https://trac.openstreetmap.fr/ est injoignable depuis quelques jours. C'est peut-être voulu. Si tel est le cas, il faudrait changer le lien présent sur https://cadastre.openstreetmap.fr/ vers le nouveau site de gestion de bogues.

**Comment by Marc-marc-marc** [comment]
c'est en effet voulu, merci pour le signalement, on va corriger/supprimer le lien trac.
le dépôt du projet est accessible avec le lien git https://github.com/osm-fr/export-cadastre
et "issues" est le bon endroit pour signaler un bug.
a noter que pour la partie fantoir qu'une version 2 est en cours de finalisation et déjà bien utilisable sur https://dev.cadastre.openstreetmap.fr

**Comment by vdct** [comment]
cf https://github.com/osm-fr/export-cadastre/issues/40

**Comment by cquest** [comment]
cadastre.openstreetmap.fr pointe vers osm104, ne devrait-il pas à minima pointer vers osm162/bano et dev.cadastre ?

**Comment by vdct** [comment]
> 
> 
> cadastre.openstreetmap.fr pointe vers osm104, ne devrait-il pas à minima pointer vers osm162/bano et dev.cadastre ?

Non car il fait appel à des ressources qui ne sont que sur osm104. La redirection c'est quand on décide de couper osm104, notamment la brique qadastre. Il n'est pas clair pour moi de savoir quels services autres s'appuient dessus
