### ISSUE TITLE
Ajout infra aux « Pinned repositories »

### ISSUE THREAD

**Issue by RoPP** [osm-fr/infrastructure#16]
Sur la page d’osm-fr, rajouter le projet infrastructure aux projets épinglés.
![capture d ecran de 2017-11-13 16-26-12](https://user-images.githubusercontent.com/45775/32733434-8773c6c0-c88f-11e7-81ce-0326e116eee6.png)

**Comment by jocelynj** [comment]
Bonne idée - c'est fait.
