### ISSUE TITLE
Orthophoto de Bayonne, 2019

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#160]
la ville de Bayonne a publié une nouvelle orthophoto en opendata. Celle-ci couvre uniquement le centre-ville (Petit et Grand Bayonne), précision 5cm, prise en octobre 2019

https://www.data.gouv.fr/fr/datasets/orthophotographie-petit-et-grand-bayonne-2019/

@cquest c'est bien ici que l'on signale d'éventuelles nouvelles orthophotos ?

**Comment by Marc-marc-marc** [comment]
christian étant au front, c'est sans doute l'occasion d'écrire un mini howto et partager l'accès sur ce serveur pour pouvoir aider

**Comment by Marc-marc-marc** [comment]
contourné par https://github.com/osmlab/editor-layer-index/pull/830

**Comment by gitouche-sur-osm** [comment]
C'est bien Bayonne 2016 qui est dans le PR :)

"Petit & Grand" Bayonne 2019 est limité au coeur de la ville, et viendra en complément mais ne remplace pas totalement Bayonne 2016. Actuellement tuiles en attente d'un hébergement :)

A+,
Guillaume

**Comment by cquest** [comment]
Je l'ai ajoutée, couche bayonne_2019 par WMS et elle est aussi intégrée dans l'ortho composite "tous_fr" en TMS.

**Comment by vinber** [comment]
merci

**Comment by rbuffat** [comment]
Hi all. In https://github.com/osmlab/editor-layer-index/pull/870, there are some questions regarding the requirement of a waiver for the attribution of the  [license](https://www.etalab.gouv.fr/licence-ouverte-open-licence)  for the [bayonne_2019](https://www.data.gouv.fr/fr/datasets/orthophotographie-petit-et-grand-bayonne-2019/)  dataset.

If somebody has any insights, a comment in https://github.com/osmlab/editor-layer-index/pull/870 would be very welcome.
