### ISSUE TITLE
impossible de s'enregistrer sur le forum ?

### ISSUE THREAD

**Issue by althio** [osm-fr/infrastructure#161]
Bonjour,

Comment se passe normalement l'activation des nouveaux comptes sur forum.openstreetmap.fr ?

Un nouveau membre inscrit reçoit actuellement :
> Le nom d’utilisateur que vous avez spécifié est actuellement inactif. Si vous rencontrez des difficultés lors de l’activation de votre compte, veuillez contacter un administrateur du forum.

Pas de trace d'email d'activation envoyé par le forum.

Pas de trace d'action à prendre dans le panneau des modérateurs.

Est-ce une action manuelle d'un administrateur ?

**Comment by Marc-marc-marc** [comment]
à ma connaissance il y a un admin forum qui valide les comptes manuelement (pour une raison que j'ignore)

**Comment by althio** [comment]
Et on est tombé dans le bus factor ? Plus personne ne s'en occupe ?

**Comment by vinber** [comment]
je viens de demander à celui que je crois savoir qui est peut-être l'admin :D

**Comment by Marc-marc-marc** [comment]
c'est un covid-factor :) et un choix discutable : le nouveau doit attendre la validation de son compte sur le forum mais pas sur une liste de diffusion alors que celle-ci n'est plus réelement modérable une fois son email envoyé (on peux virer l'archive de la liste mais pas annuler l’envoi de son email)

**Comment by gendy54** [comment]
Hello,
C'est moi qui valide les comptes (plusieurs fois/jour), car on est envahi par les spams. C'est pour ca qu'on parlait avec Christian et Jocelyn de changer de techno de forum, parce que franchement c'est lourd. Pour 100 inscriptions, y a 95% de spam.

**Comment by Marc-marc-marc** [comment]
pourquoi ne pas simplement basculer sur le [nabble de talk-fr](http://gis.19327.n8.nabble.com/France-f5380434.html) ? on évite le défaut "fragmentation" de la situation actuelle.
l'autre solution est de voir s'il n'y a pas de formulaire d'inscription plus robuste

**Comment by gendy54** [comment]
La 2eme solution, j'ai déjà tout essayé et ce n'est pas de gaité de coeur que j'ai fait ca. Il y a des mises à jour à faire sur le forum, mias je ne suis pas sûr que ca change grand chose.
On avait pensé à un forum type Discourse qui fait un peu plus moderne.
En tout cas, si des tech veulent se pencher sur le sujet, je veux bien.

**Comment by Marc-marc-marc** [comment]
De quand datent les maj non faite ?
Si (et cela semble être le cas) on n'a pas les ressources humaines pour maintenir un forum à jour avec une réactivitée suffisante, changer le nom de forum ne fait que reporter le problème.
dans ce cas solution un : remplacer le forum par une page avec les liens nabble des différents forum francophone et ou relatif aux zones en france (genre talk-fr-bzh).
en passant ceux qui l'utilisent gagneront la possibilité d'avoir plus de chance d'avoir une réponse

**Comment by althio** [comment]
@gendy54 
> C'est moi qui valide les comptes (plusieurs fois/jour), car on est envahi par les spams.
> Pour 100 inscriptions, y a 95% de spam.

Salut :wave:
Est-ce que c'est modéré/validé à l'inscription (sur la base du nom d'utilisateur / adresse mail / IP) ou sur le premier message ?
Il semble qu'il y a du faux-positif : des (vrais) gens qui n'arrivent pas à s'inscrire.

Pour info, tout a démarré [ici sur le forum international OpenStreetMap](https://forum.openstreetmap.org/viewtopic.php?pid=781506#p781506).

**Comment by althio** [comment]
@Marc-marc-marc 
La présentation "forum" de la liste talk-fr sous nabble, c'est bien pour avoir un accès différent et structuré aux archives (mon avis et mon ressenti).

Mais je trouve que l'esprit d'utilisation, la finalité sont différents pour une liste d'échange et un forum.
Et que le format forum est beaucoup, beaucoup plus agréable pour les nouveaux et les gens de passage.

Cela étant dit... ça n'enlève rien à aux difficultés humaines et techniques pour faire tourner ces outils.

**Comment by gendy54** [comment]
Hello,

Voilà un exemple de ce qui arrive tous les jours!
![image](https://user-images.githubusercontent.com/10323517/78872531-b79de100-7a49-11ea-810d-e809ea1b2646.png)

Une seule adresse parait normale, mais elle vient du Cameroun.
![image](https://user-images.githubusercontent.com/10323517/78872695-f59b0500-7a49-11ea-8eff-8675d343917a.png)

En général, tout est un faisceau d'indice, mais parfois je n'ai pas d'élément par rapport à la localisation de l'adresse IP. C'est pas impossible qu'il y ait des faux positifs, mais en général, les vrais gens se voient facilement.

Donat

**Comment by Marc-marc-marc** [comment]
prévoir à mini-minimal une maj php histoire de retomber sur une version supportée
prévoir idéalement une maj phpBB histoire d'éviter de traîner des failles de sécurités
prévoir idéalement backup de la vm avant de toucher à cet antiquité
prévoir idéalement un renfort admin ou une bascule "hors osm-fr" (Nabble ?) vu l'absence de bras ayant fait les points précédents en 3 ans.

**Comment by Marc-marc-marc** [comment]
avant maj :
ii  libapache2-mod-php5             5.6.40+dfsg-0+deb8u11             
ii  php5-cli                        5.6.40+dfsg-0+deb8u11             
ii  php5-common                     5.6.40+dfsg-0+deb8u11             
rc  php5-gd                         5.6.40+dfsg-0+deb8u3              (explique peux-être le soucis avec captcha)
rc  php5-imagick                    3.2.0~rc1-1                       
ii  php5-json                       1.3.6-1                           
ii  php5-mysql                      5.6.40+dfsg-0+deb8u11             
ii  php5-readline                   5.6.40+dfsg-0+deb8u11   
passage du forum en maintenance
snapshot proxmox php7init
apt install php7.0-cli php7.0-gd php-imagick php7.0-mysql libapache2-mod-php7.0
apt purge libapache2-mod-php5 php5-cli php5-common php5-gd php5-imagick php5-json php5-mysql php5-readline
a2enmod php7.0
systemctl restart apache2
lecture ok, écriture/suppression d'un message de test ok
snapshot proxmox php7ok

le module image avec bruit gd à l'inscription fonctionne, @gendy54 je te laisse le soin de l'activer si tu le souhaites.
a venir un autre jour : maj phpBB

**Comment by gendy54** [comment]
Je viens d'activer le module _image avec bruit gd_ mais j'ai pas l'impression que cette pause a diminué le nb d'inscription spam.
Merci en tout cas.

**Comment by cquest** [comment]
Comme le forum était planté depuis quelques temps, ça m'a décidé à regarder la migration phpBB vers discourse.

Après deux jours de lutte avec docker, c'est réussit à migrer le contenu qu'on peut voir sur https://discourse.openstreetmap.fr/

J'ai stoppé le container de forum.openstreetmap.fr.

Les comptes utilisateurs, catégories, messages publics et privés ont en principe été migrés. Par contre, les mot de passe sont vierges, il faut donc demander à réinitialiser son mot de passe.

**Comment by Marc-marc-marc** [comment]
> J'ai stoppé le container de forum.openstreetmap.fr.

on avait décidé de le garder en mode lecture pour éviter les 404

**Comment by gendy54** [comment]
Perso ca ne me choque pas. Il y avait a priori peu de liens vers le forum. 
Pour le coup, le moteur de recherche de Discourse est autrement plus performant et permettra de retrouver les infs recherchées.
J'en ai discuté avec Christian cette aprem. Il est possible qu'il soit passé à côté de ce transfert ou qu'il faille faire quelques modifs de paramétrage pour que les liens se fassent.
Mais pour moi l'essentiel, c'est que le maximum a été sauvegardé et ce n'était pas forcément une mince affaire.

**Comment by Marc-marc-marc** [comment]
s'il n'y a pas de soucis que l'utilisateur se ramassent un "serveur inacessible" ou un "404" basé sur des "à priori", bah pourquoi je me préoccupe, le but c'est de s'amuser, pas "l'expérience utilisateur" de la communautée

**Comment by cquest** [comment]
Suite de la discussion (constructive) sur https://github.com/osm-fr/infrastructure/issues/272
