### ISSUE TITLE
Certificat TLS HTTPS osm104.openstreetmap.fr expiré

### ISSUE THREAD

**Issue by gileri** [osm-fr/infrastructure#162]
Bonjour,
Depuis 08/04/2020 à 03:49:20 (heure d’été d’Europe centrale) sont touchés (SAN du certificat) :

- bano.openstreetmap.fr
- cadastre.openstreetmap.fr
- imagery.openstreetmap.fr
- osm104.openstreetmap.fr
- tms.cadastre.openstreetmap.fr

**Comment by Marc-marc-marc** [comment]
Merci pour le signalement.
il y a un soucis dans la conf qui empêche son renouvellement, je regarde...

**Comment by Marc-marc-marc** [comment]
corrigé. la config avait un redirect dont je vois pas trop l'utilité. je l'ai commenté si quelqu'un souhaite analyser le pourquoi cela a été mis

**Comment by jocelynj** [comment]
J'ai appliqué la même modif sur ansible: https://github.com/osm-fr/ansible-scripts/commit/520f70c47aaa5ad59a112c4387a36f3f6689eec0
