### ISSUE TITLE
Timestamp invalide dans les extracts OSM-FR

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#164]
Les extracts ont un champ `time` dans le header qui est invalide (négatif), probablement non initialisé.

Ça serait bien de l'avoir (comme le champ d'url pour les idff).

Ça pose problème à imposm.

https://github.com/omniscale/imposm3/issues/244
https://github.com/omniscale/imposm3/pull/245

Je pense que l'on a plus chance de faire al correction des extract que de voir mon RP sur imposm accepté, il n'a plus maintenu.

**Comment by frodrigo** [comment]
J'ai parlé trop vite le PR sur imposm est déjà mergé.

Mais je pense qu'il faut quand même ajouter ces champs aux extracts. Ça permettra plus aux outils de les utiliser et de finir par ne plus avoir besoin dans certains cas du state.txt.

**Comment by jocelynj** [comment]
C'est lié à l'ajout de ces champs pour faciliter la mise à jour: https://wiki.openstreetmap.org/wiki/PBF_Format#What_are_the_replication_fields_for.3F

On m'a proposé ça pour initialiser les champs:
```
osmium cat -o gibraltar-with-headers.pbf \
	--output-header=osmosis_replication_timestamp=2020-01-01T14:16:21Z \
 	--output-header=osmosis_replication_sequence_number=3456 \
 	--output-header=http://download.openstreetmap.fr/replication/europe/gibraltar/ gibraltar.osm.pbf
```

**Comment by frodrigo** [comment]
Il faut ajouter ça par là ?
https://github.com/jocelynj/osm/blob/master/osc_modif/init_pbf.py#L77

J’aimerais voir si osmupdate est plus rapide qu'osmosis pour osmose. Il utilise aussi ces champs. Ça permettrait d'éviter d'émuler le state file d'osmosis.

**Comment by jocelynj** [comment]
Ces champs sont ajoutés sur http://download.vm.openstreetmap.fr. Par exemple:
```
$ osmium fileinfo /data/work/osmbin/extracts/europe/france/france.osm.pbf
File:
  Name: /data/work/osmbin/extracts/europe/france/france.osm.pbf
  Format: PBF
  Compression: none
  Size: 4378145012
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=pyosmium-up-to-date/3.0.1
    osmosis_replication_base_url=http://download.openstreetmap.fr/replication/./europe/france/minute
    osmosis_replication_sequence_number=4281344
    osmosis_replication_timestamp=2020-11-13T10:01:03Z
    pbf_dense_nodes=true
    timestamp=2020-11-13T10:01:03Z
```

**Comment by jocelynj** [comment]
Ajoutés sur download.openstreetmap.fr.
