### ISSUE TITLE
libwww-perl missing for munin apache plugin + www-browser for apache2ctl status

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#165]
- see #30 : error msg : WP::UserAgent not found at /etc/munin/plugins/apache_accesses
- apache2ctl: www-browser: not found -> for ex links in ansible role for apache

**Comment by jocelynj** [comment]
Corrigé par https://github.com/osm-fr/ansible-scripts/commit/fdeef4466ba80d2f32736c7c01311bcc00bf6292

Merci pour la suggestion.
