### ISSUE TITLE
Peertube en 502, nextcloud en dérangement également

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#166]
https://peertube.openstreetmap.fr/
502 Bad Gateway

**Comment by Marc-marc-marc** [comment]
osm28 (son hosteur) a rebooté (raison inconnu/non cherchée) ce matin. vu son uptime d'un an, c'est tout a fait possible qu'il y ai eu une veille modif dans un fichier de config qui ne s'est appliquée que maintenant. idem avec une maj système.
en passant, il y a 2 versions de pg, il serait utile de ne garder que la plus récente

**Comment by jocelynj** [comment]
Je viens de regarder, et c'est suite à une mise à jour du paquet "nodejs", qui est passé à la version du paquet debian plutôt que la version de nodesource. J'ai forcé l'install du bon paquet via un `apt-get install nodejs=10.20.1-1nodesource1` (qui est pourtant plus récent que la version debian), et peertube remarche.
