### ISSUE TITLE
Mise à jour de Proxmox v5 en v6 sur le cluster OVH

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#167]
A planifier prochainement, car la maintenance de la v5 s'arrête fin juillet.

ATTENTION: il y a une manip à faire en plusieurs temps à cause du changement de version de corosync

- [x] osm25: corosync 3 + proxmox 6
- [x] corosync 3 sur osm26, osm27 et osm28
- [x] osm26: proxmox v6
- [x] osm27: proxmox v6
- [x] osm28: proxmox v6

**Comment by jocelynj** [comment]
@cquest: tu sais si cette mise à jour peut se faire sur chaque host séparément, ou est-ce qu'on doit mettre à jour les 3 en même temps ?

**Comment by cquest** [comment]
Elle se déroule en 3 étapes:
- mise à jour de corosync en v3.x, sur l'ensemble du cluster
- mise à jour de proxmox, noeud par noeud

Je l'ai fait plusieurs fois, il y a environ un an sur des noeuds seuls ou en cluster.
La coupure est minime essentiellement due aux reboot.

**Comment by jocelynj** [comment]
Ok, c'est donc très similaire à la précédente mise à jour qu'on avait faite sur ce même cluster. Si tu as besoin d'aide, on peut se synchroniser pour une soirée particulière.

De mon côté, je vais continuer à mettre à jour les VMs du cluster ovh vers debian buster.

**Comment by cquest** [comment]
osm25 mis à jour.

Attention, un pépin avec les eno1 devenus eth0 et donc non reconnus au reboot...

**Comment by cquest** [comment]
Je viens de faire la mise à jour de corosync en 3.x sur osm26/27/28

On peut passer à la mise à jour de proxmox lui même noeud par noeud...

**Comment by cquest** [comment]
@jocelynj et @Marc-marc-marc je vous propose de migrer osm28 ce soir... il n'y a rien de critique dessus donc autant commencer par lui.

**Comment by cquest** [comment]
Content de la fermer celle là :)
