### ISSUE TITLE
Installation de matomo pour umap et www

### ISSUE THREAD

**Issue by yohanboniface** [osm-fr/infrastructure#17]
https://openstreetmap.fr/piwik/

![screenshot from 2017-11-28 20-00-11](https://user-images.githubusercontent.com/146023/33338583-c79a97b8-d476-11e7-9256-c09eb9a40b47.png)

**Comment by MaelREBOUX** [comment]
Ca c'est le genre de chose sur laquelle je pourrai aider si vous le souhaiter.

**Comment by jocelynj** [comment]
Hum, il est possible qu'on n'ait pas migré piwik lors de la migration du site web.

Est-ce que ça aurait un sens de monter une VM avec piwik seulement, sur piwik.openstreetmap.fr ?

**Comment by MaelREBOUX** [comment]
Vous suivez qui comme sites www avec ?
- http://www.openstreetmap.fr 
- ?

Piwik ne prend des grosses ressources que si on fait une analyse de log sur une grosse période. Ou sur des sites à très forts trafic. La BD (MySQL) peut devenir assez volumineuse assez vite si on ne purge pas les imports bruts de logs. Petite stratégie à définir à un moment.

cf https://piwik.org/faq/troubleshooting/faq_42/

**Comment by jocelynj** [comment]
J'ai trouvé un dump .sql.bz2 de la base mysql, qui fait 4Go. Je ne sais plus quel site on avait dessus. Je regarderais pour le mettre sur une autre VM.

**Comment by yohanboniface** [comment]
> Vous suivez quoi comme sites www avec ?

Y avait aussi https://umap.openstreetmap.fr

**Comment by jocelynj** [comment]
@MaelREBOUX merci pour ton aide. Je peux te créer une VM quand tu veux.

Tu saurais combien de disque dur il faudrait pour stocker les données ?

L'idéal serait un rôle ansible, ou un script, mais on peut s'en passer.

**Comment by Marc-marc-marc** [comment]
pour mémoire, Jocelyn a créé osm160 en octobre, documenté comme en cours d'install.
manque de temps ou soucis ? ce n'est pas du tout une critique, c'est juste pour mettre à jour le ticket vu qu'on pourrait en avoir besoin, cfr discussion sur talk-fr à propos de prev.*

**Comment by MaelREBOUX** [comment]
Bonjour @Marc-marc-marc @jocelynj

**Comment by MaelREBOUX** [comment]
Bonjour @Marc-marc-marc @jocelynj

Je suis tjs ok pour gérer cette installation. J'attendais tranquillement de disposer login / mdp sur une VM. Rappel de mon mail : mael.reboux  chez breizhpositive.bzh

Pour info le matomo de  https://stats.openstreetmap.bzh tourne comme un charme.

Bon, comme tout le monde je cours après le temps mais pour un simple matomo ça devrait le faire :)

**Comment by Marc-marc-marc** [comment]
essaye de te connecter sur osm160. ton compte y est bien présent. identification par clef

**Comment by MaelREBOUX** [comment]
connexion réussie :D

**Comment by MaelREBOUX** [comment]
Mise à niveau debian 9.11 -> 10

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by MaelREBOUX** [comment]
Un pb munin pour @Marc-marc-marc  #140

**Comment by MaelREBOUX** [comment]
Je note toute la procédure d'installation que je mettrais sur le serveur mais note pour le détour : eu de gros soucis car il manquait des fichiers système.

L'erreur :
`mariadb.service: Failed at step EXEC spawning /etc/mysql/debian-start: No such file or directory`

Résolu avec :
`apt-get install --reinstall -o Dpkg::Options::="--force-confmiss" mariadb-server-10.3`

manquaient :
* /etc/init.d/mysql
* /etc/mysql/debian-start
* /etc/mysql/mariadb.conf.d/50-mysqld_safe.cnf
* /etc/mysql/mariadb.conf.d/50-server.cnf

**Comment by MaelREBOUX** [comment]
base de données maria-db installée
apache + php 7.3 installés

attente de la propagation DNS de stats.openstreetmap.fr pour terminer

**Comment by MaelREBOUX** [comment]
DNS ok.

@jocelynj : il faudrait rajouter stats dans la liste des sous-domaines pour le certificat SSL / HTTPS.
merci.

**Comment by MaelREBOUX** [comment]
et également amha rajouter un truc dans la conf nginx du frontal pour bénéficier des IP réelles car j'ai modifier la conf apache mais je ne vois que du 10.0.0.26 passer.

**Comment by MaelREBOUX** [comment]
sinon le site est HYPER lent depuis le passage à stats

**Comment by jocelynj** [comment]
Pour les IPs, il manquait la configuration pour mod_remoteip sur osm160, que je viens d'activer via ansible.

Le site http://stats.openstreetmap.fr me sort une page blanche ici. C'est normal ?

**Comment by MaelREBOUX** [comment]
oui / non : je tente d'installer GeoIP2

**Comment by MaelREBOUX** [comment]
J'ai réinstallé matomo proprement. Par contre maintenant après tes changements je ne peux plus me connecter et j'ai cette erreur  :

Erreur: La sécurité du formulaire a échoué. Veuillez recharger le formulaire et vérifier que vos cookies sont activés. Si vous utilisez un serveur proxy, vous devez configurer Matomo pour accepter les en-têtes du proxy qui relaient les en-têtes de l'hôte. Vérifiez aussi que l'en-tête de votre référent est correctement transmis.

https://matomo.org/faq/how-to-install/#faq_98

**Comment by jocelynj** [comment]
Et si tu suis cette procédure, sans modifier la config de matomo pour reverse proxy, vu qu'on a mod_remoteip, ça ne marche pas ?
```If you use Apache 2.4 or Apache 2.5, there is an alternative solution, you could use mod_remoteip to override the client IP with the IP as provided by a proxy or load balancer. Then you won’t need to specify these Matomo config settings.```

**Comment by MaelREBOUX** [comment]
Bon. ça passe bien en https maintenant. Bizarre.

**Comment by jocelynj** [comment]
Le certificat https de https://stats.openstreetmap.fr est maintenant à jour

**Comment by MaelREBOUX** [comment]
Super !

Faut que je règle ce truc maintenant :
![Capture d’écran 2020-01-06 à 19 58 34](https://user-images.githubusercontent.com/6370443/71841117-f628a600-30be-11ea-9427-5909d9f37379.png)

**Comment by MaelREBOUX** [comment]
`WP-Matomo 1.0.22 a bien été connecté à Matomo 3.13.0. Vous utilisez WordPress 5.2.5.`

**Comment by MaelREBOUX** [comment]
Installé et configuré : les données arrivent. Je laisse tourner qqs jours et je reviens pour les réglages fins. Notamment calcul auto des rapports et purge auto.

**Comment by MaelREBOUX** [comment]
Récapitulons :

- [x] configuration serveur (apache php mariadb)
- [x] installation matomo
- [x] installation greffon WP-Matomo dans le WordPress
- [ ] configuration cron calcul rapport
- [ ] configuration cron archivage
- [ ] backup auto mysql

**Comment by MaelREBOUX** [comment]
ok. je pense que je suis bon pour l'installation. je viens de configurer le calcul auto + backup mysql quotidien.

les infos remontent bien dans le WordPress :

![Capture d’écran 2020-01-15 à 21 40 34](https://user-images.githubusercontent.com/6370443/72469477-c6c11a00-37df-11ea-8b34-b7bf8c22f5c4.png)

Je vois dans 2-3 jours si les backups de la base se passent bien.

@yohanboniface : je te prépare un 'site' sur matomo pour que tu mettes le code javascript qui va bien sur umap.osm.fr c'est ça l'idée ?

**Comment by MaelREBOUX** [comment]
Les backups de la base mysql se font bien.

Récapitulons :

- [x] configuration serveur (apache php mariadb)
- [x] installation matomo
- [x] installation greffon WP-Matomo dans le WordPress
- [x] configuration cron archivage
- [x] backup auto mysql
- [ ] script purge des backups
- [ ] infos SMTP

**Comment by MaelREBOUX** [comment]
Vérifier le réglage "Supprimer les logs plus anciens que 180 jours"  (onglet "anonymiser les données")
mi juillet

**Comment by MaelREBOUX** [comment]
Je viens de mettre à jour 3.13.1 -> 3.13.6
RAS

**Comment by Marc-marc-marc** [comment]
tu as listé "info smtp" : il n'y a pour le moment pas de smtpd central sortant dans l'infra. le plus simple est soit d'en installer sur cette vm (la + part des autres serveurs utilisent postfix) soit de mettre le mx du domaine souhaité (ex listes.openstreetmap.fr si tu veux envoyer un email aux emais de ce domaine)

**Comment by Marc-marc-marc** [comment]
pour info https://listes.openstreetmap.fr/wws/arc/association/2020-06/msg00031.html
Florian LAINEZ y dit (à propos du site wordpress)
> Le module de stat WP-Matomo n'est pas bien configuré et ne renvoie rien

**Comment by MaelREBOUX** [comment]
Rajout d'un script cron pour calculer automatiquement les rapports toutes les heures

```
# +++++++++++++++++++
# matomo
# pour tester >>  su www-data -s /bin/bash -c "/usr/bin/php /data/www/vhosts/stats.osm.fr/htdocs/console core:archive --url='https://stats.openstreetmap.fr'"
0 * * * * /usr/bin/php /data/www/vhosts/stats.osm.fr/htdocs/console core:archive --url='https://stats.openstreetmap.fr' > /dev/null
```

https://matomo.org/docs/setup-auto-archiving/

**Comment by MaelREBOUX** [comment]
@Marc-marc-marc  pour le SMTP, bof : on reçoit surtout les mails informant des maj dispo. Pas vital. Je laisse comme ça pour le moment.

Je regarde pour le plugin WordPress

**Comment by MaelREBOUX** [comment]
Quelqu'un avait modifié le token global de Matomo. Pour ça que ça ne fonctionnait plus.

Étrange car les infos pour les stats remontaient quand même vers Matomo pour calcul.

**Comment by overflorian** [comment]
Hello @MaelREBOUX sur conseil de @Marc-marc-marc je te demande un accès à Piwik.
J'ai quelques modifs sur openstreetmap.fr (dont je suis admin) et j'aimerai étudier les stats pour pouvoir hiérarchiser les futures évolutions. Merci par avance.

**Comment by MaelREBOUX** [comment]
@overflorian oups : demande passée sous les radars. Je te fais ça mais il me faut une adresse de courriel.
On peut voir ça sur IRC ?

**Comment by frodrigo** [comment]
Fermé sur demande de @MaelREBOUX
