### ISSUE TITLE
maj des versions qui ne sont plus maintenue, principalement les os

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#173]
une partie de l'infra tourne sur des versions qui ne sont plus maintenue

**Comment by cquest** [comment]
Pour les hosts, le plus ancien est osm12, en centos6 mais pas encore obsolète (EOL en novembre 2020).

Pour les containers... possible de lister avec case à cocher pour suivre l'avancement ?

**Comment by jocelynj** [comment]
J'ai récupéré la liste avec `ansible all -m setup -a 'filter=ansible_distribution_release'`, puis `grep ansible_distribution_version ansible_cache/* | grep '"[78]'`:

* version 7 (=wheezy)
  - [ ] osm105.openstreetmap.fr
* version 8 (=jessie)
  - [ ] osm23.openstreetmap.fr
  - [ ] osm103.openstreetmap.fr
  - [ ] osm104.openstreetmap.fr
  - [ ] osm108.openstreetmap.fr
  - [ ] osm138.openstreetmap.fr

**Comment by Marc-marc-marc** [comment]
maj osm105 de wheezy en jessie en attendant que son hosteur supporte mieux ou qu'on migre le contenu ailleurs

**Comment by jocelynj** [comment]
Merci - j'ai du coup copié osm105 dans la partie jessie.

**Comment by cquest** [comment]
osm24 maintenant en buster, comme tout s'est bien passé, je fais de même avec osm23

**Comment by cquest** [comment]
osm23 lui aussi en buster, j'ai profité de la migration/upgrade de VM pour terminer l'upgrade debian

**Comment by JacLavi** [comment]
Si des « case à cocher  » me sont accessibles je suis candidat.

**Comment by jocelynj** [comment]
@cquest , @Marc-marc-marc : est-ce qu'on désactive définitivement osm149 et osm152, qui étaient prévues par du monitoring en 2018, mais pas utilisées depuis ?

**Comment by Marc-marc-marc** [comment]
les monitorings actuels ne me sont pas utile (déluge de notification ou absence de notification nécessaire), donc pas d'avis sur quoi garder vu que j'utilise aucun de ceux en place.
par contre si désactiver=garder sur les serveurs de prod, cela me semble peu utile. soit on a espoir de les mettre en route soit on supprime

**Comment by cquest** [comment]
osm149 et 152 ne me manqueront pas, vu que les services n'ont jamais été effectifs. tu peux éliminer.

**Comment by jocelynj** [comment]
osm149 et osm152 sont maintenant éteints, et désactivé au boot sur osm28. Je supprimerai dans quelques jours.

**Comment by jocelynj** [comment]
osm153 ayant été migré sur osmose.vm, il ne reste plus que osm146, pour le site web prev.openstreetmap.fr.

**Comment by jocelynj** [comment]
osm146 est actuellement bloqué par php/drupal, d'où passage sur un site statique - cf #370
