### ISSUE TITLE
màj carte des serveurs de l'asso sur umap

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#176]
http://umap.openstreetmap.fr/fr/map/serveurs-osm-fr_4188#6/47.048/3.076
- ajouter les osmose-* (dont Paulla)
- virer les ko

**Comment by cquest** [comment]
J'ai mis à jour pour ce que je connais ;)
- aquinetics, grenoble et cachan sont en gris car plus rien chez eux
- j'ai ajouté ce qui est chez moi
- pas sûr pour Nantes, on a encore de l'infra là bas ?

**Comment by zorun** [comment]
Le cache tuile osm.org de Paulla n'a pas/plus l'air d'exister ? https://hardware.openstreetmap.org/

En revanche il y a de nombreux autres caches osm.org en France, mais les recenser sur une carte est un peu redondant avec le suivi osm.org.

**Comment by cquest** [comment]
Cette carte montre les serveurs de l'asso OSM France ou mis à disposition pour l'asso.
Il n'y en a que deux qui servent de cache pour nos tuiles... rien à voir avec ceux de la fondation.

**Comment by Cyrille37** [comment]
Je ferme ce vieux ticket. J'ai ajouté le lien de la carte sur la [page des serveurs](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#%C3%89tat_des_services).
