### ISSUE TITLE
6tunnel sur osmose slave

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#178]
hivane1 et 2 utilisent 6tunnel vers osm26.
il faudrait migrer le script est dans un répertoire avec backup et/ou etckeeper, par exemple /data/project/6tunnel ou /etc/cron-6tunnel

**Comment by Marc-marc-marc** [comment]
les ip 2001:41d0:1008:1f65:10::100 à 104 jadis sur osm26 n'y sont plus, peut-être lié à https://github.com/osm-fr/infrastructure/issues/209
j'ai mis en pause hivane1 hivane2 aquilenet
a noter que download.openstreetmap.fr est renseigné comme utilisant le tunnel alors qu'il est dispo en ipv6

**Comment by jocelynj** [comment]
Pour download.openstreetmap.fr, je l'avais mis parce que hivane n'a qu'une connectivité ipv6, et que osmosis (ou java?) ne sait/savait pas se connecter en ipv6-only.

J'ai remis ces IP sur osm26, en lançant le bout de code qui est dans /etc/network/interfaces, et je ne sais toujours pas pourquoi ces post-up n'ont pas été lancé au dernier reboot.

**Comment by Marc-marc-marc** [comment]
il y a une utilitée réelle à avoir autant d'ipv6 sur osm26 ? une seule ip et une seule range serrait beaucoup plus lisible

**Comment by jocelynj** [comment]
Remplacé par wireguard - #402.
