### ISSUE TITLE
supprimer ou commenter les host mort ?

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#179]
@Jocelyn ta maj de hosts.conf pour munin a réinjecter une série de host mort depuis longtemps
osm101.openstreetmap.fr
osm102.openstreetmap.fr
osm109.openstreetmap.fr
osm110.openstreetmap.fr
osm111.openstreetmap.fr
osm112.openstreetmap.fr
osm116.openstreetmap.fr
osm117.openstreetmap.fr
osm135.openstreetmap.fr
osm137.openstreetmap.fr
osm150.openstreetmap.fr
osm235.openstreetmap.fr
ne serrait-il pas utile de les commenter dans le fichier hosts d'ansible ?

**Comment by jocelynj** [comment]
C'est bizarre, parce que osm101 et osm102 sont commentés dans le fichier hosts - je vais vérifier ce qui se passe lors du lancement d'ansible sur le serveur munin.

**Comment by jocelynj** [comment]
Fait sur https://github.com/osm-fr/ansible-scripts/commit/551cca085b2b8392675829192444f5fc161b96f5.
