### ISSUE TITLE
test non abouti

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#180]
plusieurs vm de test reste en l'état alors que cela n'a pas abouti. on vire ? on relance ?
- [ ] osm130 maposmatic
- [x] osm135 bato
- [ ] osm151maposmatic backend
- [ ] osm303 dev-analyser
- [x] osm312 dev-comcommaker

**Comment by frodrigo** [comment]
comcommaker je maintenais, mais ça n'a plus vraiment d’intérêt maintenant.

**Comment by Marc-marc-marc** [comment]
il est ko et il y a une demande [sur le forum](https://forum.openstreetmap.fr/viewtopic.php?f=5&t=7418)
pourquoi il te semble ne plus avoir d'intérêt ?
si est maintenu, je t'ajoute un compte sur osm312 pour le remettre sur pied ?

**Comment by frodrigo** [comment]
Le volume de zones à fusionner maintenant n'est plus le même qu’en fasse initiale de création.

**Comment by gendy54** [comment]
Concernant Bato à voir avec @overflorian, mais à mon avis, on peut le dégager.
L'idée était de lancer le Bano pour les transports, mais depuis cela a été repris par Etalab.

**Comment by gendy54** [comment]
Concernant MapOsmatic, il était question de créer une instance française pour reprendre ce service très utile qui est longtemps resté en carafe. On entend plus parler de pb, mais ca semble moins urgent.

**Comment by overflorian** [comment]
En effet on peut dégager BANO. Le projet a abouti sur Jungle Bus donc on peut dire qu'au final ce fut un succès :D

**Comment by gendy54** [comment]
Bato tu veux dire ;)

**Comment by Marc-marc-marc** [comment]
@overflorian tu parles bien de baTo ?

**Comment by frodrigo** [comment]
@Marc-marc-marc oui c'est bien BATO (transport), comme Jungle Bus

**Comment by overflorian** [comment]
Oui Bato, désolé, lapsus

**Comment by frodrigo** [comment]
Les vm restantes ne sont plus dans la liste des serveurs, on doit pouvoir cloturer.
