### ISSUE TITLE
nextcloud n'est plus là :)

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#182]
en ligne https://nextcloud.openstreetmap.fr/ "Update in process"

par le client "Aucune connexion au serveur Nextcloud" le serveur a répondu "503 service unavailable"

**Comment by jocelynj** [comment]
Nextcloud est à jour sur la version 18.0.6, et la VM sur debian buster (la dernière stable)

**Comment by vinber** [comment]
hiphiphip hourra :) merci
