### ISSUE TITLE
Le rendu humanitaire est en carafe sur les niveaux 18, 19 et 20

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#183]
C'est tout gris : https://www.openstreetmap.org/#map=18/43.42571/-1.59358&layers=H

**Comment by Marc-marc-marc** [comment]
Jun 04 17:30:52 osm13 renderd[15134]: socket bind failed for: /var/run/renderd/renderd.sock
le répertoire manque, sans doute depuis le reboot, sans doute créé à la main les autres fois (c'0est le défaut de ne pas rebooter souvent).
créé à la main, redémarage renderd ok, tuile ok

**Comment by vinber** [comment]
merci !

**Comment by vinber** [comment]
les lampadaires me manquaient :)
