### ISSUE TITLE
vérifier la création de /var/run/renderd sur les serveurs de rendu au démarage du service

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#184]
cfr #183

**Comment by jocelynj** [comment]
Ça pourrait se faire directement dans l'unit systemd.

**Comment by cquest** [comment]
ajouté dans /etc/systemd/system/renderd.service sur osm13

**Comment by cquest** [comment]
Ajouté sur osm13, osm25 et osm166

Je n'ai pas trouvé de config ansible pour cela.
