### ISSUE TITLE
munin indispoblie quasi tous les jours

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#186]
munin est indisponible quasi tous les jours, parfois même plus d'une fois par jour, même la page statique.
suffit de redémarrer apache pour rétablir.
j'ai augmenté le nombre de worker pendant pouvoir ensuite faire un status, mais le status semble passer de "tout est normal" à "il y a plus un slot libre donc pas de status"
a faire :
- activer monit (et voir s'il faudrait ajouter qlq chose dans ansible pour cela)
- chercher la cause

**Comment by Marc-marc-marc** [comment]
activation monit : fait

**Comment by jocelynj** [comment]
Corrigé par @cquest, en désactivant les plugins munin apache sur cette VM.
