### ISSUE TITLE
TMS Cadastre et BANO ne répondent pas

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#188]
Le serveur https://tms.cadastre.openstreetmap.fr/*/tout/17/67603/46680.png ne répond plus.

https://lists.openstreetmap.org/pipermail/talk-fr/2020-June/099960.html

**Comment by Marc-marc-marc** [comment]
la maj debian wheezy vers jessie a provoqué des soucis avec la conf très particulière d'apache
en cours...

**Comment by Marc-marc-marc** [comment]
pour bano : déplacé dans https://github.com/osm-fr/infrastructure/issues/189 parce que non lié à ce problème

pour cadastre :
- soucis 1 : dans la config des vhost (fichier ne se terminant pas par .conf alors que la nouvelle version a un include précisant *.conf, corrigé.
- soucis 2 : le [code ruby](https://github.com/osm-fr/cadastre-joker) ne semble pas répondre comme il devrait.

**Comment by frodrigo** [comment]
C'est moi qui ai fait ça et connais ruby. Je regarde ce soir.

**Comment by frodrigo** [comment]
Pour moi ce n'est pas un erreur ruby mais de config de apache surement à corriger apres la mise à jour
```
[Fri Jun 19 14:33:11.669783 2020] [proxy:warn] [pid 7522] [client 163.62.112.57:20917] AH01144: No protocol handler was valid for the URL /*/tout/16/33607/22252.png. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.

```

**Comment by frodrigo** [comment]
Un `a2enmod proxy_http` a corrigé le problème de config apache.

**Comment by frodrigo** [comment]
Pour les erreurs ruby qu'il y a ensuite j'ai mise à jour les dépendances, il devait y en avoir des binaires.

Problème suivant, il faut que la postgres marche. Là elle est off, elle doit être HS suite à la mise à jour. Elle contenait les limites de communes de 2017. Je pense que l'on doit pouvoir le recréer et y mettre des données plus actuelles.

**Comment by frodrigo** [comment]
up

**Comment by Marc-marc-marc** [comment]
pour mémoire, le service est lancé par : 
/var/spool/cron/crontabs/cadastre-joker
@reboot bash ~/run.bash &

**Comment by Cyrille37** [comment]
Merci <3
