### ISSUE TITLE
Mise à niveau du rendu BANO actuellement indisponible

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#189]
multiples soucis :
- la bdd osm utilisée ne se met plus à jour
- le rendu ne fonctionne pas depuis mai, même pour les veilles données
- le code pointe vers bano v1 dont les sources (fantoir, ...) ne sont plus à jour
- l'os et les logiciels des 2 serveurs (rendu et bdd) utilisés sont archaïque

solution : 
choix 1 : mettre le rendu (=la feuille de style utilisé par renderd) sur osm166 afin de mutualiser toute la partie render/mod_tile/script d'expiration des tuiles/... au prix d'une "dépendance" (le rendu utiliserait donc 2 vm : renderd+bdd, comme d'ailleurs cyclosm)
choix 2 : mettre le rendu (=la feuille de style utilisé par renderd) sur osm162 afin d'avoir tout bano v2 sur une seule vm, au prix d'une duplication render/mod_tile/script dont on peux atténuer l'impact si on s'abstient de modifier la version de chaque serveur et si le role ansible gère la maj sans écraser les fichiers de conf existant (à vérifier)

**Comment by cquest** [comment]
Il faut revoir le style, car je pense que la base PG de bano2 n'a plus exactement la même structure.
C'est une refonte un peu plus importante qu'il faut envisager.

Pourquoi osm166 ? C'est le container de cyclosm, que j'éviterai de mélanger avec BANO.
Il serait plus cohérent qu'une couche BANO soit produite par le container BANO, en interrogeant osm165 là où c'est nécessaire (ça ne l'est peut être même pas).

**Comment by vdct** [comment]
Oui cyclosm a ses propres contraintes, et d'autant plus si le rendu devient accessible depuis osm.org. Les ressources pour les tuiles BANO v2 n'ont sûrement pas besoin des mêmes capacités. 
@cquest  partant pour retravailler les requêtes Mapnik en fonction des changements de modèle entre bano v1 et v2, j'aurai juste besoin d'un pied à l'étrier de ta part

**Comment by Marc-marc-marc** [comment]
un des soucis actuels c'est qu'il y a 6 serveurs de rendus, tous différent en version logiciel et en script
alors une façon d'harmoniser cela vers le haut c'est de mettre les maigres tuiles bano v2 sur un des serveurs de tuiles existant au lieu de créer un 7ieme serveur de rendu, et vu que le seul serveur "ansible" de rendu est osm166, c'est pour cela que je pensais à lui.
Il est trivial d'installer un 7ieme serveur de rendu si un jour les qlq tuiles banos pertubent cyclosm... mais à mon avis la priorité et le soucis n'est pas là

**Comment by cquest** [comment]
Marc, le rendu BANOv2 na pas besoin de s'appuyer sur une base monde osm2pgsql.

Si il y a un rôle ansible pour déployer un apache+mod_tile/renderd + un style sur github, ça peut sûrement simplifier le déploiement initial et l'administration.

Mais je ne vois pas l'intérêt d'avoir ça sur osm166, c'est sur le CT de BANO que ça a plus logiquement sa place de mon point de vue pour ne pas se créer d'interdépendances.

**Comment by Marc-marc-marc** [comment]
j'ai maj la description de l'issue avec les 2 choix possibles.
cyclosm dépend aussi de 2 CT différent renderd<>bdd. cela apporte de la souplesse.
passer du temps en premier sur tout duplique est évidement une possibilité, temps qui ne serra donc pas passé en premier sur la création de la seule chose qui manque : la feuille de style v2
je vous laisse choisir la priorité, mon avis est connu.

**Comment by cquest** [comment]
@vdct pour mémoire, le projet cartocss est sur https://github.com/osm-fr/bano-cartocss si tu veux t'y mettre

Il faut l'adapter pour le nouveau schéma de BANOv2, il n'a pas bougé depuis 2018.

Il y a des requêtes que tu va aimer qui croisent adresses et voirie pour montrer ce qui manque dans OSM.

Bien sûr dispo si besoin d'aide !

**Comment by vinber** [comment]
Je fais une petite tournée pour savoir comment cela se passe !
Toujours indisponible, cela a été séparé en 2 taches #196 #19, cette isue est-elle toujours nécessaire ?

**Comment by cquest** [comment]
Rendu BANOv2 de retour, je ferme !

**Comment by tuxayo** [comment]
Super nouvelle, merci beaucoup aux personnes qui ont travaillées dessus!
