### ISSUE TITLE
overpass osm-fr

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#19]
runtime error: open64: 0 Success /ssd/overpass/database/areas.bin.idx File_Blocks_Index: bad pos in index file
info venant de Stereo sur irc.
je supose qu'il a fait une requête sur une aire
j'ai reproduis le cas pour l'ajouter dans le moniteur script ~marc_marc/test_area.sh (il reste à comprendre pq il ne veux pas l'exécuter sur localhost

**Comment by Marc-marc-marc** [comment]
autre problème : 
-saturation espace disque. il semble y avoir un bug dans le script qui n'efface pas les fichiers apres utilisation.
j'ai fait un nettoyage à la main. la base de donnée est corrompue.
j'ai lancé un download_clone pour récupérer une base saine

**Comment by Marc-marc-marc** [comment]
maj en version 0.7.54.13
download_clone fait
reconstruction des area fait
redirection vers osm-de supprimée
le serveur refonctionne, j'attends qlq heures pour vérifier que tout est stable avant de faire la modif sur le wiki

**Comment by Marc-marc-marc** [comment]
pour mémoire on a migré la semaine passée osm147 sur le ssd (confusion hdd-sDd (4ieme disque) <>sDd)

**Comment by Marc-marc-marc** [comment]
Fait la semaine passé : 
- migrer le reverse proxy de osm148 vers osm147
- migrer /ssd de osm148 vers le ssd
- migrer le reverse proxy de osm147 vers osm148

A faire : 
- adapter les patchs à la dernier version d'overpass api et mettre à jour osm147 puis osm148

**Comment by Marc-marc-marc** [comment]
> Fait la semaine passé :
>     * migrer le reverse proxy de osm147 vers osm148

semble avoir été annulé. a vérifier. cause du premier problème signalé dans #101 

> A faire :
>     * adapter les patchs à la dernier version d'overpass api et mettre à jour osm147 puis osm148

toujours à faire,cfr deuième problème dans #101

**Comment by matkoniecz** [comment]
According to https://wiki.openstreetmap.org/wiki/Servers/overpass.openstreetmap.fr

"Since 21 September 2017, it is now offline, the Overpass API (via this URL only) is redirected to the German instance."

but per

> redirection vers osm-de supprimée
>le serveur refonctionne, j'attends qlq heures pour vérifier que tout est stable avant de faire la modif sur le wiki

it seems outdated. Would it be OK for me to edit Wiki to remove this note?

**Comment by matkoniecz** [comment]
I managed to find way to check this

> [out:xml][timeout:60];
way[building](if: length()>1000.0)({{bbox}}); out meta;>; out meta;

query works on German instance but crashes on French one. I will remove redirect claim in the wiki.

**Comment by Marc-marc-marc** [comment]
Hello,
yes indeed the redirect was removed a long time ago. thanks for the fix.
Regards,
Marc

**Comment by frodrigo** [comment]
Can we close?

**Comment by Marc-marc-marc** [comment]
base corrompue sur osm147 le 2020-06-19 à cause d'un manque de place sur /ssd
en cours : download_clone.sh
a faire : ajout d'un test dans le script de maj pour sortir en erreur en cas d'espace faible

**Comment by Marc-marc-marc** [comment]
instance à nouveau hs suite aux plantages de osm26 (entre temps résolus), clone à lancer.
constat que la config mémoire a été réduite à 512Mo pour une raison inconnue, qui sait pourquoi ?

**Comment by Marc-marc-marc** [comment]
en l'absence de réponse et de documentation concernant cette modification, je prévois de l'annuler demain

**Comment by jocelynj** [comment]
En regardant la config /etc/pve/nodes/osm26/lxc/147.conf (et git log), je vois que la config mémoire n'a pas bougé, et est à 16384 Mo.

Et il y a bien 16Go sur osm147. Tu parles d'une autre VM ?

**Comment by Marc-marc-marc** [comment]
je parle bien de osm147 qui dans le gui proxmox affiche 512Mo + un message d'erreur Result verification failed (400)
[6].value: type check ('string') failed - got ARRAY
D’où ma question vu les modifs faites autour du plantage de osm26 pendant mon absence

**Comment by jocelynj** [comment]
Je n'utilise jamais le GUI pour modifier la RAM, du coup, je ne sais pas pourquoi l'interface web donne des infos différentes de celles réellement utilisées par osm147.

**Comment by Marc-marc-marc** [comment]
problème GUI sorti de ce ticket pour un ticket dédié https://github.com/osm-fr/infrastructure/issues/225
clone base overpass en cours...

**Comment by Marc-marc-marc** [comment]
clone et lag résorvé vers 13h, création des area en cours

**Comment by Marc-marc-marc** [comment]
```
After 37h6m27s: in "osm-script", part 0, on line 2.
update finished
```
les area sont à nouveau disponible

**Comment by bagage** [comment]
@Marc-marc-marc l'instance est down à nouveau ?

**Comment by Marc-marc-marc** [comment]
@bagage oui l'espace disque n'est plus assez grand pour contenir toute la base. j'ai relancé la reconstruction (~1h), à défaut d'avoir assez d'espace disque, il faut que je continue a blinder les scripts pour ne pas corrompre la base lorsqu'on approche la saturation

**Comment by bagage** [comment]
Ce n'est pas possible de le relocaliser sur un autre serveur et/ou d'augmenter son espace disque ?

**Comment by Marc-marc-marc** [comment]
c'est un problème humain bien avant d'être un problème technique.
le lag des données est résorbée puis a ensuite réaugmenté légèrement. sur ce point c'est le cpu qui sature.
Vu que le host se tourne les pouces avec un pic cpu de 33% seulement et que la raison du bridage est inconnue/non documenté ou pas vu où c'était documenté, j'ai remonté l'allocation cpu de 1 coeur à 2 coeurs.
il est probable que je remonterai encore selon les besoins des area (qui n'est pas encore réactivé)

**Comment by Cyrille37** [comment]
Hello
Sur la page [serveurs du wiki](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France) il semble que tous les points OverpassAPI d'osm_fr sont abandonnés. Est-ce le cas ?

**Comment by Cyrille37** [comment]
Bon, je conclus que ce ticket peut-être clot ;-)
