### ISSUE TITLE
Quel avenir pour osm105 (rendu "layers") ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#191]
Serveur "historique", installé à l'origine par sly !

osm105 fournit:
- les rendus "layers", très historiques... 30000 tuiles servies en une semaine
- le rendu BANO, aussi 30000 tuiles servies en une semaine mais à migrer/refondre

Je ne vois pas d'autres services dessus, l'essentiel est donc une base monde, schéma osm2pgsql... dont la mise à jour est stoppé depuis à cause d'osmosis et de la version de java.

La base PG monde était aussi utilisée aussi par les scripts BANO, mais BANO2 est maintenant autonome (à confirmer par @vdct). C'était aussi notre base monde de secours pour le rendu FR lorsqu'il n'y avait qu'osm13 comme serveur de tuiles.

Si on doit les conserver, les couches de **layers** pourraient s'appuyer sur la base monde d'osm165. Mon avis est que cela n'a plus d'utilité, on a beaucoup mieux en outils QA depuis longtemps.

Pour le rendu BANO, il faut créer le nouveau (BANOv2), potentiellement directement depuis la base interne de BANOv2.

Je propose de vérifier que la disparition des "layers" n'attristera personne en stoppant apache et en attendant une éventuelle réaction.
_________________

- [x] Les rendus "layers", ont été migrés sur osm13: https://github.com/osm-fr/infrastructure/issues/195
- [ ] Rendu BANOv2 à remettre en place: https://github.com/osm-fr/infrastructure/issues/189

**Comment by vinber** [comment]
c'est quoi des rendus layers ?

le rendu BANO c'est le rendu avec les couleurs concernant les adresses ? mais il est trés difficielement utilisable car vraiment trés lent en plus non ?

**Comment by cquest** [comment]
CQFD: si on le coupe, ça ne te manquera pas ;)

C'est ici: http://layers.openstreetmap.fr/?zoom=14&lat=44.79586&lon=-0.55525&layers=B000000000FTFFFFFFFFFFFFFFFFFFFFFFFFFFF

là tu as les voies sans nom...

**Comment by vinber** [comment]
ok, mais en fait ma difficulté (je connaissais effectivement) c'est que souvent c'est vide ou lent, mais les idées sont supers.
Exemple ici les voies sans nom (merci d'avoir mis cela sur Boreaux pour que j'aille voir :) :) ) c'est super mais je zoome et je n'ai rien qui arrive, donc j'abandonne, je viens l'écrire ici, je repars vérifier, et là je comprends en fait qu'il y a entre 7 et 10 secondes pour afficher la couche. C'est peu utilisable en fait.

**Comment by cquest** [comment]
Oui, c'est devenu peu utilisable... en lien avec la masse de données qui n'est plus du tout la même aujourd'hui et à l'époque où cela avait été mis en place.
Même code, même machine, mais bien bien plus de données !
Des optimisations sont sûrement possibles, mais je comme pense que ça n'est plus utilisé que très marginalement, c'est l'occasion de s'alléger...

Pour chercher des rues sans nom, une requête overpass (qui n'existait pas à l'époque) fait aujourd'hui bien mieux l'affaire.

**Comment by Marc-marc-marc** [comment]
on refait la même discussion un peu partout :)
le rendu bano est ko depuis début mai, totalement ko, ce qu'on voit sont des bouts de cache

il était proposé de migrer les rendus de osm105 vers osm166, pour ceux qui sont à conserver

**Comment by vdct** [comment]
Je confirme qu'osm105 servait pour alimenter BANO v1 en données OSM. Du point de vue BANO, depuis le passage en BANO v2, il n'y a plus d'utilité pour cette base

**Comment by jocelynj** [comment]
Le rendu layers était pas mal aussi pour voir les communes/départements/régions/pays, et si les relations étaient cassés. Ça utilisait une colonne simplifiée des géométries pour accélerer le rendu à faible zoom, et je ne crois pas qu'on ait cette colonne sur les rendus modernes - à moins qu'on n'en ait plus besoin ?

Par exemple pour les départements autour de Paris: http://layers.openstreetmap.fr/?zoom=9&lat=48.77634&lon=2.5925&layers=000B000000FFFFFFFFFFFFTFFFFFFFFFFFFFFFF (faut attendre ~20 secondes)

**Comment by cquest** [comment]
Une petite base imposm serait plus pertinente (et performante) car pouvant contenir uniquement ce qui nous intéresse plutôt qu'une base monde quasiment complète...

**Comment by vdct** [comment]
Totalement d'accord. C'est exactement le mouvement que j'ai opéré entre bano v1 t v2, au profit d'une base imposm dédiée

**Comment by Marc-marc-marc** [comment]
je n’avais pas réalisé que bano v2 avait une base décidée pour les objets osm, triste nouvelle.

de quel gain de perf parle-t-on ?
osm2pgsql <> imposm ?
select dans une base monde <> base ne contenant que les objets souhaités ?

quelqu'un se risque à chiffre le gain technique ? sachant que le rendu des limites admin, c'est sans doute le genre de chose qu'on devrait garder en cache pour un an
la conséquence humaine en vaut la peine ? car cela veux dire qu'on va passer de 6 serveurs de rendus tous différent à 7, et quand on voit que osm105 est ko depuis 2 mois par manque de temps humain du à sa différence avec les autres serveurs de rendu, cela aurait été l'occasion de résoudre un problème au lieu de cette fuite en avant toujours plus chronophage en sysadmin.

**Comment by frodrigo** [comment]
> je n’avais pas réalisé que bano v2 avait une base décidée pour les objets osm, triste nouvelle.
> 
> de quel gain de perf parle-t-on ?
> osm2pgsql <> imposm ?
> select dans une base monde <> base ne contenant que les objets souhaités ?

Bano est un besoin "méteir", ça me semble logique davoir une base dédié.

> quelqu'un se risque à chiffre le gain technique ? sachant que le rendu des limites admin, c'est sans doute le genre de chose qu'on devrait garder en cache pour un an

C'est un rendu qui sert de débug. Il ne faut qu'il soit figé.

**Comment by vdct** [comment]
Non @Marc-marc-marc pas triste nouvelle" au contraire. Il ne faut pas tout mélanger. Comme le rappelle @frodrigo on parle d'une base métier, et même si le point commun avec d'autres bases (osm2pgsql ou pas) est de stocker des objets OSM, le point commun s'arrête là, tout est différent au niveau modélisation, car taillé pour un besoin précis. Tu peux comparer des talons-aiguille et des bottes en caoutchouc, en disant que les 2 étant des chaussures, elles font double emploi car ce sont toutes des chaussures. Là c'est pareil. S'escrimer à vouloir unifier les BDs est pour moi un non-sujet, une fausse optimisation qui n'optimise rien mais complexifie tout, sous des apparences de simplicité et d'uniformisation.

**Comment by Marc-marc-marc** [comment]
> > je n’avais pas réalisé que bano v2 avait une base décidée pour les objets osm, triste nouvelle.
> > de quel gain de perf parle-t-on ?
> > osm2pgsql <> imposm ?
> > select dans une base monde <> base ne contenant que les objets souhaités ?
> 
> Bano est un besoin "méteir", ça me semble logique davoir une base dédié.

c'est un critère pertinant dans une entreprise qui peux faire un arbitrage entre "c'est important" <> "tout brique différente des autres prend plus de temps".
mais pour osm-fr, il n'y a pas d'option "c'est metier" dans les outils de déploiement ni même pour l'aspect humain (pour preuve c'est ko depuis 2 mois)
soit c'est une brique commune à X outils et mettre à jour ces x copies prend de l'ordre de la minute
soit c'est une brique différente des autres outils et analyser un bug affectant 2 briques différentes 
prend de l'ordre de 2x le temps.

> > quelqu'un se risque à chiffre le gain technique ? sachant que le rendu des limites admin, c'est sans doute le genre de chose qu'on devrait garder en cache pour un an
> C'est un rendu qui sert de débug. Il ne faut qu'il soit figé.

on peux le voir comme cela en effet.
cela ne change pas beaucoup ma question : à quel niveau est le gain ? quel ordre de grandeur de gain on espere ? est-ce que cet ordre de grandeur vaut la peine de subir 2 mois de panne ?

**Comment by cquest** [comment]
Une clarification me semble nécessaire...

Pour BANOv2, il ne s'agit pas de faire un rendu carto, mais d'utiliser des données géographiques pour produire les données BANO. L'utilisation de la base monde osm2pgsql d'osm105 avait été une forme de bricolage, avec une sorte de dépendance externe dans une chaine de traitement par ailleurs fort intégrée et unique.
Il y avait aussi (si ma mémoire est bonne) quelques requêtes vers overpass... et une autre dépendance externe, qui fragilise la chaine de traitement.

Pour le rendu BANOv1, j'ai aussi bricolé entre des données provenant de la base monde d'osm105 + les données BANO que j'allais piocher sur la base PG de BANO... ça marchait, mais là encore de l'inter-dépendance.

Pour le rendu BANOv2, je pense qu'il y aura tout ce qu'il faut dans la base PG de BANO et qu'il n'y aura pas à s'ajouter une dépendance.

Se trimbaler des bases PG d'1To, c'est lourd et souvent handicapant. Pour les rendus carto, la mise en commun a de l'intérêt car on s'appuie quasiment sur les mêmes données (pas à 100% non plus). Les données OSM dans la base PG de BANOv2 c'est 31Go.

**Comment by vinber** [comment]
Si je comprends, cela veut dire que BANOV2 est "autonome", en grande partie gérée par @vdct et @cquest pour le "layer bano". et les layers,, affichage allégé de données thématiques ne nécessite pas l'utilisation d'une base monde.

La question de la mise en commun d'une base monde concerne donc surtout les 3 rendus fr, humanitaire et cyclosm ?
L'objectif étant d'avoir quelques choses "d'homogène" pour ces 3 rendus pour faciliter l'administration, la gestion et la résolution de bugs.

**Comment by Marc-marc-marc** [comment]
ce ticket mélange plein de chose sans rapport, j'ai pris la liberté de diviser le ticket en 3
#189 rendu bano
#195 rendu limite administrative
le reste (?) ici 

l'harmonisation concerne aussi la partie render/apache/... comme détaillé dans les 2 tickets mono-sujet

**Comment by vinber** [comment]
Bonjour,
je ne sais pas faire grand chose, je me perds un peu donc je tente une relance !
Le rendu layers "titre de cette issue" est-il revenu "fonctionnel et utilisable ?

**Comment by jocelynj** [comment]
La seule chose qui reste du ticket original est ce qu'on fait d'osm105. Vu que layers a été migré sur osm167, et que le style bano a été migré sur le ticket #195, on doit pouvoir supprimer la VM osm105.

@cquest, @Marc-marc-marc : vous confirmez ?

**Comment by cquest** [comment]
Pour répondre à @vinber oui, ces rendus sont de retour, on a fait un peu de ménage en supprimant des couches expérimentales qui ne servent à rien.
Le wiki a été mis à jour: https://wiki.openstreetmap.org/wiki/FR:Serveurs/layers.openstreetmap.fr

Il n'y a que le rendu BANO qui manque à l'appel.

@jocelynj , on peut l'éteindre déjà pour voir ;)

**Comment by vinber** [comment]
merci :D

**Comment by cquest** [comment]
Fin de sujet... RIP osm105
