### ISSUE TITLE
osm153 frontend osmose à réinstaller

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#193]
Sur osmsoe frontend le répertoire /etc/apache2/.links2 dans la structure
d'apache avec des fichiers de liens douteux laisse penser que le serveur
s'est fait hacké, probablement en 2018 vu l'age des fichiers.
je préconise de réinstaller le serveur depuis 0 via ansible
et de ne reprendre que le dump de la bdd si nécessaire.
ce serra aussi l'occasion de passer en debian buster histoire
d'avoir une version python identique à celle du docker.
cela ferra une différence de moins pour le bug remonté par Noémie.

**Comment by jocelynj** [comment]
J'ai regardé plus en détail, et en fait, ce répertoire .links2 est lié au programme links2, qui est un navigateur internet. Je suppose que quelqu'un a lancé links2 depuis ce dossier, et qu'il a créé ces fichiers de config dans /etc/apache2.

**Comment by Marc-marc-marc** [comment]
vu la présence d'une page de type "site douteux hébergé sur un serveur lui aussi compromis" dans ce répertoire, j'ai l'impression que le "quelqu'un" qui l'a créé n'est pas l'un de nous ayant lancé links2.
je te laisse fermer le ticket si tu le souhaites.

**Comment by jocelynj** [comment]
Le frontend a été réinstallé avec une version plus récente de debian et postgresql, du coup, on peut fermer.
