### ISSUE TITLE
Etudier la necessité de faire un fstrim

### ISSUE THREAD

**Issue by anayrat** [osm-fr/infrastructure#194]
Il peut être nécessaire/utile de faire un fstrim pour les container sur un stockage "thin-provisionné". Ca permet de récupérer l'espace disque. La commande sous proxmox est `pct fstrim <vmid>` pour les container. On peut le croner toutes les semaines par exemple:
```bash
#!/bin/bash

#fstrim de l'hyperviseur
fstrim -av

# fstrim de tout les CT
for vmid in $(pct list|tail -n +2|awk '{print $1}')
do
   pct fstrim ${vmid}
done 
```
Avec cet unit systemd:
```
/etc/systemd/system/fstrim.timer 
[Unit]
Description=Run pct fstrim daily and on boot

[Timer]
OnBootSec=15min
OnUnitActiveSec=1d

[Install]
WantedBy=timers.target
```

```
/etc/systemd/system/fstrim.service 
[Unit]
Description=Perform fstrim

[Service]
Type=oneshot
User=root
Nice=19
ExecStart=/root/fstrim.sh
```

Ca peut aussi être utile sur les vm kvm pour récupérer de l'espace de qcow2 : https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_hard_disk_discard

**Comment by cquest** [comment]
Pas sûr qu'on ait besoin du pct fstrim:
- pas de VM KVM
- l'essentiel des CT en ZFS

Pour les SSD utilisés directement, un fstrim peut par contre être utile.

Comme je ne vois pas d'effet de bord négatif, je pense que ça ne fait pas de mal à ajouter.

**Comment by anayrat** [comment]
Tu es sûr qu'on n'a pas besoin de fstrim pour les containers en ZFS? Ou alors on n'utilise pas de thin provisionning?

**Comment by cquest** [comment]
Avec des CT, proxmox gère ça avec des filesystem ZFS, pas en images disque/raw, je ne vois donc pas ce que le trim viendrait faire.
Pour des VM KVM c'est différent et là ça peut être utile, mais on n'en utilise pas du tout.

**Comment by anayrat** [comment]
Pourtant ça se fait sur des CT, c'est l'utilité de la commande `pct fstrim`. Il faut bien que le CT indique aux couches inférieures qu'il discard tel ou tel bloc. En tout cas ça se fait sur du LVMthin.

Je n'ai pas de proxmox en ZFS sous la main, peut être que tu pourrais tester? Ca doit être assez simple, il suffit de créer un gros fichier avec de la donnée dedans, regarder l'évolution de la taille du volume du CT (en s'assurant qu'il est bien thin povisionné avant).
Supprimer le fichier, regarder si la taille du volume a changé (normalement non), faire un `pct fstrim` là on devrait avoir récupéré l'espace.

**Comment by cquest** [comment]
Les CT en ZFS ne sont pas en thin provisionning, mais fonctionne directement en filesystem (fichiers, etc), la logique est toute autre et pas comparable.
C'est ZFS qui gère son espace sur les disques et sauf si on est sur SSD le trim n'a aucune utilité.

Si on avait un pool avec stockage sur SSD (pas encore le cas), là un `zpool trim` régulier (ou un autotrim=on sur le pool) serait utile pour le SSD (pas pour les CT).

**Comment by anayrat** [comment]
Ahhh ok je viens de comprendre. Sur l'hyperviseur tu vois directement les fichiers des CT et pas juste un volume.

**Comment by jocelynj** [comment]
Je ferme le ticket, vu que non applicable, parce qu'on utilise principalement un stockage direct en ZFS.
