### ISSUE TITLE
service : rendu limite admin dégradé/ko

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#195]
division de #191 en services : le rendu des limites admin fourni sur osm105 est dégradé/ko (bdd sans maj depuis 2 mois). au moins 2 personnes s'en servent et aimeraient le voir rétablit.
candidat possible osm166 dont l'avantage est une harmonisation vers le seul serveur de rendu "ansible" et donc diminution du temps nécessaire pour la maintenance ou pour un éventuel déplacement vers un clone de celui-ci
la question base monde@osm165 <> base dédiée@osm165 <> base ailleurs est à mon avis un autre sujet à discuter dans un autre sujet si besoin afin de se concentrer ici pour aboutir sur un choix de mutualisation ou non de la partie renderd/apache/...
a argumenter si la proposition de candidat n'est pas idéale

**Comment by jocelynj** [comment]
J'ai migré le rendu layers sur osm13, en installant via ansible.

Trois trucs que je n'ai pas automatisé:
  - recompilation de renderd avec XMLCONFIGS_MAX=64 pour autoriser plus de styles
  - configuration de mod_tile
  - expiration des tuiles

**Comment by cquest** [comment]
J'ai rajouté la simplification des géométries au niveau datasource postgis: https://github.com/osm-fr/layers-mapnik-styles/pull/1

Pour le ménage quotidien, /data/project/layers/layers-mapnik-styles/render_tile_purge.sh n'est pas actif ?

Le service est de retour, je retire le label "hs"

**Comment by cquest** [comment]
Certaines couches de "layers", pourraient être éliminées :
- [ ] note : rendu des objets avec un tag note=*, mais **absent de la base car filtré à l'import**
- [ ] my_own : rendu des objets avec un tag 'validate:my_own', non documenté qui sent le truc maison de sly ;)

**Comment by jocelynj** [comment]
Ok, je vire ces deux là de la config généré par ansible

**Comment by jocelynj** [comment]
J'ai enlevé tous ces styles de layers via https://github.com/osm-fr/ansible-scripts/commit/7d24bd577fb1a2dcf7e923c5d37350becb4724f9:
  - bano
  - noref-notertiary
  - note
  - my_own
