### ISSUE TITLE
Peertube 502 Bad Gateway

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#197]
Peertube est down : https://peertube.openstreetmap.fr

**Comment by Cyrille37** [comment]
Related #166

**Comment by cquest** [comment]
shame on me... sorry

**Comment by jocelynj** [comment]
J'ai changé la config apt sur osm155 de la manière suivante, pour éviter d'installer les paquets nodejs venant de Debian. -10 signifie que les paquets de cette origine ne sont pas considérés pour l'installation:
```
/etc/apt/preferences.d/00force-nodejs

Package: nodejs
Pin: release o=Debian
Pin-Priority: -10
```

Ce qui a un impact sur la policy utilisé:
```
$ apt-cache policy
...
Pinned packages:
     nodejs -> 10.21.0~dfsg-1~deb10u1 with priority -10
     nodejs -> 10.19.0~dfsg1-1 with priority -10
```

@frodrigo : est-ce qu'on risque d'avoir le même souci sur le frontend osmose, qui installe aussi le nodejs de nodesource ?

**Comment by cquest** [comment]
Je ferme, vu qu'il n'y a plus de problème.
