### ISSUE TITLE
Cadastre indisponible dans JOSM pour Paris Lyon et Marseille

### ISSUE THREAD

**Issue by Franssoize** [osm-fr/infrastructure#199]
Le cadastre n'est plus accessible dans JOSM pour Marseille Lyon et Paris. Message d'erreur : "la commune demandée n'existe pas ou n'est pas accessible".

**Comment by Marc-marc-marc** [comment]
à ma connaissance, le plugin josm n'utilise rien d’hébergé par osm-fr
je penche pour un soucis dans le plugin josm ou plus vraisemblablement chez etalab

**Comment by frodrigo** [comment]
Non. C'est le TMS cadastre.
Suite au dernier problème, j'ai passé la liste de commune de 2017 à 2020.
Il doit y avoir une histoire avec les arrondissements.

**Comment by cquest** [comment]
Oui, les arrondissements... c'est ce que j'ai indiqué sur talk-fr comme cause probable.

**Comment by frodrigo** [comment]
Ajout en base modif doc.

**Comment by Franssoize** [comment]
Merci merci!

**Comment by bmallet** [comment]
Je plussoie, merci  Frédéric (avec esprit d'escalier;-)
