### ISSUE TITLE
ram sur l'ancien serveur overpass api osm103

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#2]
l'overpass api sur osm103 n'est plus en prod
mais il reste probablement d'autre chose à migrer de cette vm
dici là on pourrait diminuer la ram qui lui est allouée (+ utile temporairement pour le problème osmose frontend)

**Comment by jocelynj** [comment]
J'ai baissé la quantité de ram sur osm103 à 2 GB.
