### ISSUE TITLE
whitelist http://preview.ideditor.com/ pour proxy BDortho IGN

### ISSUE THREAD

**Issue by bagage** [osm-fr/infrastructure#20]
Pour pouvoir utiliser le fond de carte BDOrtho depuis iD via http://preview.ideditor.com/release et http://preview.ideditor.com/master

**Comment by bagage** [comment]
Ping @cquest

**Comment by jocelynj** [comment]
I've just added preview.ideditor.com as allowed on proxy-ign. Can you check ?

**Comment by bagage** [comment]
Yes it works, thanks @jocelynj!

**Comment by althio** [comment]
il y a un comportement bizarre (accès refusé à l'imagerie) sur [cadastre.openstreetmap.fr/segmented](https://cadastre.openstreetmap.fr/segmented) 
c'est utilisé cette page ?
