### ISSUE TITLE
osm11 promox: certificat https expiré le 7 février 2020

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#201]
la tâche tourne dans proxmox : 
Loading ACME account details
Placing ACME order
Order URL: https://acme-v02.api.letsencrypt.org/acme/order/xxx
Getting authorization details from 'https://acme-v02.api.letsencrypt.org/acme/authz-v3/yyy
The validation for osm11.openstreetmap.fr is pending!
Setting up webserver
TASK ERROR: Failed to initialize HTTP daemon

**Comment by jocelynj** [comment]
Je ne vois pas comment la génération par proxmox peut marcher, vu que le port 80 de osm11 va sur nginx pour rediriger vers les différentes VMs. Par contre, on doit pouvoir configurer proxmox pour utiliser le certificat utilisé par nginx.

**Comment by Marc-marc-marc** [comment]
je l'ignore, je constate juste qu'une tâche pour le certificat a été mise en place et qu'elle est en erreur alors qu'on a un certificat valide dans le passé

**Comment by cquest** [comment]
Problème (et solution) similaire à https://github.com/osm-fr/infrastructure/issues/112

**Comment by cquest** [comment]
On ferme ?

**Comment by jocelynj** [comment]
J'avais mis un script dans /usr/local/bin/letsencrypt-to-proxmox.sh, mais c'est pas encore complétement automatisé dans ansible et letsencrypt.

**Comment by jocelynj** [comment]
Le script est maintenant en place sur tous les nodes proxmox, via https://github.com/osm-fr/ansible-scripts/commit/160bb45d273dff95a8f621e74ba8cdb1d854bb93.
