### ISSUE TITLE
osm165: bases PG osm2pgsql étrangement grosse

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#202]
La base PG produite par osm2pgsql sur osm165 est nettement plus volumineuse que ses cousines sur osm13 et osm25.

dans `psql`, `\l` indique 1.3To
un `du` indique la même chose

La vue db_size par contre fournit des infos contradictoires.
Exemple sur planet_osm_line où on a 380 Go au total dont 156 Go de data.
Mais en additionnant la taille des index on a 55 Go d'index et pas 224 Go (380-156).
Et un `\d+` indique... 325Gb pour la même table...

J'ai déjà vu des cas où PG ne libérait pas une partie de l'espace disque qu'il occupe... est-ce que ceci vous inspire ?

L'espace ne manque pas, mais c'est anormal et pourrait poser un problème à terme.

**Comment by anayrat** [comment]
Je peux regarder mais il me faut des accès...

**Comment by anayrat** [comment]
Ok, il te manquait le toast dans tes calculs:

```
select 
	a.relname as table,
	c.relname as index,
	pg_size_pretty(pg_relation_size(a.oid)) as tbl_size_data,
	pg_size_pretty(pg_relation_size(a.reltoastrelid)) as toast_size,
	pg_size_pretty(pg_relation_size(b.indexrelid)) as index_size,
	pg_size_pretty(pg_table_size(a.oid)) as tbl_size_data_index,
	pg_size_pretty(sum(pg_relation_size(b.indexrelid)) over ()) sum_indexes,
	pg_size_pretty(pg_total_relation_size(a.oid)) as tbl_size_data_index_toast
from pg_class  a
join pg_index b on a.oid=b.indrelid
join pg_class c on b.indexrelid=c.oid
where a.relname='planet_osm_line';
      table      |           index            | tbl_size_data | toast_size | index_size | tbl_size_data_index | sum_indexes | tbl_size_data_index_toast 
-----------------+----------------------------+---------------+------------+------------+---------------------+-------------+---------------------------
 planet_osm_line | planet_osm_line_ferry      | 156 GB        | 165 GB     | 2656 kB    | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_bicycle_routes  | 156 GB        | 165 GB     | 356 MB     | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_waterway   | 156 GB        | 165 GB     | 1156 MB    | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_manmade    | 156 GB        | 165 GB     | 51 MB      | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_ref        | 156 GB        | 165 GB     | 1199 MB    | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_minor      | 156 GB        | 165 GB     | 15 GB      | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_osm_id_idx | 156 GB        | 165 GB     | 7732 MB    | 325 GB              | 55 GB       | 380 GB
 planet_osm_line | planet_osm_line_way_idx    | 156 GB        | 165 GB     | 30 GB      | 325 GB              | 55 GB       | 380 GB
(8 rows)

```

**Comment by anayrat** [comment]
Ah et la table est pas mal fragmentée
```
SELECT * FROM pgstattuple('planet_osm_line');
  table_len   | tuple_count |  tuple_len  | tuple_percent | dead_tuple_count | dead_tuple_len | dead_tuple_percent | free_space  | free_percent
--------------+-------------+-------------+---------------+------------------+----------------+--------------------+-------------+--------------
 167552573440 |   204030841 | 65858666336 |         39.31 |          9276238 |     8818266168 |               5.26 | 90057175448 |        53.75
```

**Comment by jocelynj** [comment]
@cquest , @Marc-marc-marc : j'ai passé l'update sur osm165 à toutes les 5 minutes, vu que c'était suggéré par Christian, et que ça devrait diminuer la fréquence d'écriture.

**Comment by cquest** [comment]
à verser au dossier...

http://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm165.openstreetmap.fr/postgres_size_ALL.html

C'est en janvier que la base à commencer à rapidement gonfler en se prenant 400Go, depuis la pente de progression est revenu à celle d'avant janvier, sans récupérer ces 400Go. Que s'est-il passé à ce moment ? Un changement de config ?
etckeeper a fait un daily autocommit le 17 janvier... sauf erreur la seule modif est la désactivation de jit (jit=off).

Le VACUUM d'hier ne semble pas avoir fait gagner significativement de place :(

**Comment by frodrigo** [comment]
Ça peut arriver si on coupe temporairement l'autovaccum, pour des raisons de perf par exemple. On a ça sur la base du front d’osmose.

**Comment by anayrat** [comment]
> à verser au dossier...
> 
> http://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm165.openstreetmap.fr/postgres_size_ALL.html
> 
> C'est en janvier que la base à commencer à rapidement gonfler en se prenant 400Go, depuis la pente de progression est revenu à celle d'avant janvier, sans récupérer ces 400Go. Que s'est-il passé à ce moment ? Un changement de config ?
> etckeeper a fait un daily autocommit le 17 janvier... sauf erreur la seule modif est la désactivation de jit (jit=off).

Probablement un update massif? le jit n'a aucun impact là dessus.

> 
> Le VACUUM d'hier ne semble pas avoir fait gagner significativement de place :(

un vacuum simple ne fait pas gagner de la place, pour ça il faut un full ;)

**Comment by anayrat** [comment]
> Ah vu que c'est étalé sur beaucoup de temps c'est possible que ça soit une transaction ouverte sans activité qui ait bloqué l'autovacuum

Ah en ça collerait bien http://munin.openstreetmap.fr/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=osm11.openstreetmap.fr/osm165.openstreetmap.fr/postgres_autovacuum&size_x=800&size_y=400&start_epoch=1558606646&stop_epoch=1593166646

Il y a eu plein d'autovacuum lancé en boucle j'imagine.

Bingo http://munin.openstreetmap.fr/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=osm11.openstreetmap.fr/osm165.openstreetmap.fr/postgres_querylength_ALL&size_x=800&size_y=400&start_epoch=1558606646&stop_epoch=1593166646

**Comment by cquest** [comment]
Une idée de la cause ces multiples AUTOVACUUM qui sont partis en sucette ?

Donc pour récupérer cet espace perdu, la solution c'est un recompactage des tables, mais pour qu'il ne soit pas bloquant, VACUUM FULL n'est pas la solution, car le rendu de tuiles serait impossible pendant ce temps.

Je fais des recompactages une à deux fois par an sur osm13 et osm25 en procédant ainsi:
- suspension des update d'osm2pgsql
- CREATE TABLE xxx_new AS SELECT * FROM xxx ORDER BY way
- recréation des index (en paralèlle pour gagner du temps et des IO)
- ALTER TABLE xxx RENAME TO xxx_old ; ALTER TABLE xxx_new RENAME TO xxx
- DROP TABLE xxx_old

Si on est short en espace disque, il faut bien sûr commencer par la plus petite. Si on est TROP short en disque, il faut libérer de la place... et là, le plus radical c'est de virer l'index monstrueux sur planet_osm_ways, et le recréer à la fin (c'est TRES long).
Pas de problème de place sur osm165, donc ça sera moins long.

**Pourquoi le "ORDER BY way" ?**
Ce recompactage est l'occasion d'optimiser le stockage des données pour que des données géographiquement proches se retrouvent sur les même pages. Le gain en I/O est très important (j'avais mesuré jusque 8 fois moins d'IO), j'avais fait une conf à ce sujet au SOTM à Buenos Aires, et c'est implémenté depuis dans osm2pgsql et imposm lors des imports.
ATTENTION, ce order by way fonctionne directement avec les versions récentes de postgis, pour les plus anciennes il faut utiliser les geohash pour obtenir quelque chose de similaire.

Avant de se lancer (ce n'est pas urgent), ce serait l'occasion d'upgrader PG en 12 ainsi que postgis si besoin, pour s'harmoniser avec ses cousins et profiter des dernières optimisation de ces deux briques essentielles qui s'améliorent sans arrêt.

**Comment by cquest** [comment]
Recompactage en cours... point, line et roads sont faits, polygon en cours, déjà 400Go de récupérés :)

**Comment by cquest** [comment]
Voici la même requête après recompactage pour planet_osm_line :
```
      table      |      index      | tbl_size_data | toast_size | index_size | tbl_size_data_index | sum_indexes | tbl_size_data_index_toast 
-----------------+-----------------+---------------+------------+------------+---------------------+-------------+---------------------------
 planet_osm_line | line_ferry      | 67 GB         | 9380 MB    | 1672 kB    | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_manmade    | 67 GB         | 9380 MB    | 49 MB      | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_minor      | 67 GB         | 9380 MB    | 12 GB      | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_osm_id_idx | 67 GB         | 9380 MB    | 4373 MB    | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_ref        | 67 GB         | 9380 MB    | 1175 MB    | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_waterway   | 67 GB         | 9380 MB    | 1146 MB    | 76 GB               | 47 GB       | 123 GB
 planet_osm_line | line_way_idx    | 67 GB         | 9380 MB    | 28 GB      | 76 GB               | 47 GB       | 123 GB
(7 rows)
```

123GB au lieu de 380...

**Comment by cquest** [comment]
planet_osm_polygon terminée elle aussi, on passe de 322 à 230Go :)

**Comment by cquest** [comment]
Recompactage terminé, je ferme

**Comment by anayrat** [comment]
> Une idée de la cause ces multiples AUTOVACUUM qui sont partis en sucette ?

C'était à cause d'une requête qui a duré une éternité, les autovacuum tournaient mais ne pouvaient rien faire tant que cette requête ne s'était pas terminée.
