### ISSUE TITLE
osm166 : migrer les tuiles sur ssd

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#204]
extraction de l'hors-sujet de https://github.com/osm-fr/infrastructure/issues/174#issuecomment-649714120
- [ ]  basculer /var/lib/mod_tile sur ssd-sata

**Comment by Marc-marc-marc** [comment]
puisque tu m'apprends par hasar que t'es occupé à cela en ce moment...

**Comment by cquest** [comment]
Désolé, vu que je suis sur osm165 et que les updates sont suspendus, j'ai pensé que c'était le bon moment en oubliant de le signaler ici.

**Comment by cquest** [comment]
C'est fait, osm166 est maintenant sur ssd-zfs, pool ZFS sur le petit SSD SATA de 1To.

**Comment by Marc-marc-marc** [comment]
df -h /var/lib/mod_tile/cyclosm/17
Filesystem                 Size  Used Avail Use% Mounted on
ssd-zfs/subvol-166-disk-0  578G  424G  155G  74% /
il y a une erreur dans la taille du nouveau volume, l'ancien était de 1To pour compléter le cacheavant l'activation de la bascule osm.org, là on va passer son temps à créer/effacer/recréer les tuiles

**Comment by Phyks** [comment]
À l'instant sur osm166,

```
phyks@osm166:~$ df -h /var/lib/mod_tile
Filesystem                 Size  Used Avail Use% Mounted on
ssd-zfs/subvol-166-disk-0  500G  335G  166G  67% /
```

Est-ce volontaire de réduire de moitié la taille du disque alloué au stockage du cache de tuiles ? Il me semblait avoir compris au contraire qu'il fallait plutôt viser d'augmenter cet espace en vue de basculer sur une distribution monde (osm.org).

En tout cas, j'ai l'impression que l'effet est notable en terme de charge du serveur https://munin.openstreetmap.fr/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=osm11.openstreetmap.fr/osm166.openstreetmap.fr/load&size_x=800&size_y=400&start_epoch=1593034364&stop_epoch=1593725564.

**Comment by vinber** [comment]
Salut @Phyks je ne sais pas ce que cela veut dire mais si il faut plus d'espace pour le cache de tuile alors oui nous avons effectivement dit lors de l'ag que nous devions mettre les moyens car nous souhaitons bien que cela arrive sur osm.org.

Ce que je ne comprends pas c'est pourquoi la taille aurait été réduite si il y a besoin de plus de place ?
@cquest @Marc-marc-marc

**Comment by Marc-marc-marc** [comment]
@vinber j'ignore aussi pq la modif précédente a été annulée à l'opposée de la décision collective

**Comment by jocelynj** [comment]
Le SSD est plus petit que les disques durs, et n'a pas 1To de libre - est-ce qu'on a vraiment besoin de 1To de tuiles en SSD ?

**Comment by Marc-marc-marc** [comment]
```
$ ssh osm11.openstreetmap.fr df -h /ssd-sata
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdh1       1.8T  180G  1.5T  11% /ssd-sata
```
l'espace est disponible, ce n'est donc pas cela la question.
gagner 1ms sur la récupération d'une tuile depuis un ssd au lieu d'un disque mécanique n'a aucun sens s'il faut d'abord passer plusieurs secondes à générer la tuile

**Comment by vinber** [comment]
j'avoue que je ne comprends pas, on parle d'un ssd de 1to -> ici il y a 1,8 de dispo. Je suis perdu messieurs :)

mais en résumé, pour cyclosm, si on a la place on la prend et si nous ne l'avons pas on fait en sorte de la trouver :)

**Comment by cquest** [comment]
Pour couper le moins longtemps possible, j'ai transféré le cache de tuiles d'osm166 via synchro ZFS sur un espace libre sur le "petit" SSD dispo sur ce serveur. L'effet sur les IO est déjà bien visible sur les graphes et l'urgence était avant tout là.

On va pouvoir remettre plus d'espace une fois le stockage remis d'équerre, c'est à dire refaire le pool ZFS sur les HDD, migrer l'autre SSD SATA de 2To en ZFS lui aussi.

osm14 sera chez free à partir de mardi prochain pour aider aussi ces migrations.

**Comment by vinber** [comment]
ok, j'ai l'impression que l'urgence dont tu parles ne colles pas avec l'urgence de fournir les tuiles cyclosm. Je relative les urgences néanmoins :)

- d'une part si je comprends le ssd c'est pour arréter les gros pics que montre @Phyks sur le graphe (l'urgence que @cquest  cite).
- d'autre part la taille du disque est réduite mais @Marc-marc-marc dit qu'il y a la place et que cela permettrait de répondre donc à l'urgence de fournir les tuiles cyclosm. Ne peut-on fournir la place sans avoir à remettre tout d'équerre ?
