### ISSUE TITLE
uMap et calques de données externes cassé (CORS)

### ISSUE THREAD

**Issue by gsurrel** [osm-fr/infrastructure#206]
Salut !

J'ai des cartes uMap qui récupèrent des données depuis l'exterieur, et il semblerait que la politique de sécurité ait récemment changé car maintenant, chaque requête vers le fournisseur de données est bloquée par le navigateur :

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://docs.google.com/spreadsheets/[redacted]. Raison : échec de la requête CORS.

Un exemple est la carte suivante :
https://umap.openstreetmap.fr/fr/map/mes-chateaux-a-acheter_467594

**Comment by Marc-marc-marc** [comment]
à voir la config sur l'ancien serveur avant le jeu de chaise musicale

**Comment by cquest** [comment]
Quel ancien serveur ? osm144 est opérationnel depuis bien longtemps.

Il n'y a en effet aucun entête CORS dans les headers renvoyés actuellement par umap.openstreetmap.fr, rien dans la config du proxy sur le cluster, rien dans la config nginx sur osm144 inchangée depuis avril 2019 ce qui me fait penser que c'est plutôt un politique plus dure côté navigateur qui cause désormais ce problème.

@yohanboniface ok pour ajouter la totale ?

**Comment by yohanboniface** [comment]
Si j'ai bien compris le problème, ajouter les headers CORS à uMap ne changera rien, c'est le serveur distant qui "pose problème".

Après, est-ce que c'est pas bêtement un souci https vs http ? C'est-à-dire que si on charge uMap en https, et que la requête vers les données distantes est en http, elle sera bloquée par le navigateur.

**Comment by gsurrel** [comment]
Alors j'avoue ne pas vraiment savoir comment se passe en détail la gestion des headers CORS. J'ai supposé que c'était posé par le serveur qui sert la page, mais je peux tout à fait me tromper.

Après inspection dans la console, il est vrai que je ne vois rien de spécial y faisant référence...

J'ai testé en changeant de http**s** à http dans le calque de données distantes que j'ai donné en exemple, mais je me retrouve avec une autre erreur (qui me semble tout à fait légitime) :

> Blocage du chargement du contenu mixte actif (mixed active content) « http://docs.google.com/spreadsheets/[redacted] »

Je vais remettre l'adresse en https en attendant.

Pour information, ça marchait jusqu'à jeudi passé (de mémoire) depuis Chrome sur un téléphone. Avant le rapport de bug, j'avais aussi testé avec un Firefox (macOS et Ubuntu) sur un profil vierge.

**Comment by yohanboniface** [comment]
> J'ai testé en changeant de https à http dans le calque de données distantes

Si le calque est en https, alors c'est bon (j'aurais pu regarder moi-même, désolé, répondu un peu vite).

Apparemment, on est pas le seul à constater le changement:

https://stackoverflow.com/questions/62587802/fetching-a-google-sheet-csv-file-yields-cors-error

**Comment by yohanboniface** [comment]
> Je comprends ça comme "ça n'aurait pas dû marcher avant, mais maintenant, ça réagit comme attendu". Par contre, si uMap interdit toutes les données venant d'ailleurs, ça casse un peu l'idée de la fonctionnalité de calque "Données distantes". sweat_smile

uMap n'y est pour rien ;)

C'est un "souci" entre un navigateur (en l'occurrence le tien) et un serveur (en l'occurrence celui de Google).

En attendant, tu peux cocher "Cacher la requête", c'est un façon de contourner le souci (la requête va partir sur nos serveur, qui vont eux-mêmes demander à Google, puis renvoyer la sauce).

**Comment by gsurrel** [comment]
@yohanboniface Oh, merci d'avoir trouvé ces infos.

D'ailleurs, en regardant du côté de "Cacher la requête", il y a une option "Proxy" qui a comme bulle d'information :

> Cocher si le serveur distant n'autorise pas le cross domain (plus lent)

Du coup c'est exactement mon cas 🤦  Merci beaucoup du coup, c'est super et ça marche :)
Je vous laisse fermer le ticket si vous pensez qu'il peut permettre de faire un suivi quelconque.
