### ISSUE TITLE
blocage osm2pgsql sur les 3 serveurs de rendu principaux - > maj osm2pgsql 1.2.2

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#208]
bloqué depuis ce matin, selon TomH, il faudrait faire une maj
osm2pgsql 1.2.1 which is 1.2.0 with a newer libosmium that fixes a bug where complex relations can use large amounts of memory and hence time
________
Mise à jour à faire sur:
- [x] osm13
- [x] osm25
- [x] osm165

**Comment by Marc-marc-marc** [comment]
hum, osm13 a bien besoin d'une maj
mais étrangement osm25 et osm165 sont deja en v1.2.1, donc p'tre un autre problème en +
vive les serveurs tous différent :S

**Comment by Marc-marc-marc** [comment]
il y a 2 bug : l'un qui affecte osm13 avec v1.2.0
l'autre qui affecte osm25/osm165 avec la v1.2.1, investigation en cours par les dev/sysadmin osm.org

**Comment by cquest** [comment]
J'ai testé la 1.2.2 avec libosmium 2.15.9 chez moi et c'est passé.
libosmium est dispo dans le repo osmadmins, mais pas encore osm2pgsql 1.2.2.

Donc soit... patience, soit compil locale d'osm2pgsql le temps que le package soit dispo ?

**Comment by cquest** [comment]
osm25: j'ai recompilé osm2pgsql 1.2.2 avec libosmium 2.15.6, update en cours...

**Comment by cquest** [comment]
osm165:
- j'ai aussi recompilé osm2pgsql 1.2.2
- le package osm2pgsql avait été supprimé, du coup il manquait des fichiers de config (le default.style)
- j'ai réinstallé le package 1.2.1 vu que le 1.2.2 ne passe par à cause de libproj12
- dans config.sh, chemin d'accès modifié pour osm2pgsql pour que ça soit la 1.2.2 qui soit utilisée (/usr/local/bin/osm2pgsql)

Premier update en cours... je réactive le cron si il se déroule normalement.

**Comment by cquest** [comment]
osm13 et osm25 ont rattrapé leur retard.
En cours pour osm165 (cron réactivé, sur update par tranches d'1 heure), issue à fermer si rien de plus à faire.

**Comment by cquest** [comment]
Re-blocage des mises à jour... sur les 3 serveurs et au même moment (9h10 UTC)

C'est planet.openstreetmap.org qui est down, plantage de 3 disques dans la grappe RAID :(

Donc, pas d'action de notre côté, mais à surveiller...
