### ISSUE TITLE
certificat https expiré

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#21]
le certificat https du forum et de taginfo ont expiré (et sans doute les autres aussi)
@jocelynj  tu avais mis un script en place il y a quelques mois pour les renouveler chaque mois mais d'après la date du certificat, il ne semble pas s'exécuter.

Let's encrypt est aussi supposé envoyer un email d'alerte. ce serrait probablement utile de changer l'email d'alerte au profit de celle de la ml technique.

**Comment by Marc-marc-marc** [comment]
celui de http://{switch:a,b,c}.layers.openstreetmap.fr a aussi expiré : 
The certificate is only valid for the following names: *.openstreetmap.fr, openstreetmap.fr
The certificate expired on 15. 05. 16 22:29

**Comment by jocelynj** [comment]
Merci. Tous les certificats devraient être à jour maintenant.

Pour taginfo et co, j'ai changé le script pour se lancer toutes les semaines, et regénérer le certificat si il a plus de 2 mois.

Pour [abc].layers, letsencrypt n'était pas encore en place, et je viens de l'y installer.
