### ISSUE TITLE
Plantages sur osm26 et osm28

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#211]
On a eu deux plantages d'osm26 qui ont demandé une opération de reboot manuelle par OVH, lancé parce que le ping ne répondait plus:
  * 2020-06-25 19:34:57 CEST 
  * 2020-06-30 11:48:50 CEST

En épluchant le logs, je vois ça dans kern.log:
```
Jun 30 11:15:35 osm26 kernel: [401682.897326] CPU: 3 PID: 3023367 Comm: ipmitool Tainted: P           OE     5.4.44-1-pve #1
Jun 30 11:15:35 osm26 kernel: [401682.898961] Hardware name: Supermicro Super Server/X10SDV-4C-TLN2F, BIOS 1.1b 07/13/2016
Jun 30 11:15:35 osm26 kernel: [401682.905569]  __alloc_pages_slowpath+0xde9/0xe30
Jun 30 11:15:35 osm26 kernel: [401682.910631]  __alloc_pages_nodemask+0x2df/0x330
Jun 30 11:15:35 osm26 kernel: [401682.913732]  kmalloc_order+0x1e/0x80
Jun 30 11:15:35 osm26 kernel: [401682.916631]  ipmi_create_user+0x5f/0x240 [ipmi_msghandler]
Jun 30 11:15:35 osm26 kernel: [401682.919588]  ipmi_open+0x54/0xe0 [ipmi_devintf]
Jun 30 11:15:35 osm26 kernel: [401682.922436]  ? cdev_default_release+0x20/0x20
Jun 30 11:15:35 osm26 kernel: [401682.925203]  vfs_open+0x2d/0x30
Jun 30 11:15:35 osm26 kernel: [401682.927844]  ? unlock_page_memcg+0x12/0x20
Jun 30 11:15:35 osm26 kernel: [401682.930348]  ? wp_page_copy+0x361/0x750
Jun 30 11:15:35 osm26 kernel: [401682.932782]  ? __alloc_fd+0x46/0x150
Jun 30 11:15:35 osm26 kernel: [401682.935031]  ? __do_page_fault+0x250/0x4c0
Jun 30 11:15:35 osm26 kernel: [401682.937093]  __x64_sys_openat+0x20/0x30
Jun 30 11:15:35 osm26 kernel: [401682.939027]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Jun 30 11:15:35 osm26 kernel: [401682.940841] Code: 25 00 00 41 00 3d 00 00 41 00 74 48 48 8d 05 59 65 0d 00 8b 00 85 c0 75 69 89 f2 b8 01 01 00 00 48 89 fe bf 9c ff ff ff 0f 05 <48> 3d 00 f0 ff ff 0f 87 a6 00 00 00 48 8b 4c 24 28 64 48 33 0c 25
Jun 30 11:15:35 osm26 kernel: [401682.943759] RAX: ffffffffffffffda RBX: 000055be2c771e20 RCX: 00007fdb974851ae
Jun 30 11:15:35 osm26 kernel: [401682.945772] RBP: 0000000000000000 R08: 0000000000000000 R09: 00007ffd7b210fb7
Jun 30 11:15:35 osm26 kernel: [401682.947535] R13: 00007ffd7b211240 R14: 00007ffd7b211250 R15: 0000000000000000
Jun 30 11:15:35 osm26 kernel: [401682.948488] Mem-Info:
Jun 30 11:15:35 osm26 kernel: [401682.961251] lowmem_reserve[]: 0 1824 31950 31950 31950
Jun 30 11:15:35 osm26 kernel: [401682.962455] Node 0 DMA32 free:133020kB min:3856kB low:5724kB high:7592kB active_anon:277928kB inactive_anon:49624kB active_file:323788kB inactive_file:491488kB unevictable:6332kB writepending:820kB present:1976012kB managed:1910476kB mlocked:6332kB kernel_stack:16kB pagetables:320kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jun 30 11:15:35 osm26 kernel: [401682.980204] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
```

Et pas mal d'autres erreurs.

**Comment by anayrat** [comment]
Tu n'aurais pas des pages allocation failure plus tôt?

**Comment by cquest** [comment]
Pour info, ce sont des freeze complets du serveur, qui nécessitent un **reboot HARD** de la part d'OVH.
Pas sûr d'avoir quelque chose dans les logs en lien direct avec ces freeze.

**Comment by cquest** [comment]
Encore un reboot HARD cette nuit, freeze détecté par OVH à 1h30, reboot terminé à 2h06... rien de probant dans les logs :(

J'ai migré les containers sur osm27, sauf osm147 (overpass) et osm312 (stoppé). Wait and see...

**Comment by cquest** [comment]
osm312 migré sur osm27, il ne reste plus qu'overpass sur osm26.

**Comment by anayrat** [comment]
J'ai zieuté hier soir, on a pas mal d'erreurs "page allocation failure". Ca peut expliquer le freeze complet de la machine. Par contre un truc qui m'interpelle c'est que c'est tout le temps lié à ipmitool. Est-ce que la carte ipmi est accessible sur internet? C'est souvent bourré de faille de sécu. Est-ce que les firmware sont à jours? Il faudrait aussi regarder les logs de la carte ipmi.

**Comment by cquest** [comment]
C'est l'IPMI géré par OVH (osm25-28 sont des serveurs OVH de leur offre commerciale).

On n'a pas vraiment la main dessus et c'est accessible en passant par leur interface de management... je doute que ce soit accessible publiquement.

Peut-être qu'une question à leur support ne serait pas du luxe vu les 3 freeze répétés en peu de temps alors qu'on n'avait jamais eu le moindre pépin avec osm26 et qu'osm27/28 ne sont pas touchés (serveurs identiques, osm25 est différent).

**Comment by cquest** [comment]
Encore un freeze ce matin et un reboot HARD d'OVH.

J'ai ouvert un ticket au support pour demander si il n'y avait pas un problème hardware.

Pour les messages concernant l'IPMI, on a les mêmes sur osm27 et osm28 qui n'ont pas de problème. Je pense que c'est une fausse piste (échange sur irc avec @anayrat)

**Comment by cquest** [comment]
Rebelote à 2h50 cette nuit.

Réponse du support OVH:

> Nous allons dans un premier tempes réaliser ensemble un diagnostic hardware complet pour vérifier l'état du serveur à l'aide du mode rescue64pro : https://docs.ovh.com/fr/dedicated/ovh-rescue/
> Attention en mode rescue, vos services ne seront plus actifs.
> 
> Une interface graphique vous permet de tester le matériel, il faut effectuer les tests CPU et RAM disponibles dans cette interface : https://********:444
> 
> Ensuite, je vous invite à vous connecter en SSH et nous fournir les résultats des tests suivants :
> 
> - Lister les disques :
> fdisk -l
> 
> - Vérifier l'état des disques :
> smartctl -a /dev/sda
> smartctl -a /dev/sdb
> smartctl -a /dev/sdc
> smartctl -a /dev/sdd
> 
> - Vérifier l'état du raid :
> cat /proc/mdstat
> 
> - Température CPU :
> sensors
> 
> - RAM :
> free -m
> dmidecode -q -t memory | grep Size
> 
> - Network :
> ethtool ethX| grep Speed (X correspond au numéro de votre interface réseau)
> ethtool -S ethX | grep error (X correspond au numéro de votre interface réseau)
> 
> Nous analyserons vos résultats et nous conviendrons ensemble d'une interventions si nécessaire.
> 
> Dans l'attente de votre retour.

Je vois pour déplacer osm147 afin de couper complètement osm26 sans rupture de service pour overpass...

**Comment by jocelynj** [comment]
On a normalement un autre overpass sur osm148, sur lequel on peut basculer quand osm147 est coupé. @Marc-marc-marc devrait avoir plus d'info.

**Comment by cquest** [comment]
J'ai regardé il est "dev" avec juste les données de monaco pour test, donc pas substituable.

**Comment by jocelynj** [comment]
Le plantage de vendredi matin à 2:50 était en fait sur osm28, pas sur osm26.

**Comment by jocelynj** [comment]
Une piste possible: https://forum.proxmox.com/threads/proliant-dl360e-gen8-freezes-with-kernel-5-4-44.71796/#post-325051. osm26 et osm28 ont rebootés sur un kernel plus récent (5.4.44-2-pve) - on va voir si ça freeze moins souvent qu'avant. osm27 a toujours l'ancien kernel (5.4.44-1-pve)

**Comment by cquest** [comment]
11 jours sans plantage d'osm26 ni osm28... espérons que ça soit bien ça !

**Comment by cquest** [comment]
17 jours... je pense qu'on peut fermer :)
