### ISSUE TITLE
Certificat https invalide sur cadastre.openstreetmap.fr/, site down

### ISSUE THREAD

**Issue by bagage** [osm-fr/infrastructure#213]
Lorsqu'on ouvre https://cadastre.openstreetmap.fr/, il y a une erreur : 

> Une erreur est survenue pendant une connexion à cadastre.openstreetmap.fr. PR_END_OF_FILE_ERROR

**Comment by JacLavi** [comment]
Confirmé :   La connexion a échoué Firefox ne peut établir de connexion avec le serveur à l’adresse cadastre.openstreetmap.fr. Ping Ok. (osm104)

**Comment by cquest** [comment]
apache n'était pas en démarrage auto au boot dans osm104, corrigé par un `systemctl enable apache2`
