### ISSUE TITLE
décomptes incohérents sur taginfo

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#214]
Christian Rogel signalait taginfo.openstreetmap.fr comme inaccessible, 

Il est bien accessible pour moi, par contre, les chiffres n'ont pas l'air cohérents...

https://taginfo.openstreetmap.fr/tags a des chiffres qui m'ont l'air corrects, **dès qu'on demande le détail, tout est à 0**... https://taginfo.openstreetmap.fr/tags/building=yes#overview

**Comment by Bibi56** [comment]
Exact mais si tu pars de la page https://taginfo.openstreetmap.fr/tags et que tu utilises la recherche du bas, ça marche !

Par exemple
wall=no
11 560 552

Maintenant :
https://taginfo.openstreetmap.fr/search?q=wall%3Dno
marche aussi.
C'est "seulement" si tu sélectionnes une clé par exemple
https://taginfo.openstreetmap.fr/keys/wall
que ça ne marche pas.

**Comment by jocelynj** [comment]
C'est quand même bizarre... Je pense qu'une des tables générés par taginfo n'a pas été généré correctement, ce qui expliquerait que seule certaines pages soient incorrectes.

**Comment by jocelynj** [comment]
Je viens de retester sur les liens que vous avez donnés, et je vois bien des chiffres sur ces pages. Quelqu'un peut confirmer ?

**Comment by frodrigo** [comment]
Je pense aussi que c'est revenu à la normale.

**Comment by Bibi56** [comment]
Je confirme, ça roule.

**Comment by Bibi56** [comment]
Ouille !
http://taginfo.openstreetmap.fr/search?q=school%3AFR
http://taginfo.openstreetmap.org/search?q=school%3AFR
173 en France, 45 000 dans le monde.

Les pages détaillées sont pareillement fausses.
http://taginfo.openstreetmap.fr/keys/school%3AFR
http://taginfo.openstreetmap.org/keys/school%3AFR
 
Ou encore : 
https://taginfo.openstreetmap.fr/keys/school%3AFR#values

C'est faux mais homogène.

**Comment by Bibi56** [comment]
@jocelynj je crois qu'il faut vraiment réouvrir le ticket car même en utilisant :
http://taginfo.openstreetmap.fr/search?q=ref%3AFR%3ABigBus , la version française ne trouve rien.
http://taginfo.openstreetmap.fr/search?q=ref%3AFR%3ABigBusà l'opposé trouve bien les 14 sur Paris comme [Overpass](https://overpass-turbo.eu/s/Wyr).

**Comment by jocelynj** [comment]
@Bibi56 : est-ce que tu n'aurais pas mis deux fois la même URL ?

**Comment by Bibi56** [comment]
@jocelynj non, pas après mise à jour du commentaire^^.

**Comment by jocelynj** [comment]
Je viens de mettre à jour taginfo sur http://taginfo.openstreetmap.fr, sans impact visible. Je vais vérifier l'extract utilisé pour l'analyse.

**Comment by jocelynj** [comment]
On dirait que la VM n'a pas assez de mémoire: le script d'update plante en remplissant toute la mémoire, qui était configuré à 2G+1G swap. J'ai passé à 8G, avec toujours le même souci.

**Comment by jocelynj** [comment]
En passant la VM à 16Go, le script d'update passe, en prenant jusqu'à 10Go de ram. Je pense que c'est ce plantage qui causait le problèmes sur les nombres incorrects sur http://taginfo.openstreetmap.fr/search?q=school%3AFR

@cquest : est-ce qu'on aurait réduit la RAM en passant de osm26 à osm27 ?

**Comment by cquest** [comment]
Oui, j'ai sûrement réduit la RAM lorsqu'on a chargé osm27 pour libérer osm26... voyant très peu de RAM utilise j'avais réduit, mais visiblement trop.
Etonnant d'avoir besoin par pic de plus de 16Go.

**Comment by lenny31** [comment]
Je trouve encore des différences par exemple avec ref:FR:FANTOIR
http://taginfo.openstreetmap.fr/search?q=ref%3AFR%3AFANTOIR en trouve 359 558 et
https://taginfo.openstreetmap.org/search?q=ref%3AFR%3AFANTOIR en trouve 360 157

**Comment by Bibi56** [comment]
Là ça ne me choque pas : osm.fr porte sur la France métropolitaine uniquement : https://taginfo.openstreetmap.fr/keys/ref%3AFR%3AFANTOIR#map
Manquent donc les confettis ultramarins :
https://taginfo.openstreetmap.org/keys/ref%3AFR%3AFANTOIR#map

**Comment by Bibi56** [comment]
C'est normal : sur fr c'est la France métropolitaine : 
https://taginfo.openstreetmap.fr/api/4/key/distribution/nodes?key=ref%3AFR%3AFANTOIR
et sur org la France entière :
https://taginfo.openstreetmap.org/api/4/key/distribution/nodes?key=ref%3AFR%3AFANTOIR

**Comment by lenny31** [comment]
j'entends, désolé pour le bruit

**Comment by Bibi56** [comment]
Pas de soucis, la réponse n'était pas évidente.
