### ISSUE TITLE
Nextcloud est tombé, 502 https://nextcloud.openstreetmap.fr/

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#215]
https://nextcloud.openstreetmap.fr/

**Comment by cquest** [comment]
apache2 et mysqld était down... je les ai relancé manuellement, nextcloud est à nouveau opérationnel.

Il y a eu un reboot cette nuit du container à 1h18. J'ai rebooté le container et les services sont bien lancés au boot. Etrange...

**Comment by jocelynj** [comment]
Ça doit être lié au reboot HARD d'osm28 de vendredi matin. Je pense qu'il y a aussi un souci dans la config réseau sur osm28, que je crois avoir corrigé en activant la ligne gateway en ipv6.

Pour info, http://www.openstreetmap.fr avait le même souci.
