### ISSUE TITLE
osm110 - munin - load

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#217]
La VM osm310 a été renommé osm110
* [x] Munin n'a pas suivi
* [ ] le load sur osm110 augmente de façon continue, mais là machine n'a pa l'air chargé, hier à 200, aujourd’hui à 300

**Comment by Phyks** [comment]
Idem sur osm166 pour le load

**Comment by jocelynj** [comment]
Munin a été mis à jour, et j'ai migré les données d'osm310 vers osm110: http://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm110.openstreetmap.fr/load.html

Effectivement, le load sur osm166 monte: http://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm166.openstreetmap.fr/load.html. Je pense que ça affiche le load du host, et pas de la VM.

**Comment by cquest** [comment]
Oui, le load vu par les containers est celui du host... je ne sais pas si c'est voulu ou un bug.
