### ISSUE TITLE
Tunnel  backend osmose -> download HS

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#218]
Toujours des problèmes de tunnel backend osmose -> download.fr

* hivane1
* hivane2

**Comment by jocelynj** [comment]
Il y avait trois soucis sur osm26:
  - manque de l'IP utilisé par raw.githubusercontent.com dans /etc/network/interfaces
  - les IPs n'avaient été créées au boot, malgré ces lignes dans /etc/network/interfaces:
```
        p ost-up /sbin/ip -6 addr add 2001:41d0:1008:1f65:10::100 dev vmbr1  # geofabrik
        post-up /sbin/ip -6 addr add 2001:41d0:1008:1f65:10::101 dev vmbr1  # github
        post-up /sbin/ip -6 addr add 2001:41d0:1008:1f65:10::102 dev vmbr1  # download.openstreetmap.fr
        post-up /sbin/ip -6 addr add 2001:41d0:1008:1f65:10::103 dev vmbr1  # raw.githubusercontent.com
```
  - le script de création des tunnels ne créait pas /var/run/6tunnel/, utilisé pour les fichiers de pid
