### ISSUE TITLE
orthophoto Tours 2010+2013 et Bordeaux 2012 ko

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#22]
ces 3 orthophoto sont ko (celle de Bordeaux 2016 fonctionne par contre)
est-ce un problème sur wms.openstreetmap.fr ou est-ce c'est un reverse proxy vers une source externe qui est ko temporairement ou définitivement ?

**Comment by Marc-marc-marc** [comment]
@cquest il parait que c'est ton serveur :)

**Comment by cquest** [comment]
Je ferme... tout est de retour.
