### ISSUE TITLE
Soucis de rendu de la osm-fr au niveau de la Russie

### ISSUE THREAD

**Issue by descl** [osm-fr/infrastructure#221]
Bonjour depuis 1 ou 2 semaines j'ai remarqué sur OSM France il y a des carrés étranges qui sont apparus au dessus de la Russie:
![image](https://user-images.githubusercontent.com/1270023/89403233-4aa90800-d718-11ea-8bda-a97fd7aa43be.png)

Après avoir pas mal bataillé et j'ai trouvé leur source: https://www.openstreetmap.org/relation/11285957#map=4/75.35/69.26&layers=H ce sont ces données ajoutées il y a justement un mois sur OSM qui sont visibles directement sur le fond de carte.
La donnée est très interessante et plutôt triste :( cependant je suppose que nous ne souhaitons pas la voir apparaitre sur le fond de carte "standard".

J'avoue que j'ai du mal à savoir ou reporter cette observation, j'espère ne pas être au mauvais endroit. Merci pour tout ce que vous faites c'est top!

Christophe

**Comment by frodrigo** [comment]
C'est plutôt à signaer ici : https://github.com/hotosm/HDM-CartoCSS/issues

**Comment by descl** [comment]
upps effectivement, merci @frodrigo  https://github.com/hotosm/HDM-CartoCSS/issues/319

**Comment by cquest** [comment]
Et non c'est le fond FR et pas humanitaire...

Oui, j'ai vu aussi ces pâtés sortir depuis la mise à jour de ma couche d'occupation des sols pour les premiers zoom.

C'est laid, mais c'est aussi la réalité... des zones poubelles de déchets nucléaires... à garder ou pas, ça se discute.
Pour l'instant je garde.

**Comment by descl** [comment]
(en faite le soucis est présent sur les 2 fonds de carte du coup c'est "logique" de créer l'issue sur les 2.)

**Comment by frodrigo** [comment]
Ils n'y sont pas ou plus sur le rendu fr.
Si besoin créer l'issue ici  https://github.com/cquest/osmfr-cartocss/issues
