### ISSUE TITLE
okay with download.openstreetmap.fr being listed at switch2osm.org?

### ISSUE THREAD

**Issue by andrewharvey** [osm-fr/infrastructure#223]
I've proposed adding download.openstreetmap.fr to the list of extract providers at https://switch2osm.org/serving-tiles/ via https://github.com/switch2osm/switch2osm.github.io/pull/131.

The maintainers of that site just wish to confirm with the owners of download.openstreetmap.fr that this is okay or not?

**Comment by cquest** [comment]
Ok for me

**Comment by Marc-marc-marc** [comment]
no objection, but perhaps it would be preferable to wait for the resolution of https://github.com/osm-fr/infrastructure/issues/224 to avoid a merger when there is an ongoing problem.
