### ISSUE TITLE
extrait asie sans maj depuis mai

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#224]
signalé sur https://github.com/switch2osm/switch2osm.github.io/pull/131#issuecomment-681968632
le fichier asia.osm.pbf date du 2020-05-13 04:21

**Comment by jocelynj** [comment]
Le fichier asia est effectivement trop vieux, et ne peut être mis à jour parce qu'on n'a plus les diffs. Je crois que le moment du plantage colle avec un plantage osmosis sur des diffs.

J'ai supprimé le pbf en attendant de le regénérer sur une nouvelle VM.

**Comment by jocelynj** [comment]
L'extract asia est maintenant à jour sur la nouvelle VM.
