### ISSUE TITLE
osm26 proxmox erreur dans la GUI

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#225]
osm147 sur osm26 : 
RAM : affiche 512Mo au lieu de 16 Go
+ un message d'erreur Result verification failed (400)
[6].value: type check ('string') failed - got ARRAY

**Comment by jocelynj** [comment]
J'ai enlevé la ligne suivante de la config lxc d'osm147:
```lxc.hook.mount: "/root/osmfr/run-in-ct"
```
C'était utilisé pour la config initiale des clés ssh lors de la création de la VM, et ce n'est plus nécessaire avec la façon actuelle de créer les VMs dans ansible.
