### ISSUE TITLE
Pour info : HOT (et umap) très lent

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/infrastructure#226]
Bonjour,

Couche HOT et affichage umap très lents voire inexistants depuis quelques jours. tile-[a,b,c].openstreetmap.fr met très longtemps à répondre ou ne répond pas du tout.

HTH

**Comment by jocelynj** [comment]
La machine est chargé, mais pas tellement plus que d'habitude. On a juste une différence sur munin: un taux de hit nginx très faible sur http://munin.openstreetmap.fr/openstreetmap.fr/osm13.openstreetmap.fr/nginx_cache_ratio.html

@cquest: On a un cache sur osm13, en plus de celui sur osm23 ?

**Comment by cquest** [comment]
Le cache nginx ne sert que pour les couches layers, pas pour le rendu humanitaire qui a son cache nginx sur osm23.

uMap fonctionne sur un tout autre serveur et ne s'occupe pas directement des fonds de carte.

**Comment by frodrigo** [comment]
C'est encore d'actualité ? on peut ferme ?
