### ISSUE TITLE
live is dead

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#229]
Live.OpenStreetMap.fr ne fonctionne pas

**Comment by jocelynj** [comment]
J'ai vu deux soucis:
  - le crontab ne marche plus, parce que utilisant $USER, qui n'est pas défini
  - la base de donnée dans /data/work/live/changesets.db fait 7Go. Je vais la vider, et ajouter un cron pour ça.

**Comment by jocelynj** [comment]
live remarche: le souci était en fait que le serveur n'arrive pas à accéder à download.openstreetmap.fr en ipv6. J'ai mis en ipv4 pour réparer.
