### ISSUE TITLE
Certificat invalide pour tilecache.openstreetmap.fr

### ISSUE THREAD

**Issue by FramaJosephK** [osm-fr/infrastructure#231]
Bonjour,

Je ne sais pas si c’est volontaire de votre part mais je le signale au cas où il s’agirait d’un bug.
Apparemment, votre certificat a été renouvelé le 30/09 et n’est valide que pour 
```
a.tile.openstreetmap.fr, 
b.tile.openstreetmap.fr, 
c.tile.openstreetmap.fr, 
cachelyon.openstreetmap.fr, 
tile-a.openstreetmap.fr, 
tile-b.openstreetmap.fr, 
tile-c.openstreetmap.fr
``` 
Les tuiles sont toujours accessibles en http mais du coup elles ne peuvent plus être affichée sur framacarte.org où on force l’utilisation du https.

Notre uMap était initialement configuré avec les tuiles provenant de ce domaine. 
Je les ai remplacé par `{s}.tile.openstreetmap.fr` du coup comme indiqué [sur votre wiki](https://wiki.openstreetmap.org/wiki/FR:Serveurs/tile.openstreetmap.fr) mais beaucoup de cartes de nos utilisateurs ont encore l’ancienne URL dans leur configuration (visiblement le changement n’est pas complètement rétroactif ou alors ce sont des cartes où l’ancienne url a été enregistrée comme un fond personnalisé).

**Comment by cquest** [comment]
Je viens de regénérer le certificat.
Il est en effet préférable d'utiliser `{s}.tile.openstreetmap.fr` pour un affichage plus rapide.

**Comment by jocelynj** [comment]
@cquest : est-ce que tu sais pourquoi tilecache a disparu du certificat ?

**Comment by cquest** [comment]
Non, en fait il avait disparu des server_name... sûrement un ménage trop intense de ma part, ce nom de domaine ne faisant pas partie des "officiels" (comme cachelyon).

**Comment by cquest** [comment]
Une remarque... le forçage de https est-il nécessaire ?

Dans umap, on peut définir les tilelayers en mixte (// au lieu de http:// ou https://).
umap.openstreetmap.fr fonctionne aussi bien en http que https et n'impose pas le https.

**Comment by FramaJosephK** [comment]
En fait il n’y a pas vraiment d’avantage à rester sur une version non sécurisé du site surtout quand il y a des espaces avec accès restreint où il faut s’authentifier.
Donc à Framasoft, on fait le choix de systématiquement rediriger tous nos sites vers la version https qu’il y ait des données sensibles ou non à faire transiter entre le navigateur et le site. 
Ça nous semble plus simple de n’avoir qu’un seul cas de figure à gérer aussi bien pour la mise en œuvre technique que pour répondre aux gens qui rencontrent des problèmes.

Après, oui pour les tuiles on pourrait les mettre en mixte mais peu importe en fait puisqu’en pratique chez nous ce serait forcément la version https qui serait appelée.

**Comment by cquest** [comment]
Sur nos services, http/2 est activé, IPv6 aussi
Nous utilisons letsencrypt
Le nom de domaine ne fuite plus avec TLSv1.3 et eSNI :)

Pour le choix de forcer https, quand c'est un service "embed", je ne l'impose pas c'est à celui qui intègre de choisir.
De même, je suis plutôt partisan de config TLS "light" (donc TLSv1 est ok), pour rester assez universel, sauf là où ça peut être sensible.
