### ISSUE TITLE
ML tech@ semble envoyer les e-mail en double.

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/infrastructure#232]
From: Jacques Lavignotte <jacques@lavignotte.org>
    To: tech@listes.openstreetmap.fr
    Subject: [tech] e-mails de la liste tech reçus en double ?
    Date: Wed, 7 Oct 2020 14:07:23 +0200

Mail unique dans les archives mais bien reçus en double dans ma mbox.

**Comment by jocelynj** [comment]
Je vois que tu es inscrit sur deux emails: jacques.lavignotte@gm*.com + jacques@lavignotte.org
