### ISSUE TITLE
Munin sur tile-vect.vm.openstreetmap.fr

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#235]
Est-il possible d’ajouter munin au serveur de tuiles vecto pour suivre son comportement. Juste des indicateurs de base. Le reste état dans du docker.

**Comment by frodrigo** [comment]
Stats d'Nginx dispo sur

http://127.0.0.1:8082/nginx_status

**Comment by jocelynj** [comment]
Nginx est dispo ici: http://munin.openstreetmap.fr/osm14.openstreetmap.fr/tile-vect.vm.openstreetmap.fr/index.html#nginx

**Comment by frodrigo** [comment]
Merci.
