### ISSUE TITLE
Mise à jour de l'instance PeerTube

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#237]
Je relance une issue pour un passage en 2.4.0, une grosse release avant le live prévu pour bientôt :)

https://github.com/Chocobozzz/PeerTube/releases/tag/v2.4.0

Mais attention, cette instance est en 2.1.1, il y a eu entre temps la 2.2.0 et la 2.3.0.

Merci pour le boulot que vous faites !

**Comment by jocelynj** [comment]
C'est à jour, merci d'avoir prévenu !
