### ISSUE TITLE
OSM-Fr :: Wordpress :: Flux RSS

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/infrastructure#239]
Bonjour,

Il est confortable de recevoir une mention lorsqu'un nouvel article apparaît sur le Wordpress de l'asso. RSS est un bon vieux dispositif bien commode pour alerter. 
Est-il possible d'installer le plugin RSS sur openstreetmap.fr ?

J.

**Comment by cquest** [comment]
https://www.openstreetmap.fr/feed/rss/ est l'URL par défaut du feed RSS d'un site sous Wordpress.

Il manque juste une icône quelque part pour l'indiquer...

**Comment by JacLavi** [comment]
En effet. A l'icône près on peut fermer.
