### ISSUE TITLE
Migration d'osm108 vers download.vm.openstreetmap.fr

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#242]
osm108 est actuellement sur osm12, qui est sur CentOS, et ça va être mis à jour. L'idée est de ré-installer sur une nouvelle VM sur osm14.

Les diffs sont en déjà en cours de génération: http://munin.openstreetmap.fr/osm11.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html
Reste à générer les extracts.

**Comment by jocelynj** [comment]
Le DNS a été modifié pour utiliser la nouvelle VM, dont j'ai documenté l'installation dans ansible: https://github.com/osm-fr/ansible-scripts/blob/master/roles/osmbin/tasks/main.yml

Reste juste polygons.openstreetmap.fr à migrer, qui utilise la même base osmbin.

**Comment by jocelynj** [comment]
polygons.openstreetmap.fr a aussi été migré.

**Comment by Marc-marc-marc** [comment]
la [doc](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#VMs) dit que osm108 est à couper, mais la vm ne répond plus
il [semblerait](https://github.com/osm-fr/osmose-backend/issues/1097) que l'ancienne vm est toujours pointés par 6tunnel pour les slave osmose-backend ipv6-only

**Comment by jocelynj** [comment]
Le souci de tunnel n'était pas lié à la migration, vu que le script lançant le tunnel utilise le domainname plutôt que l'IP.
