### ISSUE TITLE
502 sur ComComMaker

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/infrastructure#244]
Bonjour, http://comcommaker.openstreetmap.fr/ répond :
502 Bad Gateway

C'est normal ? Connu ? À corriger ?

**Comment by Marc-marc-marc** [comment]
marqué ko sur https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#Liste_des_services_web_sur_le_domaine_openstreetmap.fr
gileri est renseigné comme testant une vm de remise en état en janvier 2019 mais pas de nouvelle

**Comment by Bibi56** [comment]
Merci, on va lui faire un petit coucou alors : @gileri ;-) pour qu'il sache que son idée était bonne !

**Comment by gileri** [comment]
À l'époque j'avais proposé de regarder, mais j'avais pas trop le temps. Désolé d'avoir abandonné sans donner de nouvelles...

Mais là j'ai plus de temps :)

La VM osm312 (dev-comcommaker) a été mentionnée pour du nettoyage dans #180, mais j'arrive toujours à m'y connecter. Est-ce que je peux continuer dessus ?

**Comment by Marc-marc-marc** [comment]
oui oui vas-y :)

**Comment by jocelynj** [comment]
@gileri : Maintenant que le rôle ansible est mergé, est-ce qu'i reste quelque chose à faire pour activer le site ?

**Comment by gileri** [comment]
@jocelynj J'ai appliqué le rôle avant le merge de https://github.com/osm-fr/ansible-scripts/pull/50.

Le service est bien utilisable depuis http://comcommaker.vm.openstreetmap.fr/ mais pas http://dev.comcommaker.openstreetmap.fr/ . J'ai fait https://github.com/osm-fr/ansible-scripts/pull/51 qui devrait j'espère suffire pour le rendre accessible "en prod".

**Comment by gileri** [comment]
Le service marche bien sur https://comcommaker.openstreetmap.fr/, je pense qu'on peut fermer l'issue :)

Il faudrait je pense corriger l'enregistrement DNS/reverse proxy dev.comcommaker.openstreetmap.fr, mais c'est secondaire.

Merci pour votre aide !

**Comment by Bibi56** [comment]
Je confirme, bon pour fermeture, maintenant reste à retrouver le message pour lequel je proposais d'utiliser le service^^ (déjà je me souviens de l'auteur). @Marc-marc-marc je te laisse le plaisir de mettre à jour le statut sur la page indiquée.

**Comment by gileri** [comment]
Bien vu @Bibi56, j'ai [mis à jour le wiki](https://wiki.openstreetmap.org/w/index.php?title=FR:Serveurs_OpenStreetMap_France&diff=2082067&oldid=2065793).

**Comment by Marc-marc-marc** [comment]
@gileri Il reste un "En cours d'installation" :) et le prefixe dev. a supprimer du wiki 
à propos de dev.com... j'ai pas compris ce que tu vois à modifier dans le dns à ce sujet, le virer ?

**Comment by gileri** [comment]
> @gileri Il reste un "En cours d'installation" :) et le prefixe dev. a supprimer du wiki

Je viens de le faire :+1: 

> à propos de dev.com... j'ai pas compris ce que tu vois à modifier dans le dns à ce sujet, le virer ?

Oui t'as raison @Marc-marc-marc  autant enlever dev.comcommaker.openstreetmap.fr c'est plus simple !

Il faudrait aussi enlever [l'ancienne VM osm312](https://github.com/osm-fr/ansible-scripts/commit/4be581c16bd9a6d5c6c0b2d8c23d94edca917e93) qui est toujours démarée et inutilisée. Elle a été crée uniquement pour comcommaker donc elle peut être supprimée sans soucis.

**Comment by jocelynj** [comment]
Je viens d'enlever dev.comcommaker du DNS, et j'ai aussi supprimé la VM osm312.

**Comment by gileri** [comment]
Merci @jocelynj, je confirme pour les deux !
