### ISSUE TITLE
Certificate issue on download.openstreetmap.fr

### ISSUE THREAD

**Issue by SanderH** [osm-fr/infrastructure#245]
I hope this is the correct place to report this issue.

When navigating to https://download.openstreetmap.fr/ it presents a certificate for osm14.openstreetmap.fr and there is no SAN entry for download.openstreetmap.fr

![image](https://user-images.githubusercontent.com/5428967/100078813-37938280-2e44-11eb-97c6-39579d70e83d.png)
![image](https://user-images.githubusercontent.com/5428967/100078873-4aa65280-2e44-11eb-8838-d40d8a8e0563.png)

**Comment by Marc-marc-marc** [comment]
> I hope this is the correct place to report this issue.

yes, thanks

> When navigating to https://download.openstreetmap.fr/ it presents a certificate for osm14.openstreetmap.fr and there is no SAN entry for download.openstreetmap.fr

@jocelynj the doc is incoherent. donwload is listed as being on osm12, to be migrated to osm11 and seems to be on osm14 (not found in the hosts file) 
https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France

**Comment by frodrigo** [comment]
I don't know about the details, but @jocelynj switchs the VM yesterday.

**Comment by jocelynj** [comment]
I forgot to regenerate the certificate on osm14, sorry.

@Marc-marc-marc : the new VM is download.vm.openstreetmap.fr, which is listed in ansible hosts file.

**Comment by Marc-marc-marc** [comment]
witch hoster ? osm14 is not found in the ansible hosts file
`$ ansible-playbook -l osm14.openstreetmap.fr letsencrypt.yml`
`skipping: no hosts matched`

**Comment by jocelynj** [comment]
@SanderH : Certificate was regenerated, and you shouldn't get any https error on https://download.openstreetmap.fr.

@Marc-marc-marc : this error is because osm14 is not in the "letsencrypt" section of the hosts file. I will check why it wasn't updated on github.

**Comment by SanderH** [comment]
Thanks, you're very fast guys!!!
