### ISSUE TITLE
Accès à une base osm2pgsql France (ou plus grande) pour comcommaker

### ISSUE THREAD

**Issue by gileri** [osm-fr/infrastructure#246]
Bonjour,

Afin de rendre fonctionnel de nouveau comcommaker (voir #244), il faudra que la [VM osm312](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#VMs) ait accès en lecture seule à une base osm2psql contenant au minimum la France, mais j'imagine que l'outil pourrait être utilisé pour d'autres régions.
Les requêtes qu'elle effectue sont des simples [intersection entre un point et des limites administratives](https://gitlab.com/gileri/ComcomMaker/-/blob/047c1437277521763b5c7f6fbb4ea5102856db9f/ajax.py#L54-70), la charge sur la base de données devrait être faible.

J'ai cherché [le repo ansible-scripts](https://github.com/osm-fr/ansible-scripts) mais je n'ai rien trouvé de relatif aux pare-feu, j'imagine que c'est géré hors ansible ?

Merci pour votre aide :)

**Comment by jocelynj** [comment]
@cquest : quelle base osm2pgsql pourrait-on utiliser pour comcommaker ?

La VM est actuellement installé sur osm26, mais on pourrait la déplacer sur osm11 pour pouvoir réutiliser la base qui est sur osm165.

**Comment by cquest** [comment]
On peut la déplacer, ou pas vu le faible volume de requêtes et des réponses qui ne devrait pas poser de problème même si chaque morceau est dans un cluster différent.

Sinon, le plus simple pour déplacer un petit conteneur entre cluster, c'est un backup+restore au niveau proxmox.

**Comment by gileri** [comment]
Je me permet de le remettre là, mais elle peut aussi être supprimé+recréée si c'est plus simple qu'une migration, [elle est toujours vide](https://github.com/osm-fr/ansible-scripts/pull/48#issue-525815137) (je fais mes tests sur une VM Vagrant locale)

**Comment by jocelynj** [comment]
Je vais la réinstaller sur osm11, ce qui sera plus simple pour les autorisations postgres. D'ailleurs, je vais aussi renommer la VM en comcommaker.vm.openstreetmap.fr.

**Comment by jocelynj** [comment]
@gileri : j'ai réinstallé sur comcommaker.vm.openstreetmap.fr = 2a01:e0d:1:c:58bf:fac1:8000:179.
J'ai mis les infos de connection à la base osm2pgsql dans le fichier /home/gileri/connection-postgres.

Si tu veux pouvoir y accéder via ta propre IP pour tester comcommaker chez toi, je peux rajouter cette IP dans les IP autorisées dans postgresql.

**Comment by gileri** [comment]
Merci pour vos réponses et la migration !

Je n'ai pas accès à ce fichier sur les deux machines auquelles je peux me connecter, je regarde au bon endroit ?

```
% ssh osm312.openstreetmap.fr /home/gileri/connection-postgres
stat: cannot stat '/home/gileri/connection-postgres': No such file or directory
% ssh osm26.openstreetmap.fr stat /home/gileri/connection-postgres
stat: impossible d'évaluer '/home/gileri/connection-postgres': Aucun fichier ou dossier de ce type
```

J'ai aussi fait un `find / -name connection-postgres\*` au cas où.

L'enregistrement `comcommaker.vm.openstreetmap.fr` pointe en effet sur l'IP que tu donnes @jocelynj, mais l'adresse IPv6 du serveur semble être différente, ai-je loupé quelque chose ? J'arrive à me connecter à Apache sur `[2001:41d0:1008:1f65:1::312]:80` mais pas `comcommaker.vm.openstreetmap.fr:80`

```
% dig +short AAAA comcommaker.vm.openstreetmap.fr
2a01:e0d:1:c:58bf:fac1:8000:179
% ssh osm312.openstreetmap.fr ip ad | grep 'scope global'
    inet 10.1.1.56/24 brd 10.1.1.255 scope global eth0
    inet6 2001:41d0:1008:1f65:1::312/80 scope global

% curl -6 -I '[2001:41d0:1008:1f65:1::312]:80'
HTTP/1.1 200 OK
Date: Mon, 30 Nov 2020 11:03:30 GMT
Server: Apache/2.4.38 (Debian)
Last-Modified: Mon, 30 Nov 2020 10:46:13 GMT
ETag: "2409-5b550b80a7714"
Accept-Ranges: bytes
Content-Length: 9225
Vary: Accept-Encoding
Content-Type: text/html

% curl -6 -I comcommaker.vm.openstreetmap.fr:80  
curl: (7) Failed to connect to comcommaker.vm.openstreetmap.fr port 80: Connexion refusée
```

**Comment by gileri** [comment]
Oups, merci d'ignorer le précédent message, je viens de lire le [commit de migration](https://github.com/osm-fr/ansible-scripts/commit/4be581c16bd9a6d5c6c0b2d8c23d94edca917e93) et c'est normal pour l'enregistrement DNS IP et sûrement le fichier. Je me suis embrouillé vu que l'ancienne VM existe toujours.

Mais je n'arrive pas à me connecter à cette nouvelle VM :
```
% ssh -o PasswordAuthentication=no comcommaker.vm.openstreetmap.fr
gileri@comcommaker.vm.openstreetmap.fr: Permission denied (publickey,password).
```

**Comment by jocelynj** [comment]
Je n'avais pas mis la clé ssh :(
Tu peux retester ?

**Comment by gileri** [comment]
Tout fonctionne, merci bien ! Je vais faire la PR pour le rôle Ansible.
