### ISSUE TITLE
Certificat invalide pour dev.osm162

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#247]
Les URLs de https://dev.osm162.openstreetmap.fr/ (par exemple https://dev.osm162.openstreetmap.fr/20km_chacun.html diffusée ce matin) déclenchent des alertes des navigateurs à cause d'un certificat. Voici le log de ce que dit Chrome : 

NET::ERR_CERT_COMMON_NAME_INVALID
Subject: osm11.openstreetmap.fr
Issuer: Let's Encrypt Authority X3
Expires on: 29 janv. 2021
Current date: 25 nov. 2020
...

Merci

**Comment by jocelynj** [comment]
Le certificat est maintenant généré avec dev.osm162.

**Comment by vdct** [comment]
Merci @jocelynj
