### ISSUE TITLE
Download, merge non regenéré

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#249]
Les exports de merge ont les diff de mise à jour, mais les extract sont vieux.

**Comment by frodrigo** [comment]
Les diff ne remontent pas non plus assez loin pour mettre à jour l'extract.

**Comment by jocelynj** [comment]
Bien vu: la non présence des vieux diffs doit expliquer que ça ne se mette pas à jour. Je vais regénérer les extracts des merge.

**Comment by jocelynj** [comment]
C'est maintenant à jour: http://download.openstreetmap.fr/extracts/merge/

Est-ce qu'il faut enlever ces extracts de backend osmose ?

**Comment by frodrigo** [comment]
Je ne sais pas. Je ne connais pas la raison pour la qu’elle tu as supprimé tous les extracts des backends.

Je pense aussi que le changement de serveur à fait bugger la mise à jour de la base de CRO. Mais je ne sais pas pourquoi.

Il n'y a que osm110 qui l'utilise ? À voir s'il est à jour ou bloqué par le manque de diff.

**Comment by jocelynj** [comment]
J'ai enlevé les extracts des backend pour partir de nouveaux extracts, au cas où il y aurait eu un souci non-vu sur l'ancien serveur.

Sur osmose, on a france_taaf, fiji et kiribati qui utilisent les merge: je regarde si on aurait un souci sur un des backends.

osm110 a l'air à jour: 
```
timestamp=2020-11-28T09\:39\:03Z
```

**Comment by jocelynj** [comment]
C'est bon.

Pour CRO, je n'ai pas d'info, il faudrait contacter directement les responsables.

**Comment by frodrigo** [comment]
C'est moi qui fait tourner la version actuelle de CRO.
