### ISSUE TITLE
OSM202 down

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#25]
Bonjour,

La machine osm202 qui abrite le service teol.openstreetmap.bzh est injoignable ce matin.

Ni par HTTP ni SSH.

Qqn pourrait regarder ? @jocelynj @cquest

**Comment by MaelREBOUX** [comment]
On a une erreur 502 renvoyée par le frontal osm25.

**Comment by jocelynj** [comment]
La machine host osm25 a été rebooté hier, et la VM osm202 n'a pas l'attribut nécessaire pour qu'elle démarre au reboot.

J'ai rajouté "onboot: 1" dans la config, et lancé la VM manuellement.

**Comment by MaelREBOUX** [comment]
Merci.
Tout a l'air d'être bien reparti. On va voir la maj de cette nuit mais pas de raison que ça coince.

PS : je vais te solliciter dans pas longtemps pour mettre en route sur tile.osm.bzh.

**Comment by MaelREBOUX** [comment]
Aïe non : renderd n'a pas redémarré correctement et ne répond pas.

**Comment by MaelREBOUX** [comment]
Bon : comme dans ma VM : un reboot et ça repart. J'ai jamais trouvé d'autre palliatif.

**Comment by jocelynj** [comment]
Quand renderd ne démarre pas, redémarrer postgresql puis renderd ne marche pas habituellement ?

**Comment by MaelREBOUX** [comment]
Redémarrer PostgreSQL ? Me souviens plus si essayé dans cet ordre. Je le ferai la prochaine fois pour voir.

J'ai le même phénomène depuis longtemps dans la VM de test.

**Comment by MaelREBOUX** [comment]
Sinon le reboot de osm25 a réglé le pb des jauges de htop. Elles sont conformes à l'utilisation de la VM. Avant on voyait celles de l'hôte.
Mais la quantité de mémoire indiquée est tjs celle de l'hôte.
