### ISSUE TITLE
Besoin nouvelle VM pour héberger service export cadastre

### ISSUE THREAD

**Issue by tyndare** [osm-fr/infrastructure#250]
Bonjour, 

Suite à https://github.com/osm-fr/infrastructure/issues/243

j'aurais besoin d'une vm type debian buster avec un serveur web/php
pour héberger cadastre.openstreetmap.fr

La version modifiée prévue du code du service est ici:
https://github.com/osm-fr/export-cadastre/tree/lxc-buster-migration

Je n'y connais rien en configuration/sécurisation de vm et serveur web,
donc je suis preneur d'un exemple ou un lien vers une procédure.

Merci beaucoup

**Comment by jocelynj** [comment]
La VM a été crée sur cadastre.vm.openstreetmap.fr = 2001:41d0:1008:1f65:1::180, et tu as un accès sudo

J'ai installé les dépendances debian d'après la doc ci-dessus: https://github.com/osm-fr/ansible-scripts/commit/743923ffd48271da34482d359f012f32a62fd7e0

Le git est cloné sur /data/project/cadastre/export-cadastre

**Comment by tyndare** [comment]
Merci, je n'arrive pas à m'y connecter par ssh, j'ai tenté 
- tyndare @ cadastre.vm.openstreetmap.fr 
- cadastre  @ cadastre.vm.openstreetmap.fr 

Est-ce que je devrais y arriver en ayant cette clef: https://github.com/tyndare.keys ?

**Comment by jocelynj** [comment]
J'avais une autre clé de mon côté, avec un email en @wanadoo.fr. J'ai copié cette clé, tu peux confirmer que ça marche sur tyndare@cadastre.vm.openstreetmap.fr ?

**Comment by tyndare** [comment]
Cool ça marche merci.

Pour la configuration du https et de let's encrypt, est-ce qu'il existe des chose dans le projet https://github.com/osm-fr/ansible-scripts qui serait réutilisables ou est-ce qu'il faut que j'essaye de refaire comme c'était fait sur osm104 ?

**Comment by jocelynj** [comment]
Pour https, c'est géré différemment.

Comme cette nouvelle VM n'a pas d'ipv4, mais uniquement une ipv6, on configure un proxy passant par osm26 (le host de cette VM), et ce proxy gère directement le certificat letsencrypt pour https. En gros, on configurera ça quand la nouvelle sera en place, et qu'on pourra basculer cadastre.openstreetmap.fr dessus.

**Comment by tyndare** [comment]
Ah c'est génial ça. Merci.

J'ai essayé de voir pour compléter le script ansible: 
https://github.com/tyndare/ansible-scripts/commit/e404ccef5fa1e0a249b1d2c60475731b74fd03c8

est-ce que c'est la bonne approche ?

**Comment by jocelynj** [comment]
Yep, c'est parfait.

Tu sais tester le rôle de ton côté ?  Ça peut se faire via `ansible-playbook -l cadastre.vm.openstreetmap.fr cadastre.yml`

**Comment by tyndare** [comment]
Merci je ne connaissait pas, j'ai un peu galéré pour réussir à le lancer car j'avais pas =(ALL) dans le fichier sudoer me permettant d'exécuter les commandes "become", mais une fois fait, la commande ansible-playbook a marché, j'ai debuger mon ficiher merci.

**Comment by tyndare** [comment]
Merci !
