### ISSUE TITLE
Taginfo : activer chronology (nécessite une mise à jour de l'instance)

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#251]
l'instance de https://taginfo.openstreetmap.org a une nouvelle fonctionnalité sur la Chronology for intéressante (https://taginfo.openstreetmap.org/keys/emergency#chronology).

Cette possibilité n'existe par dans la version de taginfo http://taginfo.openstreetmap.fr/tags/emergency=defibrillator

Issuer à considérer comme ce qu'elle est :) juste pour ne plus avoir à y penser mais pour le faire, moi je ne sais pas :)

**Comment by jocelynj** [comment]
Pour activer l'option de chronology, il faut un extract historique de la France, qu'on n'a pas actuellement.

@Marc-marc-marc avait commencé à regarder, mais je ne sais pas où il en est maintenant.

**Comment by vinber** [comment]
ok merci  !

donc :

1. - [ ] extract historique de la france

2. - [ ] activer l'option Chronology

**Comment by pyrog** [comment]
@jocelynj et @Marc-marc-marc 
Si je comprends bien, il faut :
1. télécharger chez [GeoFabrik](https://osm-internal.download.geofabrik.de) le fichier France contenant toutes les métadonnées et l'historique complet.
1. vider complètement la base sql de taginfo ?
1. Mettre à jour le code de Taginfo
1. recharger le fichier télécharger précédemment.
1. modifier la procédure d'import des "minutes" ?

Pour le dernier point, est-il fait automatiquement avec la mise à jour du code de taginfo ?

**Comment by frodrigo** [comment]
>     1. télécharger chez [GeoFabrik](https://osm-internal.download.geofabrik.de) le fichier France contenant toutes les métadonnées et l'historique complet.

Non ce fichier n'est pas un fichier historique.

**Comment by pyrog** [comment]
Leur site indique que c'est le cas dans la partie privée 😃 

Anyway : on trouve un fichier historique ne contenant que la France, c'est bien ça ?

PS: quel est le bon lien si GeoFabrik ne convient pas ?

**Comment by frodrigo** [comment]
Effectivement, il y a bien l'historique. sur cette version de geofabrik.

**Comment by Marc-marc-marc** [comment]
de ce que j'en sais, la maj du code peux se faire indépendamment du reste, le code est capable de traiter un pbf normal tel qu'il existe.

a faire selon moi
- [ ]  mettre à jour le code taginfo, attention il y a un PR non finit concernant le fichier de configuration et une modif pour le drapeau dont j'ignore si cela a été remonté sur git
- [ ]  test possible de l'option avec le fichier geofabrik, mais celui-ci n'tétait pas maj tous les jours, pour la mise en prod cela n'est pas top
- [ ]   tester la maj du fichier historique avec les diff (script 10_update_pbf et 20_filter.sh qui mériteraient d'être déplacé pour rentrer dans git)

@pyrog qu'est-ce qui te fait penser qu'il faut purger qlq chose lors de l'activation de cette option ?

**Comment by jocelynj** [comment]
Le code de taginfo est normalement déjà à jour avec le support de pbf historique. Pour le PR dont tu parles, il n'a en fait jamais été mergé dans les scripts ansible, et le fichier de configuration sur taginfo.openstreetmap.fr a largement divergé depuis.

**Comment by Marc-marc-marc** [comment]
PR osh publié, mergé, tourne depuis "un certain temps" sans soucis et de quasi a à z (reste le téléchargement initial du osh depuis geofabrik https://github.com/osm-fr/ansible-scripts/issues/65)
