### ISSUE TITLE
Impossible de commenter l'instance Peertube

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#252]
Bonjour à tous,

Suite à la sortie de cette vidéo : https://peertube.openstreetmap.fr/videos/watch/db21f74d-44ba-46c8-8162-35c25ab0da65 j'ai voulu la commenter comme je le fais toujours depuis mon compte Mastodon.

Il semblerait que cela ne fonctionne pas, de même, si on met en favori sur Mastodon, cela doit générer un _J'aime_ en plus sur la vidéo.

Pour reproduire : 

- Dans Mastodon, cherchez https://peertube.openstreetmap.fr/videos/watch/db21f74d-44ba-46c8-8162-35c25ab0da65
- Puis mettre en favori ou faire une réponse.
- Sur la page de la vidéo, aucun changement :(

Merci !

**Comment by bristow** [comment]
Bizarre, une personne du même serveur Mastodon a réussi à publier un commentaire. J'ai refait le test et pas mieux :(

**Comment by gendy54** [comment]
Bonjour,

Sauf erreur, nous (je) avons désactivé les commentaires sous les vidéos car des spams à caractères sexuels venaient s'y déposer. Il s'agit d'un travail à faire sous chaque vidéo pour l'instant. Peut-être que certaines ont les com activées quand elles sont déposées par d'autres personnes que moi.

**Comment by bristow** [comment]
Oui en effet, la vidéo dont je fais référence a les commentaires ouverts. Il y a un commentaire issu de framapiaf (une instance Mastodon) et de mon côté, impossible de commenter. Bizarre.

**Comment by jocelynj** [comment]
Je ferme, vu que les commentaires ont l'air de marcher.
