### ISSUE TITLE
Erreurs sur polygons avec relation contenant des sous-relations

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#254]
polygons.osm.fr à des problèmes avec des polygons qui sont pourtant valide dans OSM
 Par ex: 396461 ou 192783

http://polygons.openstreetmap.fr/?id=192783
http://polygons.openstreetmap.fr/?id=396461

**Comment by jocelynj** [comment]
Le problème est que la relation https://www.openstreetmap.org/relation/192783 contient des relations de type=collection, et ça rajoute des ways en trop.

Je peux le rajouter en relations à ne pas regarder lors du parcours des relations, comme j'ai déjà fait pour les types subarea, land_area et disputed_exclave.

**Comment by frodrigo** [comment]
Oui exclure les collections.

Par contre l'autre relation n'a pas ce problème.

Je cherche à validation les id de relation de la config d'Osmose, mais ce n'est peut être pas le bon moyen non plus.

**Comment by jocelynj** [comment]
Pour l'autre relation 396461, il s'agit d'un admin_centre: `Relation San Rafael (112679) avec le rôle admin_centre`

Je me demande si je ne devrais pas mettre une liste blanche des types à prendre en compte, plutôt que d'exclure des types. Surtout que je crois que seul le polygone France utilise des sous-relations pour les frontières.

**Comment by jocelynj** [comment]
J'ai modifié le site web polygons.openstreetmap.fr pour exclure tout ça:
`["subarea", "land_area", "water_area", "collection", "admin_centre", "disputed_exclave"]`

**Comment by frodrigo** [comment]
J'ai maintemant des relations qui plantent sur la génération :
- 192778
- 1703814

**Comment by jocelynj** [comment]
Je viens de tester, et ça marche sur la page http://polygons.openstreetmap.fr/?id=1703814. Tu vois un autre souci ?

**Comment by frodrigo** [comment]
Non, quand on veut en générer un nouveau ça ne marche pas.

**Comment by Marc-marc-marc** [comment]
à mon avis vu l'inventivité à rajouter n'importe quoi dans les relations admin, il est préférable de ne prendre que les roules outer et inner et ignorer tout le reste

**Comment by jocelynj** [comment]
Pour 1703814, le bouton "Refresh original geometry" marche bien chez moi. Par contre, le bouton pour générer un polygone simplifié foire, et ça doit être un autre problème.

**Comment by jocelynj** [comment]
Sur la relation 192778, il y avait un way incorrect, que j'ai corrigé sur https://www.openstreetmap.org/changeset/96394366

Je pense que l'autre relation a le même souci, et ça serait bien que les erreurs postgresql soient récupérables par psycopg2 pour les afficher sur la page web...

**Comment by frodrigo** [comment]
J'ai toujours un problème pour générer un nouveau poly sur 1703814, 17657, 151304 et 151339.

Quand la relation n'existe pas ça serait bien d'avoir un 404 pour faire la différence entre erreur interner et la relation n'existe pas (1953041)  (ce dont on a besoin pour osmose)

Plus un autre code quand elle est invalide (913101).

**Comment by jocelynj** [comment]
Est-ce que tu peux refaire ta vérification des polygones ?  J'ai corrigé la génération des polygones simplifiés (le bouton d'en bas du http://polygons.openstreetmap.fr/?id=1703814) vers 18h.

Tu parles de code HTTP différent pour ces deux cas ?

Et je ne comprends pas comment tu tombes sur le troisième cas qui arrive quand on génére un polygone "aggrandi": il me semblait que osmose n'utilise que le polygone "normal". Tu pourrais montrer ton script de test de polygone quelque part ?

**Comment by frodrigo** [comment]
Erreur de génération, plus que un :
17657

Non présent (-> 404)
2905554
1997192
374810
1953041

Polygone invalide (-> autre erreur http)
913101

En fait je cherche pour l'instant juste à avoir le statut du polygone, pas à le récupérer. Mais c’est peut-être pour l'étape d'après. C'est vrai que je cherche le polygone simplifié alors que je pourrais juste regarder le polygone de base.

Mon script est osm110 /home/fred/osmose-backend/tools/test-polygons.py

**Comment by frodrigo** [comment]
C'est bien ce répo https://github.com/jocelynj/osm-polygons-generation
Tu dois avoir du code non commité ?

**Comment by jocelynj** [comment]
C'est normalement tout commité dans ce git. Est-ce que tu as encore des soucis de polygones ?

**Comment by jocelynj** [comment]
J'ai relancé le script dimanche, et je n'ai plus que ces erreurs:
```
['usa_california_san_bernardino', 396509, 'Geom Error']
['afghanistan', 303427, 'Geom Error']
['brazil_espirito_santo', 54882, 'Geom Error']
['brazil_minas_gerais', 315173, 'Geom Error']
['germany_bayern_schwaben', 17657, 'Geom Error when simplified']
```

En regardant:
  - afghanistan avait une région en "member" plutôt que "subarea", que j'ai corrigé
  - brazil_* avaient perdu le même way dans leur boundary, que j'ai corrigé
  - germany_bayern_schwaben est une région avec deux morceaux accolés par un seul node, et ça faisait planter postgis. J'ai rajouté un ST_MakeValid() pour que ça marche
  - usa_california_san_bernardino n'a rien de cassé à ce que je vois, et c'est bien généré dans polygons.openstreetmap.fr. Peut-être que ça a été réparé depuis dimanche ?

**Comment by jocelynj** [comment]
Je ferme le ticket, parce qu'il y a plus de souci sur polygons.openstreetmap.fr

https://github.com/osm-fr/osmose-backend/actions/workflows/poly.yaml affiche encore des erreurs, mais il s'agit de relations incorrectes dans OSM (je viens de corriger les deux dernières erreurs sur india_tamil_nadu et china_tibet)
