### ISSUE TITLE
educosm, faire la mise à jour de Yeswiki

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#255]
Suite échange avec Jocelyn, concernant https://educosm.openstreetmap.fr.
La machine est en Debian stretch, et du coup à mettre à jour avant de mettre php7.
Donc soit :
- ré-installer une nouvelle VM avec la dernière Debian, et il faudra récupérer les infos de l'ancien wiki.
- tenter une mise à jour vers la dernière Debian, ce qui devrait marcher, mais je ne garantis rien.

Donc je dirai :
1. faire une sauvegarde
2. tenter la mise à jour vers la dernière debian

---
Actions finalement prévues :
- [ ] création compte ssh pour Louis-Julien (jocelyn)
- [x] snapshot
- [x] upgrade debian (cquest)
- [ ] vérification que tout est ok (vinber/ljb)
- [x] upgrade php si pas fait en (cquest)
- [ ] re-vérification (vinber/ljb)
- [ ] upgrade yeswiki (lbj)

**Comment by cquest** [comment]
Un snapshot du container avant upgrade permet de revenir facilement en arrière.

Je peux tenter l'upgrade debian si tu veux en procédant ainsi :

- [ ] snapshot + upgrade debian
- [ ] vérification que tout est ok (par toi)
- [ ] upgrade php si pas fait en 1)
- [ ] re-vérification

**Comment by Ljbouere** [comment]
Bonjour et merci Christian

A première vue le plus simple serait de :

 - sauvegarder l'ensemble du site en le téléchargeant via ftp ou sftp (mais les codes sont où ? on peut les avoir ? )😁
 - sauvegarder la base sql (qui peut faire ça ?)

Une fois que c'est fait on a tout ce qu'il faut de sauvegardé. Et ensuite on peut installer un nouveau debian avec le bon php et réinstaller le wiki proprement.

C'est vrai que c'est plus simple quand on peut mettre les mains dans le cambouis directement. et vous enlever du boulot tech que pour une fois je sais un peu faire !!!!

Bon désolé si j'ai pas les bons mots MERCI en tous cas !

**Comment by cquest** [comment]
Le snapshot c'est un backup instantané (et un restore qui l'est tout autant), pour ça que je propose de le faire plutôt qu'un classique backup/restore plus long et finalement complexe.

Dispo pour faire les étapes 1 et 3, à vous de faire 2 et 4 sauf si vous tenez vraiment à repartir d'une install debian vide (mais ça veut dire créer une nouvelle VM, etc, etc).

**Comment by vinber** [comment]
donc les étapes :
@cquest la méthode snapshot (cela signifie que l'on a une sauvegarde),  mise à jour debian.
avec @Ljbouere on vérifie qu'educosm est ok.
@cquest mise à jour PHP
avec @Ljbouere nous vérifions
puis passage à la dernière version de yeswiki quand la peinture est sèche

il serait cependant utile d'ouvrir à @Ljbouere un accès sftp pour pouvoir gérer yeswiki

**Comment by cquest** [comment]
Oui, voilà... et à chaque étape, on peut faire un snapshot pour revenir un cran en arrière si il y a un pépin.
Dès votre feu vert, j'enclenche l'étape 1.

Pour l'accès sftp, je laisse @jocelynj créer le compte pour @Ljbouere et mettre sa clé SSH.

**Comment by Ljbouere** [comment]
Bonjour @cquest et @jocelynj On fait comment pour passer à la prochaine étape ?

Je ne pige pas tout techniquement parlaant donc je redis ce qu'il est nécessaire de mon côté :
 - un accès ftp clé ssh pour sauvegarder le site et surtout pouvoir y apporter des modifs par la suite
 - une sauvegarde de la base sql aucazou
 - Ensuite pour installer la nouvelle version du wiki : php > 7.3 et mysql > 8.12

Merci merci

**Comment by cquest** [comment]
Etapes:
1. on te fait un snapshot avant de faire les manip, ça vaut un backup (et c'est instantané à faire)
2. ajout de la clé SSH (@jocelynj je peux la mettre à la mano, mais c'est sûrement plus propre avec ansible)
3. vous faites votre chantier (php, etc) ou besoin d'aide pour ça ?

Si ça merdoie, on pourra faire un rollback sur le snapshot (lui aussi quasi instantané)
J'ai mis des cases à cocher dans le premier post pour le suivi.

**Comment by jocelynj** [comment]
La partie qui bloque actuellement, c'est pour donner accès. Je n'ai pas de clé ssh pour @vinber ou @Ljbouere.

**Comment by cquest** [comment]
J'avance sans cela, qui n'est pas indispensable... mise à jour debian, php, mysql, en principe ljb m'a dit que le wiki pouvait s'auto-mettre à jour su php et mysql sont récents.
Snapshot fait, j'avance sur le reste ce week-end.

**Comment by vinber** [comment]
super, merci
je sens bien que ces histoires de clé ssh il va falloir que je comprenne :) mais en ce moment peu de temps pour comprendre !!! mais non bloquant pour l'instant donc parfait

**Comment by cquest** [comment]
Upgrade fait vers debian 10 buster
Remplacement de php 7.0 par php 7.3
MariaDB est en 10.3.27

yeswiki devrait accepter sa mise à jour... mais j'ai pas la main pour ça, je passe le relai à @vinber ou @Ljbouere

**Comment by cquest** [comment]
Des news après l'update ?

**Comment by Ljbouere** [comment]
Bonjour, désolé pour le retard de retour. Je fais des tests . Il y a un truc qui bug...je fais retour plus tard

**Comment by Ljbouere** [comment]
tu peux me dire quel sql ?
merci

**Comment by cquest** [comment]
C'est MariaDB (le successeur de MySQL) qui était installé et qui a été mis à jour. Si besoin, tu m'appelle, même en soirée.

**Comment by cquest** [comment]
Des news @Ljbouere ?

**Comment by vinber** [comment]
je relance quand même car je ne crois pas que @Ljbouere est terminée la mise à jour ?

**Comment by Ljbouere** [comment]
Et bien je viens d eposer la question aux devs yeswiki car je n'arrive pas à faire la maj du wiki vers la dernière version cercopitheque avant de passer ensuite à doryphore. Dès que j'ai une info debugage je vous dis

**Comment by cquest** [comment]
L'issue concernait la mise à jour de l'OS, elle est faite et le service tourne...
Pour la suite (mise à jour de yeswiki), si il y a un pépin, on peut la réouvrir ou en ouvrir une adaptée.

**Comment by vinber** [comment]
oui peut-être la garder car au début on avait listé les divers points à faire.
Je renomme en mise à jour Yeswiki.
Je ne peux pas réouvrir cette note

**Comment by Ljbouere** [comment]
J'ai reçu ce message des devs 

il te faut au minimum php 5 pour que tout tourne bien pour cercopitheque et php 7.3 pour doryphore 

Et le bug de curl_init serait dû à :

php avant 4
certaines librairies php ne sont pas installées : voir la doc :https://yeswiki.net/?DocumentationInstallation
En cas de bug pour les mises à jour sur certains systèmes très légers, vérifiez la présence des librairies php-curl, php-zip, php-mbstring et php-mysqli.


Il manquerait la librairie php-curl qui était installée par défaut pour les vieilles versions de php mais qui maintenant doit parfois être installée à la main sur certaines distributions Linux 

Vous avez pigé ? :)

**Comment by cquest** [comment]
php avait été mis à jour en 7.3
php-curl n'était pas présent, je viens de l'installer, donc l'upgrade devrait pouvoir se faire.

**Comment by Ljbouere** [comment]
Super ça a marché pour passer à la dernière version cerco... et bing plus rien lors de la maj doryphore. Bon je reboucle mais on tient le bon bout

**Comment by Ljbouere** [comment]
Voici le dernier message . dingue cette histoire c'est ma plus longue maj de wiki de ma vie ! :)
Et si ça ne marche pas, il te faudra modifier par ftp le fichier /tools/webhooks/desc.xml
https://educosm.openstreetmap.fr/tools/webhooks/desc.xml
et remplacer active="1" par active="0" afin de pouvoir ensuite mettre à jour cette extension

C'est possible pour toi @cquest  ?

**Comment by cquest** [comment]
C'est modifié

**Comment by Ljbouere** [comment]
Merci t'es génial ! tout est en ordre. on peut même clore cet échange. Merci merci
