### ISSUE TITLE
Problème récurrent d'espace disque sur bzh202 à cause de Matomo

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#256]
Monit me renvoyait de plus en plus souvent des alertes de places. En fait : tous les jours depuis plusieurs semaines.

Grâce à matomo j'ai pu voir une sollicitation plus forte des services mais ça n'expliquait pas selon moi la fréquence de +/+ forte des alertes disque.
Pas trop de souci que ça plante la machine car le monitoring actif purge le cache de tuiles mais là ça ne suffisait pas et malgré ça le dique est constamment au-dessus de 80 %. Bizarre.

J'ai trouvé la cause ce matin :
- /data/db/mysql/ à 25 Go
- /data/backup/mysql/ à 17 Go

Une table plus particulièrement était énorme : 
- log_link_visit_action : 24 Go
- log_action 468 Mo
- log_visit 292 Mo

Du coup : purge manuelle via la console matomo 

```bash
/data/www/vhosts/matomo/current/console core:delete-logs-data --dates=2017-01-01,2020-12-31 --idsite=4 --optimize-tables
Preparing to delete all visits belonging to website 4 between 2017-01-01 00:00:00 and 2020-12-31 00:00:00.
You are about to delete log data. This action cannot be undone, are you sure you want to continue? (Y/N) y
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successfully deleted 540811 visits. Time elapsed: 12825.559s
```
cela a pris 2h20 minutes.

Après cela, via phpmyadmin, on a bien une taille de table log_link_visit_action réduite à zéro **MAIS** /data/db/mysql/ à 25 Go reste bloqué à 25 Go. Plus particulièrement le fichier `/data/db/mysql/matomo/log_link_visit_action.ibd` resté à 24 Go.

Pour parer à cela : obligé de faire les commandes SQL suivantes (on en profite pour s'occuper des autres tables) :

```sql
OPTIMIZE TABLE log_link_visit_action ;
OPTIMIZE TABLE log_action ;
OPTIMIZE TABLE log_visit ;
```

Après cela, le dossier de la base matomo est descendu à 1,5 Go.

Donc à faire :
- [ ] créer un script hebdomadaire pour purger cette table plus proprement
- [ ] passer à GoAccess car la plus-value n'est pas flagrante actuellement

**Comment by MaelREBOUX** [comment]
graphique après purge des caches de tuiles, des logs, de la bd matomo.
on voit bien l'augmentation de la place occupé sur le disque, tous les jours vers 23h00 après le dump de la BD MySQL. On monte au-dessus de 95 % de place prise, seuil de déclenchement des actions par monit.

![Capture d’écran 2020-12-22 à 15 05 44](https://user-images.githubusercontent.com/6370443/102896862-5c8d0c80-4467-11eb-83c4-dff54ac33e62.png)

**Comment by cquest** [comment]
Je regarde ça...

**Comment by MaelREBOUX** [comment]
y a rien à voir ;)
c'est pour le suivi… et la transparence de ce qu'il se passe sur cette machine.
Je pouvais pas m'auto-assigner ;)

**Comment by cquest** [comment]
Il y a quand même l'espace disque général qui se remplit...

Il sert à quoi ce matomo ?

**Comment by MaelREBOUX** [comment]
Stats très globales sur la consommation des tuiles. Mais ça fait qqs temps que je songe à le dégager au profit de GoAccess.

Faut "juste" que je trouve le temps de le faire. Je vais essayer semaine prochaine sur mes congés.

**Comment by cquest** [comment]
Ah oui, matomo pour ça c'est overkill et gérable avec peu de hits.

**Comment by MaelREBOUX** [comment]
Mais pi on a quand même eu une pointe ces derniers temps

![image](https://user-images.githubusercontent.com/6370443/102902162-df659580-446e-11eb-9161-250fea4afdcc.png)

**Comment by cquest** [comment]
ça sent le download massif...

**Comment by MaelREBOUX** [comment]
Je ferme ce ticket car il n'y a plus de matomo sur ce serveur depuis quelques mois déjà.
