### ISSUE TITLE
Faire pointer munin vers l'API Osmose 0.3

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#257]
Munin uutilise 
`/fr/api/0.2/meta/tags`
Il fait passer à la 0.3
`/api/0.3/tags`

**Comment by jocelynj** [comment]
Est-ce que tu peux donner un lien vers le munin qui utilise cette URL ?

L'idéal serait de commiter ce plugin munin dans le git osmose-frontend.

**Comment by frodrigo** [comment]
Je ne sias pas, j'ai vu ça dans les logs
Je pense que ça doit être ça
http://munin.openstreetmap.fr/osm28.openstreetmap.fr/osm153.openstreetmap.fr/http_loadtime.html

**Comment by jocelynj** [comment]
J'ai changé l'URL utilisé par ce plugin dans /etc/munin/plugin-conf.d/munin-node sur osm153.
