### ISSUE TITLE
Peertube: Activer le live sur l'instance OSM-FR

### ISSUE THREAD

**Issue by gendy54** [osm-fr/infrastructure#259]
Bonjour,

La v3.0 de Peertube est sortie en prod. Elle permet notamment de faire des live ce qui me parait intéressant si on veut développer quelque chose à la place du  SotmFR.

https://github.com/Chocobozzz/PeerTube/releases/tag/v3.0.0

**Comment by cquest** [comment]
Je tente l'update complet... avec un snapshot préalable.

**Comment by cquest** [comment]
Mise à jour 3.0.1 fait.

Il faut par contre configurer la partie live et modifier sûrement quelques config réseau pour permet le flux vidéo entrant.

**Comment by jocelynj** [comment]
J'ai mis à jour la config peertube dans production.yaml, ainsi que la config nginx. La config pour le live est du coup activée, mais ça parle d'un port à rediriger:
```
  # Your firewall should accept traffic from this port in TCP if you enable live
  rtmp:
    port: 1935
```
Il doit sûrement falloir rediriger ce port sur les proxy osm26/27/28.

**Comment by gendy54** [comment]
J'ai l'impression qu'on peut clôturer ce ticket, non?

**Comment by jocelynj** [comment]
Oui, on peut fermer, et le live est activé via une regle iptable sur le host:
```
iptables -t nat -A PREROUTING -i vmbr1 -d 164.132.171.132 -p tcp --dport 1935 -j DNAT --to-destination 10.1.0.155:1935
iptables -t nat -A PREROUTING -i vmbr1 -d 164.132.171.132 -p tcp --dport 1936 -j DNAT --to-destination 10.1.0.155:1936
```
