### ISSUE TITLE
Certificats https manquants

### ISSUE THREAD

**Issue by grischard** [osm-fr/infrastructure#26]
Il n'y a pas de certif valide sur tms.cadastre.openstreetmap.fr et wms.openstreetmap.fr

**Comment by don-vip** [comment]
@cquest on a un script qui teste le bon fonctionnement des ressources accédées par JOSM en HTTPS.
tms.cadastre.openstreetmap.fr est malheureusement listé en serveur qui ne fonctionne pas:
https://josm.openstreetmap.de/wiki/IntegrationTestIgnores

**Comment by don-vip** [comment]
@cquest @jocelynj est-ce qu'on peut essayer de mettre en place le https sur tms.cadastre.openstreetmap.fr pour voir si ça corrige https://github.com/osm-fr/infrastructure/issues/99 ?

**Comment by jocelynj** [comment]
@don-vip je regarde ça demain.

**Comment by jocelynj** [comment]
En fait, ce n'était pas un souci de certificat https, mais que le site configuré dans apache n'écoutait pas sur le port 443.

Ça devrait être corrigé !

**Comment by don-vip** [comment]
Je confirme que c'est bon pour https://tms.cadastre.openstreetmap.fr
Par contre le certificat de https://wms.cadastre.openstreetmap.fr n'est pas bon

**Comment by 2803media** [comment]
@ocelynj est ce que vous avez pu regarder l'histoire du certificat de wms.openstreetmap.fr il y a tjs l'erreur NET::ERR_CERT_COMMON_NAME_INVALID, a priori le domaine n'est pas renseigné dans la config let's encrypt

**Comment by jocelynj** [comment]
Les deux sites ont un certificat qui me semble cohérent.
