### ISSUE TITLE
osm145 + osm168 en surcharge...

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#260]
Phénomène étrange sur osm145 (P4CaaS) et osm168 (Pic4Review) avec une charge CPU anormale.

Impact sur munin qui n'arrive plus à grapher, et l'alerte m'est venue d'uMAp...

J'ai rebooté les containers, charge revenue à un niveau habituel.

osm145 a besoin d'une mise à jour (encore en debian-jessie 8.x plus maintenue de juin 2020).

De nombreux packages à mettre à jour... n'est-ce pas @panieravide ;)

**Comment by PanierAvide** [comment]
J'ai regardé rapidement les logs, rien vu de particulier... Et je m'occupe de mettre à jour osm145 (je pensais que c'était fait automatiquement sur les VMs OSM).

**Comment by cquest** [comment]
Pas de mise à jour auto dans les containers, vu que ça peut avoir un impact sur le fonctionnement.

C'est donc à chacun de faire ses propres upgrades mineurs et encore plus majeurs !

**Comment by PanierAvide** [comment]
À priori c'est OK pour la mise à jour de osm145, passé en Debian Stretch (9), support LTS jusqu'en juin 2022.

**Comment by cquest** [comment]
Vu que t'es chaud, tu ne veux pas passer à buster (debian 10) ?

**Comment by PanierAvide** [comment]
C'est fait

**Comment by cquest** [comment]
Je ferme, et on rouvrira si le surcharge réapparait...
