### ISSUE TITLE
sudo: faille de sécurité et donc mise à jour générale à faire...

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#261]
Doit pouvoir se faire avec ansible plutôt que host par host et CT par CT...

**Comment by jocelynj** [comment]
Tu parles de quel mise à jour ?
Juste un `apt update && apt install sudo` ?

**Comment by jocelynj** [comment]
J'ai lancé ça pour tout mettre à jour:
```
ansible -b -m apt -a "update_cache=yes name=sudo state=latest" "*"
```
