### ISSUE TITLE
Problème de connectivité IPV6 sur cluster OVH ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#262]
munin.openstreetmap.fr a de gros problèmes de mise à jour depuis ce matin.

J'ai l'impression que la connectivité IPv6 est perdue.

**Comment by Marc-marc-marc** [comment]
le soucis est peut-être plus général, depuis osm144-uamp, il n'est pas possible de joindre api.openstreetmap.org en ipv6, peut-être que c'est la cause de https://github.com/umap-project/umap/issues/876
l'ajout de l'ipv4 dans /etc/hosts n'a pas permis de résoudre le problème, j'ignore s'il faut redémarer qlq chose côté umap ou si l'OAuth utilise une autre resource

**Comment by cquest** [comment]
Oui ça semble un pépin d'IPv6 plus général au sein des CT du cluster.

**Comment by frodrigo** [comment]
Les téléchargements des extracts par osmose sont aussi touchés.

**Comment by jocelynj** [comment]
Pour ajouter la connectivité d'umap, qui est sur osm144, sur une ipv6 liée à osm26, j'a lancé cette commande sur osm26:
```
sudo /sbin/ip -f inet6 neigh add proxy 2001:41d0:1008:1f65:1::144 dev vmbr1
```
Je ne m'explique pas pourquoi on avait perdu ce proxy, vu qu'il était bien présent via `ip -6 neigh | grep 144`
