### ISSUE TITLE
osm177/tile-vect : plus de mise à jour de la base...

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#263]
La base ne semble plus mise à jour depuis décembre...

http://munin.openstreetmap.fr/osm14.openstreetmap.fr/tile-vect.vm.openstreetmap.fr/osm_replication_lag.html

**Comment by jocelynj** [comment]
@frodrigo , tu pourrais regarder la raison ?

**Comment by frodrigo** [comment]
https://github.com/makina-maps/makina-maps/issues/36

Je connais le problème et sais comment le corriger. Manque le temps.

**Comment by frodrigo** [comment]
PR fait sur imposm
https://github.com/omniscale/imposm3/pull/263

Correction manuelle de la base pour pouvoir reprendre la mise à jour par les diff.

**Comment by jocelynj** [comment]
En plus, le retard a été récupéré très vite: bien plus vite que sur les bases osm2pgsql qu'on a. Si je compte bien, 2.5 mois de retard en ~15 heures.

Merci pour la correction.

**Comment by frodrigo** [comment]
Après ce n'est qu'une base France.
Main contrairement à une base osm2pgsql pour carto-osm, il y a en plus du pré-calcul des niveaux de zoom inférieurs fait coté base de données, donc en théorie c'est plus lourd.
