### ISSUE TITLE
download. returns 403 Forbidden

### ISSUE THREAD

**Issue by andrewharvey** [osm-fr/infrastructure#264]
https://download.openstreetmap.fr/ used to provide directory listings, I'm not sure if this is an issue, or an intentional change to not provide this services anymore?

**Comment by jocelynj** [comment]
I had to block user-agent "AppleWebKit/537.36" yesterday, because there was an ongoing attack against download.openstreetmap.fr. I have just disabled this block, as the attack has stopped.

Can you tell which browser you are using, so that I could user a better user-agent next time?

**Comment by andrewharvey** [comment]
No problem, I am using Chromium.
