### ISSUE TITLE
Orthophoto 2020 Bordeaux Métropole :)

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#269]
https://opendata.bordeaux-metropole.fr/explore/dataset/ortho2020/information/
@cquest ce n'est pas un département, juste une métropole, plus difficile pour le bingo de l'ortho ! C'est un bout de 33 juste.

**Comment by cquest** [comment]
Je suis arrivé à bout du clicodrome... bientôt sur les écrans ;)

**Comment by vinber** [comment]
merci

**Comment by cquest** [comment]
La couche bordeaux_2020 est maintenant disponible et aussi intégrée dans tous_fr
