### ISSUE TITLE
imagery.openstreetmap.fr not reachable

### ISSUE THREAD

**Issue by rbuffat** [osm-fr/infrastructure#271]
Not sure if this is the correct place to ask. 

There seem to be 3 sources in ELI pointing to imagery.openstreetmap.fr: https://github.com/osmlab/editor-layer-index/search?q=imagery.openstreetmap.fr and this server seems to be not reachable since 37 days. Is this server just temporarily down or should these sources be deleted?

**Comment by cquest** [comment]
It's temporarily down, while moving old imagery to a new server.

Thanks for the link, I'll move these first ;)

**Comment by rbuffat** [comment]
There is no rush. I just wanted to ask in case they are not available anymore.

**Comment by Cyrille37** [comment]
Hi. By the way, I would like to point out that the imagery.openstreetmap.fr is not listed in the wiki at https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#Liste_des_services_web_sur_le_domaine_openstreetmap.fr

**Comment by tykayn** [comment]
2023 update, this service is down :)

**Comment by Cyrille37** [comment]
il n'y a plus de dns pour imagery.openstreetmap.fr, sujet clot ...
