### ISSUE TITLE
Migration phpBB > Discourse pour forum.openstreetmap.fr

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#272]
Le forum était complètement HS il y a quelques temps.

Plutôt que de remettre un coup de pied dans phpBB, j'ai enfin creusé le sujet de la migration phpBB vers Discourse.

Après 2 jours à batailler pour la connexion depuis le docker de discourse vers le mysql de phpBB, j'ai pu transférer l'essentiel du contenu (catégories, messages, comptes utilisateurs).

C'est donc sur https://discourse.openstreetmap.fr/

**Il ne reste plus qu'à modifier le proxy pour faire pointer forum.openstreetmap.fr vers 10.1.0.169, l'IP interne du container Discourse (un coup d'ansible ?).**

**Comment by jocelynj** [comment]
J'ai reconfiguré le proxy pour pointer vers la VM de discourse, mais ça ne marche pas: faut-il aussi activer le support de forum.openstreetmap.fr sur cette VM ?

D'après les logs de firefox, ça ressemble à des requetes interdites par le navigateur vers du code javascript.

**Comment by cquest** [comment]
En attendant de trouver mieux, j'ai mis un 302 forum > discourse.

**Comment by jocelynj** [comment]
Merci, ça marche parfaitement :)

Concernant les backups de la bdd, est-ce que tu as mis un truc du genre automysqlbackup ou autre, pour garder des "vieilles" versions de la bdd ?

**Comment by cquest** [comment]
la BDD phpBB ? je pensais archiver le container, tout simplement. On peut le restaurer si besoin et qu'il soit fonctionnel.

Discourse est répliqué sur les 2 autres noeuds du cluster, je l'ai ajouté aux backups proxmox

**Comment by cquest** [comment]
Quid des redirections...

Le script d'import phpBB de Discourse a un mécanisme pour générer des redirections sur les anciennes URL de phpBB vers le nouveau contenu sur Discourse.

Le problème c'est que visiblement, ça ne fonctionne pas actuellement, soit à cause d'un problème lors de la migration, soit à cause d'une configuration manquante. Du coup on arrive sur une page générique, pas trop catastrophique, qui liste les sujets en cours et propose de faire une recherche. Mieux que rien mais pas idéal.

Comment améliorer ça ?

- soit on arrive à faire fonctionner le mécanisme prévu par Discourse (ce qui serait l'idéal),
- soit on conserve l'ancien forum en lecture-seule, en y ajoutant un bandeau pour signaler que c'est une archive + un lien pour aller sur Discourse. Dans ce cas, forum.openstreetmap.fr seul peut être redirigé vers Discourse, mais le reste non, pour arriver sur le contenu archivé.

Qu'en dites-vous ?

**Comment by jocelynj** [comment]
> Discourse est répliqué sur les 2 autres noeuds du cluster, je l'ai ajouté aux backups proxmox

Je parlais effectivement de la bdd de discourse. Mettre la VM de forum en archive me va parfaitement :)
En fait, je me demande comment la mise à jour de discourse va se gérer, mais la config de replication/backup que tu as faite est parfaite.

> Quid des redirections...

On avait essayé de faire une copie lecture-seule du forum avec @JacLavi, mais c'était pas idéal, surtout parce qu'on ne gardait pas toutes les URLs, et que le lien de recherche était cassé. Perso, je préférerais que ça fonctionne avec discourse directement, surtout que ça permettrait aussi aux gens de commenter sans souci.

**Comment by cquest** [comment]
Discourse génère ses propres backups, au sein de la VM, VM dont le contenu est répliqué par proxmox sur les autres noeuds du cluster et qui fait aussi un backup 2 fois par semaine sur le HDD... ceinture et bretelles.

**Comment by Marc-marc-marc** [comment]
la proposition 2 est celle qui avait été décidée et sur laquelle avait travaillé Jocelyn (hormis la redirection forum->discourse qui me semble elle aussi une mauvaise idée, le visiteur va devoir récupérer son mot de passe, autant lui mettre une page l'informant de cela au lieu de l'envoyer sur une page où il va tester son mot de passe sans succès.
mais si ton bidule gère les redirections, pourquoi changes-tu de nom de domaine ? autant garder le même, cela permettra automatiquement d'avoir l'ancien contenu et la possibilité de "continuer é discuter" autour de celui-ci

**Comment by gendy54** [comment]
C'est vrai que j'ai pas compris pour le nom de domaine avait changé. Comme le dit Marc, ca peut faciliter la reprise des URL, non?
Pour le coup du mdp, je ne trouve pas ca gênant et c'est bien expliqué. Ca permettra peut-être à terme de faire le ménage des comptes crées sous l'ancien forum et pour lesquels il n'y a pas de messages.

**Comment by vinber** [comment]
ce que je comprends :

- pour commencer @cquest fait discourse.openstreetmap.fr parce que le forum est moribond (qui "traine" depuis un moment)
- cela serait bien de garder plutôt forum.openstreetmap.fr (et dans l'idéal garder les éventuels liens qui pourraient être disséminés sur les internets ou à minima comme le dit dit @Marc-marc-marc éviter de se trouver sur une page incompréhensible et d'arriver sur la page d'accueil du "discourse" au "pire")

Comment on fait cela, aucune idée :)

**Comment by cquest** [comment]
J'ai fait un rebuild du docker pour changer de domaine, qui est donc maintenant forum.openstreetmap.fr

Le discourse.openstreetmap.fr était temporaire, le temps de migrer, de valider que c'était ok, etc.

J'ai aussi ajouté quelques plugins que je détaillerai plus tard... j'ai un rdv à St Mandé à honorer ;)

**Comment by JacLavi** [comment]
https://discourse.openstreetmap.fr/ -> https://forum.openstreetmap.fr/  ->  Welcome to nginx!

**Comment by cquest** [comment]
Corrigé, désolé, modif faite trop vite avant de partir ce matin.

**Comment by cquest** [comment]
Premier plugin activé: l'ajout d'un "footer", qui nous permet d'avoir des liens vers nos autres outils, etc...

**Comment by cquest** [comment]
Les problèmes de diffusion de mail sont en principe réglés.
