### ISSUE TITLE
Maj WP à faire

### ISSUE THREAD

**Issue by gendy54** [osm-fr/infrastructure#273]
Hello,

Ca fait longtemps que la version de WordPress n'a pas été mise à jour sur le site. J'arrive pas à savoir combien on a de versions de retard.

Merci ;)

**Comment by cquest** [comment]
Je regarde ça... un petit snapshot avant les mises à jour, mais en général ça se passe bien avec wordpress.

**Comment by gendy54** [comment]
Effectivement, comme il faut toujours faire des sauvegardes, je préfère laisser ca aux pros ;)

**Comment by cquest** [comment]
Voilà, c'est fait:
- wordpress passé en 5.6.2
- plugins mis à jour
- thèmes mis à jour
