### ISSUE TITLE
rendu admim_level ko

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#275]
le [rendu admin_level=4](https://github.com/osm-fr/layers-mapnik-styles/blob/master/admin4.xml) (et à priori les autres) https://layers.openstreetmap.fr/?zoom=9&lat=-37.84665&lon=144.87094&layers=B000000000FFFFFFFTFFFFFFFFFFFFFFFFF
les tuiles sont 404 https://a.layers.openstreetmap.fr/admin4/9/459/314.png

**Comment by cquest** [comment]
A voir une voir que https://github.com/osm-fr/infrastructure/issues/276 sera réglé.

**Comment by vinber** [comment]
mais n'était pas une annonce de #276 ?

est-ce osm113 dépendant ?

**Comment by cquest** [comment]
Oui, c'était lié, comme c'est de retour je ferme l'issue.
