### ISSUE TITLE
osm13 DOWN (rendus humanitaire, layers, etc)

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#276]
**osm13** ne répond plus depuis cette nuit, même pas de ping en local.

Contact pris avec free pour voir ce qu'il y a.

Impact:
- rendu humanitaire (que je vais rediriger temporairement sur le rendu osm.org)
- certains niveau du rendu FR (que je vais remettre sur osm25)
- les rendus "layers"
- rendu bdtopo et volta
- des analyses osmose qui ne se font plus (bdtopo/volta)

**Comment by Marc-marc-marc** [comment]
ajout : https://tile.openstreetmap.fr (la page html et le code js pour afficher les couches principales) impacte par ex https://github.com/tankaru/OpenSwitchMaps/issues/46#issuecomment-792129431

**Comment by cquest** [comment]
Action prévue au DC sur osm13 cet après-midi...

**Comment by cquest** [comment]
osm13 relancé cet après-midi.

Etrange problème de défaut lié à l'alimentation une erreur de "voltage" indiquée en panneau avant.
Les alims ont été débranchées du secteurs, l'un a été rebranchée, le serveur a redémarré, l'autre a été ajoutée.
Puis quelques cycles de reboot / extinction... sans problème.

**Comment by jocelynj** [comment]
Merci pour la gestion de l'erreur.

Tu sais si c'est quelque chose qu'on peut tracker sur munin ? Genre via le power sur http://munin.openstreetmap.fr/openstreetmap.fr/osm13.openstreetmap.fr/ipmi_power.html, qu'on voit baisser quelques jours avant le plantage.

**Comment by cquest** [comment]
Effectivement, je n'avais pas regardé les graphes munin et ils sont bavards...

Oui, la consommation a baissé à partir du 4, mais c'est semble-t-il parce que /ssd2 a disparu aussi des graphes !
Du coup, postgresql DOWN, plus de rendu, la conso globale baisse.

Il y a donc eu un problème sur un SSD, soit causé par le défaut électrique, soit c'est le SSD qui a causé le défaut.
Bref, problème hardware quelque part :(

La base PG est maintenant à jour, j'ai retiré la redirection du rendu HOT, donc retour à la normale.

**Comment by cquest** [comment]
En creusant un peu plus les graphes munin, on constate:

Le 4 mars:
- un reboot à 6h39
- puis une charge CPU faible (load average très bas)... du au non redémarrage de renderd*
- du coup des ventilo qui ralentissent,
- du coup des SSD qui prennent 10° en température

Le 5 mars:
- un reboot à 3h07
- là /dev/sdc disparait
- la température /dev/sdb prend 10° de plus (70°, 50° en temps normal).

Rien d'utile dans syslog pour la cause des reboot du 4 ou du 5 et pas de lien établi avec l'erreur "voltage" affichée sur l'avant du serveur.

* renderd: encore un problème avec /var/run/renderd qui ne se recréait pas suite à un reboot. J'ai ajouté deux ExecStartPre dans la config du service systemd pour qu'il soit créé ET accessible par www-data

**Comment by cquest** [comment]
/dev/sdb semble avoir quelques soucis... temps de latence très élevé (plus de 100ms).

Je vais migrer son contenu pour le libérer.

**Comment by vinber** [comment]
et est-ce qu'il n'existe pas des alertes pour ne pas avoir à aller chercher sur les graphes ?
Quand munin parle de manière suffisament forte ou des variations particulières, @tech reçoit un mail ?
j'ai l'impression que munin sait faire plein de choses, je suis surpris que cela n'utilise pas des systèmes d'alertes ?

**Comment by cquest** [comment]
Il y a des alarmes sur des valeurs anormales, mais ce valeurs ne sont pas forcément renseignées partout (bel exemple avec la latence sur les disques).

Là c'est une combinaison de valeurs anormales + l'analyse des logs qui permet de comprendre que quelque chose ne va pas ou de revenir en arrière.

**Comment by Marc-marc-marc** [comment]
pour ma part je me suis désabonné il y a longtemps de la ml qui relayent les alertes : une alerte n'est utile que si on souhaite la traiter.
hors pendant les mois précédents, munin était remplit d'alerte permanente (munin aussi a subit un gros recalibrage pour ne plus considérer comme critique ce qui est ainsi en état permanent, par ex les disques bien remplis)
il y a un niveau de "bruit de fond" beaucoup trop élevé que pour pouvoir faire autre chose que "maintenant qu'on sait qu'il y a eu un soucis grave, on retrouvera l'anomalie dans le tas des infos".
Si on veux en faire quelque chose d'utile, faut les traquer une à une ou faire une nouvelle liste de diffusion oü on ajoute au cas par cas des alertes réelles (genre renderd est ko pendant plus de X min, ce que permet facilement monit par ex)

**Comment by Marc-marc-marc** [comment]
https://listes.openstreetmap.fr/wws/info/admin-notification
abonné 0 :) apparemment je ne suis pas le seul à m'en être désabonné
février 2021 2604 Messages soit quasi 100 messages par jour

**Comment by cquest** [comment]
La portion de données PG qui était sur /ssd2 est maintenant sur /ssd-nvme
Le cache de tuiles humanitaires a lui été migré sur /ssd-zfs dans des datasets séparés à partir du zoom 14.

J'en ai profité pour upgrader PG en v13 (depuis la 12).
