### ISSUE TITLE
[URGENT] le certificat Let's Encrypt pour *.openstreetmap.bzh est expiré

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#278]
Bonsoir,

après signalement d'un pb sur le serveur de tuiles en langues régionales je constate que le certificat est expiré depuis 2 j

![Capture d’écran 2021-03-16 à 22 53 50](https://user-images.githubusercontent.com/6370443/111385034-82aefb00-86aa-11eb-917c-43b5d3154ed9.png)

C'est géré sur le frontal web osm25 en reverse proxy vers bzh202.

Un pb avec le cron ?

**Comment by jocelynj** [comment]
Le cron tourne bien, mais on a une erreur "urllib2.HTTPError: HTTP Error 403: Forbidden" dans le log.

**Comment by MaelREBOUX** [comment]
Ha zut.

une url pour tester à la fin : https://tile.openstreetmap.bzh/br/9/254/179.png

**Comment by jocelynj** [comment]
C'est corrigé: le git de "acme-tiny" n'avait pas été mis à jour depuis 2017, et il y a besoin d'une mise à jour pour des changements lié au site de letsencrypt.

D'après les logs (emails sur le compte letsencrypt d'osm25), ça s'est mis à planter en 2021.

**Comment by MaelREBOUX** [comment]
\o/

merci @jocelynj

**Comment by MaelREBOUX** [comment]
25 min entre le signalement et la résolution. balaise.

**Comment by jocelynj** [comment]
Pour info, j'ai vérifié sur les autres machines, et elles ont toutes la bonne version de acme-tiny. J'ai utilisé cette commande:
```ansible letsencrypt -b --become-user letsencrypt -m shell -a "cd ~/acme-tiny && git describe --long"```
