### ISSUE TITLE
addr.openstreetmap.fr ne répond pas

### ISSUE THREAD

**Issue by Bonbadil** [osm-fr/infrastructure#28]
If you need the issue in english, just ask.

Bonjour,
Sur l'osmecum "Intégrer les adresses" (https://wiki.openstreetmap.org/w/images/8/86/Osmecum_integration_adresses_v1.odt) indiqué sur la page https://wiki.openstreetmap.org/wiki/WikiProject_France/Osmecum, le site http://addr.openstreetmap.fr est utilisé comme outil de base. Or j'ai bien une résolution du nom mais pas de réponse du serveur.

**Comment by Marc-marc-marc** [comment]
le service est renseigné comme HS sur https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#Liste_des_services_web_sur_le_domaine_openstreetmap.fr
le osmecum mériterait une maj, en attendant voici une doc plus à jour https://bano.openstreetmap.fr/

**Comment by Marc-marc-marc** [comment]
ping @vinber :)

**Comment by vinber** [comment]
je suis découvert :)
