### ISSUE TITLE
taginfo : maj sans effet cette nuit

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#281]
la maj de cette nuit (terminée sans erreur dans les logs) n'est pas visible sur https://taginfo.openstreetmap.fr (en haut à droite Données du: 2021-03-22 17:33 UTC, heure d'une maj manuelle que j'avais lancé)
j'ai vu que l'host a changé de host et rebooté, il y a d'autre chose qui ont été faite et qui pourrait expliquer le soucis ?
20_update.sh + 30_restart_webserver.sh en cours au cas oü cela suffit à résoudre le soucis

**Comment by Marc-marc-marc** [comment]
après 20_update.sh + 30_restart_webserver.sh : même problème
maj avec le script du cron (pbf+base de tagingo+redémarage service web) : ok
à sruveiller demain pour voir s'il y a une différence entre à la main et en cron

**Comment by jocelynj** [comment]
Je n'ai en fait pas changé le host: j'ai juste changé le hostname en taginfo.vm.openstreetmap.fr, pour aligner avec le nouvelles VMs. Et effectivement, avec un reboot.
Peut-être un lock qui ne s'est pas supprimé correctement au reboot ?

**Comment by Marc-marc-marc** [comment]
cront de ce nuit ok

**Comment by jocelynj** [comment]
Super: c'est rassurant sur le renommage :)

Je vais continuer à renommer les VMs petit à petit: ça sera bien pratique pour mieux lire le status backuppc et munin.

**Comment by JacLavi** [comment]
> Peut-être un lock qui ne s'est pas supprimé correctement au reboot ?

Un lock qui ne serait pas dans /tmp ?
