### ISSUE TITLE
impossible d'accéder à bzh202 en ssh

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#282]
Bonjour,

j'ai des alertes de "pics" réseau sur bzh202 (pê anodin)
mais impossible d'aller sur la machine en rebond depuis  osm25 :

```ssh: connect to host 10.1.0.202 port 22: Connection refused```

**Comment by cquest** [comment]
J'ai stoppé/redémarre le conteneur.

**Comment by MaelREBOUX** [comment]
j'y accède bien de nouveau. merci.
