### ISSUE TITLE
Live is dead (ok j'adore la faire celle là :) )

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#283]
https://live.openstreetmap.fr/

cela s'affiche mais il ne se passe rien, vrai pour 2 personnes (dont moi).

**Comment by vinber** [comment]
ah, là cela fonctionne :) j'ose jamais fermé car aucun idée si c'est le hasard !

**Comment by Marc-marc-marc** [comment]
il semble y avoir plusieurs problèmes : 
- le cron produit un message trop gros, qui du coup est rejeté 
` status=bounced (cannot update mailbox /var/mail/live for user live. error writing message: File too large)`
- @jocelynj avait écrit un test pour basculer sur osm.org si les infos osm.fr était trop veille... ce test semble s'être activé ce qui indiquerait un soucis ailleurs dans l'infra (mais il manque un peu de débug à ce test pour le rendre pratique)
`Switch to http://planet.openstreetmap.org/replication/minute/`
- en passant l'url ci dessus devrait être en https, p'tre que la redirection http->https pose soucis au code
- ensuite 2 lignes incompréhensible
`4470641 4470642
004/470/642`
- puis un message d'erreur à propos d'un fichier
`python: can't open file 'compute-changeset-data.py': [Errno 13] Permission denied``
le seul fichier du même nom n'a pas de soucis de permission
`-rwxr-xr-x 1 live live 5067 Dec  4  2016 /data/project/live/osm-livechanges/backend/compute-changeset-data.py`

**Comment by vinber** [comment]
je confirme l'instabilité :)

le live est reparti, je l'ai laissé tourné un moment puis j'ai fermé l'onglet.
J'ouvre de nouveau le live et c'est bloqué quelques minutes (les minutes s'affichent) mais rien d'autres, puis tout fonctionne

**Comment by jocelynj** [comment]
@Marc-marc-marc : tes modifs m'ont l'air pertinente en tout cas. Tu sais si c'est pushable sur un git ?

Concernant le souci sur /var/mail/live, je pense que c'est pas la taille de l'email qui pose problème, mais qu'on doit avoir trop d'email non lus dedans. Rediriger dans un log avec rotation des logs est effectivement une meilleure solution.

**Comment by jocelynj** [comment]
Le script de @Marc-marc-marc a été mis en place, et marche correctement.
