### ISSUE TITLE
docker et proxmox

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#284]
documenter ce qui a été fait, ce qui va et ce qui ne va pas pour installer un docker dans un CT proxmox.
ex de CT docker : cadastre-joker et pdm

**Comment by jocelynj** [comment]
Pour créer un CT proxmox avec support de docker, li faut juste lancer:
```
$ ./tools/add-vm.py --help
...
  --docker              Enable docker support
```
Ça ajoute les features `keyctl=1,nesting=1` sur le container, et s'assure qu'on a au moins 50G de disque.

@frodrigo m'a proposé d'aussi installer les paquets docker et docker-compose dans le CT, que je rajouterai sous peu.

**Comment by jocelynj** [comment]
Paquets ajoutés sur https://github.com/osm-fr/ansible-scripts/commit/920424f8cfb9ff63c2f222ed8c020e560497f992
