### ISSUE TITLE
overpass : pas de rotation/pruge du log nginx

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#286]
en prod (osm147)
`head -n 1 /var/log/nginx/access.log`
2020/06/25 ....

**Comment by Marc-marc-marc** [comment]
purge effectuée à la main pour /var/log/nginx/access.log et /var/log/nginx/error.log
a faire : vérifier pq c'est pas fait automatiquement

**Comment by cquest** [comment]
Le service logrotate ne semble pas démarré au niveau systemd (enabled mais failed)

Côté config logrotate pour nginx ça semble correct, vérifée avec: `logrotate -d /etc/logrotate.d/nginx`

Voir par la même occasion pourquoi osm147 n'a pas de graphes munin ? Ceci aurait permis de voir de l'orange puis du rouge apparaitre dans le dashboard général et d'agir préventivement.

**Comment by JacLavi** [comment]
Les services logrotate, man-db et munin-node sont failed.

**Comment by cquest** [comment]
Lien avec le chantier démarré en juin dernier mais qui ne semble pas achevé ?

https://github.com/osm-fr/infrastructure/issues/19#issuecomment-648882260

Entre autre, osm147 est toujours en unpriviledged=no, ce qui semble avoir un lien avec les problèmes systemd de logrotate mais aussi munin-node.

**Comment by JacLavi** [comment]
https://forum.proxmox.com/threads/logrotate-issue-in-buster-lxc.56726/

J'ai appliqué ceci :

systemctl edit logrotate.service

[Service]
PrivateDevices=false
PrivateTmp=false
ProtectControlGroups=false
ProtectKernelModules=false
ProtectSystem=false

systemctl daemon-reload
systemctl start logrotate.service



Considérer de généraliser la soluton de 'ndoo'   : 

1- turn nesting off
2- add these lines to the lxc config file
Code:
lxc.apparmor.profile = generated
lxc.apparmor.allow_nesting = 1

Vérifier demain avant de clore le ticket.

**Comment by cquest** [comment]
Je ne doute pas que ce puisse être une solution, mais qu'en est-il de l'isolation de ce conteneur ?

Il n'y a pas de raison, il me semble, de rester en unpriviledge=no (donc en priviledged) et d'avoir à faire ce genre de config spécifique vu que pour les autres CT, il n'y a, à ma connaissance, pas de problème avec logrotate ni munin-node (jamais vu sur ce que j'administre ici ou ailleurs).

**Comment by JacLavi** [comment]
La rotation des logs est effective (vérifié sur 3 jours) 

Le problème dépasse le cas spécifique de osm147,
voir https://github.com/osm-fr/infrastructure/issues/210

Le lancement de munin se heurte au même problème.  Il tourne cependant sur lancement manuel.

On peut fermer ce ticket.

**Comment by cquest** [comment]
Il n'y a que osm147 qui semble encore être en unpriviledged=no (cause initiale des problèmes rencontrés), osm148 a migré, les autres aussi.

**Comment by jocelynj** [comment]
Est-ce qu'on peut basculer overpass sur osm148, et ré-installer osm147 avec la bonne configuration, directement en Debian Buster ?  En plus, on a un rôle ansible qui devrait réinstaller overpass.

**Comment by Marc-marc-marc** [comment]
pour mémoire, on n'a plus 2 vm overpass, on a 1 vm overpass prod coincée avec les soucis qui nécessiterait un backup/restore et une vm overpass dev coincé parce que l'espace disque a été réduit à moins que ce qu'il faut pour y faire tourner l'instance de prod

**Comment by JacLavi** [comment]
Que faudrait-il faire pour avoir à nouveau 2 CT Overpass (osm147 et osm148 ou une nouvelle)  rapidement opérationnelles ?

**Comment by cquest** [comment]
Le plus simple a l'air d'être un backup/restore d'osm147, même si ça coupe le service pendant quelques minutes, non ?

**Comment by JacLavi** [comment]
> Le plus simple a l'air d'être un backup/restore d'osm147, même si ça coupe le service pendant quelques minutes, non ?

L'idée un peu discutée hier sur Irc est d'avoir 2 overpass opérationnels (identiques ?)  pour assurer la redondance par bascule. 

Et donc qu'en est il de l'espace disque a été réduit sur 148 (si j'ai bien compris) ?

**Comment by jocelynj** [comment]
> Le plus simple a l'air d'être un backup/restore d'osm147, même si ça coupe le service pendant quelques minutes, non ?

On peut faire ça sans faire un backup de /ssd, qui contient la base overpass ?

Si oui, je pense que c'est la bonne solution aussi.

**Comment by JacLavi** [comment]
> On peut faire ça sans faire un backup de /ssd, qui contient la base overpass ?
> 
> Si oui, je pense que c'est la bonne solution aussi.

Certes ; ça règle seulement le problème ponctuel d'osm147.

J'insiste pour ne pas abandonner l'idée d'avoir 2 overpass opérationnels (identiques ?) pour assurer la redondance par bascule. Et semble t-il redonner du disque à osm148.

**Comment by JacLavi** [comment]
> Le plus simple a l'air d'être un backup/restore d'osm147, même si ça coupe le service pendant quelques minutes, non ?

Ce dépend de la continuité de service que l'on veut.

**Comment by cquest** [comment]
> J'insiste pour ne pas abandonner l'idée d'avoir 2 overpass opérationnels (identiques ?) pour assurer la redondance par bascule. Et semble t-il redonner du disque à osm148.

Dans ce cas osm148 pourrait plutôt aller sur le cluster free, où l'on a plus de ressources SSD dispo pour ça.

**Comment by JacLavi** [comment]
Pas de problème pour aller chez Free. Nous préparons une demande de CT. Et nous allons regarder à mettre en place un round-robin osm147 <-> osm148.

**Comment by JacLavi** [comment]
> [Service]
> PrivateDevices=false
> PrivateTmp=false
> ProtectControlGroups=false
> ProtectKernelModules=false
> ProtectSystem=false


J'ai l'ai fait aussi pour munin.

**Comment by jocelynj** [comment]
overpass a été coupé, et devra être réinstallé à partir de 0, ce qui corrigera ce souci.
