### ISSUE TITLE
Munin ::  502 Bad Gateway nginx/1.14.2

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/infrastructure#287]
Deux fois cet après-midi et maintenant (21:15) impossible de consulter munin 

 https//munin.openstreetmap.fr

502 Bad Gateway.

**Comment by cquest** [comment]
Encore plein de CLOSE_WAIT... j'ai donc essayé

`ss --tcp state CLOSE-WAIT -K`

Sans succès bien que les socket en CLOSE_WAIT aient disparu... par contre le restart d'apache résoud bien le problème.

On avait déjà eu ce type de conportement, @Marc-marc-marc avait réglé le problème avec monit (
https://github.com/osm-fr/infrastructure/issues/186) mais il y a une rechute ou un nouveau problème.

**Comment by cquest** [comment]
Ces CLOSE_WAIT étant sur des connexions de localhost à localhost:80, j'imagine que ce sont les graphes de l'apache de munin qui les provoquent.

Comme ce graphe n'a pas d'utilité, **j'ai supprimé les liens symboliques dans /etc/munin/plugins pour apache_accesses apache_processes apache_volume** et relancé munin-node

**Comment by jocelynj** [comment]
J'avais aussi vu qu'on avait pas mal de CLOSE_WAIT venant de localhost, mais pas fait le lien avec munin (ou peut-être monit ?)

Ta solution de supprimer les logs apache sur munin me convient parfaitement, et ça devrait corriger le souci. Après, reste à voir pouvoir on n'a jamais vu ça ailleurs...

**Comment by JacLavi** [comment]
Testé deux fois aujourd'hui. On peut fermer. A surveiller de près.

**Comment by jocelynj** [comment]
À ce que je vois, on a plein de CLOSE_WAIT sur le port 80, venant de 10.0.0.26/27/28. Je regarde si ces connections sont aussi visibles côté hosts.

**Comment by cquest** [comment]
apache encore dans les choux ce matin.

Aux grands maux les grands remèdes, voici ce que j'ai ajouté en cron:

`* *     * * *           cd /root; wget -q -N -T 1 http://localhost/ || service restart apache2`

Donc si pas de réponse d'apache sur localhost au bout d'1s , il est relancé, mais c'est quand même louche ces soucis.

**Comment by JacLavi** [comment]
> Donc si pas de réponse d'apache sur localhost au bout d'1s ,

1 minute ;)

# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command

Oui, c'est louche.

**Comment by cquest** [comment]
1s pour le wget... vérifié toues les 1mn par le cron ce qui est amplement suffisant pour un service absolument pas critique.

**Comment by JacLavi** [comment]
> `* * * * * cd /root; wget -q -N -T 1 http://localhost/ || service restart apache2`
> 
> Donc si pas de réponse d'apache sur localhost au bout d'1s , il est relancé, mais c'est quand même louche ces soucis.

Je remets 50 roupies dans le bastringue car là ça semble bloqué de chez coincé.   

De 'plusieurs srv sans graphe' on est passé à 'pas de Munin du tout'  la plupart du temps.

**Comment by cquest** [comment]
J'ai trouvé le conteneur stoppé ce matin. Relancé.
syslog indique des OOM.

RAM du conteneur passée à 2Go + 256Mo de swap (était à 1Go et pas de swap).

**Comment by cquest** [comment]
Dans les trucs étranges sur les graphes, le nombre de threads/process passe progressivement d'une centaine à plus de 700, tous en "sleeping".

http://munin.openstreetmap.fr/osm26.openstreetmap.fr/osm127.openstreetmap.fr/processes.html

**Comment by cquest** [comment]
Voilà qui fonctionne (enfin):

`curl http://localhost/ -s --max-time 2 --connect-timeout 1 > /dev/null || service apache2 restart`

**Comment by jocelynj** [comment]
En regardant "git log -p apache2/mods-available/mpm_event.conf", j'ai vu qu'on avait diminué de beaucoup le nombre de threads en 2018. J'ai tout monté, et désactivé le cron pour voir si ça corrige:
```diff
-       StartServers            1
-       MinSpareThreads         1
-       MaxSpareThreads         2
+       StartServers            2
+       MinSpareThreads         5
+       MaxSpareThreads         75
        ThreadLimit             64
-       ThreadsPerChild         4
-       MaxRequestWorkers       16
-       MaxConnectionsPerChild  100
+       ThreadsPerChild         25
+       MaxRequestWorkers       150
+       MaxConnectionsPerChild  500

```

**Comment by Marc-marc-marc** [comment]
de mémoire le nombre de thread apache avait été diminué parce que c'était pas très utile de consommer de la mémoire pour avoir des thread inactif dans apache alors que par ailleurs il y avait de nombreux OOM... avec 64 connexions simultanées max cela me semblait déjà largement surdimensionné (4 personnes regardant la page au même instant en chargeant 3 images en //, cela fait 16 connexions simultanées).
le soucis est ailleurs, les slots ne sont pas fermés proprement donc reste ouverte... et ce peu importe si on met 1 slot ou 1000.

**Comment by Marc-marc-marc** [comment]
Le script est-il une amélioration par rapport à monit `timeout` ? actuelement configuré à 25, il suffirait de la baisser à 1
et/ou d'utiliser
```
#     networkTimeout:    1 seconds   # timeout for network I/O
#     programTimeout:    2 seconds # timeout for check program

```
et si vraiment la ligne curl a un avantage, la convertir en `check program myscript with path /usr/local/bin/myscript.sh` aurait l'avantage d'éviter un 7ieme système de monitoring

**Comment by jocelynj** [comment]
N'oublie pas que quand tu ouvres la page http://munin.openstreetmap.fr, tu peux te retrouver à faire plein de requêtes pour accéder à toutes les images. De plus, la config par défaut d'apache est normalement bien faite pour les petits sites. Je peux baisser MinSpareThreads à 1 si tu veux, en laissant la config max.

Pour info, j'ai regardé le log apache au moment de la coupure d'hier à 18:40, et j'ai juste vu qu'il y avait plein de GET d'une seule IP pour récupérer les images, et ceci, jusqu'au relancement par le cron. C'est ce qui me fait penser qu'on n'avait pas assez de threads apache.

Pour le moment `netstat -tapn` ne montre pas de connexion en CLOSED_WAIT. On verra si ça change.

**Comment by cquest** [comment]
1 semaine sans redémarrage d'apache... on peut fermer, non ?

**Comment by jocelynj** [comment]
Yep, on peut fermer, surtout qu'on n'a toujours pas de connexion en CLOSED_WAIT.
