### ISSUE TITLE
Corrupted extract of Polynésie

### ISSUE THREAD

**Issue by Stephixus** [osm-fr/infrastructure#288]
Extract of Polynésie seems empty.

**Comment by PanierAvide** [comment]
Same behaviour seen from 9 April. Many of exports listed in http://download.openstreetmap.fr/extracts/south-america/ have a quite small size (few kb). Polynesia export only contain some relations data, but are nearly empty.

**Comment by jocelynj** [comment]
I've changed the polygons around this date: https://github.com/osm-fr/osm-extract-replication/commits/master

Maybe the new extract for south-america is incorrect?

**Comment by Stephixus** [comment]
Polynesia is now part of the australia-oceania.poly of Geofabrik.

**Comment by jocelynj** [comment]
Interesting. I thought that the polygon for south-america had to go to the -180° meridian as tools weren't able to use a polygon crossing the 180° boundary.

**Comment by jocelynj** [comment]
I've moved the polygons for several countries from south-america to oceania on https://github.com/osm-fr/osm-extract-replication/commit/c09ac476f4f528adb3288f82cb26abba8472c006.

Extracts are re-generated, and diffs will soon be available.

**Comment by jocelynj** [comment]
Can you verify if the extracts are correct on http://download.openstreetmap.fr/extracts/oceania/ ?

**Comment by Stephixus** [comment]
Yes, the extract is correct.
However, the .poly for Polynesia is smaller on Geofabrik and matches better to reality.
https://download.geofabrik.de/australia-oceania.poly
So the extraction is a bit too large.

**Comment by jocelynj** [comment]
I've compared the two extracts, but didn't see islands that were present on the OSM-FR extract, but not on Geoabrik one. Can you point me to one difference?

In any case, I've updated the polygon on https://github.com/osm-fr/osm-extract-replication/commit/322174996c6ace6aaca041c2d89fbad214660323

**Comment by Stephixus** [comment]
The polygon is the same now. Thanks!
About the extract, you’re right. Sorry!
There are 3 Cook Islands outside the polygon within both!
I thought this was the case only with the osm-fr extract.

So it’s all right. Thank you very much.

**Comment by jocelynj** [comment]
Thanks for checking - I can now close the issue :)

@frodrigo: This change impacts osmose, as some extracts were moved from south-america to oceania. I will change this later today.
