### ISSUE TITLE
la base de données PostgreSQL monde n'aime pas les ST_SIMPLIFY ?

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#29]
Bonjour,

Je bute sur un problème pour la mise en prod de la carte en breton.
J'ai trouvé d'où vient le problème : aucune requête contenant un ST_SIMPLIFY n'aboutit.
Cela touche bien évidemment toutes les couches dédiées aux petites échelles.

2 exemples ci-dessous qui aboutissent très bien et assez vite sur ma base Bretagne en local mais qui ne rend rien ou un truc bizarre dans la console psql quand on les joues sur la base monde.

```sql
SELECT osm_id, ST_Simplify(way, 20) AS way, way_area AS area, COALESCE(landuse, leisure, "natural", highway, amenity, tourism) AS type  FROM planet_osm_polygon  WHERE way_area > 100000
AND way && ST_SetSRID('BOX3D(-205462.7320305551 6095394.383573093,-146759.0943075371 6154098.02129611)'::box3d, 3857);

SELECT osm_id, ST_Simplify(way, 10) AS way, COALESCE(railway) AS type, tags->'usage'::text AS usage, tunnel, bridge FROM planet_osm_line  WHERE railway IN ('rail') AND tags->'usage'::text IN ('main', 'branch')
AND way && ST_SetSRID('BOX3D(-607072.89 6105178.323193599,-469629.1017841224 6590288.74)'::box3d, 3857) ;
```
Une idée de la cause @cquest ?

**Comment by jocelynj** [comment]
Est-ce que ça ne serait pas un problème d'index ?

Je me demande si "way && ..." n'utiliserait pas la valeur de way après le ST_Simplify() plutôt qu'avant.

**Comment by MaelREBOUX** [comment]
> Je me demande si "way && ..." n'utiliserait pas la valeur de way après le ST_Simplify() plutôt qu'avant.

Je ne sais pas. Ce genre de requête spatiale me semble classique et plutôt basique.

**Comment by jocelynj** [comment]
Tu peux vérifier si c'est ça en remplaçant le "AND way &&" par "AND planet_osm_polygon.way"

**Comment by cquest** [comment]
Vieille issue, je ferme... à réouvrir si besoin.

**Comment by MaelREBOUX** [comment]
J'ai pas testé récemment. 
J'ai tout repris dernièrement pour passer en YAML. Et je me demande toujours la différence entre un ST_SIMPLIFY dans la requête SQL et le paramètre "simplify_geometries" de mapnik...
