### ISSUE TITLE
Replication france_metro_dom_com_nc à l'arrêt

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#290]
Je ne sais pas si c'est lié à #289 mais http://download.openstreetmap.fr/replication/merge/france_metro_dom_com_nc/minute/ reste bloqué au 17 avril (constaté ce matin).
Merci pour votre coup d’œil

**Comment by jocelynj** [comment]
C'est lié au déplacement de la Polynésie et de Wallis et Futuna du continent "south-america" vers "oceania".

Après correction, les minute-diffs sont disponibles. Vu qu'on a perdu des modifications pendant quelques semaines sur ces deux territoires, je te conseille de réimporter depuis le dernier pbf sur http://download.openstreetmap.fr/extracts/merge/.

**Comment by vdct** [comment]
Ok je fais ça. Merci Jocelyn
