### ISSUE TITLE
Bloquer Google FloC

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#291]
Google a mis en place un nouveau système de pistage des internautes: FloC

Celui-ci se fait par Chrome, sans cookies et il semble pourvoir être désactivé en ajoutant ceci aux entêtes fournis par le serveur:
`
Permissions-Policy: interest-cohort=()`

Je propose d'ajouter ça dans les config nginx de nos proxy.

**Comment by jocelynj** [comment]
Je n'ai aucune objection, au contraire. D'après https://borismallach.fr/desactiver-votre-site-web-du-reseau-floc-de-google/, il suffit de rajouter ça:
```
      add_header Permissions-Policy interest-cohort=();
```

Est-ce que c'est à ajouter ligne 46 de https://github.com/osm-fr/ansible-scripts/blob/master/roles/proxycache/templates/nginx-site.j2#L35 ?
