### ISSUE TITLE
Echec connection à geofabrik depuis les backends osmose osm21x

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#293]
Echec connection à geofabrik depuis les backends osmose osm21x

https://buildbot.osmose.openstreetmap.fr/#/builders/310/builds/250

`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='download.geofabrik.de', port=80): Max retries exceeded with url: /north-america/us/michigan-latest.osm.pbf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0394fb6438>: Failed to establish a new connection: [Errno 113] No route to host'))`

**Comment by Marc-marc-marc** [comment]
depuis osm211
```
PING download.geofabrik.de (138.201.219.183) 56(84) bytes of data.
From 10.42.109.1 (10.42.109.1) icmp_seq=2 Destination Host Unreachable
```
c'est peut-être lié au soucis de migration ipv4 chez Paulla, j'ai posé la question à Dam sur irc

**Comment by Marc-marc-marc** [comment]
réponse de Dan 

> oui toujours si vous n'avez pas changé les IPs

**Comment by jocelynj** [comment]
C'est maintenant corrigé, suite à modifications des IP v4 et v6 sur les machines osm21x.
