### ISSUE TITLE
overpass ko car nginx planté et monit ne le surveille pas

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#294]
Hello

Pour dire que https://overpass.openstreetmap.fr/api/interpreter répond `502 Bad Gateway`.

Est-ce en rapport avec #19 ?

**Comment by Marc-marc-marc** [comment]
nginx était planté et monit ne surveille pas nginx... c'est l'occasion de le rajouter

**Comment by jocelynj** [comment]
systemd n'aurait pas du surveiller nginx ?

**Comment by JacLavi** [comment]
systemd trouvait nginx en état de marche....

**Comment by alkino** [comment]
overpass semble refonctionner.

Et le nginx de ce serveur semble être présent dans munin : https://munin.openstreetmap.fr/osm26.openstreetmap.fr/osm147.openstreetmap.fr/index.html#nginx

On peut donc fermer le ticket ?

**Comment by Marc-marc-marc** [comment]
j'avais proposé ci-dessus d'ajouter un moniteur monit tant pour recevoir une alerte que pour détecter le cas présent (nginx qui tourne mais ne répond pas)

**Comment by jocelynj** [comment]
overpass a été coupé, du coup, on peut fermer ce ticket.
