### ISSUE TITLE
Replication france_metro_dom_com_nc stoppée

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#295]
Bonjour,
Constaté via bano : la réplication dispo à http://download.openstreetmap.fr/replication/merge/france_metro_dom_com_nc/minute/ semble bloquée au 25/04, ça ressemble une redite de #289 
Merci pour vos coups d’œil

**Comment by jocelynj** [comment]
C'est corrigé: il faudrait que je rende ce systéme de lock plus robuste en cas de plantage temporaire.

**Comment by vdct** [comment]
Merci @jocelynj
