### ISSUE TITLE
wms.openstreetmap.fr enedis returns HTTP 403

### ISSUE THREAD

**Issue by rbuffat** [osm-fr/infrastructure#297]
~~In https://github.com/osmlab/editor-layer-index/pull/1133#issuecomment-837462334 there was a discussion about if the maximum zoom level of the rennes_2014, respectively craig_2019 data is 20 or 21. Is there a way to find out the maximum zoom level of datasets hosted on wms.openstreetmap.fr?~~

Recently, the enedis data was added to ELI (https://github.com/osmlab/editor-layer-index/pull/1133)
But currently, https://wms.openstreetmap.fr/tms/1.0.0/enedis seems to be offline, respectively returns HTTP 403.

**Comment by don-vip** [comment]
Just by checking these URLs it appears to be indeed 20:
* https://wms.openstreetmap.fr/tms/1.0.0/rennes_2014/
* https://wms.openstreetmap.fr/tms/1.0.0/craig_2019/

Not sure why it was set to 21 in JOSM wiki, I'm updating our entries as well.

**Comment by rbuffat** [comment]
@don-vip I didn't think about that! Thanks!

**Comment by cquest** [comment]
enedis tile access is limited to OSM editing because this imagery is not fully open.

We're checking user-agent and referer to authorized access or not, that's why your script gets a 403.

**Comment by rbuffat** [comment]
@cquest That makes sense. Thanks for this information.
