### ISSUE TITLE
Liens sur polygons.openstreetmap.fr pour les relations cassées à changer

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#298]
Peut-être un résidu : http://polygons.openstreetmap.fr/?id=5936703 indique une relation cassée mais le premier lien c'est un 404 (https://analyser.openstreetmap.fr/cgi-bin/index.py?relation=5936703) et le second n'aboutit pas (https://analyser.openstreetmap.fr/cgi-bin/index.py?relation=5936703). Il est possible que l'analyse soit "simplement" trop complexe pour le second service par contre le premier semble un résidu de migration. Indirectement dû à la migration pg ?

_Originally posted by @Bibi56 in https://github.com/osm-fr/infrastructure/issues/190#issuecomment-841626076_

**Comment by jocelynj** [comment]
@Bibi56: le lien que tu proposes est effectivement pas mal. Peut-être qu'on devrait même prendre http://ra.osmsurround.org/analyzeMap?relationId=5936703 à la place ?

**Comment by Bibi56** [comment]
@jocelynj, c'est comme vous voulez, c'est effectivement le lien que j'utilise en général mais là j'étais tombé sur des liens morts, je suis donc mal placé pour comparer les différentes analyses, je sais seulement que j'apprécie celui que j'ai donné. Mais si c'est simple et comme c'est bien, je ne vois pas d'inconvénient à partir là-dessus.

**Comment by jocelynj** [comment]
J'ai changé les URLs sur le site.

Mais je me demande: vu que ta relation est une ligne de chemin de fer, avec des embranchements, c'est normal d'avoir des erreurs de connectivités, non ? Ça me semble normal d'avoir plusieurs morceaux, et ces analyses de relation ne sont pas appropriés - c'est plutôt pour vérifier les limites administratives.

**Comment by jocelynj** [comment]
J'ai remis un lien vers http://polygons.openstreetmap.fr/analyse-relation-open.py?id=5936703 sur la page d'erreur.
