### ISSUE TITLE
anomalie graphe munin cpu max

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#3]
exemple hier sur https://munin.openstreetmap.fr/osm11.openstreetmap.fr/osm117.openstreetmap.fr/cpu.html
idle max > 10 millions
iowait max > 11 millions

il me semble qu'aucune valeur ne peux être supérieur a 2400 % vu que la vm a 24 coeurs cpu.
cela se produit aussi sur 101 qui est sur le même hosteur
mais sur le hosteur lui même, pas vu d'anomalie.

Pour voir les moments oü se produisent ces anomalies, il suffit de demander le graphe des valeur >2400%
https://munin.openstreetmap.fr/static/dynazoom.html?plugin_name=osm11.openstreetmap.fr%2Fosm117.openstreetmap.fr%2Fcpu&start_iso8601=2017-11-04T12%3A23%3A58%2B0100&stop_iso8601=2017-11-05T18%3A23%3A58%2B0100&start_epoch=1509794638&stop_epoch=1509902638&lower_limit=2400&upper_limit=2500&size_x=800&size_y=400&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph

**Comment by Marc-marc-marc** [comment]
http://guide.munin-monitoring.org/en/latest/howtos/remove-spikes.html

**Comment by jocelynj** [comment]
J'ai regardé sur munin, et on n'a plus de pics - peut-être que ça a été corrigé tout seul avec les mises à jour de munin ?
