### ISSUE TITLE
osmose2.davintech.ca not rebooting correctly

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#300]
to @matthewdarwin: I've launched "sudo reboot" on osmose2 to solve some strange issues around postgresql, but the machine is not restarting. Could you take a look on the host?

**Comment by matthewdarwin** [comment]
The uptime on there showed `17:21:48 up 1 day,  3:16,  0 users,  load average: 0.31, 0.13, 0.04`.  So it looks like it rebooted.

I rebooted it again using your same process and now shows uptime of 0 minutes.

I'm not sure what I need to investigate.

**Comment by matthewdarwin** [comment]
Oh, I see, networking issue.  Let me fix.

**Comment by matthewdarwin** [comment]
Fixed.

**Comment by matthewdarwin** [comment]
There is a known networking issue for osmose1/2/3/4.  I am aware of it and will work to resolve it in the future.

**Comment by jocelynj** [comment]
Thanks, I now have access to the VM osmose2.

By the way, do you have something specific on the osmose[1-4] VMs around locales? I've seen that I need to restart postgresql after a reboot - otherwise, postgresql doesn't understand locale "en_US.UTF-8", as shown on https://buildbot.osmose.openstreetmap.fr/#/builders/589/builds/268/steps/1/logs/stdio:
```
psycopg2.OperationalError: FATAL:  database locale is incompatible with operating system
DETAIL:  The database was initialized with LC_COLLATE "en_US.UTF-8",  which is not recognized by setlocale().
HINT:  Recreate the database with another locale or install the missing locale.
```

**Comment by jocelynj** [comment]
I'm closing the ticket, as the VM is working correctly.
