### ISSUE TITLE
osmose.openstreetmap.fr appears to be down

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/infrastructure#301]
Independently verified by three different people (Poland, Bulgaria and Netherlands - so likely not a user/Wifi/ISP problem)

**Comment by frodrigo** [comment]
We switched yesterday to a new VM.

Anyone can check the proxy and the new WM please ?

**Comment by frodrigo** [comment]
@matkoniecz note the old copy is here http://beta.osmose.openstreetmap.fr

**Comment by jocelynj** [comment]
I've restarted apache on the VM, and the site is now working again. I will check why it failed.

**Comment by jocelynj** [comment]
Looks like it was failing because postgresql extension "pgcrypto" wasn't installed. I will add it to the installation script.

**Comment by matkoniecz** [comment]
osmose.openstreetmap.fr appears to be online, thanks :)

is it some hotfix? Should I close this issue or keep it open until root cause is fixed?

**Comment by matkoniecz** [comment]
And thanks for a fix!

**Comment by jocelynj** [comment]
I would like to keep the ticket open for a day, to make sure that we don't see the issue again.

**Comment by jocelynj** [comment]
Following some changes on apache configuration, it is now working correctly. See https://github.com/osm-fr/ansible-scripts/commit/7938cd95182de7e1046e58e0ca39c0d308092843 for the changes.
