### ISSUE TITLE
Batimap : demande serveur d'hébergement

### ISSUE THREAD

**Issue by bagage** [osm-fr/infrastructure#302]
Suite à discussion avec @jocelynj sur osm-fr-tech à l'instant et suite à des échanges avec @Marc-marc-marc, ça serait cool si un serveur osm-fr était dispo pour héberger [batimap](https://gitlab.com/bagage/batimap/).

A priori @Marc-marc-marc avait commencé à travailler là dessus, à confirmer ?

## Batimap : présentation brève

Il sert à comparer l'état du bâti OSM vs celui du cadastre par commune : 

1. ça estime la date de dernier import par commune
2. ça prépare les jeux de données nécessaires (via cadastre.openstreetmap.fr) pour la mise à jour du cadastre d'une commune
3. ça ouvre JOSM avec ce qu'il va bien pour faire la mise à jour du bâti 

## Stack technique / fonctionnement

* DB PostGIS
* [Imposm3](https://imposm.org/) pour l'import quotidien des données depuis geofabrik
* [Tegola](tegola.io) pour la génération des tuiles vectorielles
* Backend en [Python flask](https://flask.palletsprojects.com/) + [celery](docs.celeryproject.org) pour la gestion des requêtes longues
* Frontend en [Angular](https://material.angular.io/)

Actuellement ça tourne dans ~10 containers docker, orchestré ensemble avec [docker-compose](https://gitlab.com/bagage/batimap/-/blob/master/docker-compose.yml) et déployé via ansible. 

C'est à la fois ce qui est utilisé pour développer et en production actuellement. 

On *pourrait* se passer de docker mais ça demande un peu de boulot et de temps que je n'ai pas forcément immédiatement pour info :).

## Besoins

* docker et docker-compose

Et niveau matos, sur mon (ex) instance : 

* 75Go de données (principalement l'import imposm dans Postgis)
* 4Go de RAM ça tourne (mais c'est pas hyper rapide)
* beaucoup (trop) de CPU (principalement import quotidien via imposm + génération des tuiles vectorielles - [cf les requêtes](https://gitlab.com/bagage/batimap/-/blob/master/tiles/config.toml))

Merci !

**Comment by cquest** [comment]
Avec autant de containers docker, il serait judicieux que ça tourne dans une VM QEMU et pas un container LXC.

Les tuiles vectorielles sont particulières ? N'est-il pas possible d'utiliser celles déjà produites ?

**Comment by frodrigo** [comment]
> Avec autant de containers docker, il serait judicieux que ça tourne dans une VM QEMU et pas un container LXC.

Pour quoi ça peut poser problème ?
 
> Les tuiles vectorielles sont particulières ? N'est-il pas possible d'utiliser celles déjà produites ?

C'est des tuiles pour la couche des données de l'appli, pas du fond de carte.

**Comment by frodrigo** [comment]
> En fait il y a de la génération à la volée, mais je prégénere les zooms 1-10 (±).

Si tu généres des MBTiles ou des repertoires, tu peux ensuite les fusionner.

**Comment by cquest** [comment]
J'ai rapidement survolé le repo... j'ai pas bien compris si l'import était fait une fois puis update ou refait sans arrêt avec regénération systématique de tout le reste à chaque fois.

Tu indiques un besoin important en CPU, pour quelles tâches ? Uniquement lors de demandes d'utilisateurs ?

As-tu un bout de descriptif de l'ensemble autre que du code et des dockerfile ?

Ton serveur actuel est en surcharge ? Pour combien d'utilisateurs/usages quotidiens ?

**Comment by bagage** [comment]
> Si tu généres des MBTiles ou des repertoires, tu peux ensuite les fusionner.

Ça génère du protobuf (`.pbf`), mais je ne suis pas sûr de comprendre de quoi on parle ici. Les fusionner pourquoi faire ?

> si l'import était fait une fois puis update ou refait sans arrêt avec regénération systématique de tout le reste à chaque fois.

Au premier lancement, on importe les data OSM France en DB. Puis on gènére les tuiles vectorielles du zoom 1 à 9.
Ensuite, on attend les mises à jour quotidiennes ([ici](http://download.geofabrik.de/europe/france-updates/)) pour mettre à jour la DB avec les changements de bâti d'un jour sur l'autre. Puis on regènere les tuiles de 1 à 9 (de mon experience c'etait plus rapide avec tegola de tout supprimer et tout reconstruire, plutôt que de regenerer une par une les tuiles nécessaires). Une fois par jour donc.
Et lorsqu'un utilisateur demande un zoom > 9, on génère à la volée ce qu'il faut.

> Tu indiques un besoin important en CPU, pour quelles tâches ? Uniquement lors de demandes d'utilisateurs ?
Non c'est plutôt l'import quotidien (imposm3 + tegola) qui prend du temps. Comme la plupart des tuiles sont prégénérées c'est relativement indolore pendant la journée ensuite.

> As-tu un bout de descriptif de l'ensemble autre que du code et des dockerfile ?
Tu veux dire de la *doc* ? Rien de plus que le readme / code et l dockerfiles actuellement, j'avais commencé un schema sur draw.io mais pas finalisé :) Quel type de document tu aimerais ?

> Ton serveur actuel est en surcharge ? Pour combien d'utilisateurs/usages quotidiens ?
Il fait tourner une 10aine d'autres services (tous dans docker), sur un CPU `Intel(R) Atom(TM) CPU N2800   @ 1.86GHz`... donc surcharge oui, mais c'est assez indépendant du nombre d'utilisateur de batimap (encore une fois la majeur partie du boulot est faite une fois par jour).

**Comment by frodrigo** [comment]
> > Si tu généres des MBTiles ou des repertoires, tu peux ensuite les fusionner.
> 
> Ça génère du protobuf (`.pbf`), mais je ne suis pas sûr de comprendre de quoi on parle ici. Les fusionner pourquoi faire ?

Des pbf dans un répertoire ou dans un MBTiles, tu peux les fusionner. L'idée est de ne pas générer le monde entier, mais une série de BBox que tu fusionnes. Pour économiser du CPU.

**Comment by cquest** [comment]
Ok, donc ce n'est pas l'update quotidien de la DB qui est lourd, mais la génération des tuiles vectorielles après chaque update.

Pourquoi des tuiles vectorielles ? N'est-il pas possible d'interroger la DB quand un utilisateur veux vérifier le bâti ?

Je ne comprends pas non plus l'intérêt de tuiles en zoom 9 pour le bâti.

PS: je n'ai jamais utilisé ce service, je ne sais pas comment il fonctionne... j'avais été fait un tour il y a longtemps (donc oublié) et pas bien compris la marche à suivre.
Sans descriptif global et service fonctionnel difficile de se faire une idée et de ne pas faire de remarques/suggestions décalées.

**Comment by jocelynj** [comment]
@bagage : pour y voir plus clair, est-ce que tu peux relancer une instance chez toi, sans les mises à jour hebdomadaires ?

**Comment by bagage** [comment]
Le plus simple est probablement de le lancer en local si vous voulez voir à quoi ça ressemble, ça se résume à : `cp .env-example .env && docker-compose up -d`.
Mais j'ai relancé l'instance https://cadastre.damsy.net (limité à Rhône-Alpes) si c'est plus simple (devrait être dispo dans l'aprem). Je crois qu'il y a globalement un mal-entendu sur les tuiles vectorielles (qui ne sont **pas** utilisées comme fond de carte)

**Comment by JacLavi** [comment]
@bagage mais c'est quoi donc la config de ce PéCé de ouf dans ta maison qui supporte cette appli qui fait si peur ?

**Comment by bagage** [comment]
Cf plus haut : `Intel(R) Atom(TM) CPU N2800 @ 1.86GHz`, 4Go de RAM et 75Go de SSD pour l'instant. Ça fonctionne mais j'ai fais le choix de le couper parce que j'ai d'autres services plus prioritaires.

**Comment by cquest** [comment]
> Je crois qu'il y a globalement un mal-entendu sur les tuiles vectorielles (qui ne sont **pas** utilisées comme fond de carte)

Justement, c'est ce que j'essaye de comprendre. Elles sont utilisées pour quoi et pourquoi ne pas directement tirer les données utiles de la DB ?

**Comment by frodrigo** [comment]
> > Je crois qu'il y a globalement un mal-entendu sur les tuiles vectorielles (qui ne sont **pas** utilisées comme fond de carte)
> 
> Justement, c'est ce que j'essaye de comprendre. Elles sont utilisées pour quoi et pourquoi ne pas directement  tirer les données utiles de la DB ?

De ce que je comprends, elles servent justement à tirer les données de la DB à fort zoom, c'est le format de distribution. À faible zoom elles sont pré calculées.

Y a-t-il vraiment besoin de ces tuiles à faible zoom ? De les reclaculer tous les jours ?

**Comment by jocelynj** [comment]
Merci pour l'instance sur https://cadastre.damsy.net/, @bagage. 

Sans parler de la stack technique, est-ce qu'on peut déjà voir si ça vaut le coup de l'héberger sur OSM-Fr ? Je sais qu'on a des utilisateurs, comme @alkino. Perso, je l'ai jamais utilisé, mais je vois l'intérêt pour mettre à jour les bâtiments dans OSM à partir du cadastre.

**Comment by hamlet** [comment]
@jocelynj  J'ai commencé à vouloir mettre à jour les bâtiments de mon secteur il y a quelques mois, et surtout ajouter les nouveaux. Après la lecture du wiki consacré à ce sujet, et le test des différentes méthodes, j'ai clairement trouvé celle-ci la meilleure ! Et je crois que rien que l'outil de visualisation est intéressant. Peut-être ces outils pourraient être plus mis en valeur par une mise à jour du wiki, en enlevant les méthodes obsolètes, en décrivant mieux celle-ci... Mais effectivement, seulement si l'infrastructure sous-jacente est stable.

En espérant que ça aide le débat... ;-)

**Comment by JacLavi** [comment]
Tout comme @hamlet il m'arrive d'utiliser Batimap. Je pense aussi qu'il faudrait l'héberger.

**Comment by alkino** [comment]
batimap est pas facile à prendre en main, mais c'est vraiment l'outil qui permet de faire des importations de manière exhaustive facilement dès qu'on le maitrise.
De plus, la doc directement sur l'outil est vraiment bien !

**Comment by alkino** [comment]
Un utilisateur que j'ai mené sur la voie du batimap (eGreeter sur télégram) me demandait justement à l'instant pourquoi ça ne marchait plus. Il a mit à jour une grande partie de sa région grâce à l'outil et se trouve fort dépourvu maintenant !

(un de plus)

**Comment by alkino** [comment]
Bump ?

**Comment by jocelynj** [comment]
J'ai créé un containeur LXC sur osm14, avec accès pour @bagage. L'idée est de mettre au moins le serveur web et le serveur postgres direct sur le containeur, sans passer par docker. Et les différents dockers sont en fait surtout des scripts temporaires: genre, il y a un docker pour l'import dans la base de donnée via imposm, ce qui veut dire qu'il y a en fait peu de docker qui tournent en permanence.

**Comment by bagage** [comment]
Ça y est ça tourne, peinture fraiche :) https://cadastre.damsy.net as usual! Merci @jocelynj pour le coup de main !
