### ISSUE TITLE
Rendu humanitaire zoom 11 et 12 en carré blanc

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#303]
Signalé via le forum https://forum.openstreetmap.fr/t/problems-with-hot-layer/6718

j'ai pu le constater également

**Comment by cquest** [comment]
En cours de résolution... lente :(

**Comment by cquest** [comment]
Ce devrait être en principe bon maintenant. Je ferme.

**Comment by JacLavi** [comment]
Le zoom 12 est résolu mais le 11 rend toujours du blanc sur une grande partie de la côte atlantique.

**Comment by JacLavi** [comment]
Un cache DNS ? ;)

**Comment by cquest** [comment]
Le cache d'osm23 a été vidé, la revalidation activée, tout est rentré dans l'ordre.
