### ISSUE TITLE
Cardinalité de clés incorrectes dans taginfo.openstreetmap.fr

### ISSUE THREAD

**Issue by gileri** [osm-fr/infrastructure#304]
Bonjour et merci pour cette instance, elle est bien pratique pour comparer les usages entre la France et le reste du monde !

Je suis pas sûr que ce soit le bon endroit de le rapporter, mais certaines clés affichent "0 instances" dans taginfo FR, par exemple [source:maxspeed](https://taginfo.openstreetmap.fr/keys/source%3Amaxspeed). Pas de soucis côté taginfo "global".

**Comment by jocelynj** [comment]
C'est intéressant: tous les `source:*`, ainsi que `source` n'apparaissent pas sur taginfo.openstreetmap.fr. Alors que c'est bien présent sur https://taginfo.geofabrik.de/europe/france/search?q=source.

Je suppose qu'un des outils de génération ou de filtre enlève les sources.

@Marc-marc-marc: une idée ?

**Comment by Marc-marc-marc** [comment]
oui, il a été mis en place un filtre pour m'avoir que les données et non les metadonnées.
source:maxspeed est une clef hybride (fourretout diront les moins diplomates) qui contient à la fois des meta (survey, mapillary, ...) et des données (sign, urban, rural, ...).
faudrait lancer une discussion sur talk-fr maintenant que maxspeed:type est dominant

**Comment by gileri** [comment]
Merci pour la réponse @Marc-marc-marc !

Je suis d'accord que les tags `source:*` sont souvent pas très adaptés. Avoir l'accès aux statistiques via Taginfo FR aiderait bien à montrer ces problèmes. Notamment pour [source:maxpseed](https://www.openstreetmap.org/changeset/105584431) en effet :)

Par curiosité quelle est la raison de cette exclusion, l'instance n'a pas assez de ressources pour les traiter ? J'ai cherché un peu dans les archives de la ML tech FR mais je trouve rien, idem ici dans les issues.

**Comment by jocelynj** [comment]
Me semble que ces tags sont enlevé pour rendre le rapport taginfo plus simple à utiliser et à lire.

Sinon, https://taginfo.geofabrik.de/europe/france/keys/source:maxspeed peut être utilisé.
