### ISSUE TITLE
umap: problèmes d'authentification ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#305]
Un signalement de problème d'authentification par OSM sur talk-fr
et un autre via l'OAuth de github sur le forum...

Comme je doute que quelque chose ait changé dans umap, y a-t-il un changement sur le reverse proxy du closter OVH qui pourrait expliqué ce double problème ?

**Comment by jocelynj** [comment]
Est-ce qu'il y a encore des soucis d'authentification ?

Il faudrait un peu plus d'info pour éplucher dans les logs :(
