### ISSUE TITLE
osmose.openstreetmap.fr is down

### ISSUE THREAD

**Issue by Dimitar5555** [osm-fr/infrastructure#306]
The website is not working. It returns 502 Bad Gateway error. It may be related to #301.

**Comment by jocelynj** [comment]
I've restarted apache, and it is now working correctly.

I will check why we add Recv-Q > 0 in netstat:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6     512      0 :::80                   :::*                    LISTEN      54272/apache2
```

**Comment by Dimitar5555** [comment]
The website is down again. The same error message is returned.

**Comment by frodrigo** [comment]
Same message, but not the same issue https://github.com/osm-fr/infrastructure/issues/307

Hoster network problem.
