### ISSUE TITLE
Tuiles blanches ou très lentes sur le rendu FR

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/infrastructure#308]
Observé via Umap.fr  Semble affecter le rendu Fr.

**Comment by cquest** [comment]
Aucun rapport avec uMap lui même, c'est au niveau du serveur de tuiles (et de ses caches) que ça patine un peu (et de plus en plus souvent).

J'ai réglé un problème ce matin sur osm25 qui s'occupe de l'essentiel du rendu FR. Le cache devrait se mettre à jour petit à petit.

**Comment by cquest** [comment]
Problème identifié... lié à IPv6. La config nginx d'osm25 pour le rendu FR n'écoutait que sur IPv4.
