### ISSUE TITLE
osm13 en panne

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#312]
Récap de remise en route des services (coché = remis en route):
- [x] le rendu humanitaire (redirigé temporairement vers le fond OSM standard de l'OSMF) -> migré sur osm12
- [x] le rendu OpenRiverBoat
Les rendus techniques:
  - [x] BANO
  - [x] Volta
  - [x] Route500
  - [x] Hydro
  - [x] BDTopo
  - [x] QA
  - [x] layers -> migré sur osm12
- [x] quelques analyses osmose

---
*Issue d'origine:*

Notre serveur osm13 est en panne depuis vendredi après une première panne jeudi et un redémarrage.

Suite à son upgrade hardware, osm12 a été remis en place dans le même datacenter pour prendre petit à petit le relais.

**Comment by cquest** [comment]
Rendu humanitaire remis en route sur osm12 et redirection vers les tuiles osm.org supprimé d'osm23.

**Comment by cquest** [comment]
Deuxième intervention sur site:
- **Votage error** sur l'afficheur, impossible d'éteindre/rallumer la machine
- après débranchement puis rebranchement des alims 220V, on relance...
- ça commence à booter, puis en plein milieu: **Regulator error** on CPU2 sur l'afficheur

**C'est donc bien un problème hardware.**

J'ai ramené osm13 chez moi, maintenant installé dans ma cave pour observation et tests.
Il n'a pas eu d'erreur après 30mn de fonctionnement.

**Comment by cquest** [comment]
Après 36h de service... rien à signaler mais le serveur n'est pas du tout aussi chargé qu'il l'était.
Je vais donc faire des tests en charge en simulant des demandes de tuiles à partir des tile-logs.

**Comment by jocelynj** [comment]
Les courbes munin montrent qu'il fait plus chaud dans ta cave que dans le datacenter :)
http://munin.openstreetmap.fr/openstreetmap.fr/osm13.openstreetmap.fr/ipmi_temp.html

Mais les processeurs sont loin d'autant chauffer que dans le datacenter:
http://munin.openstreetmap.fr/openstreetmap.fr/osm13.openstreetmap.fr/sensors_temp.html

Il faudrait effectivement monter la charge pour voir un truc équivalent:
http://munin.openstreetmap.fr/openstreetmap.fr/osm13.openstreetmap.fr/cpu.html

**Comment by cquest** [comment]
Sûr que la température n'est pas la même (pas de clim), mais le bilan CO² non plus ;)

Simulation de charge en cours en rejouant le premier million de tuiles les plus consultées sur les tile-logs disponibles sur https://planet.openstreetmap.org/tile_logs/

**Comment by cquest** [comment]
osm13 était DOWN hier, j'ai pu m'y connecter à distance (150km) avec l'iDRAC et forcer un redémarrage (power OFF/ON).
Cela n'a pas suffit... le boot ne se terminait pas.
Ce matin, j'ai trouvé une bidouille pour la connexion en KVM/IP qui ne fonctionne qu'avec un vieux Java...

Un des volumes ext4 ne voulait pas monter donc un petit coup de fsck dessus et c'est reparti.

A surveiller, car je n'ai pas encore trouvé pourquoi il avait rebooté sauvagement... problème hardware qui revient ?

**Comment by cquest** [comment]
osm13 de retour, mais sûrement temporairement.

C'est à nouveau un problème hardware qui l'a fait planter, toujours au niveau alimentation CPU (erreur E1229 CPU 2 VCORE regulator failure).

Actions possibles:
- [ ] remplacement par un R710, migration du contenu (les cartes PCIe à réinstaller)
- [ ] remise en place chez free

**Comment by cquest** [comment]
Re-plantage hier soir, encore une histoire d'alimentation CPU...

**Comment by cquest** [comment]
J'ai transplanté les organes d'osm13 (disques HDD+SSD et RAM) dans un autre serveur inutilisé (un R710).

Tous les services devraient être à nouveau disponibles et stables.

**Comment by cquest** [comment]
Coupure temporaire pour passage sous Proxmox et retour chez free.

**Comment by Cyrille37** [comment]
<3 Hello <3

Ben ce soir le rendu BANO n'est pas joignable depuis josm:
- java.net.ConnectException: Connexion refusée

Info:
- host: a.layers.openstreetmap.fr is an alias for osm13.openstreetmap.fr
- related: #317

```
        (¯`·._.·[  Thanks to ours so lovely teckies  ]·._.·´¯)
ø¤º°`°º¤ø,¸¸,ø¤º°`°º¤ø,¸¸,ø¤º°`°º¤ø,¸¸,ø¤º°`°º¤ø¸¸,ø¤º°`°º¤ø¸¸,ø¤º°`°º¤ø```

**Comment by cquest** [comment]
Je vais avancer sur osm13 durant le week-end...

**Comment by cquest** [comment]
Rendus BDtopo, volta et hydro de retour
Le reste va suivre... ainsi que les analyses osmose
