### ISSUE TITLE
forum.openstreetmap.fr is down

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#313]
je ne sais pas si c'est en lien avec la panne d'osm13 mais ce matin je n'arrive pas à me connecter au forum, page blanche

**Comment by cquest** [comment]
Pas de rapport, le forum est sur le cluster OVH et à 9h30 pas de souci.

**Comment by vinber** [comment]
je ferme car d'autres sites down seulement pour moi, je viens de le comprendre à l'instant
