### ISSUE TITLE
Extract et diff plus mis à jour

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#314]
Les diff des extracts OSM-FR ne se mettent plus à jour depuis (hier) le 15 juillet.

À noter que les extract Geofabrik sont aussi à l'arrêt depuis le 14 juillet.

Le planet est OK.

**Comment by jocelynj** [comment]
Je ne vois pas de trou dans la génération des diffs sur download hier, et munin ne marchait plus à cause d'un souci de connectivité ipv6 (maintenant réparé)

Tu saurais vers quelle heure les diffs étaient bloqués ?

**Comment by frodrigo** [comment]
Pour moi c'est toujours bloqué. Ou alors c'est en retard ?
http://download.openstreetmap.fr/replication/europe/france/bourgogne/yonne/minute/state.txt
```
#Thu Jul 15 22:43:00 UTC 2021
sequenceNumber=4629078
timestamp=2021-07-15T22\:42\:57Z
```

**Comment by jocelynj** [comment]
En rafraichissant, tu verras que le state.txt avance petit à petit.

**Comment by jocelynj** [comment]
C'est le téléchargement des diffs depuis le planet qui a pris du temps. Exemple:
```
2021-07-15 23:44:22   download diff
2021-07-15 23:48:44   generate bbox
```
Un problème côté planet.openstreetmap.org, corrigé depuis ?
