### ISSUE TITLE
Cadastre plus dispo

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#316]
Bonjour à la team,

Depuis plusieurs jours, le fond cadastre n'est plus disponible dans les éditeurs JOSM et iD.

Vous savez sûrement pourquoi :) 

Merci !!

**Comment by frodrigo** [comment]
Je veux aller voir le TMS cadastre HS, mais je ne sais pas aller sur la vm, cadastre-joker.vm n'a pas l'air présente sur osm14

**Comment by jocelynj** [comment]
`ssh cadastre-joker.vm.openstreetmap.fr`marche d'ici pourtant. Tu n'arrives pas à accèder à sa connexion en ipv6 ?

**Comment by frodrigo** [comment]
Ok, comme ça ça marche. J'essayais depuis l’hôte osm14.

La base de donnés avant planté et est repartie. Mais la web avait perdu la connexion. J'ai jute fait un restart du web.

**Comment by bristow** [comment]
C'est mon PC ou bien le cadastre est retombé ?

**Comment by bristow** [comment]
Confirmé, c'est bien le même problème : https://forum.openstreetmap.fr/t/josm-imagerie-cadastre-ne-fonctionne-plus/6924/10

Merci :pray:

**Comment by frodrigo** [comment]
Voilà.

**Comment by bilboed** [comment]
Il est revenu en panne ? Les fonds ne sont plus dispo

**Comment by frodrigo** [comment]
La base de données se fait tuée `server process (PID 20223) was terminated by signal 9: Killed`. Puis le service perd la connection.

J'ai aussi relancé la base de données cette fois.

**Comment by jocelynj** [comment]
Est-ce que ça ne serait pas tué par un OOM ?

Je regarderais sur munin si il faudrait monter la quantité de RAM.

**Comment by laurentriffard** [comment]
Bonjour,

le serveur de tuiles du cadastre a l'air à nouveau HS :
2021-08-04 13:49:45.933 INFOS: GET https://tms.cadastre.openstreetmap.fr/*/tout/20/520112/372223.png -> HTTP/1.1 500 (10,0 s; 30 B)

Cordialement
~~
laurent

**Comment by frodrigo** [comment]
Je suis loin de la clé ssh. Je ne peux pas aller voir. 
@jocelynj tu peux essayer de voir pourquoi la base se fait tuer, stp ?

**Comment by jocelynj** [comment]
Je n'avais pas regardé la bonne VM précédemment (cadastre au lieu de cadastre-joker). cadastre-joker était configuré avec 1G de ram, qui était remplie. Je l'ai passé à 4G, et j'ai redémarré la VM.

**Comment by bristow** [comment]
Cela ne semble pas suffisant. Le cadastre ne semble pas être dispo à nouveau :(

**Comment by jocelynj** [comment]
@frodrigo : Où peut-je trouver les logs du serveur web ?

J'ai redémarré la VM, puis fait un "cd /home/fred/cadastre-joker/; sudo -u fred docker-compose up -d". On a toujours des "Internal Error" sur les tuiles

**Comment by frodrigo** [comment]
Peut être que cadastre démarre avant la bd.
Il faut peut-être le relancer.
docker-compose restart cadastre-jocker

Pour le log
docker-compose logs
(Voir l'aide)

**Comment by jocelynj** [comment]
Merci !

J'ai rédémarré juste "cadastre", et le rendu marche correctement.

**Comment by bristow** [comment]
pour le moment, il n'est pas encore dispo sur iD :crossed_fingers:

**Comment by jocelynj** [comment]
Désolé, j'ai cassé un truc en voulant configurer la dépendance entre les deux services :(
Je dois recréer les deux volumes docker, mais ça devrait être simple avec la doc.

**Comment by bristow** [comment]
Pas grave, on te fait entièrement confiance !!

**Comment by jocelynj** [comment]
C'est bon cette fois: je vais préparer des modifs sur https://github.com/osm-fr/cadastre-joker pour la prochaine fois
