### ISSUE TITLE
BANO :: Des gros points de couleur à la place des numéros dans la rue.

### ISSUE THREAD

**Issue by JacLavi** [osm-fr/infrastructure#317]
Voir : 

https://lists.openstreetmap.org/pipermail/talk-fr/2021-August/104389.html

**Comment by Cyrille37** [comment]
Je confirme, ça fait un peu n'importe quoi, même en attendant plusieurs minutes et recharger les tuiles en erreur.

![image](https://user-images.githubusercontent.com/368965/128363540-434b7a45-c809-4759-9ae1-6be4671ad5a4.png)

**Comment by cquest** [comment]
Effectivement, la couche est en erreur, donc ce ne sont que des tuiles en cache et anciennes qui sont retournées.

Je regarde ce qui coince... ça doit venir du déménagement d'osm13 dans ma cave qui n'arrive pas à se connecter à au conteneur de BANO.

**Comment by Rpnpif** [comment]
Les tuiles du cadastre renvoie une erreur interne du serveur. C'est peut-être le même problème ?

**Comment by Franssoize** [comment]
J'ai constaté le même pb. avec les images du cadastre, manifestement avec JOSM je n'ai accès qu'aux tuiles qui sont déjà en cache...
(au passage merci à Christian pour tout ce temps qu'il nous consacre dans sa cave...)

**Comment by cquest** [comment]
Aucun rapport, les tuiles du cadastre sont servies directement par un conteneur qui ne fait que ça et qui est sur osm11/14, pas sur osm13.

**Comment by Franssoize** [comment]
Alors ce n'était qu'une coïncidence ... et ce matin ça a l'air OK, après test de vidage du cache.

**Comment by cquest** [comment]
osm13 a encore eu quelques soucis hier... je suis en train de regarder d'où ça vient.

https://github.com/osm-fr/infrastructure/issues/312#issuecomment-894758820

**Comment by cquest** [comment]
C'est en principe réglé... je ferme :)

**Comment by Cyrille37** [comment]
Hé hé, on dirait que c'est tombé en marche !
Et c'est carrément plus rapide que jamais :-)
Merci <3

**Comment by cquest** [comment]
Plus rapide car osm13 n'est plus utilisé pour le rendu humanitaire... ça lui laisse du temps libre :)

**Comment by Rpnpif** [comment]
> C'est en principe réglé... je ferme :)

Essayé hier soir, je confirme. Et aussi la rapidité. Merci beaucoup.

**Comment by cquest** [comment]
Rendu BANO de retour :)

**Comment by Cyrille37** [comment]
> Rendu BANO de retour :)

Yearh!! So lovely <3
