### ISSUE TITLE
Les tuiles Cadastre  sont trop lentes entraînant des timeouts permanents

### ISSUE THREAD

**Issue by Rpnpif** [osm-fr/infrastructure#318]
Bonjour,
Activer la couche Cadastre sous JOSM (Imagerie, carte, cadastre) ainsi que sous Id.
Rien ne s'affiche et on obtient java.net.SocketTimeoutException
java.net.SocketTimeoutException: Read timed out. Cause : java.net.SocketTimeoutException: Read timed out

En essayant d'afficher une tuile sous Firefox, elle arrive après plusieurs minutes.
Exemple : https://tms.cadastre.openstreetmap.fr/*/tout/17/65183/45734.png

**Comment by JacLavi** [comment]
Hi. Je n'observe pas de lenteur inhabituelle.

**Comment by jocelynj** [comment]
Idem, je ne vois pas de problème.

@Rpnpif : n'hésite pas à réouvrir le ticket si tu vois toujours des lenteurs.
