### ISSUE TITLE
uMap: `OSM Roads` not available anymore

### ISSUE THREAD

**Issue by joker234** [osm-fr/infrastructure#319]
The [uMap](https://umap.openstreetmap.fr) map background layer `OSM Roads (uni-heidelberg)` isn't available anymore for at least 1 year. I couldn't find the layer as default in the [uMap repository](https://github.com/umap-project/umap) so I assume it has to be removed by you in the individual uMap configurations.

**Comment by cquest** [comment]
I've move it to "outdated" (down in the list) and it is now pointing to osm.org base map.
Same for OSM Hydda (openstreetmap.se).
