### ISSUE TITLE
ajustement après la migration osmose frontend de osm117 vers osm153 

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#32]
L'optimisation des valeurs d'apache pour éviter la surconsommation de ram n'a probablement pas été mise dans le rôle ansible, le nouveau serveur ne l'avait plus, je l'ai fait à la main
fichier /etc/apache2/mods-enabled/mpm_event.conf
le plus important : 
- MaxConnectionsPerChild	100 (pour limiter l'effet fuite mémoire)
- MaxRequestWorkers	40 (pour éviter que le serveur s'écroule en cas de pic de requête)

moins important : 
- ServerLimit		40 (nécessaire pour éviter la réservation par défaut de 256)
- MaxSpareThreads		7 (après un micro pic, cela sert a rien de garder + de thread que ce qu'on consomme 99% du temps)
- ThreadsPerChild		8 (on a tellement peu de thread simultanés actifs)

par ailleurs il n'y a pas de www-browser nécessaire pour apachectl2 status
j'ai regardé sur osm117, c'était le paquet firefox-esr qui fournissait la dépendance
ne sachant pas si c'était voulu d'avoir si lourd pour si peu, j'ai installé temporairement links pour tester, cela suffit.
je te laisse le soin de choisir lequel des 2 tu souhaites :-)

**Comment by Marc-marc-marc** [comment]
non, c'est pour voir "à la main" ce que fais un serveur apache.
je m'en suis servit par exemple pour voir si le front était entrain de recevoir un update avant de lancer un restart

pour les paramètres, je pense que les 2 premiers ont du sens dans ansible.
les valeurs par défaut son inadaptée à un environnement virtualisé où les ressources de chaque vm sont évidement plus limitée que celle d'un serveur physique moyen.

**Comment by jocelynj** [comment]
J'ai pushé la config de mpm_event ici: 
https://github.com/osm-fr/ansible-scripts/commit/c50fff6897aca8dfef0d28a2dea51bb50460d7e9

Pour l'installation de links, je préfére ne pas le mettre dans le rôle d'osmose-frontend, parce que ce n'est pas lié.
