### ISSUE TITLE
TMS openriverboatmap semble HS

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#320]
Hello
Les tuiles du fond openriverboatmap répondent avec HTTP 504 (504 Gateway Time-out).
https://a.tile.openstreetmap.fr/openriverboatmap/9/263/187.png
Information [remontée sur talk-fr](https://lists.openstreetmap.org/pipermail/talk-fr/2021-August/104413.html) par un utilisateur de umap.

**Comment by jocelynj** [comment]
C'est malheureusement lié à #312. Je vais voir si on peut déjà rediriger ces tuiles vers le rendu osm.org en attendant.

**Comment by cquest** [comment]
Oups... oublié d'ajouter la redirection, c'est fait.

**Comment by Cyrille37** [comment]
Hello les techs. @cquest ce ticket peut-il être fermé ? Je vois bien les tuiles openriverboatmap. Ou bien la redirection n'est qu'un pansement  ?

**Comment by cquest** [comment]
Je laisse ouvert car la redirection est un pansement, le temps de remettre osm13 sur les rails ou de redéployer le rendu sur un autre serveur.

**Comment by cquest** [comment]
De retour sur les écrans... après transplantation d'osm13 sur une nouvelle machine.
