### ISSUE TITLE
Ajouter le plugin postgres sur minun osmose.vm.openstreetmap.fr 

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#321]
Le plugin pour suivre l'état de la base postgres est manquant sur osmose.vm.openstreetmap.fr
http://munin.openstreetmap.fr/osm26.openstreetmap.fr/osmose.vm.openstreetmap.fr/index.html#disk

**Comment by jocelynj** [comment]
Ajouté via https://github.com/osm-fr/ansible-scripts/commit/6f4ef3edda467a2cb4b89ff30e3ebdeee6de96c8
