### ISSUE TITLE
Service web tile.openstreetmap.fr HS

### ISSUE THREAD

**Issue by zorun** [osm-fr/infrastructure#322]
Le site `tile.openstreetmap.fr` (qui affiche le rendu FR) semble HS. Il y a bien une IP renvoyée par le DNS, mais la connexion ne marche pas :

```
$ curl -v http://tile.openstreetmap.fr/
*   Trying 109.190.177.37:80...
* connect to 109.190.177.37 port 80 failed: No route to host
* Failed to connect to tiles.openstreetmap.fr port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to tiles.openstreetmap.fr port 80: No route to host
```

Idem pour `tiles.openstreetmap.fr` (avec un S) ainsi que HTTP / HTTPS pour les deux noms.

Peut-être lié à #312  ?

**Comment by cquest** [comment]
Oui, tile.openstreetmap.fr est sur osm13 qui est indisponible en ce moment.
