### ISSUE TITLE
upgrading overpass.openstreetmap.fr to a new version

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/infrastructure#323]
Would it be possible to upgrade overpass.openstreetmap.fr to a new version that supports some nice syntax like `nwr` and `is_closed`?

**Comment by mmd-osm** [comment]
Old versions tend to be a source of confusion for unsuspecting users, as can be seen here: https://help.openstreetmap.org/questions/83000/function-length-not-known

**Comment by jocelynj** [comment]
@Marc-marc-marc , @cquest : should we stop the overpass instances, as they are too old?

**Comment by mmd-osm** [comment]
So bumping the version number in https://github.com/osm-fr/ansible-scripts/blob/master/hosts#L244-L245 wouldn't be sufficient to switch to a newer version?

Latest version according to http://dev.overpass-api.de/releases/ would be osm-3s_v0.7.57.1.tar.gz at this time.

**Comment by jocelynj** [comment]
I think we also have to re-import the database from planet.

**Comment by mmd-osm** [comment]
It would probably make sense to remove area files and create them from scratch using the much reduced set of rules. Besides, the on disk file format should be still the same. You can also download the clone files from https://dev.overpass-api.de/clone/ to avoid the import step.

**Comment by jocelynj** [comment]
Thanks for the reminder.

As we don't have any person to maintain this server, I will switch it off for the moment. We can reinstall it from scratch later.

**Comment by jocelynj** [comment]
I've just shutdown the service, and will add a redirect to https://wiki.openstreetmap.org/wiki/Servers/overpass.openstreetmap.fr

**Comment by mmd-osm** [comment]
Thank you for the update! It's really unfortunate to see this instance go. Maybe at some point in the future, there's a bit more bandwidth available to bring it back to life.

**Comment by Marc-marc-marc** [comment]
> So bumping the version number in https://github.com/osm-fr/ansible-scripts/blob/master/hosts#L244-L245 wouldn't be sufficient to switch to a newer version?

@mmd-osm no, given the patches not merged upstream witch need some changes too often (the main one being the one that switch from log file to journald, which avoids both having a log on ssd and being able to manage a purge of the log data).
From memory, there was an upstream ticket on this subject, feel free to ping me if we can make progress on this issue

**Comment by mmd-osm** [comment]
I think you're referring to https://github.com/drolbr/Overpass-API/issues/432#issuecomment-379842226 right?

You can try pinging drolbr again, if that doesn't help send him an email. I'm not sure if this helps in the end, but you could try it.
