### ISSUE TITLE
Overpass turbo: request rejected

### ISSUE THREAD

**Issue by ridalalven** [osm-fr/infrastructure#324]
Using **overpass turbo** (https://overpass-turbo.eu), I always receive this **error** message when overpass has chosen to send the query to https://overpass.openstreetmap.fr/:

![alt text][1]

Here, some more information, there seems to be issues with **CORS**. The messages are from the browser's **debugging** tool (F12):

![alt text][2]

According to https://help.openstreetmap.org/questions/81727/overpass-turbo-request-rejected/81779, this error stems from the **server configuration** which seems not to allow for request from http://overpass-turbo.eu. Could you please have a look at the issue that the user *escada* describes, thanks! **Would be great if this could be fixed :)**

Below, all details of the debugging messages in text format:

    Access to XMLHttpRequest at 'https://overpass.openstreetmap.fr/api/interpreterinterpreter' from origin 'https://overpass-turbo.eu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
    turbo.4decdd916893e57ee8ff.js:66 Uncaught TypeError: Cannot read property 'getBaseLayer' of undefined
        at Object.j.a.handlers.onDone (turbo.4decdd916893e57ee8ff.js:66)
        at e (turbo.4decdd916893e57ee8ff.js:40)
        at Object.error (turbo.4decdd916893e57ee8ff.js:40)
        at u (turbo.4decdd916893e57ee8ff.js:24)
        at Object.fireWith [as rejectWith] (turbo.4decdd916893e57ee8ff.js:24)
        at i (turbo.4decdd916893e57ee8ff.js:24)
        at XMLHttpRequest.<anonymous> (turbo.4decdd916893e57ee8ff.js:24)
    j.a.handlers.onDone @ turbo.4decdd916893e57ee8ff.js:66
    e @ turbo.4decdd916893e57ee8ff.js:40
    error @ turbo.4decdd916893e57ee8ff.js:40
    u @ turbo.4decdd916893e57ee8ff.js:24
    fireWith @ turbo.4decdd916893e57ee8ff.js:24
    i @ turbo.4decdd916893e57ee8ff.js:24
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:24
    error (async)
    send @ turbo.4decdd916893e57ee8ff.js:24
    ajax @ turbo.4decdd916893e57ee8ff.js:24
    run_query @ turbo.4decdd916893e57ee8ff.js:40
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:66
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:66
    e.parse @ turbo.4decdd916893e57ee8ff.js:58
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:58
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:82
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:66
    success @ turbo.4decdd916893e57ee8ff.js:66
    u @ turbo.4decdd916893e57ee8ff.js:24
    fireWith @ turbo.4decdd916893e57ee8ff.js:24
    i @ turbo.4decdd916893e57ee8ff.js:24
    (anonymous) @ turbo.4decdd916893e57ee8ff.js:24
    load (async)
    send @ turbo.4decdd916893e57ee8ff.js:24
    ajax @ turbo.4decdd916893e57ee8ff.js:24
    t @ turbo.4decdd916893e57ee8ff.js:66
    e.get @ turbo.4decdd916893e57ee8ff.js:66
    e.getBest @ turbo.4decdd916893e57ee8ff.js:66
    s @ turbo.4decdd916893e57ee8ff.js:82
    e.parse @ turbo.4decdd916893e57ee8ff.js:58
    getQuery @ turbo.4decdd916893e57ee8ff.js:66
    update_map @ turbo.4decdd916893e57ee8ff.js:66
    onRunClick @ turbo.4decdd916893e57ee8ff.js:66
    dispatch @ turbo.4decdd916893e57ee8ff.js:24
    _.handle @ turbo.4decdd916893e57ee8ff.js:24
    turbo.4decdd916893e57ee8ff.js:24 POST https://overpass.openstreetmap.fr/api/interpreterinterpreter net::ERR_FAILED

  [1]: https://help.openstreetmap.org/upfiles/err.jpg
  [2]: https://help.openstreetmap.org/upfiles/err2.jpg

**Comment by mmd-osm** [comment]
You've entered an incorrect URL in overpass turbo:  **/interpreterinterpreter**

Correct URL would be: `//overpass.openstreetmap.fr/api/`

**Comment by ridalalven** [comment]
Thanks for your answer @mmd-osm! I am using pretty simple scripts in overpass turbo where the selected default server (in my case) is set to //overpass-api.de/api/, but it ends up with the French one. Even if I chose //overpass.openstreetmap.fr/api/ from the list or add {{data:overpass,server=https://overpass.openstreetmap.fr/api}} or {{data:overpass,server=https://overpass.openstreetmap.fr/api/interpreter}} in the code, the query is rejected with just the same error message as above.

**Comment by mmd-osm** [comment]
Maybe you have installed some plugin which redirects Overpass traffic to another server. Try another browser, disable all plugins, or even try another computer. This is nothing we can help you with, it's all caused by your local set up.

**Comment by ridalalven** [comment]
Thanks @mmd-osm! From https://stackoverflow.com/a/55446202, I got the impression, that CORS is something that is handled on the server side. My IT colleagues have already checked proxy and network settings, nothing related to that could solve the issue. As overpass turbo is such an easy-to-use tool which gives access to the powerful OSM database, it would be really efficient if more colleagues in our company could use it. That is why I would like to solve the issue. In case, you have **any hints** that can help me or my IT colleagues, I would be delighted! 

As long as the request is only seems to be handled by https://overpass-api.de/api/interpreter, everything works fine. Is there any possibility to **trace** requests in order to **identify** the problem? Alternatively to "steer" requests towards https://overpass-api.de/api/interpreter instead of https://overpass.openstreetmap.fr/api?

**Comment by mmd-osm** [comment]
Your browser send requests to a non-existing URL. which is the main issue here - and CORS won't solve this. You really need to fix the invalid URL on your end. Check your browser settings, plugins, etc. We cannot help you with that.

Please ask your IT colleagues, we cannot fix any issues on your local machine in this repo.

**Comment by ridalalven** [comment]
First now, I spotted the typo you referred to: .../interpreter**interpreter**. Sorry for being that slow ;) Just one final **clarification**: How can I as a user change the URL? I understood that this is exactly one of the features of *overpass turbo* making it easier for users by letting them write "simple" code instead of "real code" for the *overpass API*. Could this be a bugg in *overpass turbo*?

**Comment by mmd-osm** [comment]
You need to head to "Settings" in overpass turbo:

![image](https://user-images.githubusercontent.com/5842757/133768410-def2e7da-b23f-49eb-bf87-ef409317dad1.png)

**Comment by ridalalven** [comment]
That I have tried already :(

**Comment by mmd-osm** [comment]
Can you please share a screenshot of what the popup looks like on your end?

**Comment by ridalalven** [comment]
Here the query https://overpass-turbo.eu/s/1bfF and here two screenshots, one with the French endpoint, one with the German endpoint (both causing the described error):

![settings_fr](https://user-images.githubusercontent.com/46749659/133771884-939927f3-944f-4f25-a236-13d9f626aec2.jpg)

![settings_de](https://user-images.githubusercontent.com/46749659/133771908-b67cca42-4c9a-4e85-96a5-46f0ffcfc32d.jpg)

**Comment by mmd-osm** [comment]
The query includes multiple data sources. The second and third entry are incorrect, you need to remove "interpreter" in there, so it looks like the kumi.systems examples. Also, please keep only one of the three entries in your query. Even if they are commented out, they might confuse overpass turbo.

```
// Alternative API
//{{data:overpass,server=https://overpass.kumi.systems/api/}}
//{{data:overpass,server=https://overpass-api.de/api/interpreter}}
//{{data:overpass,server=https://overpass.openstreetmap.fr/api/interpreter}}
```

**Comment by ridalalven** [comment]
Thanks @mmd-osm, I did not expect commented lines to create trouble ;) . I will try again later. Right now - using "//overpass-api.de/api/" in the settings dialogue and deleting the four lines or (I tested both cases) just keeping `{{data:overpass,server=https://overpass-api.de/api/}}` - I...

- ...either get the same error message as before, but first after a minute or so and not any longer - as before - directly at the beginning when sending the query:

![image](https://user-images.githubusercontent.com/46749659/133788381-f2f35f47-cd2b-409d-bbff-1d2a6fbd4e29.png)

- ...or a run-time error:

![image](https://user-images.githubusercontent.com/46749659/133789057-fe6e0881-7ea0-43ae-ab4e-f4f4cca40ce6.png)

The second one might sound promising but it appears first after a minute or so and the quota on http://overpass-api.de/api/status says `1 slots available now.` both right before I send the query and after I received the error message.

**Comment by mmd-osm** [comment]
Yes, your queries are very resource intensive and need a much higher timeout value, if they run at all.

**Comment by ridalalven** [comment]
Thanks a lot for your help @mmd-osm, it **works fine** now! As you said, the **main problem** was that I added multiple data sources in the code even though they were commented out. Seems to be best to only use the settings menu and not to add them in the overpass turbo code at all. 
Strange tough that it worked on other devices, something on my company laptop might sometimes (not: always) interfere with handling of larger queries (never had a problem with short ones). However, my IT colleagues checked and could not find anything. Removing the data sources in the code was a very good solution! I will close this issue.

**Comment by mmd-osm** [comment]
I think your conclusion to only use the settings menu makes no sense. Your problem was caused by *invalid* URLs which were considered even they were commented out. When using *correct* endpoint URLs, embedding URLs is totally fine.

**Comment by ridalalven** [comment]
That is true! To summarise: 

- Problem 1: Wrong URL; even if commented out, it must be stated correct:

```
// Alternative API
//{{data:overpass,server=https://overpass.kumi.systems/api/}}
//{{data:overpass,server=https://overpass-api.de/api/}}
//{{data:overpass,server=https://overpass.openstreetmap.fr/api/}}
```

- Problem 2: I should not have included overpass.openstreetmap.fr. Even if commented out, the query gets returned with an error message (e.g. it cannot interpret `complete` statements) as long as this server is the last mentioned in the commented text.
