### ISSUE TITLE
Ortho 2020 de la creuse

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#325]
Bonjour,
je ne sais plus où trouver la liste des millésimes des départements, je viens de tomber sur cette brève sur la creuse https://portail.pigma.org/animation/breve-mise-a-disposition-de-la-bd-ortho-2020-pour-le-departement-19/

**Comment by cquest** [comment]
La liste est ici: https://wiki.openstreetmap.org/wiki/FR:Serveurs/wms.openstreetmap.fr

A peu près çà jour... et la Creuse a été ajoutée il y a peu de temps.

**Comment by vinber** [comment]
merci parfait
