### ISSUE TITLE
Réplication bloquée

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#328]
Bonjour,
je ne sais pas s'il y a un lien avec #327 mais on me remonte ce matin (via BANO) que les màj sont stoppées. Je constate que https://download.openstreetmap.fr/extracts/merge/france_metro_dom_com_nc.state.txt reste sur :

sequenceNumber=4772099
timestamp=2021-10-25T01\:06\:45Z

merci

**Comment by vdct** [comment]
Bonjour
mêmes symptômes ce matin, blocage au 6/11 

#Sat Nov 06 14:30:43 UTC 2021
sequenceNumber=4789988
timestamp=2021-11-06T14\:30\:37Z

merci pour le coup de main

**Comment by jocelynj** [comment]
C'est corrigé à nouveau, et j'ai changé le système de lock pour être plus robuste, et relancer le process plus tard.

**Comment by vdct** [comment]
Merci @jocelynj
