### ISSUE TITLE
Container + sous domaine pour commerces.openstreetmap.fr

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/infrastructure#329]
Bonjour,

Suite à la proposition [lancée ici](https:https://listes.openstreetmap.fr/wws/arc/association/2021-11/msg00001.html//listes.openstreetmap.fr/wws/arc/association/2021-11/msg00001.html), pouvez-vous mettre à disposition une machine/container qui serait en mesure d'héberger une instance de ProjetDuMois ? La configuration à prendre est identique à celles des machines hébergeant projetdumois.fr ou enedis.openstreetmap.fr. Peut-on également prévoir une redirection du sous-domaine commerces.openstreetmap.fr vers cette même machine sur le port 3000 ? Merci d'avance :grinning:

**Comment by jocelynj** [comment]
Je viens de créer le container sur commerces.vm.openstreetmap.fr, et tu devrais y avoir accès. Le proxy est aussi configuré.

**Comment by PanierAvide** [comment]
Super, merci pour la mise à disposition, je vais essayer d'installer le service dans la journée, ça fera une démo pour le CA de ce soir :wink:

**Comment by PanierAvide** [comment]
J'ai commencé les manips pour l'installation, pour faciliter le déploiement je voulais profiter de l'image Docker qui a été créée, mais à priori il est nécessaire de configurer le container pour pouvoir y exécuter Docker ?

J'ai ce message d'erreur :

```bash
panieravide@commerces:/home/panieravide/EditeurCommercesOSMFR$ sudo docker build -t pdm/server:latest .
Sending build context to Docker daemon  5.978MB
Step 1/21 : FROM node:14.18.0-bullseye-slim
14.18.0-bullseye-slim: Pulling from library/node
7d63c13d9b9b: Pull complete 
bb262aff53d8: Pull complete 
e009996fd021: Pull complete 
11d95253f1e8: Pull complete 
35947d9db273: Pull complete 
Digest: sha256:a441283df70186f7334c77b62634b1ccb995f1da0fbe64d9e4c60bb831b77e99
Status: Downloaded newer image for node:14.18.0-bullseye-slim
 ---> 20c250d7280e
Step 2/21 : RUN groupadd --gid 10001 -r osm     && useradd --uid 10001 -d /home/osm -m -r -s /bin/false -g osm osm     && mkdir -p /data/files/pdm /opt/pdm /opt/imposm3     && apt-get update     && apt-get -y install --no-install-recommends         apt-utils curl xsltproc osmctools ca-certificates gnupg     && curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -     && echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list     && apt-get update     && apt-get -y --no-install-recommends install postgresql-client-13 libpq-dev libgeos-dev osmium-tool python3 python3-requests bc     && apt-get clean     && update-ca-certificates     && rm -rf /var/lib/apt/lists/*
 ---> Running in f4eea7a639a3
OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown
```

Et la cause semble être celle décrite ici : https://stackoverflow.com/questions/46645910/docker-rootfs-linux-go-permission-denied-when-mounting-proc

**Comment by jocelynj** [comment]
Effectivement, il y a un truc à faire en plus si on installe du docker dans un container. Je rajoute ce qu'il faut.

**Comment by PanierAvide** [comment]
Super, merci à toi, ça fonctionne pour le lancement de Docker.

Un dernier point, sur la RAM serait-il possible d'avoir la même capacité que la machine osm174 / projetdumois.fr (12Go) ? Le traitement d'analyse du fichier historique France ne passe pas actuellement faute de mémoire :sweat_smile:

**Comment by jocelynj** [comment]
Je viens de monter à 12Go.

**Comment by cquest** [comment]
osm174 monte à 4Go max... il faudrait voir si les cron ou autre peuvent être décalés entre les deux conteneurs pour que tout le monde n'ai pas besoin de RAM en même temps. Il en reste de libre donc ça passe actuellement sans problème.

**Comment by PanierAvide** [comment]
C'est possible que cette étape gourmande en mémoire ne soit qu'à l'initialisation de l'instance pdm, j'ai relancé et je surveille jusqu'à combien ça monte (on pourra sans doute baisser à 6Go). Je note aussi de vérifier les cron de part et d'autre pour être sur des heures de màj différentes.

**Comment by PanierAvide** [comment]
La mémoire n'a pas dépassé les 6Go, donc on peut sans doute baisser la VM à 8Go si besoin.

Par rapport au nom de domaine, est-ce qu'il y a possibilité de rediriger un tile-commerces.openstreetmap.fr vers la VM sur le port 7800 ? Pour la mise à dispo du service pg_tileserv qui sert les POI en surcouche.

**Comment by jocelynj** [comment]
Proxy et DNS ajouté pour tile-commerces.openstreetmap.fr

**Comment by PanierAvide** [comment]
C'est déployé et les services tournent à l'adresse https://commerces.openstreetmap.fr/ ! :rocket: 

Merci pour la réactivité et le temps consacré :grinning: Il me reste plus qu'à configurer proprement les thématiques de commerces.

**Comment by PanierAvide** [comment]
Je sais pas si c'est lié à un autre problème, mais je n'ai plus accès en SSH au serveur :

```
OpenSSH_8.6p1, OpenSSL 1.1.1k  25 Mar 2021
debug1: Reading configuration data /home/adrien/.ssh/config
debug1: /home/adrien/.ssh/config line 16: Applying options for osm191
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec ssh -i ~/.ssh/p4caas panieravide@osm26.openstreetmap.fr nc 2a01:e0d:1:c:58bf:fac1:c400:191 22
debug1: identity file /home/adrien/.ssh/oldpc type 0
debug1: identity file /home/adrien/.ssh/oldpc-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
nc: unable to connect to address 2a01:e0d:1:c:58bf:fac1:c400:191, service 22
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by jocelynj** [comment]
C'est lié au souci de plantage d'osm11: apparamment, la connectivité ipv6 s'est cassé (je ne sais pas si c'est parce qu'on passait par osm11 au lieu de osm14 par erreur)

Ça devrait remarcher maintenant.

**Comment by PanierAvide** [comment]
Effectivement, merci pour la réactivité comme toujours ! :grinning:
