### ISSUE TITLE
Instance PeerTube HS :(

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#330]
Tout est dans le titre : https://peertube.openstreetmap.fr/
502 Bad Gateway
nginx/1.14.2

Merci !

**Comment by cquest** [comment]
J'ai fait un reboot du conteneur, sans succès.

Il semble qu'une mise à jour ait été lancée hier, mais qu'elle pose problème.

@jocelynj ?

**Comment by cquest** [comment]
J'ai finalisé la mise à jour:
- nodejs maintenant en 12.x
- postgresql 11 (la 9.6 empêchait la migration de peertube de se faire, car version trop ancienne)

Il manquait aussi plein de nouvelles entrées dans le fichier de configuration suite probablement à l'upgrade partiel.

Tout a l'air de refonctionner normalement.

**Comment by jocelynj** [comment]
Merci @cquest !

J'avais effectivement lancé la mise à jour, mais vu qu'il fallait passer à node > 10, mais pas eu le temps de m'en occuper. Je pensais que peertube n'avait pas commencé la mise à jour lors de la vérification de la version de node.

**Comment by bristow** [comment]
Merci :tada:
