### ISSUE TITLE
https pour bano.openstreetmap.fr

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#331]
Bonjour,
La telecommande JOSM ne fonctionne pas via Chrome depuis http://bano.openstreetmap.fr/fantoir/ (en http). Passer en https résoud le souci, cf https://forum.openstreetmap.fr/t/telecommande-bano-fantoir-josm/7413/
Vu avec Christian : je souhaiterais forcer le https sur le sous-domaine bano, et il semble que le meilleur moyen est d'agir au niveau nginx. Sauf que je ne sais pas faire, d'où ce ticket.
merci

**Comment by jocelynj** [comment]
C'est fait via https://github.com/osm-fr/ansible-scripts/commit/222d4678c8d5016f32aefe1d66a278033a193864

**Comment by vdct** [comment]
Impec, merci @jocelynj
