### ISSUE TITLE
Reçu sur contact, le serveur de réplication est en retard

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#334]
I found the replication server is out of sync with the main OSM server.
http://download.openstreetmap.fr/replication/planet/minute/
Last modified Date: 	2021-11-18 16:13

**Comment by jocelynj** [comment]
download.vm.openstreetmap.org (et autres services sur osm14) avait perdu la connectivité ipv6. Ce qui veut dire qu'il ne pouvait plus télécharger les diffs sur planet.openstreetmap.rg

Problème résolu en lançant cette commande sur osm14 (commande qui est dans /etc/network/interface):
```
/sbin/ip -f inet6 neigh add proxy 2a01:e0d:1:c:58bf:fac1:c400:171 dev vmbr0
```
