### ISSUE TITLE
Erreur certificat osm13

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/infrastructure#336]
Dans JOSM, message "the website's HTTPS certificate cannot be verified. Do you want to continue?"
![image](https://user-images.githubusercontent.com/677071/142821939-515a2575-e972-42fb-b626-d6cd1631febf.png)

**Comment by cquest** [comment]
C'est en faisant quoi dans JOSM ? Affichage d'une couche particulière ? laquelle ?

**Comment by lmagreault** [comment]
Imagerie BANO

**Comment by cquest** [comment]
C'est réparé.
