### ISSUE TITLE
fr.osm.social - Erreur à la création d'alias

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/infrastructure#337]
Suivant la procédure https://hackmd.io/@YZ-4O4bxQwObAHD-7seW9A/HkMPoxUfK
pour migration mastodon de fr.osm.social à en.osm.town,
à la création d'alias, j'obtiens le message d'erreur  
"osm_gf@fr.osm.social could not be found" 
![image](https://user-images.githubusercontent.com/6804697/143149430-88537c70-6d98-4b8d-8003-1158fe8763ac.png)

**Comment by jocelynj** [comment]
fr.osm.social est maintenant désactivé, et n'est plus utilisable.
