### ISSUE TITLE
[bzh202] Real IP pour le apache derrière le frontal nginx

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#34]
Le but : que le serveur apache 2.4 sur osm202 reçoive bien les vraies IP des clients.

user  --->  frontal nginx (osm25)  ---> apache24 (osm202)

Docs :
*  https://buzut.fr/apache2-recuperer-ip-derriere-reverse-proxy/
*  https://gist.github.com/patrocle/43f688e8cfef1a48c66f22825e9e0678

Fait sur osm202 :

```bash
a2enmod remoteip
service apache2 restart

# pour vérifier
apachectl -M

nano /etc/apache2/conf-available/remoteip.conf
…
a2enconf remoteip
service apache2 restart
```

Contenu de remoteip.conf
```
#RemoteIPHeader X-Forwarded-For
RemoteIPHeader X-Real-IP

# ici les adresse distantes auxquelles on fait confiance pour présenter une valeur RemoteIPHeader
RemoteIPTrustedProxy 10.0.0.25
```

N'a pas marché : j'ai tjs 10.0.0.25 en IP d'origine dans les logs. Que ce soit en ```RemoteIPHeader X-Real-IP``` ou en ```RemoteIPHeader X-Forwarded-For```.

@jocelynj peux-tu remettre ici la config du nginx STP ?

**Comment by jocelynj** [comment]
Voilà la config du nginx d'osm25:
```
    location / {
        proxy_pass      http://10.1.0.202;
        proxy_redirect     off;
        proxy_buffering    off;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
```

**Comment by jocelynj** [comment]
J'ai du changé aussi ceci dans la config apache de bzh202:
```
apache2.conf
LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
```
(%a au lieu de %h)

**Comment by jocelynj** [comment]
Toutes les VMs utilisant apache sont maintenant configurées pour afficher la vraie IP au lieu du reverse proxy: https://github.com/osm-fr/ansible-scripts/commit/159055c553b5b644f46734f5fc02f5ebe967e17d

**Comment by MaelREBOUX** [comment]
Super !
Donc c'était juste la config des log apache qu'il fallait changer ??!!
Ha ben…

Je viens de tester et oui : je vois bien mon IP dans les logs.
