### ISSUE TITLE
Mise à jour Mobilizon

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#340]
La V2 est sortie :tada: 

Merci :pray: 

https://joinmobilizon.org/fr/news#21-11-23

**Comment by vinber** [comment]
je crois avoir vu passer une mise à jour vers la <V3 donc sans doute à fermer :)

**Comment by jocelynj** [comment]
J'ai passé la VM à 12G de ram pour faciliter l'upgrade - on repassera à 4G après.

**Comment by jocelynj** [comment]
@tykayn : on a un souci sur la VM mobilizon, suite à un reboot. J'ai tenté les commandes de https://docs.joinmobilizon.org/administration/install/source/ pour installer les dépendances elixir/yarn, mais sans succès.

Ça foire sur cette erreur:
```
Oct 08 01:10:20 mobilizon systemd[1]: Started Mobilizon Service.
Oct 08 01:10:21 mobilizon mobilizon[31071]: Could not find Hex, which is needed to build dependency :phoenix
Oct 08 01:10:21 mobilizon mobilizon[31071]: Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :phoenix from Mobilizon.Mixfile
Oct 08 01:10:21 mobilizon systemd[1]: mobilizon.service: Main process exited, code=exited, status=1/FAILURE
```

Une idée de ce qu'il manque ?

**Comment by jocelynj** [comment]
Ça a l'air de marcher après avoir lancé ces commandes:
```
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/usr/bin/mix local.hex
```

On dirait que le mix utilisé par l'unit systemd ne va pas sur les même libs que celui du compte "mobilizon", qui part sur "~/.asdf".

**Comment by tykayn** [comment]
ah oui, c'est parce que l'utilisateur mobilizon utilise le gestionnaire de version asdf pour modifier la version d'elixir utilisée en CLI. on peut tenter de faire un ajout au path pour avoir le dossier /home/mobilizon/.asdf

merci d'avoir tenté ce reboot, le service est de nouveau accessible

**Comment by tykayn** [comment]
arf y'a toujours des erreurs 500, faut voir si y'a pas besoin de migrer la BDD

**Comment by jocelynj** [comment]
Est-ce qu'il suffit de modifier l'unit systemd pour appeler ~/.asdf/shims/mix au lieu de /usr/bin/mix, ou faut-il modifier le PATH aussi ?

Pour la bdd, possible qu'il faille lancer la commande d'upgrade de mobilizon.

**Comment by jocelynj** [comment]
J'ai changé ça:
```
--- a/systemd/system/mobilizon.service
+++ b/systemd/system/mobilizon.service
@@ -10,6 +10,7 @@ ExecReload=/bin/kill $MAINPID
 KillMode=process
 Restart=on-failure
 Environment=MIX_ENV=prod
+Environment=PATH=/home/mobilizon/.asdf/shims:/home/mobilizon/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
```

Et lancé `MIX_ENV=prod mix ecto.migrate` pour la mise à jour de la bdd + `MIX_ENV=prod mix phx.digest` pour les static assets.

**Comment by tykayn** [comment]
ah super ça fonctionne, il y a bien les évènements qui sont de retour dans le frontend

**Comment by bristow** [comment]
Je confirme, cela fonctionne parfaitement, je viens de recréer des événements sur la plateforme.

**Comment by jocelynj** [comment]
Parfait, je ferme le ticket.

Je te laisse regarder si il faut modifier des trucs dans l'unit systemd.
