### ISSUE TITLE
Certificat expiré sur listes.osm.fr

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/infrastructure#341]
Hello,

Tout est dans le titre : "Le certificat de listes.openstreetmap.fr a expiré le 05/12/2021."

HTH

**Comment by JacLavi** [comment]
On a oublié de payer la licence ?

**Comment by jocelynj** [comment]
L'adresse IPv6 de osm138 n'était plus bonne suite à la migration de la VM sur un nouvel host. Du coup, letsencrypt n'arrivait pas à accéder au fichier dans .well-known.

J'ai mis à jour l'IPv6, et relancer le script.
