### ISSUE TITLE
Activer l'utilisation de Docker sur osm174

### ISSUE THREAD

**Issue by PanierAvide** [osm-fr/infrastructure#342]
Bonjour,

Pour faciliter le déploiement du code de ProjetDuMois sur le serveur, est-il possible d'activer sur osm174 l'utilisation de Docker, comme ça a été configuré sur osm191 (cf https://github.com/osm-fr/infrastructure/issues/329#issuecomment-964417882) ? Merci d'avance :grinning:

**Comment by jocelynj** [comment]
Pas de souci, je regarde pour ajouter le support de docker sur projetdumois.vm.openstreetmap.fr.

D'ailleurs, est-ce que c'est normal que osm191 utilise plus de 50G de disque dur ? J'ai du augmenter l'espace disponible, parce que le disque était saturé.

**Comment by PanierAvide** [comment]
Super, merci à toi :smiley:  Oui c'est normal, il y a un certain nombre de fichiers temporaires qui sont créés pendant les mises à jour, supprimés ensuite. C'est possible que compte tenu du volume de commerces en France ces fichiers prennent plus rapidement de la place que sur d'autres thématiques. Merci d'avoir augmenté l'espace disque.

**Comment by PanierAvide** [comment]
Déploiement avec Docker OK, je ferme le ticket, merci :grinning:
