### ISSUE TITLE
Improve error message when instance has no attic data

### ISSUE THREAD

**Issue by zstadler** [osm-fr/infrastructure#343]
When using `overpass.openstreetmap.fr` as the server for `overpass-turbo.eu`, there are different kinds of errors when using `[date:"..."];`

Steps to reproduce:

#### A. Use the `//overpass.openstreetmap.fr/api/` server for Overpass Turbo
1. Open https://overpass-turbo.eu/
2. Settings -> General Settings -> Server -> `//overpass.openstreetmap.fr/api/`
   <img width="33%" src="https://user-images.githubusercontent.com/1304610/147811818-eef0055a-09e7-4c5e-9ecc-62281b6d8cfe.png" />
3. Save

#### B. First example
1. Paste the following query:
   ```
   [date:"2019-01-01T00:00:00Z"];
   way [tracktype]({{bbox}});
   out meta geom;
   ```
2. Press "Run"
3. The following error is received:
   <img width="33%" src="https://user-images.githubusercontent.com/1304610/147811948-6dad236d-8454-47d0-b4f2-086865c81892.png" />

#### C. Second example
1. Open the browser's developers' tools (F12)
2. Open the "Console" tab
2. Return to the Overpass-turbo page
3. Paste the following query:
   ```
   [date:"2019-08-29T07:25:28Z"];
   way(383599639);
   out meta geom;
   ```
4. Press "Run"
5. The following error is received:
   <img width="33%" src="https://user-images.githubusercontent.com/1304610/147812224-a5033f24-cbe1-4d7d-be3e-6d24a3e66070.png" />
6. Return to the browser's developers' tools
7. Console shows a CORS error

#### Notes
- Both queries are OK if the `[date:"..."];` statement is not used.
- Both queries are OK if the `//overpass-api.de/api/` server is used.
- Tested with both Chrome and Firefox on a Windows PC.

**Comment by mmd-osm** [comment]
This is expected and documented on the wiki: https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances

This instance does not have attic data, which is mandatory for the kind of queries you want to run.

**Comment by zstadler** [comment]
Since this is a valid configuration used by a public instance, please consider providing a simple and clear message for the lame user.

For example,

> The "overpass.openstreetmap.fr"  server does not support history-related queries.
> Please consider a different server using the list at
> https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances

**Comment by mmd-osm** [comment]
Well, this is clearly out of scope for this repo. You would have to raise an issue on Overpass API. Reason is pretty clear: you're always using the same endpoint /api/interpreter, and to be able to return a meaningful error message, you would have to parse the query.

**Comment by jocelynj** [comment]
overpass.openstreetmap.fr is no longer available, and will need to be completely re-installed with a newer version of overpass, thus solving this issue.

I'm then closing this bug.
