### ISSUE TITLE
fr.osm.social - Code de sécurité non reçu

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/infrastructure#344]
Bonjour, je n'arrive pas à me connecter au compte via l'interface web.  
Un code de sécurité est demandé mais n'est jamais reçu dans la boite courriel du compte,  
même dans les indésirables.

C'est une boite `@laposte.net` qui a déjà précédement reçu des messages de `notifications@fr.osm.social` et dont `@fr.osm.social` est dans la liste des domaines de confiance.

**Comment by frodrigo** [comment]
Bonjour, l'idée est de fermer a terme fr.osm.social. Les nouveaux comptes ne sont pas activés.

**Comment by adrienandrem** [comment]
Oui, je cherche à m'identifier sur un compte existant  
pour tenter de poursuivre la procédure de [migration de ce compte](https://github.com/osm-fr/infrastructure/issues/337) vers une autre instance.

**Comment by jocelynj** [comment]
Je vois bien l'envoi d'email dans les logs postfix, mais c'est refusé par laposte:
```
Dec 31 10:36:25 mastodon postfix/qmgr[3754322]: 45F901B95D8: from=<notifications@fr.osm.social>, size=28958, nrcpt=1 (queue active)
Dec 31 10:36:25 mastodon postfix/smtp[1559044]: 45F901B95D8: to=<...@laposte.net>, relay=smtpz4.laposte.net[160.92.124.66]:25, delay=0.28, delays=0.06/0.01/0.05/0.17, dsn=5.7.1, status=bounced (host smtpz4.laposte.net[160.92.124.66] said: 550 5.7.1 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN007_510 (in reply to end of DATA command))
```

**Comment by jocelynj** [comment]
@adrienandrem : est-ce que tu pourrais redemander un code ? Je te transférerais l'email, en espérant que le code soit encore valide.

**Comment by adrienandrem** [comment]
Bien vu, bonne idée. Cependant je viens de retenter depuis une IP connue, Mastodon ne redemande pas de code 🎉
