### ISSUE TITLE
taginfo.openstreetmap.fr - Manque une grande partie des objets

### ISSUE THREAD

**Issue by PtiBzh** [osm-fr/infrastructure#352]
Cela fait quelques jours que taginfo.osm.fr indique un nombre incorrect d'objets.
 
Actuellement :

- 91 164 highway=*
- 40 561 natural=*
- 37 316 building=*
- 26 194 power=*

**Comment by jocelynj** [comment]
J'ai ré-importé le dernier extract france dans taginfo. Est-ce que vous pouvez confirmer que c'est bon maintenant ?

**Comment by PtiBzh** [comment]
Les nouvelles données me semblent correctes, merci Jocelyn.
Je vois que l'extrait de geofabrik pour la France a un nombre supérieur sur l'ensemble des tags (67341 building=*, 39434 highway=*). Cela est peut-être lié à un découpage différent ou une erreur sur leur base.

https://taginfo.geofabrik.de/europe/france

**Comment by jocelynj** [comment]
Geofabrik utilise un polygone un peu plus large pour la France, qui contient des bouts des pays voisins: http://download.geofabrik.de/europe/france.html
L'extract utilisé par le taginfo osm-fr est découpé sur la frontière exacte, ce qui fait qu'il contient un peu moins d'objets.

Du coup, cette différence est normale.
