### ISSUE TITLE
https://demo.openstreetmap.fr/map

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#353]
Bonjour,

j'ai l'impression que cela ne marche plus ?

j'ai ouvert sur le forum pour pinger JLZ aussi https://forum.openstreetmap.fr/t/osmdata-ne-semble-plus-fonctionner-https-demo-openstreetmap-fr-map/7969

**Comment by adrienandrem** [comment]
Bonjour @TANK2003,

l'outil est vide, il a dû retomber :/

**Comment by vinber** [comment]
je rouvre l'issue, lien discussion forum https://forum.openstreetmap.fr/t/demo-openstreetmap-fr-hs/10756/10

**Comment by vinber** [comment]
je ferme ici car https://github.com/osm-fr/infrastructure/issues/419
