### ISSUE TITLE
Plus d'accès à https://listes.openstreetmap.fr/

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#355]
bonjour,
je n'arrive plus à me connecter à https://listes.openstreetmap.fr/

![image](https://user-images.githubusercontent.com/890869/157082490-e4e65fc3-1c8c-41b7-b587-6678261d1419.png)

**Comment by cquest** [comment]
Très étrange, apache semblait bloqué

Résolu avec `service apache2 restart`

Monit ne tourne pas, bien qu'il soit installé, sûrement à cause d'une config manquante...

**Comment by jocelynj** [comment]
Du coup, est-ce que ça veut dire que systemd ne remplace pas monit ?  (on avait discuté de ne plus installer monit sur les prochaines VMs)

J'ai en tout cas corrigé la config de monit sur la VM listes, et monit tourne correctement.

**Comment by cquest** [comment]
Le problème c'est qu'apache n'était pas mort, mais ne répondait pas non plus... je ne pense pas que systemd puisse gérer ça.

**Comment by vinber** [comment]
je laisse ouvert ou il est préférable de fermer ?

**Comment by cquest** [comment]
On garde ouvert, vu qu'on n'a pas trouvé l'origine du problème, ni mis en place de solution automatique pour que le service se relance quand il est coupé.

**Comment by jocelynj** [comment]
Monit a été installé sur listes.openstreetmap.fr, et s'occupe de relancer apache2 si nécessaire.

On peut fermer le ticket du coup.
