### ISSUE TITLE
Ressources pour plateforme enedis, gespot.

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#356]
Bonjour à tous

Depuis le début de l'année, j'ai quelques problèmes sur la machine qu'on me met à disposition pour héberger la base et les quelques rendus que je produits autour d'osm.

Notamment le suivi de la convention [enedis](https://enedis.openstreetmap.fr), [gespot](https://gespot.fr) et [map.infos-reseaux.com](https://map.infos-reseaux.com). Actuellement indisponibles.

J'aimerais étudier avec vous les possibilités d'en porter au moins une partie vers les serveurs de l'asso qui bénéficient d'un environnement plus stable.
Examinons les possibilités techniques.
Le CA sera amené à se prononcer sur la solution que nous retiendrons et l'opportunité d'accueillir l'un, l'autre ou la totalité des outils ci-dessus.

Niveau ressources, cela dépend de la base de données, commune à tous les usages ci-dessus.
Lors des imports 8 CPU/32 Go de RAM peuvent être nécessaires. Au quotidien c'est plus 2 à 4 avec 8 Go de RAM pour l'ensemble.

J'avais dans les cartons un rendu "Emergency" pour Donat, qui se mutualise bien avec le reste.

Quelles sont nos capacités actuelles et les opportunités de mutualisation avec l'existant ?

Merci par avance pour le retour et bon weekend

François

**Comment by frodrigo** [comment]
Tu peux dire ce que font ces services stp ? Perso enedis je vois, mais pas les autres.

**Comment by flacombe** [comment]
Oui : gespot et map.ir.com sont deux démonstrateurs basés sur [OpenInfraMap](https://openinframap.org/).

[Gespot](https://github.com/flacombe/gespot) affiche les supports des réseaux aériens électriques et telecom
[Map.ir.com](https://github.com/flacombe/openinframap) affiche les mêmes thématiques que l'original OpenInfraMap, restreint à la France et avec des ajouts substantiels de symbologie (notamment pour l'hydro et les télécoms).

Une base pgsql est tenue à jour avec imposm3 pour les features qui m'intéressent.
Un serveur de tuiles vectoriel tegola fabrique 2 pyramides de tuiles spécifiques (il en fabrique 4 autres pour la plateforme Enedis depuis la même base).
Quelques ressources statiques en js sont servies par un nginx pour fabriquer le front.

Niveau stockage ça consomme ~60 Go environ.

**Comment by cquest** [comment]
Quelles technos nécessaires ? Surtout la question docker or not docker... pour savoir si on déploie plutôt une VM QEMU ou un containeur LXC...

**Comment by gendy54** [comment]
Hébergement temporaire le temps que tu investigues et trouves une solution ou hébergement pérenne?

**Comment by flacombe** [comment]
C'est 100% docker @cquest 
Sinon c'est principalement PgSQL 13, nodejs, tegola (go), imposm (avec quelques mises à jour), crontab

@gendy54 Ma demande est pérenne, surtout pour le suivi Enedis.

**Comment by flacombe** [comment]
Le serveur est de retour, la base de données est toujours figée au 10/02

https://www.gespot.fr
https://map.infos-reseaux.com
https://enedis.openstreetmap.fr

**Comment by flacombe** [comment]
Bonjour à tous,

Peut-on avancer sur le sujet s'il vous plaît ?

**Comment by jocelynj** [comment]
Je galére avec la création d'une VM plutôt que d'une container, pour faire ça automatiquement :( 

@cquest : est-ce que tu créés toujours tes VMs à la main, en refaisant l'install complète avec la gui de debian-installer, ou tu as un template comme pour les containeurs ?

**Comment by cquest** [comment]
A la mano !

Pour une install automatisée, il faudrait utiliser un fichier de définition cloudinit ou un truc de ce genre.

**Comment by jocelynj** [comment]
J'ai trouvé des templates possibles en fait, configurable via cloud-init, qui est supporté par proxmox:
https://blog.stefandroid.com/2021/07/02/proxmox-debian-cloud-init-template.html
https://cloud.debian.org/images/cloud/OpenStack/current-10/
https://pve.proxmox.com/wiki/Cloud-Init_Support

**Comment by zorun** [comment]
C'est pas très compliqué de faire ses propres templates de VM (et au moins on sait ce qu'il y a dedans !). Je l'ai documenté pour une asso :

- création d'un template : https://forge.gresille.org/salle-serveur/doc-publique/-/wikis/fonctionnement_technique/procedures/Administration-Proxmox#cr%C3%A9ation-dun-template-dos

- création d'une VM à partir d'un template : https://forge.gresille.org/salle-serveur/doc-publique/-/wikis/fonctionnement_technique/procedures/Cr%C3%A9ation-d'une-VM#installation

**Comment by jocelynj** [comment]
La VM est enfin créée - désolé pour le retard.

@flacombe : tu pourrais me donner une clé ssh publique pour ton compte ?

**Comment by flacombe** [comment]
Salut @jocelynj 

Merci pour les nouvelles et désolé de ne pas avoir pu répondre avant.

Voici ma clé publique
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDM9N0EmJinuGaVnS+96vVVCQGV5FQK5//LIgXBmNrn3dXNvXkr3E+Ep4NtL58h5BUNugRHRQMBVFy028aSm3H2XtsUyfTfxT/hjjP/mUhWBBtLBsOfXL5em7JHp4aekw2aqwxNZoJOzTpoFb789G+pRQLeGwMx0w0qtlR5DDFu9rxNkzuUHEm4zQyO6mM/p83mTueB/4/UzUw/bswxhw8owyB4g30xmF9F65g13C8HgFerEAIwzl2fc99O81szPVdAt12490PjAfUBcAIQhD5ttJjMn6eg+t7DUoekzQo+ZXbJql7koWOI6U25qyNzWeU/wkuP3GiNYTTNTfWoW2dL1FRpw2G1T7Bl8IzPkRWSXl3IQUzNv/HLuv5eiF9PBb6P4b+mTGiJvoTMYQu188T0U07wgf5jM3CVrceltpQMp3Kn2Mk+CgBr1v5jznrSLi9rv1nnLzz5YIzDfK/luGKjncnnf4spBNKVmp5J6br7df+UHovCyV8Y9OmV+HENBY64w+9QiCeP2Cgb8cEtku8yCyrq7qRRpPmc3gOnIruqBkbZwvtLOPlKuCaxNOVwSSd5V8jfaQTOhe2o+KczBNT+adU+kxeANmH7SDm2F/JleYMGf/6+7S/wHAT/MNonZphmL0uTFudmv38hlj4GOup889pRXFKx3Bso9ch6tkgwYQ==

**Comment by jocelynj** [comment]
Tu pourrais tester sur flacombe@enedis.vm.openstreetmap.fr ?

Je ne suis pas sûr que cette clé ssh marche tel quelle, vu qu'on dirait qu'il manque un bout à la fin.

**Comment by flacombe** [comment]
Aucun problème pour tester mais est-ce possible d'avoir une IPv4, n'ayant pas encore d'IPv6 partout s'il vous plaît ?

**Comment by jocelynj** [comment]
Je t'ai créé un compte sur osm34.openstreetmap.fr pour utiliser comme ProxyJump.

**Comment by flacombe** [comment]
Merci beaucoup.

Ca fonctionne sur osm34, mais pas sur enedis.vm ensuite.
L'user flacombe ne doit pas avoir la clé du bastion dans les authorized_keys.

**Comment by jocelynj** [comment]
Normalement, j'ai mis la même clé ssh sur les deux machines. Tu pourrais retester avec un `ssh -A osm34.openstreetmap.fr` ?

**Comment by flacombe** [comment]
Pardon @jocelynj je n'avais pas pris le temps de répondre ici

Tout est bon, ça fonctionne, merci pour ton temps !
il faut que je prenne le temps d'installer le nécessaire, ça sera fait au fil de l'eau vu mon emploi du temps

(laissons le ticket ouvert le temps que je termine)

**Comment by flacombe** [comment]
Hello

Je profite enfin de mes congés pour avancer le déploiement sur la VM.
Serait-ce possible @jocelynj de procéder aux augmentations suivantes s'il te plaît ?
* Disque => / 100 Go
* RAM => 16 Go

Merci et bonne fin d'après-midi

**Comment by jocelynj** [comment]
Ça devrait être bon maintenant, après un reboot de la VM.

**Comment by flacombe** [comment]
Merci beaucoup @jocelynj 

Actuellement j'ai un permission denied (public key) depuis le bastion osm34.
Quelque chose d'autre a changé ?

**Comment by jocelynj** [comment]
J'ai eu un souci similaire tout à l'heure, et j'ai du supprimé la clé ssh dans ~/.ssh/known_hosts: je me demande si le reboot de la VM n'aurait pas changé la clé ssh du serveur. Il faudra vérifier lors du prochain reboot.

**Comment by flacombe** [comment]
Étrange en effet.
Je vais faire ce qu'il faut pour pouvoir reboot, j'ai bien avancé mon déploiement.

En revanche pour l'IPV4, en a-t-on en rab ?

**Comment by flacombe** [comment]
@cquest @frodrigo 
Relativement à la question posée ce soir en CA sur la nécessité d'une IPv4.
J'ai juste les ports 443 à proxyfier semble-t-il.

**Comment by frodrigo** [comment]
@flacombe ta question de l'ipv4 c'est pour une connection ssh à la machine, c'est bien ça ?

**Comment by flacombe** [comment]
Non, l'accès ssh je l'ai via le bastion.
C'est juste pour permettre aux utilisateurs en ipv4only (il y en a encore beaucoup) d'accéder aux applications.

**Comment by frodrigo** [comment]
Tu es sûr que c'est ça le problème ? Pour moi les trois sites sont déjà accessibles en ipv4.

**Comment by flacombe** [comment]
Quand tu dis les trois sites, desquels parles-tu ?
Je veux dire, de quelle IP ?

**Comment by frodrigo** [comment]
Je parle de ça [enedis](https://enedis.openstreetmap.fr/), [gespot](https://gespot.fr/) et [map.infos-reseaux.com](https://map.infos-reseaux.com/). Tous sur la même IPv4 154.49.219.152

**Comment by flacombe** [comment]
C'est toujours l'ancienne machine que tu vois là. 154.49.219.152 n'a rien à voir avec les services de l'asso.
Rien n'est en prod sur osm34, justement c'est l'IPv4 qu'il me manque pour faire la bascule :)

**Comment by frodrigo** [comment]
Ok, tu veux connaitre l'IPv4 du reverse proxy pour configurer tes DNS !

**Comment by flacombe** [comment]
Et savoir si il a été configuré en conséquence mais oui, il semble que ce soit le fond de ma question

**Comment by cquest** [comment]
Le proxy de TH3 est sur: proxy.th3.vm.openstreetmap.fr

Fait tout passer par là, y compris l'IPv6. Il faut par contre le paramétrer pour ajouter la gestion du certificat et le reverse.
Je pense que @jocelynj a des scripts pour déployer ça sinon, je peux le faire à la main.

**Comment by flacombe** [comment]
J'oubliais le coup du certificat. Cela ne va-t-il pas être pénible ? c'est un certbot de mon côté.

**Comment by jocelynj** [comment]
Ça va être un peu pénible si on veut garder le https fonctionnel pendant la migration, vu qu'il faut le délai de propagation pour que letsencrypt puisse le regénérer. Ou alors, on s'autorise quelques heures de coupure pour le https ?

@cquest : ça va te faire plaisir, parce que proxy.th3 utilise certbot pour les certificats. Du coup, on peut rajouter des hosts en lançant certbot.

**Comment by cquest** [comment]
on peut recopier manuellement les certificats sur le proxy, le temps que l'IP soit ok, mais letsencrypt interroge directement le DNS primaire d'après ce que j'ai constaté et donc les temps de propagation DNS sont réduits au minimum.

**Comment by flacombe** [comment]
Honnêtement, ne vous inquiétez pas, quelques heures d'indisponibilité ne vont tuer personne : allons au plus simple.

J'aimerais juste comprendre ce qu'il est nécessaire de faire sur le proxy et sur la machine pour que ca fonctionne.

**Comment by jocelynj** [comment]
J'ai configuré un https://dev.enedis.openstreetmap.fr/ sur le proxy, qui va vers la VM enedis. Ça devrait permettre d'y voir plus clair, et de configurer avant la bascule de enedis.openstreetmap.fr

**Comment by flacombe** [comment]
Merci beaucoup, je m'occupe de regarder ca pendant le weekend !

**Comment by jocelynj** [comment]
@flacombe: besoin d'aide ?

**Comment by flacombe** [comment]
Bonjour  @jocelynj 

Je ne peux plus me connecter à la VM enedis depuis le bastion, petit problème de routage semble-t-il :
> user@osm34:~$ ping6 enedis.vm.openstreetmap.fr
> PING enedis.vm.openstreetmap.fr(2001:67c:1740:9031::193 (2001:67c:1740:9031::193)) 56 data bytes
> From 2001:67c:1740:9031::34 (2001:67c:1740:9031::34) icmp_seq=1 Destination unreachable: Address unreachable
> From 2001:67c:1740:9031::34 (2001:67c:1740:9031::34) icmp_seq=2 Destination unreachable: Address unreachable
> From 2001:67c:1740:9031::34 (2001:67c:1740:9031::34) icmp_seq=3 Destination unreachable: Address unreachable

**Comment by jocelynj** [comment]
Le host a son / saturé depuis ce matin, après un reboot d'après munin: http://munin.openstreetmap.fr/osm34.openstreetmap.fr/osm34.openstreetmap.fr/index.html#disk

J'ai libéré de la place en supprimant un paquet de backups de VM/CT, et je procéde à un reboot pour que les services Proxmox démarrent correctement.

**Comment by jocelynj** [comment]
@flacombe : tu devrais pouvoir te connecter maintenant.

**Comment by flacombe** [comment]
Je confirme, merci @jocelynj

**Comment by flacombe** [comment]
Hello @jocelynj 

Je ne peux à nouveau plus me connecter sur enedis.vm depuis osm34 : mon utilisateur sur osm34 n'avait plus de clé ssh semble-t-il.
Pourquoi avait-elle disparu ?

Est-ce possible d'autoriser 
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8fPM4Btd2gJJx60KIvQARecPVOy7ijkOVQZc0ZhSUtRrd0ipiHJWVEEf+oYA2GDtlYRMj7lzNGQGNp2Z0xeR84HlF+xv8DnfmSGPa9o0uxPHxflXtIQFu45BbNbVFQXRO1Jn3KEYQkKd6F2zebxX0yIhG67Ke2P2dIGcI5dU+DRyDrJj3NynqJaLWJziw4JkZuistZithGkruEr14sOsT42/sDRuh2+40YFEMe/GLf+tgpvNo7YlqowDhCw3DAoLArv2ulYjhtT735/HYnDa8ec7qEJtW+qM++eBS7dKhaTu7zxn/IQZnTlib9Y8h2D+THGpedj5Bwf6sZIhNmqzNwxQgslMDclwdo87pMqP1UmFbjqx4c95YkxeCQqVpQW5NNht3hRJiVJ0VtIm3cJgFaEDx4bAqXPhloRPwje3frTZO/I2LMcMVWLN81R7PzFh0lPFZ/W6gEnvj1PPij94aS1y+pF6eUjSBxVmGKymDRZgxLy3XsrMQxetXy/wC4F8= flacombe@osm34`

sur enedis.vm s'il te plaît ?

**Comment by jocelynj** [comment]
J'ai bien tes clés sur enedis.vm et osm34 dans /home/flacombe/.ssh/authorized_keys

Tu es sûr de ne pas avoir oublié un ssh -A pour propager la clé ssh, ou d'utiliser ProxyJump incorrectement ?

**Comment by flacombe** [comment]
Good point, il fallait ajouter un -A, désolé pour le bruit

Je supprime la clé ssh que j'ai généré par ailleurs

**Comment by flacombe** [comment]
Hello @jocelynj c'est en très bonne voie, mes services tournent désormais sur la VM.

Peux-tu supprimer dev.enedis.openstreetmap.fr et changer les IPv4 et v6 de enedis.openstreetmap.fr à la place s'il te plaît ?

J'aurais besoin de règles sur le proxy pour gespot.fr, www.gespot.fr et map.infos-reseaux.com s'il te plaît, que je vais également faire pointer sur les mêmes IP que enedis.osm.fr.

On va bientôt pouvoir enfin clore cette issue et #446 et #434

**Comment by flacombe** [comment]
Hello

Merci pour la rapidité :)
Les DNS sont à jour, tu peux mettre à jour les certificats.

Aucun lien avec #446, je n'étais pas réveillé

**Comment by flacombe** [comment]
Pour info, un script est disponible pour relancer les services présents sur la vm

`$> /opt/infra/scripts/docker.sh`

Les dockers sont relancés les uns après les autres avec un délais pour tenir compte a priori de leur readiness.

**Comment by Marc-marc-marc** [comment]
et/ou lancer le script (au boot) via systemctl :)

**Comment by flacombe** [comment]
Merci à tous, le wiki est à jour et le script a été ajouté à un [@reboot](https://phoenixnap.com/kb/crontab-reboot) sur la crontab

On peut clore cette issue si vous le voulez bien ?

**Comment by jocelynj** [comment]
Parfait, on peut fermer.

**Comment by jocelynj** [comment]
Juste une question: tu as mis le script dans `@reboot` du compte `root`, ou dans /etc/cron.d/ ?
