### ISSUE TITLE
Mise à jour proxmox v6 -> v7

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#357]
Serveurs à mettre à jour:

Cluster free:
- [x] osm12
- [x] osm13 
- [x] osm14

Cluster OVH:
- [x] osm26
- [x] osm27
- [x] osm28

Hors clusters:
- [x] osm11
- [ ] osm25

Les serveurs à TH3 sont déjà en v7.

**Comment by cquest** [comment]
Le cluster OVH est à jour.

**Comment by cquest** [comment]
osm11 (qui est dans ma cave) est à nouveau dans le cluster free.

J'ai configuré corosync pour utiliser un second "ring" et pour fonctionner en TCP au lieu d'UDP, du coup osm11 est à nouveau visible dans le cluster, ce uqi permet les upgrades proxmox.

**Comment by cquest** [comment]
Il semble y avoir un problème IPv6 sur les CT du cluster free (osm12/osm14).

Cela bloque pas mal de choses, download, osm110 (osmose back), etc.

Je ne vois pas d'où ça vient car je n'ai pas touché à la config, ni encore fait de mise à jour de l'OS, les seuls changements sont:
- la réintégration d'osm11 dans le cluster en ajoutent un second ring pour corosync basé sur les IP publiques
- un apt update + dist-upgrade préparatoire à l'upgrade v6 > v7

**Comment by cquest** [comment]
C'était la ré-intégration d'osm11 via WAN dans le cluster qui posait problème.
corosync a besoin d'une latence de 2ms pour rester synchronisé... donc LAN only !

J'ai ressorti osm11 du cluster free, upgradé osm14, et maintenant osm12...

**Comment by cquest** [comment]
J'ai intégré osm13 dans le cluster free. Il était déjà en v7 et n'avait pas pu être ajouté car le reste du cluster était en v6.

**Comment by jocelynj** [comment]
@cquest : est-ce que tu penses qu'on peut fermer le ticket, maintenant que les proxmox tournent en version 7 ?

**Comment by cquest** [comment]
Manque osm25...

**Comment by Cyrille37** [comment]
Coucou @cquest 
Du nouveau sur ce ticket ?

**Comment by cquest** [comment]
Non rien et maintenant c'est plus le passage v7 > v8 qui faut organiser !
