### ISSUE TITLE
Réplication bloquée ?

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#358]
Bonjour,
http://download.openstreetmap.fr/replication/merge/france_metro_dom_com_nc/minute/state.txt reste bloqué sur :
`#Mon Mar 14 04:24:02 UTC 2022`
`sequenceNumber=4970883`
`timestamp=2022-03-14T04\:23\:58Z`

merci

**Comment by cquest** [comment]
Débloqué... je ferme

**Comment by vdct** [comment]
merci Christian
