### ISSUE TITLE
Déplacer la VM bzh202 vers PVE XX ?

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#364]
Suite à échange avec @cquest merci de planifier un déplacement de la VM bzh202 vers un nouveau proxmox (je ne sais pas lequel).
L'espace disque est en effet occupé à plein car le script de purge de tuiles s'active très très régulièrement afin de ne pas planter le serveur.

![Capture d’écran 2022-04-24 à 09 45 54](https://user-images.githubusercontent.com/6370443/164965965-97c2ba3f-998f-44ce-8825-ffe67132ad56.png)

Cette demande précède la mise en route de la carte en catalan car une demande a été faite officiellement en ce sens. J'attends aussi le gallo (mais c'est pas mûr).

En parallèle : je me suis résolu à limiter la carte sur l'Europe de l'Ouest cf https://github.com/osm-bzh/osmbr-mapstyle/issues/30
Cette limitation peut se faire après ou avant le déplacement de la VM. De préférence avant mais bon, mes disponibilités sont ce qu'elles sont…

Donc, voici la liste des actions à faire :

- [ ] restreindre l'emprise des rendus (Maël)
- [ ] mettre en prod
- [ ] purger les tuiles
- [ ] arrêter les services
- [ ] déplacer / copier la VM vers ??
- [ ] redémarrer les services
- [ ] modifier les DNS et/ou le frontal nginx (osm25 ?)
- [ ] tester et valider

**Comment by jocelynj** [comment]
@cquest : tu pensais à migrer sur le nouveau cluster TH3 ?

**Comment by MaelREBOUX** [comment]
Je ferme à cause de #465 : de fait : nouvelle VM
