### ISSUE TITLE
cerfificat expiré

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/infrastructure#365]
Le certificat de bano.openstreetmap.fr a expiré le 26/04/2022.

#110

**Comment by csmale** [comment]
Aussi pour download.openstreetmap.fr (osm14.openstreetmap.fr). C'est le même serveur?

**Comment by jocelynj** [comment]
C'est corrigé, merci d'avoir signalé le problème.

Il y avait deux soucis:
  - le passage à Debian 11 a supprimé le binaire "python", et il faut maintenant appeler "python3"
  - bano (et d'autres) a été déplacé de osm11 vers osm14, suite au crash d'osm11. La config dans ansible n'avait pas été mise à jour.

Et oui, bano et download sont sur le même serveur, dans deux containeurs différents.

**Comment by cquest** [comment]
installe le package pythonispython3 (ou un truc du genre)

**Comment by jocelynj** [comment]
J'ai vu que le paquet python-is-python3 existait, mais j'ai hésité à l'installer partout.

**Comment by jocelynj** [comment]
J'ai ajouté `python-is-python3` sur ansible: https://github.com/osm-fr/ansible-scripts/commit/1ce660fc8da31ee6c8a08018dd5e43bc2b99f614
