### ISSUE TITLE
Problème d’accès en ipv6 à polygons.openstreetmap.fr

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#366]
L’accès à `polygons.openstreetmap.fr` depuis un hôte supportant l'ipv6 est très lent.
La connexion est essayée en ipv6 jusqu’à timeout, puis tenté en IPv4 et là ça passe.

```
curl -4 -v -X POST -F refresh=1 http://polygons.openstreetmap.fr/?id=7415
curl -6 -v -X POST -F refresh=1 http://polygons.openstreetmap.fr/?id=7415
```

Problème trouvé par l'outil de contrôle qualité de la configuration d'Osmose sur les id des relations de frontières.
https://github.com/osm-fr/osmose-backend/runs/6237909820?check_suite_focus=true

Si on force l’outil est modifié pour n'utiliser que de l'IPv4 ça enchaîne les demandes de polygones beaucoup plus rapidement.

**Comment by vdct** [comment]
ça me semble similaire au souci que j'ai eu sur Pifomètre : https://github.com/osm-fr/osm-vs-fantoir/issues/162

**Comment by cquest** [comment]
polygons.openstreetmap.fr pointe sur osm14 en IPv4 et IPv6

J'ai aussi un souci IPv6 mais pour accéder à bano.vm.openstreetmap.fr (pour le rendu BANO depuis osm13).

**Comment by jocelynj** [comment]
Pas de souci d'ici pour accéder en ipv6 à polygons, ou à bano.vm.

Vous pouvez confirmer que ça marche de votre côté ?

**Comment by frodrigo** [comment]
C'est bon pour moi depuis osm110.

Par contre depuis github actions, c'est toujours trop lent. C'est peut être autre chose

https://github.com/osm-fr/osmose-backend/runs/6342162195?check_suite_focus=true

**Comment by vdct** [comment]
> Pas de souci d'ici pour accéder en ipv6 à polygons, ou à bano.vm.

le ssh marche pour moi avec l'IP v6 de BANO mais pas via "ssh vdct@bano.vm.openstreetmap.fr". Ca marchait il y a environ 1 mois. Rien de bloquant cependant.

**Comment by jocelynj** [comment]
Bizarre, parce que ls ssh marche de chez moi. Tu peux vérifier que tu n'as pas un ProxyJump ou autre dans ton `.ssh/config`?

**Comment by vdct** [comment]
Et qui c'est qui a raison ? C'est @jocelynj :+1: 
J'avais un proxyjump via osm12. Une fois enlevé, tout fonctionne
