### ISSUE TITLE
Pas d'acces direct osm110 (ipv6 ?) et worker Osmose hors ligne

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#368]
On ne peut plus accéder directement à osm11à en ssh depuis l'extérieur.

```
$ ssh -A osm110.openstreetmap.fr
ssh: connect to host osm110.openstreetmap.fr port 22: No route to host
```

Depuis l'hôte (osm14), on ne peut plus non plus y accéder avec son nom de domaine. Mais ça passe avec l'IP locale
```
ssh 10.1.0.110
```

Buildbot ne peut plus non plus y lancer de worker Osmose. Buildbot n'arrive pas à joindre le worker.
https://buildbot.osmose.openstreetmap.fr/#/workers/8

**Comment by jocelynj** [comment]
J'ai changé les ipv6 et dns de osm110 et download comme suit, avec IP directement sur l'interface vmbr0 du host (connecté directement au switch):
 - osm110: 2a01:e0d:1:c:58bf:fac1::110
 - download: 2a01:e0d:1:c:58bf:fac1::171

En attendant un peu, le ping répond entre les deux machines. On dirait qu'il faut attendre quelques minutes avant de tester, ce que je n'avais pas fait lors de mon test précédent.
