### ISSUE TITLE
Problème accès en ssh au serveur garmin.vm.openstreetmap.fr

### ISSUE THREAD

**Issue by lannic** [osm-fr/infrastructure#369]
Bonjour

Aujourd'hui j'essaye d'envoyer les fichiers Garmin sur le serveur garmin.vm.openstreetmap.fr et ça ne fonctionne pas. Je n'arrive pas à le joindre.

Voici ma ligne de commande :
scp -P 22 /media/disk/www/randonnee/fichiers/gmapsupp.img.zip  /media/disk/www/randonnee/fichiers/gmapsupp_topo.img.zip  lann@garmin.vm.openstreetmap.fr:/data/work/garmin.openstreetmap.fr/garmin-lann/

qui fonctionnait jusqu'au 22 avril 2022

Cependant les anciens fichiers sont toujours disponibles via apache sur le serveur http://garmin.openstreetmap.fr/garmin-lann/

**Comment by jocelynj** [comment]
Ça doit être lié aux soucis qu'on a eu sur le host osm28: je vérifie la config de cette VM.

**Comment by jocelynj** [comment]
DNS mis à jour pour la nouvelle ip 2001:41d0:1008:1f84:1::176.
