### ISSUE TITLE
osm20/osm21 et vm osm200/201/202/205/206/207 osmose backend : problème divers

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#37]
@frodrigo @jocelynj 
- [x] comment accèdent-on aux vm osm200/201/202/205/206/207 ? elles ne sont pas dans le dns.
elles répondent à d'autres hosts ou utilisation de l'ip "en dur" ?
- [x] les hosteurs swappent chaque jour un peu + : > 4Go aujourd'hui
http://munin.openstreetmap.fr/munin-cgi/munin-cgi-graph/osm20.openstreetmap.fr/osm20.openstreetmap.fr/memory-year.png
à cause d'une accumulation de processus 
http://munin.openstreetmap.fr/munin-cgi/munin-cgi-graph/osm20.openstreetmap.fr/osm20.openstreetmap.fr/processes-year.png
En regardant d'un peu plus près, il y a : 
-  plus de 3000 processus sshd en cours d'exécution depuis 2016. les 2/3 sont liés à backuppc. 1/3 est lié à jenkins
- un grand nombre lié à une exécution de nc pour tester le port ssh (une partie semble être lancé par backuppc). un `killall nc` est probablement un bon début :)
- [x] les serveurs n'ont pas redémarré depuis 2 ans. ce qui veux dire que des patchs de sécurités et de performance ne sont pas effectifs.
- [ ] ce serrait peut-être aussi l'occasion de voir pour une maj de l'os (des vm et des hosteurs) et de proxmox

**Comment by jocelynj** [comment]
Concernant ces VMs, elles ne sont effectivement pas accessible directement, parce qu'elles n'ont qu'une IPv4 privée. Comme on ne se sert de ces VMs que pour osmose backend, ce n'est pas vraiment utile d'avoir une ip publique.

Bizarre que sshd ne s'arrête pas tout seul une fois les backups finis... Je vais redémarrer les hosts de suite.

**Comment by Marc-marc-marc** [comment]
j'ai contourné l'absence du dns avec l'option hostname dans .ssh/config pour munin
je pense cependant que ce serrait utile d'ajouter l'i même privée dans le dns, cela simplifierait la config

il ne semble plus y avoir de processus bloqué depuis le reboot

reste les maj (tant sécurité que l'os)

**Comment by jocelynj** [comment]
> je pense cependant que ce serrait utile d'ajouter l'ip même privée dans le dns
Ce n'est pas "autorisé" de mettre une IP privée dans le DNS, et ça ne me plaît pas du tout. On pourrait  éventuellement mettre la même IP dans le DNS pour le host et pour osm20x.

Je lance un `apt-get upgrade`, et je regarde si on peut mettre à jour simplement.

**Comment by jocelynj** [comment]
Les deux machines ont été mises à jour via `apt-get upgrade` et rebootées.

**Comment by jocelynj** [comment]
Pour les souci de ssh, ClientAliveInterval à mettre dans /etc/ssh/sshd_config, sur toutes les machines via le rôle common.

**Comment by Marc-marc-marc** [comment]
suggestion si on est frileux commencer très élevé genre 8h (ce qui coupe après 3x par défaut donc 1j)

**Comment by Marc-marc-marc** [comment]
j'ai mis ClientAliveInterval 28800 (8h) sur les 6 vm en question et tué les 262 procéssus sshd mort (login osmose et backupcc)

**Comment by jocelynj** [comment]
Ces machines ne sont plus actives.
