### ISSUE TITLE
overpass.openstreetmap.fr: redirect causes OSM wiki overload

### ISSUE THREAD

**Issue by mmd-osm** [osm-fr/infrastructure#372]
Since overpass.openstreetmap.fr has been shut down and replaced by a link to the OSM wiki, the load on the wiki has significantly increased to the point that the Wiki is completely unusable at times.

Can you please remove the redirect to the OSM wiki? Thanks!

For reference: https://github.com/openstreetmap/operations/issues/640

**Comment by jocelynj** [comment]
Sorry for the issue. I'm removing the redirect, and we should remove the DNS too.

@cquest : is it fine for you to remove the DNS entry for overpass.openstreetmap.fr?

**Comment by mmd-osm** [comment]
@jocelynj : thanks a lot for the quick follow up. I can already see a significant drop in CPU consumption on the OSM wiki!
