### ISSUE TITLE
Mise à jour Peertube

### ISSUE THREAD

**Issue by gendy54** [osm-fr/infrastructure#373]
Hello,

[La 4.2 de PeerTube est sortie](https://joinpeertube.org/news#release-4.2)

Ce n'est pas pressé, hein ;)

**Comment by vinber** [comment]
et si mise à jour alors penser au module d'édition des sous titres, comme discuté ici https://forum.openstreetmap.fr/t/sous-titrage-des-videos-du-sotm-fr/9205/10?u=vinber

**Comment by jocelynj** [comment]
C'est mis à jour !

**Comment by gendy54** [comment]
Merci Jocelyn ;)

**Comment by gendy54** [comment]
@jocelynj j'ai voulu corriger une coquille orthographique dans une prez et ca m'a fait ca.
![image](https://user-images.githubusercontent.com/10323517/178122534-ab1f5e82-ebcf-4132-b28f-017695d2e346.png)

**Comment by jocelynj** [comment]
Je viens de tester une édition simple, et ça a marché.

En lisant les logs, je pense que tu as fait ton édition pile au moment d'un redémarrage de peertube. Est-ce que tu peux retester?

**Comment by vinber** [comment]
je ne comprends pas comment on fait une édition des sous-titre ?

**Comment by vinber** [comment]
si j'ai trouvé ok, super, cela fonctionne :) merci :)

**Comment by gendy54** [comment]
> Je viens de tester une édition simple, et ça a marché.
> 
> En lisant les logs, je pense que tu as fait ton édition pile au moment d'un redémarrage de peertube. Est-ce que tu peux retester?

Je te confirme que c'est ok. Dommage qu'on n'ai pas pu le en place avant le Sotm, on aurait pu avoir des stats de visionnage intéressantes.
