### ISSUE TITLE
dysfonctionnement couche BANO

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/infrastructure#376]
Bonjour,

Le rendu BANO n'a pas l'air de fonctionner correctement.

Aux zoom 17/18, la couche BANO n'est pas à jour (pas de point vert pour des adresses récemment ajoutées).
et aux zoom 19/20, il y a des erreurs 404 .

Exemple 1 :
Adresse ajoutée ce matin : https://osm.org/node/9824677127
BANO pas à jour (absence point vert) :
    https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.58190/5.27404
Erreur 404 
    https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.58151/5.27351
    tuile http://b.layers.openstreetmap.fr/bano/20/539644/374790.png 

Exemple 2 : 
Adresse ajoutée il y a 4 jours : https://www.openstreetmap.org/node/9815274286
BANO pas à jour (absence point vert)  : 
    https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.60369/5.14495
Erreur 404 : 
    https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#20/45.60363/5.14458
    tuile http://b.layers.openstreetmap.fr/bano/20/539268/374698.png

**Comment by Marc-marc-marc** [comment]
ping @vdct

**Comment by vdct** [comment]
Les 2 adresses données en exemple sont bien présentes dans le contenu BANO, car on les trouve dans les données exportées depuis BANO et disponibles à https://bano.openstreetmap.fr/data/

Extrait de bano-38.csv  :
380530810B-8,8,Route de Saint-Jean de Bournay,38300,Bourgoin-Jallieu,OSM,45.581534,5.2733
385530148H-7,7,Rue du Sorbier,38090,Villefontaine,OSM,45.603492,5.144903

Possible qu'il y ait un souci de génération des tuiles correspondantes ? Ping @cquest

**Comment by Marc-marc-marc** [comment]
peut-être le même soucis que https://github.com/osm-fr/bano/issues/274

**Comment by laurentriffard** [comment]
Bonjour,
La situation des endroits que j'ai signalés a évoluée : les zooms 17, 18, 19 sont maintenant à jour (les points verts correspondant aux nouvelles adresses sont présents), mais le zoom 20 donne toujours des erreurs 404.

**Comment by cquest** [comment]
Un problème d'accès à la BDD BANO a été résolu il y a quelques jours.
Est-ce que le problème persiste actuellement ?

**Comment by laurentriffard** [comment]
Bonjour @cquest,
tout est rentré dans l'ordre : tuiles bano à jour, et plus d'erreur 404.
Merci.
