### ISSUE TITLE
Connection ssh impossible à osmose.vm.openstreetmap.fr

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#377]
Je n'arrive pas à me connecter à la vm du frontend d'osmose depuis plusieurs jours.
Ne marche pas en direct ou par rebond. Ça se termine en timeout.

**Comment by jocelynj** [comment]
C'est réparé, et c'était causé par un souci de connectivité ipv6 sur le host (même souci que sur #375)

Deplacer les ipv6 des containeurs sur l'interface réseau vmbr1 devrait corriger ce genre de souci.
