### ISSUE TITLE
Cyclosm est en rade non ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#378]
Suite à un mail sur contact@ le 18/06 j'ai testé cyclosm.org, après avoir zoomé et dézoomé un peu, c'est tout gris.

F12 dans firefox me dit plein de truc en rouge

![image](https://user-images.githubusercontent.com/890869/175808478-9df58b81-eb34-4ff0-a3b4-151b784cfb6d.png)

**Comment by vinber** [comment]
le mail 
> Are you aware that cyclosm gives a lot of 502 Bad Gateway errors even for normal tile requests?
> I believe the proxy timeout shall be raised a bit, seems to abort after just a few seconds.

**Comment by JacLavi** [comment]
CyclOSM est très connu et apprécié du monde cycliste mais sa réputation commence à souffrir de ses disfonctionnements à répétition. Et ce depuis le début.

**Comment by grinapo** [comment]
S'il vous plaît, ne soyez pas négatif. Donnez à l'administrateur une chance de résoudre ce problème, probablement un simple paramètre de configuration.

**Comment by vinber** [comment]
Bonjour @grinapo, je ne pense pas que l'objectif est d'être négatif, au contraire c'est parce que j'aime beaucoup le rendu cyclosm que j'ai envie qu'il fonctionne au mieux.

j'ai l'impression que cela tourne mieux, j'ai moins de carré gris. je ferme pour l'instant
