### ISSUE TITLE
Une VM pour "OSM Notes Heatmap"

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#379]
Bonjour,

Nous avons pondu le p'tit outil "[osm notes heatmap](https://demo-osm.comptoir.net/public/?pos=46.06,0.75,7)" suite à la discussion "[Gestion des notes (les fermer, les taguer, les documenter) ](https://forum.openstreetmap.fr/t/gestion-des-notes-les-fermer-les-taguer-les-documenter/8946)".

Serait-il possible de l'héberger sur une VM de l'infra OSM_FR ?
- Php 7 ou 8+
- Mariadb 10.5+!
- crontab

**Comment by jocelynj** [comment]
Pas besoin de docker du coup ?

**Comment by Cyrille37** [comment]
À priori pas de docker, mais si ça arrange je peux faire un docker-compose. Dis moi ce que tu préfères.

**Comment by jocelynj** [comment]
Je préfére largement sans docker :) 

Je te crée la VM sous peu.

**Comment by jocelynj** [comment]
Container accessible en ipv6 sur notes-heatmap.vm.openstreetmap.fr, et je t'ai créé un compte cgiquello.

Pour le site web, on voudrait quoi comme adresse ?

**Comment by Cyrille37** [comment]
Merci!
Tout simplement 
notes-heatmap.openstreetmap.fr
:-)
-- 
Cyrille Giquello, Artéfacts, Tours, FR37, Europe, Earth-A
Envoyé d'un pouce en mobilité, veuillez excuser ma brièveté ;)
Logiciel courriel "k9-mail"

Le 28 juin 2022 22:35:00 GMT+02:00, jocelynj ***@***.***> a écrit :

**Comment by Cyrille37** [comment]
Penser à la mise à jour du wiki https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France

**Comment by Cyrille37** [comment]
@jocelynj Mon auth sur la VM demande un password.

Ma clé publique est sur osm28 dans /home/cgiquello/.ssh/authorized_keys

**Comment by jocelynj** [comment]
Cette clé est déjà présente sur la VM. Tu peux vérifier que tu lances bien "ssh -A" pour propager les clés à travers le proxy osm28 ?

**Comment by Cyrille37** [comment]
Ah! Ça fonctionne depuis chez moi :-)
*Désolé, je m'étais connecté directement sur osm28, et du coup y avait pas ma clé privé :-)*

**Comment by Cyrille37** [comment]
@jocelynj Du coup il faut mettre à jour https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France ?
Je peux le faire si tu me dis sur quel host est la VM.
Dis moi :-)

**Comment by jocelynj** [comment]
La VM est sur osm28, si tu peux mettre à jour le wiki, merci d'avance.

Et http://notes-heatmap.openstreetmap.fr/ est maintenant configuré, en http et https.

**Comment by Cyrille37** [comment]
Merci @jocelynj c'est parfait <3

J'ai fini la configuration, me reste à monter les données.

**Comment by Cyrille37** [comment]
Bon ben ça tourne impeccable :-)
