### ISSUE TITLE
installation application PetiteReine

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#38]
Hello,

Je souhaite maintenir l'application petiteReine initialement écrite par Emmanuel Dewaele https://github.com/Cyrille37/petiteReine

- clé ssh: déjà sur cgiquello@osm101 et cgiquello@osm102
- language : Php
- database : Postgis
- volume : petit
    - files : 1 ou 2 Go
    - db : quelques milliers de poi (parkings vélo) segmentés par commune, mais pour commencer il n'y aura pas beaucoup de communes
- nom de domaine : petiteReine.openstreetmap.fr

Copie d'écran: https://image.slidesharecdn.com/sotmfr2018politiquedelavillecartographieparticipative-180603094058/95/sotmfr2018-politique-de-la-ville-cartographie-participative-8-638.jpg?cb=1528018986

related: https://github.com/edewaele/petiteReine/issues/6

**Comment by Cyrille37** [comment]
Est-ce que je passe le code sur le github osm-fr (tech: *j'ai les droits*) ou il reste sur mon compte Cyrille37 ? Perso je préfère le passer sur le github osm-fr.

**Comment by jocelynj** [comment]
Je vais te créer la VM.

Pour passer le code sur le github d'osm-fr, c'est à toi de voir - je pense qu'on peut laisser sur ton compte, et migrer sur osm-fr si tu veux passer la main à d'autres mainteneurs ?

**Comment by jocelynj** [comment]
La VM est disponible sur osm157.openstreetmap.fr (ou 2001:41d0:1008:2c6b:1::157). Je t'ai mis ta clé ssh, et petitereine.openstreetmap.fr est déjà configuré sur le proxy.

**Comment by Cyrille37** [comment]
Merci! Je lance l'installation de petiteReine.

**Comment by Cyrille37** [comment]
```
sudo apt-get update
sudo apt-get upgrade
sudo reboot
sudo apt-get install postgresql-9.6-postgis-2.3
```

**Comment by Cyrille37** [comment]
Je n'arrive pas à créer un utilisateur dans postgresql pour l'application. Utilisateur créé mais connection refusée

La commande `$ psql -U petiteReine -d petiteReine -h localhost` donne dans `/var/log/postgresql/postgresql-9.6-main.log` : 
```
2018-06-04 05:43:56.389 UTC [18388] petiteReine@petiteReine FATAL:  password authentication failed for user "petiteReine"
2018-06-04 05:43:56.389 UTC [18388] petiteReine@petiteReine DETAIL:  User "petiteReine" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
```
pour info:
```
$  psql -x -c "select * from pg_user where usename='petiteReine'"
-[ RECORD 1 ]+------------
usename      | petiteReine
usesysid     | 18011
usecreatedb  | f
usesuper     | f
userepl      | f
usebypassrls | f
passwd       | ********
valuntil     | 
useconfig    | 
```

Configuration d'origine `/etc/postgresql/9.6/main/pg_hba.conf` :
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
```

**Comment by MaelREBOUX** [comment]
Si ça peut aider (c'est une Ubuntu 16.04) :
- https://github.com/osm-fr/infrastructure/issues/18#issuecomment-348807257
- https://github.com/osm-fr/infrastructure/issues/18#issuecomment-377776713

pghba.conf identique à priori

**Comment by Cyrille37** [comment]
Je pense avoir trouvé le problème de connexion.
J'ai créé un user system du même nom que le user postgres, on dirait que ça met l'embrouille.
Là je viens de créer un utilisateur qui n'existe pas sur le système et je n'ai pas d'erreur de "mot de passe non assigné"

**Comment by Cyrille37** [comment]
ça fonctionne :-)
http://petitereine.openstreetmap.fr/

**Comment by Cyrille37** [comment]
Merci la communauté pour les coups de main
