### ISSUE TITLE
plus d'accès osm157 (sur osm28) pour "petitereine"

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#380]
Bonjour

Le site "[petitereine](https://petitereine.openstreetmap.fr/)" fonctionne bien mais je n'ai **plus accès à osm157** pour faire une mise à jour.

```
ssh -t -A cgiquello@osm28.openstreetmap.fr ssh cgiquello@osm157.openstreetmap.fr
ssh: connect to host osm157.openstreetmap.fr port 22: No route to host
Connection to osm28.openstreetmap.fr closed.
```

**Comment by jocelynj** [comment]
Je viens de mettre à jour l'ipv6 d'osm157, et j'ai aussi changé la configuration d'osm27. Ça devrait maintenant marcher - reste à savoir si la config ipv6 du host est la bonne...

**Comment by Cyrille37** [comment]
Parfait ! Merci @jocelynj
