### ISSUE TITLE
taginfo.openstreetmap.fr - Nombre limité de clés

### ISSUE THREAD

**Issue by PtiBzh** [osm-fr/infrastructure#383]
Le service https://taginfo.openstreetmap.fr affiche un nombre limité de clés depuis aujourd'hui (2022-07-11), le top 10 des clés connues sont actuellement :

Clé | Objets | Nœuds | Chemins | Relations | Utilisateurs | Wiki | Projets | Valeurs | Valeurs les plus fréquentes
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
4C:PK_UID | 8 530  | 0 | 8 530 | 0 | 176 | - | 0 | 7 889 | no values with more than 1%
4C:TYPE_VOIE | 8 530 | 0 | 8 530 | 0 | 176 | - | 0 | 12 | Locale • Regionale • Chemin • 99 • Chemin␣empierre • Sentier
4C:ID_VOIE | 7 004 | 0 | 7 004| 0 | 159 | - | 0 | 2 226 | no values with more than 1%
4C:ID_TRON | 7 000 | 0| 7 000 | 0 | 158 | - | 0 | 6 470 | no values with more than 1%
3dr:type | 1 218 | 2 | 1 213 | 3 | 90 | ✔ | 2 | 46 | 0.0 • 2.0 • 2.2 • 2.4 • 9.0
4wd_only | 63 | 3 | 60 | 0 | 38 | ✔ | 3 | 3 | no • yes • recommended
2 | 33  | 325 | 1 | 0 | 2 | - | 0 | 17 | tilleul • robinier • pin • érable • peuplier␣blanc • frene • pyracantha • 3 • cotoneaster • Pin
3dr:height1 | 14  | 0  | 14 | 0 | 5 | - | 1 | 8 | 3 • 6 • 0.05 • 4.3 • 4.5 • 2.1 • 1.5 • 3.4
3dr:roof | 14 | 0  | 14 | 0 | 2 | - | 1 | 2 | 2.0 • 2.4
1 | 13 | 111 | 2  | 0 | 2 | - | 0 | 9 | Olivier • cerisier • yes • prunier • amandier • noisetier • prune • abricot • bambous
3dr:length1 | 11 | 0  | 11 | 0 | 4 | - | 0 | 7 | 1.3 • 5.2 • 8 • 2 • 2.9 • 4.7 • 6.9
3dr:direction | 8 | 81 | 0 | 0  | 4 | - | 0 | 2 | end • begin
3dmr | 7 | 0 | 7 | 0 | 4 | ✔ | 1 | 7 | 4 • 9 • 17 • 19 • 18 • yes • 16
2024olympicgames | 5 | 0 | 5  | 0 | 2 | - | 0 | 1 | venue
3dr:length2 | 4 | 0 | 4 | 0 | 2 | - | 0 | 4 | 5.2 • 1.9 • 2.4 • 1.6
3dr:canopy | 4 | 0 | 4 | 0 | 1 | - | 0 | 1 | 3

**Comment by Marc-marc-marc** [comment]
l'extrait sur le serveur est corrompu
j'ai relancé un téléchargement de l'extrait complet

**Comment by Marc-marc-marc** [comment]
j'ai mis du code debug un peu partout (fichier count-key.sh), trouvé le bout de code qui semble étonnement casser quelques chose, ai j'ai désactivé cette partie le temps de comprendre
cela semble avoir produit un résultat "normal" cette nuit, à suivre...

**Comment by jocelynj** [comment]
Tu voudrais dire que l'extrait n'était en fait pas corrompu ? Ou y a t'il un second problème ?

**Comment by Marc-marc-marc** [comment]
l'extrait sur le serveur était corrompu
le lendemain, après ajout du débug, le résultat était normal (= non corrompu)
cela ne s'est plus reproduit depuis.
