### ISSUE TITLE
Osmose : installer un cache pour l'acces aux tuiles Mapillary

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#385]
Aujourd’hui on fait l’accès aux tuiles vectorielles de Mapillry depuis chaque machine qui font tourner les analyses.

Problème :
- Le téléchargement des tuiles est lent et il y a en a beaucoup (z14)
- Si une zone n'est pas ré-executé sur la même machine, ça re-élécharge pour refaire un cache local

On peut obtenir un accès accéléré en fournissant une IP à Mapillary.

Proposition : installer un proxy-cache pour les tuiles Mapillary (nginx ou autre).

Dans un second temps l'on pourrait y déporter avec la conversion des tuiles par zones en CSV.

**Comment by jocelynj** [comment]
VM créé sur proxy.osmose.vm.openstreetmap.fr, sur osm34. Il me faut encore configurer nginx pour cacher mapillary

**Comment by jocelynj** [comment]
Proxy en place sur http://proxy.osmose.openstreetmap.fr/

**Comment by frodrigo** [comment]
J'ai un problème d'acces depuis osm110

```
fred@osm110:~$ curl https://proxy.osmose.openstreetmap.fr
curl: (60) SSL: no alternative certificate subject name matches target host name 'proxy.osmose.openstreetmap.fr'
```

et depuis osmose
```
2022-08-18 14:29:44         raise SSLError(e, request=request)
2022-08-18 14:29:44     requests.exceptions.SSLError: HTTPSConnectionPool(host='proxy.osmose.openstreetmap.fr', port=443): Max retries exceeded with url: /maps/vtp/mly_map_feature_point/2/14/8529/5973/?access_token=MLY%7C3804396159685239%7Cc5712d0fb9ef5d4dfef585154b00ffa7 (Caused by SSLError(CertificateError("hostname 'proxy.osmose.openstreetmap.fr' doesn't match 'wms.openstreetmap.fr'")))
```

**Comment by jocelynj** [comment]
Je viens d'activer https - je ne l'avais pas fait en me disant qu'on pouvait accéder à ces tuiles en http sur le proxy.

**Comment by frodrigo** [comment]
Fait. Mais on a ensuite desactivé tout Mapillary dans Osmose. Comme tout passe par le proxy et que coté Mapillary pas de nouvelle du whitelist du proxy c'est plus lent.
