### ISSUE TITLE
Umap, une carte ne répond pas

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#387]
en lien avec la discussion sur le forum https://forum.openstreetmap.fr/t/jai-cree-5-cartes-umap-une-ne-fonctionne-plus-pourquoi/9273

Ma demande ici est de savoir ce que je peux faire pour aider à identifier le problème pour cette carte http://umap.openstreetmap.fr/fr/map/tremblement-de-terre-du-23-fevrier-1887-patrimoine_622500#7/43.720/9.229

Quel outil et diagnostic pour identifier le problème :)

**Comment by vinber** [comment]
je regarde avec l'outil de console de firefox, les calques semblent pas en forme

![image](https://user-images.githubusercontent.com/890869/180227854-7ee88f07-632f-4f72-8d10-eb7d53252ec8.png)

d'autres moyens de comprendre le bug ?

**Comment by jocelynj** [comment]
@cquest : est-ce que ça pourrait être des couches qui ont été supprimés par erreur lors du nettoyage de printemps ?

**Comment by cquest** [comment]
La carte semble fonctionner correctement, donc je ferme.
