### ISSUE TITLE
Fond de carte Cyclosm marche mal (erreurs 504 et 404)

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/infrastructure#388]
Bonjour,

Le fond de carte Cyclosm s'affiche mal, génère beaucoup d'erreur HTTP 404 et 504, sur les zooms 17 et plus, dans les zones avec modifications récentes.

Exemple : https://www.cyclosm.org/#map=18/45.60654/5.14902/cyclosm

![image](https://user-images.githubusercontent.com/25233732/182098913-3f91d0ba-3598-4d92-adf3-742cabccbec5.png)

**Comment by JacLavi** [comment]
Vu de ma lorgnette : certaines tuiles ne montent que très lentement quand on zoome (par ex. de 15 à 16) Fréquemment observé par le passé.

**Comment by Cyrille37** [comment]
Annoncé sur tech@listes.openstreetmap.fr :
> J'ai plusieurs remontées récemment sur les performances du rendu CyclOSM et l'affichage de tuiles grises.

**Comment by jocelynj** [comment]
J'ai l'impression que la connection réseau vers osm11 (qui héberge le rendu cyclosm) a du mal, et ça explique les soucis de perfs vus. ping @cquest 

Ce que j'ai changé pour le moment:
  - augmentation de proxy_connect_timeout de 10s à 20s sur le proxy osm24
  - redémarrage de la VM du rendu cyclosm

**Comment by laurentriffard** [comment]
Bonjour,
voici un état des lieux à ce jour (18 août, 9h00) : 
- les zooms jusqu'à 17 fonctionnent correctement, la génération de tuile peut être lente, mais cela s'affiche.
- La génération de tuiles aux niveaux 18 et 19 est assez  lente, et produit des erreurs 504 sur certaines tuiles au bout de 20 secondes (la page s'affiche sans messages d'erreur, mais avec des zones grises). Si l'on rafraîchit la page une minute plus tard, l'affichage est bon.

**Comment by Cyrille37** [comment]
Huston, ya un problème : **SSL_ERROR_BAD_CERT_DOMAIN**

https://dev.a.tile.openstreetmap.fr/cyclosm/10/522/351.png

**Comment by laurentriffard** [comment]
À ce jour, je ne constate plus d'erreurs 504 et 404.
