### ISSUE TITLE
Layers noname and oneway are gone forever?

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#389]
The layers "Sans nom" (noname) and "Sans oneway" from http://layers.openstreetmap.fr/ are no more available.

There are also listed on Osmose-QA.

The layers will be available again or not ?

**Comment by frodrigo** [comment]
It is back.
Thank.

**Comment by jocelynj** [comment]
Layers are now generated from TH3 cluster. They were previously on osm13, which had a hardware issue earlier this year, and all layers weren't reinstalled when it was moved to @cquest's house for investigation.
