### ISSUE TITLE
erreur sur peertube

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#39]
Lorsque je lance une vidéo sur peertube, j'ai régulièrement l'erreur suivante

![peertube](https://user-images.githubusercontent.com/890869/41119322-d23f0804-6a92-11e8-8a97-71d5856c98ce.png)

**Comment by jocelynj** [comment]
Je crois avoir trouvé: il faut lancer cette commande pour regénérer les .torrent:
```
cd ~peertube/peertube-latest
NODE_CONFIG_DIR=/data/project/peertube/config/ NODE_ENV=production npm run update-host
```

**Comment by jocelynj** [comment]
J'ai aussi changé la config nginx pour pointer vers 127.0.0.1 au lieu de locahost, parce que je voyais des erreurs nginx d'erreur de connection vers ::1. Et mis à jour vers la dernière version de peertube.

**Comment by vinber** [comment]
pour le moment l'erreur persiste de mon coté :) mais je ne sais pas si les 2 commentaires précédents devaient résoudre ou plutôt qui "devrait" lancer la commande pour regénérer les torrents ?

**Comment by jocelynj** [comment]
Oui, je sais que ça plante encore :(
J'ai juste référencé ce que j'ai essayé.

**Comment by vinber** [comment]
c'était pas un "reproche" hein :)

**Comment by jocelynj** [comment]
Bon, c'est corrigé en modifiant la config du proxy qui tape sur peertube avec ce morceau:
https://github.com/osm-fr/ansible-scripts/commit/f39d30eae1102a0afc024ab9e8bcd67168ec4def
