### ISSUE TITLE
La couche BANO ne s'affiche pas (erreur 404 sur les tuiles)

### ISSUE THREAD

**Issue by laurentriffard** [osm-fr/infrastructure#391]
Bonjour,

Je constate un dysfonctionnement de la couche BANO, au moins depuis hier mercredi 17 août.

URL d'exemple : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#16/45.5633/5.2286

Constat : le fond de carte osm-fr s'affiche correctement, mais la couche BANO est complètement absente.
L'appel aux tuiles BANO (ex : https://a.layers.openstreetmap.fr/bano/16/33719/23428.png) produit systématiquement une erreur HTTP 404.

**Comment by jocelynj** [comment]
C'est lié au rétablissement des autres couches layers, sur #389. Je vais regarder si on peut activer cette couche sur le serveur de rendu TH3.

**Comment by jocelynj** [comment]
J'ai copié la précédente config sur le nouveau serveur, et le calque bano remarche, mais lentement, vu que la base de donnée n'est pas sur le même cluster que le rendu.

@cquest : pour info, j'ai enlevé le calque "voie_nommee", qui dépend d'une base postgres sur localhost.

**Comment by laurentriffard** [comment]
Ça fonctionne à nouveau, avec des temps réppnse satisfaisant pour moi.
Merci !

**Comment by marius851000** [comment]
Bonjour. Il se trouve que les performance sont intenable, au point où le serveur retourne un 404 à certaines ocasion. Par exemple b.layers.openstreetmap.fr/bano/12/2073/1408.png à retourné 404 pour les premiers essaie, puis renvoie la tuile.

(et y’a aussi le problème que 404 n’est probablement pas le code d’erreur approprié, mais qu’importe)
