### ISSUE TITLE
La couche BANO ne fonctionne pas partout (erreur 404)

### ISSUE THREAD

**Issue by elmevess** [osm-fr/infrastructure#392]
Bonjour, je remarque des endroits où les tuiles ne se chargent pas comme ici: https://www.openstreetmap.org/#map=19/45.51027276769676/4.8683046220028094, ou encore ici https://www.openstreetmap.org/#map=18/45.49428/4.80355
Pouvez vous confirmer qu'il s'agit bien de la couche BANO et non pas de mon JOSM ou ID ?
![2022-08-22 09_42_48-_ Éditeur Java OpenStreetMap](https://user-images.githubusercontent.com/111694298/185866711-9cf42553-4ca5-4016-b77f-7c0c8121a14a.png)
Elle fonctionne parfaitement dans d'autres zones pour moi.

**Comment by jocelynj** [comment]
Ça pourrait être lié à #391.

@elmevess : est-ce que tu pourrais retrouver le lieu en question sur https://tile.openstreetmap.fr/~cquest/leaflet/bano.html, et donner l'url ?

**Comment by elmevess** [comment]
https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#17/45.48914/4.80994
Ici ça ne marche pas à partir de ce niveau de zoom
https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.50792/4.86025
Et là ça a l'air en ligne

**Comment by jocelynj** [comment]
Le serveur de rendu renderd avait été tué par un OOM-kill, et non redémarré par systemd. Je viens de le redémarrer.

On devait avoir encore des tuiles dispo sur le cache, ce qui explique que certaines tuiles s'affichaient encore.

**Comment by jocelynj** [comment]
J'ai changé la config systemd comme suit:
```
Restart=always
RestartSec=30s
RuntimeMaxSec=7d
```

**Comment by elmevess** [comment]
ça fonctionne à nouveau de mon côté, le temps de réponse est bon. Je ferme le billet ou on attend quelque jours ?

**Comment by elmevess** [comment]
https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.44558/4.72156
https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/45.43018/4.70581
La couche n'apparait plus à certains niveaux de zoom de mon côté

**Comment by adrienandrem** [comment]
Bonjour, de mon coté même la racine retourne l'erreur 404 :  
https://tile.openstreetmap.fr/~cquest/leaflet/bano.html

**Comment by adrienandrem** [comment]
L'adresse est pourtant toujours mentionnée [sur le wiki](https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO#M%C3%A9thode_pr%C3%A9conis%C3%A9e_pour_corriger_les_erreurs_dans_le_rendu_BANO).

**Comment by jocelynj** [comment]
En théorie, on devrait retrouver la même chose ici: https://layers.openstreetmap.fr/?zoom=6&lat=46.4&lon=5.09738&layers=B000000000FFFFFFFFFFFFFFFFFFFFFFFFT

Tu peux confirmer ? Et on mettre à jour le wiki après.

**Comment by Marc-marc-marc** [comment]
>  retourne l'erreur 404 : https://tile.openstreetmap.fr/~cquest/leaflet/bano.html

j'ai fais une redirection de cet url vers son emplacement OL réel
pour mémoire osm12 CT tile (lui meme inbriqué dans CT hdm)
```
    location /~cquest/leaflet/bano.html {
        return 301 https://layers.openstreetmap.fr/?layers=B000000000FFFFFFFFFFFFFFFFFFFFFFFFT;
    }
```

il faudra dans une prochaine itération déinbriquer le CT hdm du CT tile
