### ISSUE TITLE
Changement IP enedis.osm.fr

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#393]
Bonsoir :)

Dans l'attente que je m'occupe du nécessaire sur #356, mon hébergeur actuel a du changer d'IP la machine qui héberge actuellement le suivi enedis.

Est-ce que possible de changer le record A sur enedis.openstreetmap.fr <=> 154.49.219.152 s'il vous plaît ?

Bonne soirée

**Comment by jocelynj** [comment]
Je viens de changer l'ipv4.

Est-ce que je dois changer l'ipv6 ?

**Comment by flacombe** [comment]
Rapide !
Merci beaucoup

Non l'IPv6 reste la même, j'ai d'ailleurs un soucis à régler dessus, ca n'a pas l'air de fonctionner dessus.
