### ISSUE TITLE
Tianxin and Efeng are not rendered in green on the admin_level=8 style, it is a data problem, please close it.

### ISSUE THREAD

**Issue by qa003qa003** [osm-fr/infrastructure#394]
I really want to find the reason, it is a data problem, please close it.

**Comment by Marc-marc-marc** [comment]
osmose is a quality analysis tool. it does not render.
the rendering comes from other sources and a rendering problem is not an osmosis problem.
for the 2 names, it is convenient to have the url to the osm object
Tianxin https://www.openstreetmap.org/relation/9299808
Efeng https://www.openstreetmap.org/relation/9287318
I don't see a data problem, maybe a bug on the renderer

**Comment by jocelynj** [comment]
Link to the issue: http://layers.openstreetmap.fr/?zoom=12&lat=28.10727&lon=114.56979&layers=B000000000FFFFFFFFFFFTFFFFFFFFFFFFF

**Comment by jocelynj** [comment]
I think it is a tile expiration issue following osm data changes, as regenerating the tiles with /dirty shows these relations correctly.

**Comment by Marc-marc-marc** [comment]
found https://www.openstreetmap.org/way/667817239 today
https://www.openstreetmap.org/changeset/125508471 Repair of broken administrative boundaries
