### ISSUE TITLE
Osmose: Aquilenet pas acces a de l'ipv4

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#397]
Une analyse Osmose pour l'Espagne télécharge sur centrodedescargas.cnig.es, en ipv4 uniquement.
Ça ne marche pas depuis Aquilenet.

Il doit manque un tunnel.

**Comment by jocelynj** [comment]
J'ai ajouté le tunnel.

Pour info:
  - sur osmose-aquilenet:
    - modif de /etc/hosts pour mettre centrodedescargas.cnig.es sur 127.0.1.103
    - script dans /root/osmfr/6tunnel-cron.sh qui lance un tunnel vers osm26
  - sur osm26:
    - ajout de 2001:41d0:1008:1f65:10::104 dans /etc/network/interfaces
    - script dans /root/osmfr/6tunnel-cron.sh pour lancer un tunnel
