### ISSUE TITLE
http://export.openstreetmap.fr H.S.

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#40]
Salut
L'url http://export.openstreetmap.fr/contours-administratifs/communes/ ne répond plus.
Cheers.

**Comment by jocelynj** [comment]
export n'a pas été réactivé depuis quelques années, parce qu'il n'y avait pas de demande.

Pour les limites de communes, ça peut maintenant se trouver sur https://www.data.gouv.fr/fr/datasets/decoupage-administratif-communal-francais-issu-d-openstreetmap/. Est-ce que ça conviendrait ?

**Comment by frodrigo** [comment]
@Cyrille37 C'est bon pour toi, on peut fermer l'issue ?

**Comment by frodrigo** [comment]
Réouvrir si besoin.
