### ISSUE TITLE
Osmose – Accès à de l’IPv4 depuis des VM en IPv6 uniquement

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#402]
Certains backends Osmose (aquilenet hivane) sont sur des VM uniquement en IPv6, mais des ressources sont sur des portails en IPv4 uniquement (comme data.gouv ou l'IGN espagnol, sentry ou github).

C'est aujourd’hui géré par des tunnels par nom d'hôte. En plus d'être spécifique, il arrive de perdre les tunnels.

Idées de solutions :
- Reverse proxy nginx
- Véritable Proxy HTTP (à l'ancienne)
- Nat64
- VPN

**Comment by jocelynj** [comment]
J'ai installé wireguard entre aquilenet/hivane1/hivane2 vers proxy.ovh.vm.openstreetmap.fr, limité aux ipv4 nécessaires pour Osmose. Normalement, ça devrait être plus robuste, tant que le DNS de cette VM est changée lors de migration sur un nouvel host.
