### ISSUE TITLE
OSM Data HS :(

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#404]
Tout est dans le titre, le site OSM Data est HS et du coup, je ne peux pas faire manipuler les élèves dessus :sob: 

https://demo.openstreetmap.fr/map

Merci !!

**Comment by bristow** [comment]
Oh, c'est l'issue #404 :)

**Comment by TANK2003** [comment]
C'est resolu

**Comment by bristow** [comment]
Merci @TANK2003 ; à temps pour le 2è groupe :)
