### ISSUE TITLE
Erreurs 500 sur osmose.openstreetmap.fr/api/

### ISSUE THREAD

**Issue by JackNUMBER** [osm-fr/infrastructure#405]
Hello!
L'API d'Osmose renvoi des 500 ([exemple](https://osmose.openstreetmap.fr/api/0.3/issue/18d63e02-a526-63e4-8067-46024128062a))  qui rendent le front inopérant ([exemple](https://osmose.openstreetmap.fr/en/map/#zoom=12&lat=48.0181&lon=7.3865&item=5010%2C5030%2C5080&level=1&tags=&issue_uuid=18d63e02-a526-63e4-8067-46024128062a)).

Une idée d'où cela peut-il venir ?
Merci !

Relai de https://forum.openstreetmap.fr/t/osmose-est-casse/10750

**Comment by frodrigo** [comment]
Peut-être un problème temporaire. Là ça marche.

**Comment by JackNUMBER** [comment]
> Peut-être un problème temporaire. Là ça marche.

L'erreur est toujours présente sur les liens que j'ai donné dans mon premier post, mais pas sur d'autres. Il y a du cache coté serveur ?

**Comment by frodrigo** [comment]
Nouveau problème de corruption de la base, mais situation différente
https://github.com/osm-fr/osmose-frontend/issues/401

**Comment by frodrigo** [comment]
Fix: https://github.com/frodrigo/osmose-frontend/commit/c45a8689b59d61b79b6c30c1ba9ec4e93704d745

Fixes corrompus
```sql
select count(*) from markers where fixes IS NOT NULL AND fixes = elems
```
=> 3 514 792

Correction: suppression de la base des fix corrompus (ils reviendront au fur et a mesure)
```sql
UPDATE markers SET fixes = NULL WHERE fixes IS NOT NULL AND fixes = elems;
```

**Comment by Bibi56** [comment]
@JackNUMBER pour le second exemple c’est souvent que l’erreur a disparu (JSON.parse: unexpected character at line 1 column 1 of the JSON data signifie alors que le serveur n’a rien rendu.
@frodrigo je remarque que sur le second exemple, seule la partie française est en erreur. Tu l’as peut-être déjà remarqué mais au cas où ça peut-être un indice.

**Comment by frodrigo** [comment]
La correction des données en base n'a toujours pas pu passer, je vais ressayer plus tard ce soir avec moins de charge serveur.

**Comment by frodrigo** [comment]
Correction sur la base passé par un arrêt complet d'Osmose.

```sql
UPDATE
    markers
SET
    fixes = NULL
WHERE
    fixes IS NOT NULL AND
    fixes = elems
```

Il n'en restait déjà pus que 2 627 978.
