### ISSUE TITLE
Nextcloud est tombé ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#41]
C'est peut-être les travaux sur les serveurs, dans ce cas désolé pour ce signalement !!!
Sinon si ce n'est pas les travaux, nous avons actuellement : 502 Bad Gateway
nginx/1.6.2

**Comment by althio** [comment]
c'est plus étendu :
le site internet sotm http://sotm2018.openstreetmap.fr/
l'interface des listes listes.openstreetmap.fr
l'instance peertube peertube.openstreetmap.fr
nextcloud
...

tout cela ne répond pas, ou erreur 502

**Comment by jocelynj** [comment]
Ce sont effectivement les travaux sur les serveurs qui causent ce souci - ça devrait repartir sous peu.

**Comment by jocelynj** [comment]
C'est reparti maintenant :)

**Comment by vinber** [comment]
merci
