### ISSUE TITLE
Mettre à jour PHP pour le wordpress d'osm.fr

### ISSUE THREAD

**Issue by overflorian** [osm-fr/infrastructure#412]
Hello, je viens de réaliser 14 MAJ sur le wordpress d'openstreetmap.fr : les modules et Wordpress en lui-même.
Le dashboard indique le message suivant : "Votre site fonctionne sur une version obsolète de PHP (7.3.31-1~deb10u2), qui ne reçoit pas les mises à jour de sécurité. Une mise à jour est nécessaire."

Est-ce que quelqu'un pourrait s'en occuper svp ? Ce n'est pas urgent mais d'expérience il ne vaut mieux pas laisser trop longtemps trainer ça, merci par avance

**Comment by jocelynj** [comment]
@overflorian: wordpress ne se met pas à jour tout seul ?  Je croyais que cette option était activée.

Je m'occupe de la mise à jour de la VM vers debian bullseye, ce qui permettra de passer à php 7.4.

**Comment by jocelynj** [comment]
Mise à jour effectuée. Par rapport à un upgrade "classique", j'ai du ajouter cette commande pour conserver la base de donnée mariadb: `apt install mariadb-client mariadb-server`

**Comment by overflorian** [comment]
Super, merci.
Je viens d'activer les MAJ automatiques, on n'avait pas coché, en effet.
