### ISSUE TITLE
Installer un plugin nextloud

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#417]
une proposition est faite de tester cette extension https://forum.openstreetmap.fr/t/cartographie-des-acteurs-de-lenvironnement-historique/12204/2

est-ce possible d'installer ceci https://github.com/jgraph/drawio-nextcloud

**Comment by cquest** [comment]
Je viens d'installer ce plugin.

**Comment by overflorian** [comment]
Hello, je relance ce projet, @cquest comment puis-je accéder à ce plugin stp ? Sera-t-il possible de créer des diagrammes modifiables par tous (sans même qu'il faille créer un compte Nextcloud) ?
Merci
