### ISSUE TITLE
taginfo.openstreetmap.fr - Le graphiques ne sont plus mis à jour depuis (environ) mi-2022

### ISSUE THREAD

**Issue by PtiBzh** [osm-fr/infrastructure#418]
Sur le site taginfo.openstreetmap.fr, les graphiques plafonnent depuis quelques mois (environ mi-2022).
Exemple : https://taginfo.openstreetmap.fr/tags/building=service#chronology
![Screenshot from 2023-01-29 15-46-51](https://user-images.githubusercontent.com/3416635/215334486-7f7a3c63-1ccd-41ab-8ea7-73fdbb23f81f.png)

**Comment by jocelynj** [comment]
En fait, je crois que @Marc-marc-marc avait testé d'ajouter ces graphes avec un .pbf chronologique, mais a eu des problèmes pour les mises à jour suivantes. Du coup, on est revenu à un .pbf standard. Je ne pensais pas que la chronologie resterait.

**Comment by Marc-marc-marc** [comment]
dans les outils utilisé, osmconvert (utilisé pour le clipping sur la frontière) ne gère pas les osh -> remplacé par osmium
on utilise aussi osmfilter (filtre des metas et des relations admins des pays limitrophes) -> désactivé pour le moment, moins important dans la partie graphique historique des tags
j'ai activé la maj automatique du osh, à voir ce que cela donne

**Comment by PanierAvide** [comment]
Côté projet du mois, on utilise osmupdate + osmium pour compléter le fichier OSH.PBF de Geofabrik avec les fichiers diffs : https://github.com/vdct/ProjetDuMois/blob/master/db/10_project_update.js#L228

C'est assez long et assez coûteux en ressources, mais le fichier produit est valide et complet à la fin. On a pas encore trouvé mieux pour faire ça pour l'instant.
