### ISSUE TITLE
Nouvelle Ortho Metz 2022

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/infrastructure#420]
Nouvelle ortho de la ville de Metz datant de mars 2022
Il y a un problème avec l'accès à la vue depuis leur site Internet, je les ai contacté via le formulaire de contact, pour le moments pas de nouvelle
https://geo.metzmetropole.fr/blog/

**Comment by Jean-BaptisteC** [comment]
L'ortho est de nouveau disponible ici http://geo.eurometropolemetz.eu/

**Comment by Jean-BaptisteC** [comment]
@Marc-marc-marc quel sont les prérequis pour que l'orthophoto soit disponible sur le serveur OSM-fr WMS ?

**Comment by Marc-marc-marc** [comment]
que @cquest le dise :) il est pour le moment le seul à savoir ce qui est fait et nécessaire pour le faire

**Comment by Jean-BaptisteC** [comment]
Suite à des échanges avec la métropole, une OrthoPhoto 2023 sera disponible d'ici quelques mois.

**Comment by Jean-BaptisteC** [comment]
L'ortho 2022 est disponible dans Josm depuis peu, l'import sur le serveur wms aurait été fait récemment?

**Comment by Jean-BaptisteC** [comment]
La version 2024 a été ajouté par cquest sur tous_fr je ferme le ticket
