### ISSUE TITLE
bd topo lente et / ou parfois KO ?

### ISSUE THREAD

**Issue by Jibec** [osm-fr/infrastructure#421]
bonjour, j'ai ouvert un message sur le forum : https://forum.openstreetmap.fr/t/y-a-t-il-un-soucis-avec-la-couche-bd-topo/12839

quand je suis à cet endroit https://www.openstreetmap.org/#map=19/47.51217999715934/7.213736879384562 je n'arrive pas à avoir les niveaux de zoom de détail.

y a-t-il une saturation du serveur ?
merci de votre travail

**Comment by Cyrille37** [comment]
Bonjour.
Je confirme le problème, depuis quelques semaines. L'affichage est grossier, les détails ne sont plus accessibles. Par contre BANO est réactif (_Peut être sans aucun rapport_).

**Comment by Cyrille37** [comment]
Bon, c'était un "jour spécial" car là c'est re-devenu inutilisable depuis hier

**Comment by Jibec** [comment]
oui, c'est cassé chez moi aussi, parfois on a l'illusion que ça marche, mais au bout de quelques secondes, on se rend compte qu'on a juste eu de la chance :p

je viens d'essayer sur https://osmose.openstreetmap.fr/fr/issue/88ad53b9-285f-9f20-8363-4203b32b9019 sans succès

**Comment by Cyrille37** [comment]
Ce matin c'est rapide, j'ai essayé plusieurs endroits et quelques secondes suffisent pour avoir les tuiles BD Topo de qualité.

**Comment by Cyrille37** [comment]
Ce fut d'un cour effet, voilà que l'imagerie est à nouveau inutilisable.

**Comment by Cyrille37** [comment]
Depuis qlqs jours (mi-avril) ça va beaucoup mieux. le rendu est souvent correct après quelques secondes. Constat subjectif, mais au moins cette BD Topo est utilisable :-)

**Comment by Cyrille37** [comment]
Depuis quelques temps le service répond bien, je clos le ticket :crossed_fingers:

**Comment by pl6025** [comment]
Bonsoir,
aujourd'hui cela a l'air de ne pas fonctionner. https://tile.openstreetmap.fr/ affiche des carrés rouge et JOSM affiche des "Erreur: pas de tuile à ce niveau de zoom." et ceci pour tous les niveaux de zoom essayé.
Peut-être faut-il rouvrir le ticket.

**Comment by Cyrille37** [comment]
Effectivement, la couche "fr.ign.bdtopo" ne répond pas.

**Comment by elmevess** [comment]
Bonjour,
Je n'arrive pas à charger les tuiles de près depuis aujourd'hui
https://stats.uptimerobot.com/mQX5Vi5YW2 l'hébergement de la couche est-il visible ici ?

**Comment by jocelynj** [comment]
@elmevess : Est-ce que tu peux préciser quelles tuiles posent problème ?

**Comment by elmevess** [comment]
J'ai eu le problème sur en dessous de la tuile 14 sur la ville de Lusigny-sur-Ouche

**Comment by jocelynj** [comment]
Ce n'est pas très précis, vu qu'on a pas mal de rendus différents :) 
Tu peux donner une URL où tu vois le souci ?

**Comment by elmevess** [comment]
Le lien où on pouvait voir les couches topo et bano ne répond plus depuis quelques mois (https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#10/48.3686/-3.3014)
Y'a t'il un nouveau site qui rempli ce besoin ?

**Comment by Marc-marc-marc** [comment]
nouveau non, l'url que tu mentionnes était axé bano et pas le reste
les couches contributeurs devraient être sur https://layers.openstreetmap.fr

**Comment by elmevess** [comment]
Je ne trouve pas la couche BD Topo sur https://layers.openstreetmap.fr/.
Je ne peux pas dire précisément quelles tuiles fonctionnent ou pas, ça dépend un peu des endroits.
Pour info je suis sous JOSM. Je suis peut-être le seul à avoir ce pb

**Comment by Jibec** [comment]
Exemple https://www.openstreetmap.org/#map=19/48.63288826670949/7.82891469406814
josm me dit que c'est ce calque qui est utilisé : https://{switch:a,b,c}.tile.openstreetmap.fr/bdtopo/{zoom}/{x}/{y}.png

**Comment by flacombe** [comment]
Il semble que le nécessaire ait été fait sur le serveur concerné.
Pouvez-vous confirmer et fermer cette issue (quitte à en rouvrir une nouvelle si ca recommence), s'il vous plaît ?

https://amicale.net/@cquest/111439363709992338

**Comment by Jibec** [comment]
ça fonctionne, merci à tous
