### ISSUE TITLE
Besoin de 2 redirections vers bzh202 depuis le frontal de osm25

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#43]
Bonjour @jocelynj 

J'aurais besoin que tu me fasses 2 redirections vers bzh202 :
- kosmtik = port 6789
- monit = port 2812

Merci d'avance.

**Comment by jocelynj** [comment]
Pour le port 2812, ça va être difficile, parce qu'on utilise déjà ce port pour le monit de la machine hôte.

Ça te va si on redirige vers un autre port ?

@cquest, @Marc-marc-marc : est-ce qu'on aurait un moyen simple de rajouter des redirections de port, et de le documenter pour les autres ?  L'idéal serait un paquet "standard".

**Comment by Marc-marc-marc** [comment]
est-ce que cela ne conviendrait pas de faire monit.domaine.ext port 80 vers ip privée port 2812 ?
cela aurait l'avantage d'éviter le conflit de port sur le hosteur

**Comment by MaelREBOUX** [comment]
monit.openstreetmap.bzh:80 => {ip_bzh202}:2812
kosmtik.openstreetmap.bzh:80 => {ip_bzh202}:6789

Ca me semble jouable non ?
Après il me semble qu'on a la main dans les configs de ces 2 logiciels pour changer les ports mais j'ai tjs une préférence pou rester sur les ports standards.

**Comment by jocelynj** [comment]
Non, on ne peut pas faire ce genre de redirection 80 -> 2812/6789, parce que c'est un proxy http qui fait la redirection, et du coup, c'est du traffic http qui doit passer sur le port 80.

**Comment by Marc-marc-marc** [comment]
monit 2812 est en http :-)

**Comment by MaelREBOUX** [comment]
Heu @jocelynj sur nos infra au boulot ce genre de truc est courant. frontal 80 -> plein d'applis avec plein de ports spécifiques. Du moment que ça fonctionne en HTTP...

**Comment by jocelynj** [comment]
Ah, j'avais pas vu que monit 2812 est en http. Et pour kosmetik, c'est aussi en http ?

**Comment by jocelynj** [comment]
J'ai ajoute monit.openstreetmap.bzh sur le proxy, vers le port 2812 de bzh202.

**Comment by jocelynj** [comment]
kosmtik est aussi redirigé.

Il reste à configurer letsencrypt, ce que je ferais une fois le DNS à jour.

**Comment by MaelREBOUX** [comment]
zone DNS modifiée. en attente propagation.

**Comment by MaelREBOUX** [comment]
http://monit.openstreetmap.bzh/  fonctionne.

je peux pas valider pour kosmtik : faut que je l'installe…

**Comment by jocelynj** [comment]
Le https fonctionne maintenant. J'ai par contre du enlever `api.openstreetmap.bzh`, parce que son DNS ne pointe pas vers osm25.

**Comment by MaelREBOUX** [comment]
ok : c'est noté.
peu de temps en ce moment. Je vais essayer installer kosmtik ce soir.

**Comment by jocelynj** [comment]
Les redirections ont été mises en place. Est-ce que ça serait possible de changer le DNS pour kosmtik, afin que je puisse générer le certificat https ?

**Comment by MaelREBOUX** [comment]
Bonjour @jocelynj 

De retour de congés.

kosmtik installé (cf https://github.com/osm-fr/infrastructure/issues/18#issuecomment-414804563) et qui répond sur http://kosmtik.openstreetmap.bzh

Je te laisse finir et fermer ce ticket. Merci à toi.

**Comment by jocelynj** [comment]
Les certificats https sont en place sur kosmtik et monit.

**Comment by MaelREBOUX** [comment]
merci @jocelynj
