### ISSUE TITLE
Commerces.openstreetmap.fr erreur 502

### ISSUE THREAD

**Issue by pl6025** [osm-fr/infrastructure#431]
Bonjour,

A ce jour (17 mars 2023), depuis mon téléphone (et mon ordinateur sur une autre connexion) j’essaye ce jour d’accéder au site [http://commerces.openstreetmap.fr 2](http://commerces.openstreetmap.fr/) et même en https cela me sort une erreur :

502 Bad Gateway
nginx/1.18.0

**Comment by PanierAvide** [comment]
Bonjour,

Je regarde ça, à priori le service est en carafe à cause du disque dur qui est plein...

**Comment by vinber** [comment]
> le service est en carafe à cause du disque dur qui est plein...
les ravages de l'alcool !

**Comment by PanierAvide** [comment]
Le service est reparti, en sachant que les accès disques doivent pas être hyper rapides car y a eu pas mal de délai pour faire de la place...

**Comment by jocelynj** [comment]
Merci pour la restauration du service.
