### ISSUE TITLE
Le proxy-ign est pour la bdOrtho est out ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#432]
sous josm

![image](https://user-images.githubusercontent.com/890869/226171179-d5d5d985-6a7a-4718-b823-d62647e91256.png)

**Comment by Cyrille37** [comment]
Effectivement dans **Josm** ça ne fonctionne pas, par contre avec **Id** ça fonctionne ...

**Comment by cquest** [comment]
J'ai mis à jour l'URL car l'IGN a encore changé ses URL...

https://wxs.ign.fr/pratique/wmts
remplacé par:
https://wxs.ign.fr/essentiels/geoportail/wmts

Et ça changera encore avec la migration de ces services sur la géoplateforme, en principe d'ici la fin de l'année.

**Comment by Cyrille37** [comment]
Merci <3
