### ISSUE TITLE
Mise à jour Peertube

### ISSUE THREAD

**Issue by gendy54** [osm-fr/infrastructure#433]
Bonjour,

Mise à jour de Peertube à faire avant le SotmFR
Version déployée: 4.3
Version disponible: 5.1

Merci ;)

**Comment by cquest** [comment]
Je regarde ça...

**Comment by cquest** [comment]
Il a pas aimé, j'ai fait un rollback

**Comment by jocelynj** [comment]
C'est à jour, merci @gendy54 pour le rappel :) 

À ce que j'ai vu dans le changelog, pas tellement de nouveauté visible sur le site web.
