### ISSUE TITLE
https://enedis.openstreetmap.fr/ erreur 502

### ISSUE THREAD

**Issue by pl6025** [osm-fr/infrastructure#434]
Bonjour,

Ce jour la connection sur https://enedis.openstreetmap.fr/ retourne une erreur 502

502 Bad Gateway
nginx/1.14.2

**Comment by jocelynj** [comment]
@flacombe, c'est pour toi ?

**Comment by PtiBzh** [comment]
Voir https://github.com/osm-fr/infrastructure/issues/356
Pour enedis je pense que ça avance en fonction du temps disponible de François.

**Comment by flacombe** [comment]
C'est de retour en ligne !

Merci pour votre patience
