### ISSUE TITLE
[osmose] buildbot out of service

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#435]
Buildbot, the Osmose task scheduler is not working.

https://buildbot.osmose.openstreetmap.fr/

http://munin.openstreetmap.fr/osm28.openstreetmap.fr/buildbot.osmose.vm.openstreetmap.fr/buildbot.html

**Comment by jocelynj** [comment]
Corrigé, après déplacement de buildbot sur osm27, vu que osm26 contient 2 VMs umap, et migration des IPs sur les différents backends.
