### ISSUE TITLE
Fermer id.openstreetmap.fr

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#436]
Cette version d'id avait été installé pour avoir des presets modifiés d'iD et faire réagir la communauté sur la maintenance collaborative des presets iD. D'un part les choses on bougé depuis, d'autre part cette installation n'est pas maintenu.

**Comment by jocelynj** [comment]
J'ai coupé la VM osm163.openstreetmap.fr sur osm28. À supprimer dans quelques semaines.

**Comment by jocelynj** [comment]
VM supprimée.
