### ISSUE TITLE
Nextcloud est en erreur 500

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#437]
> Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

https://nextcloud.openstreetmap.fr/

**Comment by jocelynj** [comment]
Corrigé: le host hébergeant nextcloud a saturé son disque dur le 9 avril, et la base mariadb a planté depuis. Un reboot effectué par @Marc-marc-marc a permis de restaurer le bon état.
