### ISSUE TITLE
[Osmose] Build of unnexisting countries

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#442]
Osmose buildbot contain at least 2 non existing countries in the configuration
- [csa_delacare](https://buildbot.osmose.openstreetmap.fr/#/builders/992)
- [csa_colocado_southeast](https://buildbot.osmose.openstreetmap.fr/#/builders/993)

No idea from where this can come from.

**Comment by frodrigo** [comment]
Ok, I see there is no more update on this two:
- usa_delaware
- usa_colorado_southeast

**Comment by Marc-marc-marc** [comment]
fixed

**Comment by frodrigo** [comment]
Maintenant on a un ` usa_delacare` à la place d'un `usa_delaware`.

**Comment by Marc-marc-marc** [comment]
je n'avais pas vu la 2ieme faute dans cette valeur. corrigé également

**Comment by frodrigo** [comment]
`usa_colocado_southeast` est toujours là.

**Comment by Marc-marc-marc** [comment]
corrigé aussi
