### ISSUE TITLE
[osmose] Lost of hivane2

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#445]
We lost contact with hivane2 osmose worker.

https://buildbot.osmose.openstreetmap.fr/#/workers/6

While hivane1 is still ok.

**Comment by jocelynj** [comment]
J'ai pu me connecter par ssh sans souci sur la VM, mais qui n'avait plus buildbot qui tournait dessus. Je viens de la redémarrer.

**Comment by frodrigo** [comment]
On a repardu hivane2.

**Comment by Marc-marc-marc** [comment]
oom qui a tué buildbot-slave
a faire
- [ ] diminuer d'un cran le nombre de jobs simultané
- [ ] vérifierr pq systemd n'a pas relancé  buildbot-slave
- [ ] éventuellement changer le score oom pour qu'il tue un job en cours plutôt que de tout perdre

**Comment by frodrigo** [comment]
Encore une fois.

**Comment by Marc-marc-marc** [comment]
j'ai encore diminué d'un cran (job simultané : 3 -> 2)
