### ISSUE TITLE
VM temporaire pour JOSM

### ISSUE THREAD

**Issue by don-vip** [osm-fr/infrastructure#45]
Hello,
J'aimerais avoir temporairement une petite VM pour valider la mise à jour du serveur JOSM vers Ubuntu 18.04.1:
https://josm.openstreetmap.de/ticket/16231
La mise à jour étant dispo le 26 juillet, serait-il possible d'avoir une VM un mois environ (par exemple du 19 juillet au 19 août) avec les caractéristiques suivantes:
- 1 coeur
- 8 GB RAM
- 200 GB de disque
- Ubuntu 16.04 LTS
- droits root pour valider l'upgrade vers 18.04
- domaine à configurer sur le proxy http? Je n'ai pas compris cette question, quels sont les choix possibles ?

Merci,
Vincent

**Comment by Marc-marc-marc** [comment]
> domaine à configurer sur le proxy http? Je n'ai pas compris cette question, quels sont les choix possibles ?

Si tu as besoin d'accéder en http, quelle adresse veux tu ? Genre http://test.josm.ext
Si tu n'y accèdera qu'en ssh, la question est sans objet

**Comment by don-vip** [comment]
Ah! J'aurai besoin d'un accès HTTP, mais le nom m'importe peu, je ferai avec ce qui vous convient le mieux :)

**Comment by jocelynj** [comment]
Autre question: quel OS veux-tu pour la VM ? Ubuntu 16.04 si je comprends bien, pour mettre à jour vers 18.04 ?
Pour le http, je peux te configurer josm-dev.openstreetmap.fr si ça te convient.

**Comment by don-vip** [comment]
Oui, c'est ça, 16.04 :) Parfait pour le nom !

**Comment by jocelynj** [comment]
VM accessible directement sur osm300.openstreetmap.fr, et via proxy sur http://josm-dev.openstreetmap.fr

**Comment by don-vip** [comment]
Merci beaucoup ! Je commence à jouer avec la semaine prochaine :)

**Comment by don-vip** [comment]
Je n'arrive pas à me connecter sur "osm300.openstreetmap.fr" c'est normal ?

**Comment by jocelynj** [comment]
Elle n'est accessible directement qu'en ipv6, ça pourrait être ton souci ?

Je peux te créer un compte sur osm26 pour faire rebond si nécessaire.

**Comment by don-vip** [comment]
Ah, je crois que j'avais désactivé l'IPv6 à l'époque où ça empêchait de joindre l'API OSM... Je réactive et je te tiens au courant.

**Comment by don-vip** [comment]
Bon j'étais bien "activé" mais l'IPv6 chez Orange c'est toujours pas ça... Je veux bien un accès via osm26 du coup.

**Comment by jocelynj** [comment]
Je t'ai créé un compte sur osm26.

**Comment by don-vip** [comment]
@jocelynj encore désolé pour le retard. J'ai mis en place la VM. Une fois connecté dessus, "wget http://localhost" renvoie un contenu HTML correct? J'aimerais tester maintenant depuis chez moi en passant par http://josm-dev.openstreetmap.fr/ mais ça me renvoie un HTTP 502 bad gateway.

**Comment by don-vip** [comment]
Il y a pas un souci encore ? Je viens d'arrêter Apache et ça renvoie sur le vrai site de JOSM ?

**Comment by don-vip** [comment]
OK merci. J'avais du foirer un truc, je recommence

**Comment by don-vip** [comment]
Maintenant j'ai une redirection HTTP 301 en boucle. Erreur de mon côté ?

**Comment by jocelynj** [comment]
Dans la config apache, la redirection http est pour passer en https.

Le souci, c'est que c'est le proxy qui gère le https, et toutes les connections entre le proxy et la VM sont en http. Du coup, la VM ne sait pas directement si l'accès est en http ou en https.

**Comment by don-vip** [comment]
OK je regarde comment désactiver la redirection https

**Comment by jocelynj** [comment]
J'ai modifié le fichier de config apache, et ça marche de mon côté. Mes modifs sur le fichier ne sont pas à récupérer.

Pour la redirection http -> https, j'ai mis ceci:
```
        RewriteCond %{HTTP:X-Forwarded-Proto} !https
        RewriteCond %{HTTPS} off
        RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]
```

**Comment by don-vip** [comment]
Merci beaucoup ! :)
ça y est le site fonctionne à peu près normalement ! Suffisamment pour mes tests en tout cas.

**Comment by don-vip** [comment]
C'est bon on vient de faire l'upgrade sur le vrai serveur JOSM, sans aucun souci. Merci beaucoup pour la VM! On n'en a plus besoin maintenant, tu peux récupérer les ressources allouées :)
