### ISSUE TITLE
[dwnload|osmose] Missing extract philippines/calabarzon

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#466]
The extract philippines/calabarzon is missing on download.osm.fr

**Comment by jocelynj** [comment]
Je viens de rajouter le diff sur download, qui n'était effectivement pas présent.

**Comment by jocelynj** [comment]
File is now available - sorry for the delay.

**Comment by frodrigo** [comment]
Il y a un problème avec les minutes diff, les numéros n'ont pas l'air cohérent.

https://buildbot.osmose.openstreetmap.fr/#/builders/1000/builds/23/steps/3/logs/stdio

**Comment by jocelynj** [comment]
Ça devrait être corrigé: j'avais gardé les numéros des diffs geofabrik au lieu des diffs osm.org. On verra sur les logs demain.
