### ISSUE TITLE
Orthophoto Toulouse 2017

### ISSUE THREAD

**Issue by don-vip** [osm-fr/infrastructure#47]
Hello,
La nouvelle ortho de Toulouse est disponible ici:
https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2017/

Est-ce que quelqu'un peut la mettre à dispo sur http://wms.openstreetmap.fr/tms/1.0.0/toulouse_2017 ?

**Comment by Marc-marc-marc** [comment]
suite à notre discussion sur irc, as-tu pu avoir la recette qu'avait utilisé la personne ayant fait la manip pour l'ortho précédente ?
cela éviterait de tout refaire à 0 :-)

**Comment by don-vip** [comment]
Malheureusement non. Mais l'ortho précédente est juste un proxy vers le WMS public de Toulouse (cf. #46 qui doit être facile à corriger). Ce WMS n'est toujours pas à jour et je ne parviens pas à avoir de réponse de la métropole encore pour sa mise à jour. Donc là il faudrait télécharger les archives et offrir un vrai serveur de tuiles, pas juste un proxy.

**Comment by don-vip** [comment]
@cquest tu peux nous aider/guider ? Je suis prêt à y passer du temps si besoin mais je pense pas pouvoir y arriver seul :( Il nous faudrait un tuto pour pouvoir importer les nouvelles sources d'imagerie rapidement.

**Comment by don-vip** [comment]
L'autre solution c'est de voir si on peut importer l'ortho sur le cloud OpenAerialMap. Pour l'instant ce n'est pas possible à cause de la restriction de licence: https://github.com/hotosm/OpenAerialMap/issues/124

**Comment by cquest** [comment]
Proxy ajouté... et download des dalles en cours pour être autonome.

A suivre sur https://github.com/osm-fr/infrastructure/issues/82

**Comment by don-vip** [comment]
ça prend combien de temps le download, pour avoir une idée ?

**Comment by don-vip** [comment]
Merci beaucoup Christian pour ce cadeau de Noël ! :santa:
