### ISSUE TITLE
layers: admin7 Lucky zoom level 12 only, else 404 not found tiles

### ISSUE THREAD

**Issue by jidanni** [osm-fr/infrastructure#472]
https://layers.openstreetmap.fr/?zoom=12&lat=42.13928&lon=-87.8002&layers=B000000000FFFFFFFFFFTFFFFFFFFFFFFFF
looks good.
But if one zooms in or out, there are lots of 404 not found tiles.
That was for my USA test. Other places do have more tiles.

**Comment by Marc-marc-marc** [comment]
I don't see any 404 right now
maybe the server was a little too busy to show it, because those area isn't in the cache and need to be render live
can you test it again ?
