### ISSUE TITLE
configuration nouveau tuileur bzh202.vm.openstreetmap.fr (rendus langues minoritaires)

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#478]
À cause de #465 on dispose d'une nouvelle VM nommée `bzh202.vm.openstreetmap.fr`.
Il s'agit maintenant de la configurer le tuileur afin de servir les services de cartes en langues minoritaires.

Le domaine servi est : `tile.openstreetmap.bzh`

## Tuyauterie web

- [x] frontal nginx : tile.openstreetmap.bzh
- [x] frontal nginx : tile.openstreetmap.bzh/monit/
- [x] frontal nginx : proxy_set_header   X-Real-IP voir [ce ticket](https://github.com/osm-fr/infrastructure/issues/34#issuecomment-399773863)
- [x] apache : format des logs pour real IP voir [ce ticket](https://github.com/osm-fr/infrastructure/issues/34#issuecomment-568021516)
- [x] DNS : redirection vers le frontal
- [x] frontal nginx : https

## Tuileur

- [x] monit : configuration basique
- [x] git clone projet de rendu
- [x] configuration mapnik
- [x] rotation des logs apache
- [x] monit : configuration avancée (purge si espace disque restreint)

## Bonus
- [ ] configuration goaccess

**Comment by MaelREBOUX** [comment]
Bloqué : en attente de l'accès à la base OSM monde.

**Comment by Marc-marc-marc** [comment]
c'est fonctionnel,  c'était ton entrée ```db.openstreetmap.world``` dans /etc/hosts qui pointait vers ailleurs

**Comment by MaelREBOUX** [comment]
Le tuileur est fonctionnel ! 
Je fais des tests avant de changer le DNS.

**Comment by MaelREBOUX** [comment]
`Jul 14 09:10:11 bzh202 renderd[35699]: ** (process:35699): ERROR **: 09:10:11.798: failed to render TILE br 15 16224-16231 11368-11375
Jul 14 09:10:11 bzh202 renderd[35699]: ** (process:35699): ERROR **: 09:10:11.799:   reason: Postgis Plugin: connection to server at "db.openstreetmap.world" (127.0.0.1), port 5432 failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections
Jul 14 09:10:11 bzh202 renderd[35699]: Connection string: 'host=db.openstreetmap.world dbname=osm user=osmbr connect_timeout=4'
Jul 14 09:10:48 bzh202 renderd[35699]: Mapnik LOG> 2023-07-14 09:10:48: SVG PARSING ERROR:"SVG support error: <enable-background> attribute is not supported"
`

**Comment by MaelREBOUX** [comment]
OK : ça me semble pas trop mal.

J'ai fait la modification DNS pour pointer vers osm27.

Si qqn peut gérer la création du certificat certbot / [Let's Encrypt](https://letsencrypt.org/getting-started/) dans la journée…

**Comment by MaelREBOUX** [comment]
Bon des nouvelles : tout va très bien sur le nouveau tuileur.

Par contre : **je n'arrive plus à monitorer renderd** car il n'y a plus de fichier `/run/renderd/renderd.pid`. Il y a le .sock mais pas le fichier pid qui est censé être créé sur le 'programme' est en cours d'exécution.
Suis pas spécialiste mais il me semble que le fichier socket n'a rien à voir et est présent en permanence même si le service / programme n'est pas en route.

Une idée ?

**Comment by Marc-marc-marc** [comment]
unit systemd modifé :
Tpas de Type (donc simple) -> ype=forking
ExecStart=/usr/bin/renderd -f -> ExecStart=/usr/bin/renderd

**Comment by MaelREBOUX** [comment]
> unit systemd modifé : pas de Type (donc Type=simple) -> Type=forking ExecStart=/usr/bin/renderd -f -> ExecStart=/usr/bin/renderd

OK : vu et pris en compte : j'ai réactivé le monitoring et ça semble bien se passer.

merci.

**Comment by MaelREBOUX** [comment]
Je ferme ici car #527 prend le relais
