### ISSUE TITLE
Replication/Diff pour Luxembourg

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [osm-fr/infrastructure#48]
Bonjour,

Serait-il possible d’ajouter le Luxembourg a la liste des pays sur [http://download.openstreetmap.fr/replication/europe/](http://download.openstreetmap.fr/replication/europe/)?

Merci
David

**Comment by jocelynj** [comment]
Oui, c'est possible d'ajouter le luxembourg. Est-ce que tu pourrais me donner un ID d'une relation OSM contenant le Luxembourg ?

**Comment by DavidMoraisFerreira** [comment]
Oui, l'id [2171347](https://www.openstreetmap.org/relation/2171347 ) contient le Luxembourg. Merci :)

**Comment by jocelynj** [comment]
Les diffs sont maintenant disponible ici: http://download.openstreetmap.fr/replication/europe/luxembourg/minute/
Je rajouterai l'extract dans quelques jours.

**Comment by DavidMoraisFerreira** [comment]
Merci @jocelynj

**Comment by jocelynj** [comment]
Et l'extract est disponible sur http://download.openstreetmap.fr/extracts/europe/.
