### ISSUE TITLE
osm34 : VM Enedis HS

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#486]
Bonjour :)

La VM Enedis est encore tombée.
Pouvez-vous la réveiller s'il vous plaît ?

**Comment by jocelynj** [comment]
Pour info, le status dans proxmox: 
<img width="333" alt="enedis-utilisation" src="https://github.com/osm-fr/infrastructure/assets/68169/ca3f818e-c64f-44a5-914c-421076c129cf">

Je redémarre la VM dans l'interface proxmox.

**Comment by jocelynj** [comment]
Ça remarche.

Il faudrait trouver quel process a saturé le cpu+ram, mais je ne sais pas trop que regarder - la dernière fois, je n'avais rien trouvé dans `atop`.

**Comment by flacombe** [comment]
Top, merci @jocelynj 

Je pense que c'est imposm qui doit pédaler dans la semoule peut-être, mais c'est un problème en effet.
Il faut que je fasse un peu de mise à jour prochainement, ce sera l'occasion de me pencher dessus

**Comment by flacombe** [comment]
Bonjour @jocelynj 

Désolé je n'ai pas encore eu le temps de me pencher sur le comportement d'imposm mais la VM est encore tombée.
La RAM est encore pleine ?

**Comment by jocelynj** [comment]
Proxmox dit effectivement que la RAM est saturé, et que le CPU tourne à fond. Je viens de redémarrer la VM, en augmentant la quantité de RAM et de CPU.

**Comment by flacombe** [comment]
Bonjour @jocelynj cela n'a visiblement pas réglé le soucis de stabilité.

C'est très étrange parce que j'ai le même docker qui tourne sur un autre machine sans aucun problème et il ne sature pas le CPU ni la RAM.
Il a toutefois davantage de ressources et je ne peux pas en exiger autant de l'infra de l'asso.
Peut-être devrais-je désactiver imposm et ne le mettre à jour qu'une fois par mois ?

**Comment by Marc-marc-marc** [comment]
idée sans avoir été voir ni les graphes ni la config : diminuer le nombre de thread, le buffer pg, choisir un moment + calme sur le serveur pour faire la maj, ajouter un nice sur les processus qui peuvent se faire killer sans trop de dégat
faire que 1x par mois risque de faire un pic + haut et/ou plus long, c'est un peu la roulette russse

**Comment by Marc-marc-marc** [comment]
kvm redémaré

**Comment by zorun** [comment]
Il y a un bug connu dans le kernel Proxmox qui fait freezer certaines VMs de façon aléatoire (100% CPU, et VM qui ne répond plus). Ça arrive d'autant plus fréquemment que la VM est "chargée" en accès mémoire, CPU, I/O.

Après plusieurs mois de recherche ça a été fixé récemment, il faut mettre à jour le kernel sur l'hôte physique, cf. https://forum.proxmox.com/threads/vms-freeze-with-100-cpu.127459/page-10#post-587633

**Comment by flacombe** [comment]
Merci @zorun pour l'info, je ne savais pas.
Merci @Marc-marc-marc pour le restart

En tout cas je met ma stack en read-only en désactivant imposm en attendant que ce soit déployé chez nous

**Comment by Marc-marc-marc** [comment]
merci pour l'info, pve-kernel 6.2.16-11~bpo11+2 instrallé, reste à rebooter

**Comment by Marc-marc-marc** [comment]
@flacombe en lisant le fil du bug, cela va planter vaguement dans ~20 jours tant qu'on n'a pas redémarré le host sur le nouveau kernel. le délais pourrait être + court selon l'activité du baloon et de KSM mais le précédent plantage est même à un rien + que 20 jours... donc je suppose qu'on va vaguement vers le même délais
Donc à mon avis rien ne t’empêche de lancer aujourd'hui la maj imposm, surtout si tu le lances à la main par ex avec `nohup commande &` en laissant le cron désactivé

**Comment by flacombe** [comment]
J'ai terminé mes opérations pour ce soir, vous pouvez reboot l'hôte à votre guise.

**Comment by Marc-marc-marc** [comment]
reboot effectué
```
uname -a
Linux osm34 6.2.16-11-bpo11-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-11~bpo11+2 (2023-09-04T14:49Z) x86_64 GNU/Linux
```
