### ISSUE TITLE
Groupe local Seine-Eure : Ajout d'un tag sur le forum

### ISSUE THREAD

**Issue by lefuturiste** [osm-fr/infrastructure#489]
Bonjour,

[Un groupe local](https://wiki.openstreetmap.org/wiki/Groupe_Local_Seine-Eure) dans l'Eure en Normandie vient de ce former, 

Est-il possible d'ajouter un tag "Seine-Eure" dans la catégorie ["Groupe Locaux" du forum](https://forum.openstreetmap.fr/c/groupes-locaux/52) ?

Vous remerciant d'avance.

**Comment by jocelynj** [comment]
Est-ce que tu peux me donner un nom de compte sur le forum pour le passer en modérateur de la future catégorie ?

**Comment by remsoff** [comment]
> 

Bonjour 
Je suis comme lefuturiste membre du groupe local, mon pseudo sur le forum est Remi

**Comment by lefuturiste** [comment]
> Est-ce que tu peux me donner un nom de compte sur le forum pour le passer en modérateur de la future catégorie ?

Moi, mon username est `lefuturiste`

eh oui je sais c'est compliqué à deviner x)

**Comment by jocelynj** [comment]
J'ai créé le groupe.

Merci de modifier le message de presentation ici: https://forum.openstreetmap.fr/t/a-propos-de-la-categorie-seine-eure/16510

**Comment by lefuturiste** [comment]
Fait, Merci @jocelynj !
