### ISSUE TITLE
osm11 incessible - Rendu Volta bano BdTopo Cyclosm HS

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#490]
Bonjour

Cela peut cacher un soucis plus grave, le rendu Volta est HS depuis hier 18h semble-t-il
https://twitter.com/phd0/status/1685904953129234432?s=20

**Comment by deuzeffe** [comment]
Idem pour BANO et BD TOPO.

**Comment by Marc-marc-marc** [comment]
osm11 ne répond pas ping @cquest

**Comment by flacombe** [comment]
Bonsoir

Volta fonctionne à nouveau ce soir.
Si l'issue n'est pas fixée on peut au moins dire que c'est réparé.

Merci à ceux qui ont fait le nécessaire.

**Comment by momentmal** [comment]
CyclOSM is still not working for me anywhere.

**Comment by cquest** [comment]
Electricity outage... trying to fix it 500km away :(

**Comment by stellingsimon** [comment]
Hitting this problem made me aware of just how valuable CyclOSM is to me when planning routes... So I made a donation of €20 to OSM FR to say thanks for everything you've built and maintained so far! Should've done this long ago, but better late than never ;-)

**Comment by momentmal** [comment]
> Hitting this problem made me aware of just how valuable CyclOSM is to me when planning routes... So I made a donation of €20 to OSM FR to say thanks for everything you've built and maintained so far! Should've done this long ago, but better late than never ;-)

Same! Felt like I had to follow you with this example. 🙏
I just donated 25€ for the great service you folks provide.
CyclOSM and OSM became a big part of my planned tours 🙌

**Comment by Marc-marc-marc** [comment]
servers osm11 osm13 are back
uptime show that the outage isn't at the server level but at the network level
feel free to report stuffs still broken if any

**Comment by tuxayo** [comment]
>  feel free to report stuffs still broken if any

Still the BANO tiles. Maybe it's unrelated so I should make another ticket?

https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#17/43.77766/5.55726

**Comment by jocelynj** [comment]
@tuxayo : it is related, as tile.openstreetmap.fr was merged because of the outage, but we weren't able to copy all files.

Is there a reason to use this page instead of a layer from http://tile.openstreetmap.fr or http://layers.openstretmap.fr

**Comment by cquest** [comment]
Update about network outage for osm11 (and osm13):
- servers have 2 separate power lines
- fiber routers were on the same power line, which went down several times this week

Routers are now on two different power lines, the ethernet switch has dual power inputs and was already on both lines.

IPv6 has been added to allow the front tile cache (osm23-24) to switch between both fibers (see https://github.com/osm-fr/infrastructure/commit/0e7bc558487d31099656f766f22765af80e5f0ad)

**Comment by punyidea** [comment]
I think the tiles are down again - I can't use the link for the brouter plotter or maps.openrouteservice.org

**Comment by punyidea** [comment]
Hello, I wanted to report that it's possible the server is not functioning. When on the website the tiles take quite long to generate, especially for cyclosm.

**Comment by frenzed** [comment]
On several different devices, cyclOSM shows only grey space. Other maps seem normal.  Now 21h50 28/1/24

Is there a method for ensuring that faults like this  are notified to people who can sort them, and that users can know that the problem is being attended to, preferably with progress reports/time estimates

**Comment by jocelynj** [comment]
I had commented on https://github.com/cyclosm/cyclosm-cartocss-style/issues/659 about the status, but didn't see the thread. In any case, I think it is better to open a new ticket instead of reopening an old one.

Do you still see issues on Cyclosm tiles?

**Comment by punyidea** [comment]
No, it works well, thank you!

**Comment by frenzed** [comment]
Seems to be good now.  Fixed last night.  Restarted the server.
It relies on volunteers.  How much of the delay was waiting for the
volunteers to become aware of the problem?  Most of it I suspect.
It may be useful to have some kind of automated check that tiles are being
served.

Ed
Edward Hitchcock +337 6607 3456
