### ISSUE TITLE
bug: erreur CORS sur les serveurs tile.openstreepmap.fr

### ISSUE THREAD

**Issue by paul-thebaud** [osm-fr/infrastructure#491]
Bonjour,
Nous expérimentons des erreurs CORS qui ne se produisaient pas il y a quelques semaines sur notre intégration de carte OpenStreetMap (via MapLibre GL JS).

Les erreurs se produisent aussi bien en `localhost` que sur les applications de production, et sur n'importe quels sous-domaines (`a`, `b` ou `c`).

Fait étrange : les erreurs ne semblent pas toujours se produire (certaines tiles s'affichent correctement), et cela ne semble pas dépendre du sous-domaine utilisé.

Voici un exemple d'erreur :

```
Access to fetch at 'https://c.tile.openstreetmap.fr/osmfr/13/4019/2856.png' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Merci d'avance pour votre aide.

**Comment by frodrigo** [comment]
Je pense qu'il y a eu un retour à la normale coté serveur. Mais le CORS n'est pas revenu.

Ç'est bloquant pour l'utilisation des tuiles par les affichages en GL : MapLibre GL JS, MapboxGL JS et peut être d'autres.

**Comment by jocelynj** [comment]
Je suis un peu étonné que CORS marchait avant, vu que je n'ai pas vu de modif sur la config nginx du proxy - @cquest, ça te parlerait ?

J'ai quand même activé les headers sur /osmfr/

**Comment by Cyrille37** [comment]
Bonjour @paul-thebaud 
As-tu un retour à faire sur ce problème ? La solution de @jocelynj via #504 a-t-elle résolu ?

**Comment by paul-thebaud** [comment]
Bonjour @Cyrille37, je crois que nous n'avons plus ces erreurs. Mais nous utilisons moins de variations de tuiles qu'avant, en raison des uptimes.
Merci.

**Comment by Cyrille37** [comment]
Merci. Alors je ferme le ticket ; et si besoin on le retrouve via search ou ouvre un nouveau
