### ISSUE TITLE
CyclOSM is not working on zoom levels above 11+

### ISSUE THREAD

**Issue by divulgacheur** [osm-fr/infrastructure#495]
Hello, 
It seems that some CyclOSM tiles are no longer rendered on zoom levels higher than 11 (except in some major cities where there must be cache) :confused: :
![image](https://github.com/osm-fr/infrastructure/assets/36365881/d412e1ad-4071-4562-92fb-3d33acbc1489)

**Comment by jocelynj** [comment]
It should work again - we had a power issue on the server handling cyclosm tiles.

**Comment by divulgacheur** [comment]
Hello, same problem again, can you check ?
