### ISSUE TITLE
 Groupe local Rouen : Ajout d'un tag sur le forum

### ISSUE THREAD

**Issue by lefuturiste** [osm-fr/infrastructure#496]
Bonjour,

[Un groupe local](https://wiki.openstreetmap.org/wiki/Groupe_local_Rouen) à Rouen en Normandie est sur point de ce former,

Est-il possible d'ajouter un tag "Rouen" dans la catégorie ["Groupe Locaux" du forum](https://forum.openstreetmap.fr/c/groupes-locaux/52) ?

Vous remerciant d'avance.

**Comment by jocelynj** [comment]
En remplacement de Seine-Eure, ou en plus ?

**Comment by lefuturiste** [comment]
> En remplacement de Seine-Eure, ou en plus ?

En plus, c'est pas les mêmes personnes et les même sujets.

**Comment by jocelynj** [comment]
C'est ajouté: https://forum.openstreetmap.fr/t/a-propos-de-la-categorie-rouen/16826
