### ISSUE TITLE
vm monitoring status.openstreetmap.fr

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#5]
demande de Rodolphe
idéalement en accès direct au moins pour http/https (histoire que le service soie accessible si le reverse proxy)
+ ajout dns d'un host genre https://status.openstreetmap.fr

**Comment by jocelynj** [comment]
@RoPP: tu veux quelle configuration ? Surtout niveau taille disque dur ?

Pour info, quasi toutes les VMs qu'on a sont accessibles en ipv6, donc on aura toujours ça en cas de souci de reverse proxy.

**Comment by RoPP** [comment]
Une petite config suffit. 10Go de HDD devrait être largement suffisant.
L’idée d’avoir un accès direct, c’était dans le cas où le reverse proxy est down mais c’est pas urgent, on pourra voir ça plus tard.

**Comment by jocelynj** [comment]
J'ai créé la VM sur osm149, cf commit osm-fr/ansible-scripts@8efb149df475137bba60e7054a3b74c232304560

**Comment by RoPP** [comment]
Ok merci. Par contre, je n’ai pas accès en ssh, tu peux regarder si ma clé est bien installée stp ?

**Comment by jocelynj** [comment]
On Fri, Nov 10, 2017 at 10:31:01AM +0000, Rodolphe Pelloux-Prayer wrote:
> Ok merci. Par contre, je n’ai pas accès en ssh, tu peux regarder si ma clé est bien installée stp ?

Effectivement, je n'avais pas mis la clé ssh, parce que je n'avais pas lancé
ansible de la machine où j'ai ta clé. Ça devrait être corrigé.

**Comment by RoPP** [comment]
https://status.openstreetmap.fr

**Comment by jocelynj** [comment]
J'ai configuré le https, qui marche maintenant. 

Tu sais pourquoi le lien "Tableau de bord" redirige vers une page de login en http ?

**Comment by RoPP** [comment]
Le `proxy_pass` étant en http, je suppose que le l’appli (laravel ?) renvoie une adresse en http lors de la redirection. Peut-être qu’il faudrait setter `proxy_redirect` sur le proxy pour le https (à vrai dire, je serais pour configurer le site en hsts tant qu’à faire :) )

**Comment by jocelynj** [comment]
Ah oui, j'ai eu un problème similaire sur wordpress.

J'ai du hacker le code php pour lui faire croire qu'on était en HTTPS si HTTP_X_FORWARDED_PROTO=https

**Comment by Marc-marc-marc** [comment]
ne serrait-il pas mieux pour ce service là uniquement de mettre une ipv4 sur la vm et de rendre le http(s) accessible en direct ? cela éviterait d'avoir le monitoring qui dépend d'un service monitoré

**Comment by jocelynj** [comment]
Le service est aussi disponible en ipv6-only sur http://osm149.openstreetmap.fr. Et ça me parait dommage de devoir rajouter une ipv4 juste pour ce service - on n'en a pas d'autres de disponible.

**Comment by RoPP** [comment]
@Marc-marc-marc ce n’est pas un serveur de monitoring, c’est un site pour indiquer l’état des services et tenir informer les utilisateurs des incidents et résolutions en cours.
À terme, il devrait être connecté avec le système de monitoring pour afficher en temps réel les indisponibilités ou ralentissements mais c’est pour plus tard.

**Comment by RoPP** [comment]
@jocelynj est-ce qu’on a un stmp sortant pour les services ? j’en aurai besoin pour les invitations et les souscriptions à un incident

**Comment by jocelynj** [comment]
Non, on n'a pas de serveur smtp centralisé - chaque machine installe son propre serveur smtp, qui envoie des emails avec un from contenant son hostname. Ça aurait un intérêt de centraliser ?

**Comment by RoPP** [comment]
Oui je pense, ça permet de centraliser la conf, notament pour dkim, dmarc, spf et ça simplifie l’utilisation par les services/vm. Pour les applis, il suffit de déclarer le smtp.osm.fr comme serveur et c’est fini et pour les hosts un simple ssmtp et tous les mails systèmes sont acheminé correctement.

**Comment by Marc-marc-marc** [comment]
pour site d'info <> onitoring, cela revient au même, avoir un site qui renseigne les pannes doit dépendre le moins possible de ce qui peux tomber en panne.
mais si on n'a pas d'IPv4 de réserve, cela rend l'acces http(s) direct en IPv4 impossible. A voir si cela a du sens de faire du direct en IPv6 (ou a voir + tard)
Pour la centralisation smtp, je trouve que c'est + qu'intéressant, cela devrait même être fait pour tous les serveurs (idéalement il en faut sur 2 sites... sinon un panne style ovh bloque les serveurs des autres hebergeurs sans raison)... ceci dit on gagnerait en lisibilité à mettre cela dans un autre ticket

**Comment by cquest** [comment]
Il en est où ce http://status.openstreetmap.fr ?

Actuellement en 502...

**Comment by jocelynj** [comment]
Ce projet de monitoring étant tombé à l'eau, je ferme le ticket.
