### ISSUE TITLE
Bug sur le rendu osm-fr

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#50]
Signalé sur la liste de discussion umap, il semble que cela concerne le rendu :+1: http://tile.openstreetmap.fr/?q=f%C3%A9nelon%20lyc%C3%A9e%20paris#

l'affichage des rues se fait parfois de manière erronée, par exemple ici Saint-André des Arts, qui s'affiche correctement à gauche et droite, mais s'affiche « Rue Sairé des Arts » au centre au croisement de la « rue des Grands Augustins » verticale, qui elle aussi s'affiche de manière erronée (« Rue des Graes Grands Augustins ». À d'autres niveaux d'agrandissement, l'affichage ne pose pas de souci. 

https://lists.openstreetmap.org/pipermail/umap/2018-July/000277.html

**Comment by Marc-marc-marc** [comment]
La rue en question dans osm https://www.openstreetmap.org/way/34868170
les 2 tuiles https://a.tile.openstreetmap.fr/osmfr/19/265551/180376.png https://a.tile.openstreetmap.fr/osmfr/19/265552/180376.png
étant donné qu'il ne semble y avoir aucun name="Rue Sairé des Arts" dans osm en ce moment,
je penche pour une étrange contraction de **Sai**nt-And**ré**

**Comment by vinber** [comment]
Oui j'aurai pu le préciser mais effectivement j'ai l'impression que ceux sont 2 tuiles proches qui font de droles de noms :)

et le niveau 20, effectivement n'affiche plus rien.

**Comment by Marc-marc-marc** [comment]
zoom 20 : 
/var/lib/mod_tile/osmfr/20 -> /data/osm2pgsql/tiles/osmfr/20
mais répertoire absent -> crée, test ok

pour le style, faudra attendre le retour de @cquest

**Comment by MaelREBOUX** [comment]
Bonjour, 

Pb sans doute lié au pb de rendu des dernières semaines. Et réglé depuis car je ne vois plus le problème décrit --> https://www.openstreetmap.org/#map=19/48.85310/2.34057

Vous confirmez @vinber ?

**Comment by vinber** [comment]
bonjour,
désolé pour le délai. @MaelREBOUX Si le problème y ait toujours mais c'est sur le rendu fr
http://tile.openstreetmap.fr/?zoom=19&lat=48.85341&lon=2.34023&layers=B000000FFFFFF

**Comment by MaelREBOUX** [comment]
Ok. Vu.
"Rue Saint-André des arts" est en fait "rendu" sur 2 tuiles :
http://b.tile.openstreetmap.fr/osmfr/19/265551/180376.png  et  http://a.tile.openstreetmap.fr/osmfr/19/265552/180376.png

C'est un cas classique de rendu en limite de tuile. Il y a des réglages de gouttières (gutter) qui servent normalement à gérer ça. En tout cas sur du GeoWebCache. Sur du mapnik - mod_tile je ne sais pas (encore).

![01](https://user-images.githubusercontent.com/6370443/45102647-7b4c2580-b12e-11e8-83cc-3aa817bd7d56.png)

![02](https://user-images.githubusercontent.com/6370443/45102656-7edfac80-b12e-11e8-8263-bff235668b6e.png)

**Comment by frodrigo** [comment]
Repporté sur le projet de rendu osm-fr https://github.com/cquest/osmfr-cartocss/issues/66

**Comment by cquest** [comment]
J'ai généralisé l'usage des directives "avoid-edges" dans le cartocss, qui est maintenant bien bien mieux géré par mapnik que lorsque la feuille de style a été originellement mise au point. Ces petits défauts doivent avoir disparu.
