### ISSUE TITLE
Perte de la vm osm211

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#502]
osm211 est un backend OSM qui ne traite plus jobs depuis quelques jours.

@anayrat et moi avons regardé sans trouver de cause apparente.

Aujoud'hui j'ai tenté un reboot, j'ai eu un timeout sur le reboot puis ça a du terminer par rebooter quand même.

Depuis plus de connexion ssh possible à la VM.

**Comment by jocelynj** [comment]
Je ne suis pas arrivé à démarrer la VM depuis le host, du coup, j'ai rebooté le host, et la VM s'est relancée correctement.
J'en ai profité pour faire un apt upgrade sur host+VM.
