### ISSUE TITLE
Pas de CORS / CORS mal configuré pour les services tile.openstreetmap.bzh

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#504]
Remontée d'une erreur par une personne qui semble maintenir une liste de référence des service de tuiles :
https://forum.openstreetmap.fr/t/technical-help-needed-cors-headers-are-not-set-for-osm-breton-occitane-and-basque-style/18160

A lier avec #491 ?

**Comment by Marc-marc-marc** [comment]
il y a une regle CORS sur bzh202 pour /br... cela voudrait donc dire qu'elle ne fonctionne pas ?
pas de règle pour oc eu donc fatalement là cela ne fonctionne pas du tout
un cron pour rebooter renderd ? cela me donne l'impression d'être la meilleur chose à faire pour ne pas voir un éventuel soucis sous-jacent

**Comment by jocelynj** [comment]
Ça devrait être corrigé - j'ai mis la config CORS pour toutes les urls de bzh202.

**Comment by MaelREBOUX** [comment]
Note : c'était à `<Location /br>`

```
        # Cross-Domain
        <Location />
                Header set Access-Control-Allow-Origin "*"
                Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
        </Location>
```

**Comment by MaelREBOUX** [comment]
Le monsieur est content et dit que ça fonctionne :D
