### ISSUE TITLE
live is down

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#505]
http://live.openstreetmap.fr/ est tombé (erreur Ngnix, bad gateway, aussi bien en http que https

**Comment by Marc-marc-marc** [comment]
CT éteinte, redémarage impossible (ainsi que sur d'autres CT du même host) -> reboot du host
le CT est maintenant up mais le script bug en pensant qu'il doit télécharger la séquence 0/0/0
débug en cours

**Comment by Marc-marc-marc** [comment]
différent bug :
le fichier PREV_SEQ était vide, ce que le script ne gérait pas -> amélioré
wget rencontre un soucis de certificat, que je ne reproduit pas en dehors du host -> ajout de --no-check-certificate pour wget
```
ERROR: The certificate of 'download.openstreetmap.fr' is not trusted.
ERROR: The certificate of 'download.openstreetmap.fr' doesn't have a known issuer.
ERROR: The certificate of 'download.openstreetmap.fr' has expired.

```
