### ISSUE TITLE
Rendus techniques inaccessibles

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#510]
Bonsoir,

Malgré la résolution récente mentionnée dans #508, il semblerait que le serveur soit à nouveau tombé.
Les rendus techniques Volta, Bdtopo, Carthage... sont inaccessibles à nouveau.

La stabilité de ces rendus conditionne certaines contributions, nous avons du mal à nous en passer.

Quelles actions permettraient d'en améliorer la stabilité ?

**Comment by frodrigo** [comment]
Je pense que ces donnes pourraient être juste servie sous forme de tuiles vectorielles plus qu'en rendu raster. C'est des données externes statiques, des tuiles vectorielles pré-généré ci permettent très bien et efficacement. Les éditeurs savent aujourd’hui charger et afficher ces tuiles / styles.

**Comment by Marc-marc-marc** [comment]
- [ ] documenter oü c'est (si tu cherches Volta sur la [page tech](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France), il n'y a rien
- [ ] documenter le problème dans le ticket qui mentionne un pouet... ssd de retour, il était ko ? parti en vacance ? dans un autre serveur ? etc
- [ ] regarder si c'est la même cause ou pas cette fois.
- [ ] en fonction du point précédent, prendre des mesures pour éviter rendre le service plus fiable
- [ ] le choix de la techno raaster<>vecto est pour moi secondaire, un vecto planté sur un serveur inconnu a le même soucis que si c'était raster... d'ailleurs si les données externe ne change pas, on devrait à minima avoir les données en cache tuile... cela n'a pas l'air d'être le cas

**Comment by frodrigo** [comment]
L'idée d'utiliser des tuiles vectorielles statiques est justement de rendre
les choses plus fiables.

**Comment by vdct** [comment]
Je suis totalement d'accord avec cette tendance à basculer en vectoriel. C'est dans mes prochains chantiers côté BANO avec 3 items :
- une génération de tuiles à intervalles réguliers (a priori quotidien)
- une feuille de style compatible JOSM pour disposer du rendu en contribution
- une feuille de style possiblement plus riche pour avoir un rendu de consultation, hébergé en ce qui concerne BANO sur une page de bano.openstreetmap.fr, et qui se substituera à l'équivalent sur layers à terme

**Comment by frodrigo** [comment]
J'ai ajouté des lignes sur tile-vect pour faire un test
http://tile-vect.openstreetmap.fr/#map=13.65/43.82815/4.36752&style=ampere

**Comment by cquest** [comment]
J'avais pas pris le temps de documenter la panne et son origine, c'est fait:

https://github.com/osm-fr/infrastructure/blob/master/cquest/osm13.md

SSD NVMe en fin de vie, à changer... serveur aussi en fin de vie, comme osm11
Moji devrait redonner de la marge, on a aussi osm34 et osm35 à compléter (SSD voire HDD) pour mise en prod.

**Comment by cquest** [comment]
La base PG a changé de SSD, on peut remplacer le NVMe sans grosse coupure.
