### ISSUE TITLE
Ajout de l’orthophotoplan 2022 de Toulouse Métropole

### ISSUE THREAD

**Issue by lenny31** [osm-fr/infrastructure#511]
Bonjour

Serait-il possible d'ajouter [orthophotoplan 2022 de Toulouse Métropole](https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2022/map/?basemap=jawg.streets&location=11,43.64924,1.40076) afin de pouvoir la retrouver dans JOSM ?

cordialement

**Comment by cquest** [comment]
C'est ajouté, couche WMS toulouse_2022 et intégré dans tous_fr en TMS.
