### ISSUE TITLE
Disques SSD

### ISSUE THREAD

**Issue by anayrat** [osm-fr/infrastructure#512]
Vu pour qu'il faut changer de SSD pour OSM 13, je pense qu'il faudrait s'attarder sur le type de SSD.
Entre un SSD grand public et un SSD datacenter, il y a un monde, mais vraiment.
Pour du Postgres, on a besoin d'IOPS en lecture écriture. Les SSD grand public ont déjà une endurance plus faible, mais surtout des performances désastreuses, l'écart peut être d'un facteur 100 voire 1000 :

* https://www.sebastien-han.fr/blog/2014/10/10/ceph-how-to-test-if-your-ssd-is-suitable-as-a-journal-device/
* https://www.percona.com/blog/fsync-performance-storage-devices/
* https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Hardware.html#power-failure-protection
* https://docs.google.com/spreadsheets/d/1E9-eXjzsKboiCCX-0u0r5fAjjufLKayaut_FOPxYZjc/edit#gid=0

Il faut des SSD avec des condensateurs : https://yourcmc.ru/wiki/Ceph_performance#CAPACITORS.21

Chez Samsung : https://semiconductor.samsung.com/ssd/datacenter-ssd/

On peut aussi regarder chez Micron ([7450 MAX ](https://media-www.micron.com/-/media/client/global/documents/products/technical-marketing-brief/7450_nvme_ssd_tech_prod_spec.pdf?la=en&rev=80f299c8d919490da865622349ef58b4) )

**Comment by anayrat** [comment]
@cquest  pour info

**Comment by cquest** [comment]
Les derniers M.2 achetés étaient des Samsung PM9A3 en 4To

Pour les U.2, Moji m'a conseillé les P4510 d'Intel.
