### ISSUE TITLE
Avenir de geoviso.openstreetmap.fr : à supprimer ?

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#514]
Une instance de geovisio avait été installée sur osm33, elle ne semble plus maintenue et plus d'actualité.

Je propose de la supprimer.

**Comment by cquest** [comment]
J'ai stoppé le conteneur... si personne ne se manifeste, on pourra l'archiver voire le supprimer.

**Comment by PanierAvide** [comment]
À priori pas de souci à ce que ce soit supprimé, c'était effectivement les premiers tests de déploiement, maintenant une infra à plus grande échelle est en place :grin:

**Comment by cquest** [comment]
https://geovisio.openstreetmap.fr est maintenant redirigé vers https://panoramax.openstreetmap.fr
