### ISSUE TITLE
http://openstreetmap.fr/ban : mauvais certif. SSL et 404

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/infrastructure#52]
Hello,

La page http://openstreetmap.fr/ban (citée dans la page BAN de data.gouv) provoque une alerte de sécurité SSL et indique "{"url":"/ban not found"}"

HTH

**Comment by Marc-marc-marc** [comment]
https://www.openstreetmap.fr/ban
mais il faudrait en effet un redirect de openstreetmap.fr/ban vers www.openstreetmap.fr

**Comment by deuzeffe** [comment]
Ah vi, c'était tout *on. Mais faut une intervention pour mettre en place un redirect et s'ocuper du certif. @Marc-marc-marc Tu assignes qui de droit (ou tu as toi-même les droits pour) ?

**Comment by jocelynj** [comment]
J'ai changé les DNS hier pour déplacer une ipv4 de openstreetmap.fr vers la nouvelle VM pour les mail. Est-ce que ça marchait avant ?

Sinon, j'ai activé le proxy pour openstreetmap.fr, mais pas encore le certificat https.

**Comment by jocelynj** [comment]
Ça marche maintenant.

**Comment by deuzeffe** [comment]
Thx!
