### ISSUE TITLE
download.osm.fr - diff - Objet supp dans le diff mais pas dans OSM

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#520]
Dans ce diff http://download.openstreetmap.fr/replication/europe/france/aquitaine/pyrenees_atlantiques/minute/005/906/744.osc.gz
Les objets sont marqués comme supprimé alors qu'ils viennent juste d'être crée dans OSM (et non supprimé en même temps).

Par ex
https://www.openstreetmap.org/way/1237297955

dans le diff
```xml
<osmChange version="0.6" generator="OsmSax">
<delete>
[...]
<way id="1237297955" version="1" timestamp="2024-01-05T15:22:13Z" uid="20810529" user="NomadeOTSX" changeset="145926583">
<bbox minlat="43.562668200000005" minlon="-1.4467021" maxlat="43.564783999999996" maxlon="-1.4446027000000001"/>
<tag k="amenity" v="shelter"/>
<tag k="building" v="yes"/>
<nd ref="11491931290"/>
<nd ref="11491931291"/>
<nd ref="11491931292"/>
<nd ref="1613554703"/>
<nd ref="11491931290"/>
</way>
[...]
</delete>
</osmChange>
```

**Comment by jocelynj** [comment]
Je vois que ce way a été ajouté dans le département des Landes, ce qui a l'air correct:
http://download.openstreetmap.fr/replication/europe/france/aquitaine/landes/minute/005/906/744.osc.gz
