### ISSUE TITLE
La fédération de l'instance Mastodon ne se fait pas

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#521]
De nombreuses instances Mastodon ne voient pas l'instance https://fr.osm.social/

On peut citer : masto.bike, piaille.fr, mastodon.underworld.fr, mastodon.mim-libre.fr...

Merci !

**Comment by cquest** [comment]
Premier test: le ping !
- masto.bike : ok, en IPv4
- piaille.fr : ok, en IPv6
- mastodon.underworld.fr : **injoignable**
- mastodon.mim-libre.fr : ok, en IPv4

Dans sidekick je trouve des erreurs de type suite à l'envoi d'un MP à destination des admins de ces instances...
`Mastodon::UnexpectedResponseError: https://mastodon.underworld.fr/inbox returned code 401
`

Un blocage de leur côté ?

**Comment by bristow** [comment]
Tu peux aussi rajouter https://mastodon.ouvaton.coop/

Ce sont quand même de grosses instances pour avoir des dysfonctionnements, non ?

**Comment by bristow** [comment]
Pas de problèmes de timesync sur l'instance ?

J'ai vu cela : https://github.com/mastodon/mastodon/discussions/18755

**Comment by cquest** [comment]
Le problème venait du système de "webfinger" qui ne passait pas le premier proxy...

Problème règlé !
