### ISSUE TITLE
download.openstreetmap.fr minutely replication stalled?

### ISSUE THREAD

**Issue by djerrard** [osm-fr/infrastructure#522]
Several of the minutely `state.txt` files on download.openstreetmap.fr have stalled at:
```
#Mon Jan 08 07:55:09 UTC 2024
sequenceNumber=5910515
timestamp=2024-01-08T07\:54\:45Z
```

For example:
https://download.openstreetmap.fr/replication/oceania/minute/state.txt
https://download.openstreetmap.fr/replication/planet/minute/state.txt

This is possibly related to #513? I note that host osm14 was to be replaced? With service "171 = download, to reinstall for migration"?

Just checking that this is work-in-progress as part of a scheduled upgrade, or whether something has broken perhaps?

**Comment by jocelynj** [comment]
No, there is no link with #513, as we haven't started the migration yet.

In fact, the update process was broken, and I've restarted it. It should take several hours/days to go back to the latest minute.

**Comment by djerrard** [comment]
Thankyou jocelynj.  We are again reading data into our system.  Appreciate your timely response.  Cheers!

(I don't know if it is up to me, but this issue can be considered closed as far as I'm concerned.)

**Comment by jocelynj** [comment]
I will close this ticket when we will have reached the latest state.

**Comment by jocelynj** [comment]
It is now fine, thanks for having reporting the issue.

**Comment by djerrard** [comment]
Thank you for fixing it! :-)
