### ISSUE TITLE
Maj instance Peertube

### ISSUE THREAD

**Issue by gendy54** [osm-fr/infrastructure#523]
Hello,

Maj à faire pour notre instance Peertube: la V6 est sortie.

**Comment by Cyrille37** [comment]
related: #499

**Comment by tomtoom1978** [comment]
Bonjour, Le SOTM FR arrive a grand pas.
Est il possible de faire la MAJ vers 6.1 avant que je test la fonction live en avance.
Attention je sais qu'il y a pas mal de chose a faire attention depuis l'évolution vers les versions 6.xx
Merci

**Comment by jocelynj** [comment]
Je vais planifier ça pour la semaine du 13 mai. Ça ira pour que tu puisses tester ?

D’ailleurs, la dernière fois, on avait pas eu des soucis de performance pour utiliser le serveur d’OSM-FR pour le live ?

**Comment by tomtoom1978** [comment]
Salut,
Si effectivement les performances CPU étaient trop juste, mais nous avions fait **plusieurs directs en simultanés** l'année dernière. Cette année il n'y a qu'un seul flux en direct, cela devrait donc passer sans problème avec la configuration actuelle.
Pas d'urgence pour la mises a niveau du peertube. Après le 13 c'est parfait.

**Comment by jocelynj** [comment]
Je viens de mettre à jour vers la version 6.1.0.

J’ai quelques erreurs dans les logs, mais ça n’a pas l’air bloquant:
```
May 13 19:47:03 peertube peertube[2276891]: It is highly recommended to use a minimum Redis version of 6.2.0
May 13 19:47:03 peertube peertube[2276891]:            Current: 6.0.16

May 13 19:47:03 peertube peertube[2276891]: [peertube.openstreetmap.fr:443] 2024-05-13 19:47:03.760 error: Cannot register plugin glavliiit, skipping. {

May 13 19:47:03 peertube peertube[2276891]: [peertube.openstreetmap.fr:443] 2024-05-13 19:47:03.760 error: Cannot register plugin upload-limits, skipping. {

May 13 19:47:03 peertube peertube[2276891]: [peertube.openstreetmap.fr:443] 2024-05-13 19:47:03.761 error: Cannot register plugin chapters, skipping. {

May 13 19:47:03 peertube peertube[2276891]: [peertube.openstreetmap.fr:443] 2024-05-13 19:47:03.762 error: Cannot register plugin video-annotation, skipping. {
```

Est-ce que ces plugins sont utiles ? Faut-il les installer à la main via `node install peertube-plugin-*` ?

**Comment by jocelynj** [comment]
Les plugins sont corrigés: la config yaml ne référençait pas le bon dossier.

**Comment by Cyrille37** [comment]
Merci @jocelynj :-)

**Comment by tomtoom1978** [comment]
C'est vrai, un grand merci @jocelynj 
J'ai pas mal testé, tout est OK !
Et Je vais procéder à des tests de diffusion en direct prochainement.

**Comment by Cyrille37** [comment]
Je me permets de ferme le ticket puisqu'il y a eu une suite #558
