### ISSUE TITLE
download.openstreetmap.fr extracts missing

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/infrastructure#526]
All the extracts are missing, and the state files are blank, for example https://download.openstreetmap.fr/extracts/north-america/canada/ontario

**Comment by jocelynj** [comment]
This issue is indirectly linked to #522: the diff generation stopped for more than 2 days, and it broke the process updating pbf files, which removed the pbf file, as it didn't see any diff to apply.

I've fixed the script, and will regenerate all extracts from planet. It will take a few days.

**Comment by jocelynj** [comment]
Extracts were all regenerated, but are one week old. I'm in the process of updating them to latest state.

**Comment by jocelynj** [comment]
It should work correctly now.
