### ISSUE TITLE
Configuration nouveau tuileur renderd-bzh.vm.openstreetmap.fr

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#527]
À cause de #525 on dispose d'une nouvelle VM nommée `renderd-bzh.vm.openstreetmap.fr` sur le cluster [TH3](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France/TH3).
Il s'agit maintenant de la configurer le tuileur afin de servir les services de cartes en langues minoritaires.

Le domaine servi est : `tile.openstreetmap.bzh`

## base machine

- [x] accès ssh
- [x] accès base OSM

## Tuyauterie web

- [x] frontal nginx : tile.openstreetmap.bzh
- [x] frontal nginx : monit.tile.openstreetmap.bzh
- [x] frontal nginx : proxy_set_header   X-Real-IP voir [ce ticket](https://github.com/osm-fr/infrastructure/issues/34#issuecomment-399773863)
- [x] apache : ajout conf remoteIP
- [x] DNS : redirection vers le frontal
- [x] frontal nginx : https

## Tuileur

- [x] git clone projet de rendu
- [x] configuration mapnik
- [x] rotation des logs apache
- [x] monit : configuration basique
- [x] monit : configuration avancée (purge si espace disque restreint)

## Bonus
- [x] configuration goaccess

**Comment by MaelREBOUX** [comment]
Le tuileur est opérationnel.

J'ai repris mes playbooks créés en juillet suite à la migration vers la VM actuelle afin de coller aux playbooks osm-fr.

C'est par ici : https://github.com/osm-bzh/osmbr-mapstyle/tree/master/ansible
et je ferai une PR dans qqs jours.

**Comment by MaelREBOUX** [comment]
@jocelynj a écrit : 

> on va sur la base osm2pgsql de osmfr, qui est un peu chargée. Il faudrait installer une autre base sur le même host que renderd-bzh

Comme le tuileur actuel est cassé depuis début décembre et ne vit plus que sur le cache calculé en stock, je suis pour :

1.  basculer en production ce tuileur dès maintenant
2.  changer de base de données quand celle qui sera sur oms27 sera disponible

**Comment by MaelREBOUX** [comment]
Le problème d'absence du fichier `/var/run/renderd/renderd.pid`est revenu. Étrange. À moins qu'il soit uniquement généré en mode debug ?

Donc :

```bash
nano /lib/systemd/system/renderd.service 
```

```
[Unit]
Description=Daemon that renders map tiles using mapnik
Documentation=man:renderd
After=network.target auditd.service

[Service]
Type=forking
ExecStart=/usr/bin/renderd
PIDFile=/var/run/renderd/renderd.pid
User=_renderd

[Install]
WantedBy=multi-user.target
```

```bash
systemctl daemon-reload
service apache2 stop
service renderd restart
service apache2 start
```

Le fichier `renderd.pid` apparaît !
**À intégrer dans le role ansible.**

**Comment by MaelREBOUX** [comment]
Sur les conseils de @jocelynj il faut utiliser le système d'override de systemd.
De plus je m'aligne sur la configuration du tuileur rendu FR avec systemd qui gère le restart automatique.

Donc : 

```bash
service renderd stop 
systemctl edit renderd
```

```
### Editing /etc/systemd/system/renderd.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file

Restart=always
RestartSec=30s
RuntimeMaxSec=1d

### Lines below this comment will be discarded

### /lib/systemd/system/renderd.service
# [Unit]
# Description=Daemon that renders map tiles using mapnik
# Documentation=man:renderd
# After=network.target auditd.service
# 
# [Service]
# ExecStart=/usr/bin/renderd -f
# User=_renderd
# 
# [Install]
# WantedBy=multi-user.target
```

```bash
systemctl daemon-reload
service renderd start
service apache2 restart
```

**Comment by MaelREBOUX** [comment]
J'ai configuré un goaccess avec cron toutes les 5 minutes.

**Comment by MaelREBOUX** [comment]
Il ne manque plus que la remise en place de HTTPS.

**Comment by MaelREBOUX** [comment]
HTTPS en place.
Ne reste plus que la purge auto des niveaux les plus bas si plus de place sur le serveur.

**Comment by Marc-marc-marc** [comment]
il y a régression sur le partitionnement avec tout à nouveau dans un / et des path non standard comparé à bzh202.vm qui avait remis les choses à leur place conventionnelle

**Comment by jocelynj** [comment]
Concernant le stockage des tuiles, on utilise `/var/lib/mod_tile`, qui est l'ancienne configuration. Mais je vois que les renderd récents utilisent `/var/cache/renderd/tiles/`, qui semble plus logique. Du coup, utiliser ce dernier chemin pour les nouvelles installations serait pas plus mal.

**Comment by Marc-marc-marc** [comment]
> Bonjour @Marc-marc-marc Sur `bzh202.vm` tu avais unilatéralement procédé à des modifications sans m'en avertir.

je ne comprend pas ce que tu veux dire
à l'installation j'avais fais par exemple une partition /var/log
c'est pas un choix de ma part qu'une installation standard linux met ces logs à cet endroit
idem pour le répertoire des tuiles
idem pour /data/project un standard depuis des années dans l'asso (libre à toi de l'utiliser ou pas)
sur la nouvelle vm tout est à nouveau dans une partition unique

>j e stocke dans /data/tiles/ 
> En quoi est-ce embêtant ?

parce que c'est non standard, donc si qlq fait une opération (par ex lister la taille des tuiles), sur tous les tuileurs hébergés, il faut rajouter un "mais si c'est bzh alors va dans tel répertoire"
pour prendre une cas réel : un serveur précédent avait saturé, si tu regardes la tailles des différents répertoires mais que chaque éléments courant est dans un répertoire principal non conventionnel, cela augmente le temps de compréhension
S'il y a une raison pour changer, pq pas, mais si changer pour simplement avoir tout ailleurs que la convention, cela me semble contreproductiif

**Comment by MaelREBOUX** [comment]
Je viens de déplacer les tuiles vers `/var/cache/renderd/tiles/` et de tout reconfigurer en conséquence.

Il me reste à modifier encore le monitoring car ce chemin est sur un point de montage à part donc là l'espace disque vient de tomber à 2,5 %.

**Comment by MaelREBOUX** [comment]
Voilà. J'ai reconfiguré monit pour le suivi de l'espace disque uniquement sur le point de montage de 100 Go dédié aux tuiles.

**Comment by MaelREBOUX** [comment]
Bon.
Il faudrait dans l'absolu redéployer tout sur une nouvelle VM pour valider les modifications du playbook.
Mais c'est une autre histoire avec je ferme ce ticket.
