### ISSUE TITLE
Augmenter la RAM sur bano.vm

### ISSUE THREAD

**Issue by vdct** [osm-fr/infrastructure#533]
Bonjour
presque tout est dans le titre. Depuis 18 mois j'ai complètement refondu les traitements BANO, et certains qui étaient gérés par département sont maintenant appréhendés France entière, c'est beaucoup plus efficace côté lecture de la BD. Cependant j'observe de manière irrégulière des plantages lors des mises à jour nocturnes : à iso code, ça passe crème certains jours et ça explose en vol d'autres jours. Je constate qu'il n'y a que 8Go de RAM sur la vm et je me demande s'il serait possible de passer de 8 à 16Go afin de constater si ces plantages disparaissent ou non. 

merci pour vos avis

**Comment by jocelynj** [comment]
J'ai monté à 12G la quantité de ram sur la VM, depuis le host osm12. D'apès munin, on utilise quasi toute la ram sur le host: http://munin.openstreetmap.fr/osm12.openstreetmap.fr/osm12.openstreetmap.fr/memory.html

**Comment by vdct** [comment]
Merci @jocelynj
