### ISSUE TITLE
le site educosm est tombé ...

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#534]
https://educosm.openstreetmap.fr/ est tombé 

> Pour des raisons indépendantes de notre volonté, le contenu de ce YesWiki est temporairement inaccessible. Probablement l'accès à la base de données a échoué. Veuillez réessayer ultérieurement, merci de votre compréhension.

**Comment by jocelynj** [comment]
Je vois que la base de donnée mariadb a été tué par l'OOM-killer - faudra vérifier la quantité de mémoire utilisé, et peut-être augmenter la mémoire sur cette VM:
```
Jan 10 00:02:46 educosm systemd[1]: mariadb.service: A process of this unit has been killed by the OOM killer.
Jan 10 00:02:46 educosm systemd[1]: mariadb.service: Main process exited, code=killed, status=9/KILL
Jan 10 00:02:46 educosm systemd[1]: mariadb.service: Failed with result 'oom-kill'.
Jan 10 00:02:46 educosm systemd[1]: mariadb.service: Consumed 6h 47min 53.322s CPU time.
```

J'ai redémarré mariadb, et le site remarche.

**Comment by jocelynj** [comment]
J'ai augmenté la RAM de 1Go à 2Go, en espérant que ça ne casse pas dans l'avenir.

**Comment by vinber** [comment]
merci, bisous :)
