### ISSUE TITLE
wms.openstreetmap.fr erreur 502

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#535]
Bonsoir

Les couches services par https://wms.openstreetmap.fr, dont les vues Enedis sont inaccessibles.
Le serveur renvoi une erreur 502.

Est-ce déjà tracé dans une autre issue ?

**Comment by jocelynj** [comment]
Le containeur a été tué par proxmox à ce qu'on dirait:
```
command 'lxc-stop -n 107 --kill' failed: received interrupt

TASK ERROR: received interrupt
```
Et le démarrage foirce - je creuse.

**Comment by jocelynj** [comment]
Après investigation, le CT a crashé brutalement le 5 février, et a laissé un process zombie:
```
www-data  800607  0.6  0.0      0     0 ?        Zl   Feb05  28:36 [apache2] <defunct>
```
Ce process bloque le cgroup `/sys/fs/cgroup/lxc/107/ns/system.slice/apache2.service`, ce qui empêche lxc de démarrer ce CT 107.

Je ne vois pas d'autre solution que de redémarrer, ce que @cquest prévoit de faire sous peu.

**Comment by flacombe** [comment]
Merci @jocelynj d'avoir regardé, bonne soirée !

**Comment by XandrexOSM** [comment]
Le serveur a été redémarré, c'est OK je vois les tuiles dans JOSM. Merci @cquest !

**Comment by XandrexOSM** [comment]
j'ai à nouveau des erreurs HTTP 502.

**Comment by XandrexOSM** [comment]
les erreurs HTTP 502 sont encore présentes aujourd'hui.
Y a-t-il une date approx de remise en service, s'il vous plaît ?

**Comment by jocelynj** [comment]
La VM a planté a nouveau dans la semaine, et ne peut pas être redémarrée, suite à erreur côté lxc (la même que la dernière fois). Pas vraiment de solution à proposer, parce que rebooter le serveur à chaque fois n’est pas envisageable.

@cquest : faudrait-il réinstaller la VM ailleurs ?

**Comment by XandrexOSM** [comment]
possible de programmer la VM pour qu'elle se redémarre périodiquement de façon pré-emptive ? Genre quotidiennement ?

**Comment by cquest** [comment]
Je mettrai bien wms.openstreetmap.fr sur un serveur Moji, sur lequel on pourra avoir des disques de stockage adaptés pour la volumétrie des orthos.

Actuellement à TH3 on a des machines assez puissantes pour servir les flux WMS, mais qui n'ont pas assez de stockage, celui-ci étant fait sur osm32 qui est un serveur de stockage mais avec peu de ressources CPU et accédé par NFS... qui n'est peut être pas sans rapport avec nos plantages.

Les T630 de Moji, permettent d'avoir la capacité de stockage et le CPU sur la même machine.

**Comment by cquest** [comment]
wms.openstreetmap.fr temporairement relancé depuis ma cave...

**Comment by cquest** [comment]
Suite... https://github.com/osm-fr/infrastructure/issues/543
