### ISSUE TITLE
Stalled process - download.openstreetmap.fr minutely replication

### ISSUE THREAD

**Issue by djerrard** [osm-fr/infrastructure#537]
It appears that the update process on download.openstreetmap.fr may have stalled?  On the face of it, it appears to be similar to the problem identified in #522 

The lag graphs all suggest the same thing:
http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by jocelynj** [comment]
I've restarted the update process, after killing the process that were stalling.

I'm still not sure why it stops updating - maybe I need to add something to detect this case.

**Comment by jocelynj** [comment]
Lag is now a lot smaller.

**Comment by djerrard** [comment]
Thank you again for your help, Jocelyn
