### ISSUE TITLE
umap demande des tuiles en HTTP/3 => erreurs 404 qui n'aboutissent pas

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#539]
Depuis décembre / janvier des utilisateurs m'ont remonté des difficultés d'utilisation du fond de plan OSM BR sur des cartes umap.

Exemple avec https://umap.openstreetmap.fr/fr/map/stummaduriou-hir-200922-br_810020

En le chargeant : pas de fond et des erreurs 404 en direction du tuileur OSM BR.

![image](https://github.com/osm-fr/infrastructure/assets/6370443/2b91a7bf-0cfd-4eab-9294-dca196f1cb3b)

moi et @jocelynj  on a regardé les logs du frontal et du tuileur : aucune trace de ces requêtes qui ont quand même une erreur 404 en retour !

En regardant de plus près, on voit que umap demande les tuiles via du HTTP/3 :

![image](https://github.com/osm-fr/infrastructure/assets/6370443/67b20d7d-d0f0-49a6-9dd5-b73fb0da94e5)

Il y a un côté déroutant car aléatoire : si on attend un peu ou qu'on zoome ou qu'on recharge plusieurs fois -> umap rebascule en HTTP/2 et le fond de plan s'affiche.

Que faire et où pour régler ce problème ?

**Comment by jocelynj** [comment]
J’ai pu voir le même souci sur mon firefox, et c’est bien un souci lié à http3: firefox réutilise la connection pour umap pour demander les tuiles bzh, et se prend un 404 parce que nginx redirige vers le serveur umap. En désactivant http3 sur umap, les tuiles s’affichent correctement.

Un bug similaire existe côté firefox, pour http2, où firefox réutilise la même connection pour http2: https://bugzilla.mozilla.org/show_bug.cgi?id=1420777. Une solution possible est d’utiliser un certif https différent par serveur en http3.

**Comment by jocelynj** [comment]
En générant un certif https dédié pour umap.openstreetmap.fr, ça a l’air de marcher correctement.

@cquest : surement un truc à faire systématiquement avec http3, de générer un certif dédié par port udp http3.

**Comment by jocelynj** [comment]
Générer un certif https dédié à umap a bien permis de corriger le problème.
