### ISSUE TITLE
tile.openstreetmap.fr : pas de redirection http -> https ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/infrastructure#54]
Hello,

On dirait qu'il n'y a pas de redirection http -> https pour tile.openstreetmap. fr, malgré HTTPS Everywhere activé et forcé. Au passage, je suis tombée sur ça : https://www.eff.org/https-everywhere/atlas/domains/openstreetmap.fr.html

HTH

**Comment by jocelynj** [comment]
@deuzeffe: Est-ce qu'il y a toujours souci de redirection via HTTPS Everywhere ?

**Comment by deuzeffe** [comment]
@jocelynj yep, toujours pas de redirection auto. via HTTPS Everywhere :( (le sous-domaine n'est même pas listé dans l'atlas :/) Pb not solved.

**Comment by jocelynj** [comment]
Je vois que tile.openstreetmap.fr est bien listé sur https://atlas.eff.org//domains/openstreetmap.fr.html

En testant rapidement avec HTTPS Everywhere, j'ai bien la redirection http -> https.

@deuzeffe: tu peux confirmer ?

**Comment by deuzeffe** [comment]
@jocelynj Ayé, c'est retombé en marche chez moi, je ne sais pas quand, mais ça l'est \o/
