### ISSUE TITLE
Ortho Eurométropole de Strasbourg 2022

### ISSUE THREAD

**Issue by llongour** [osm-fr/infrastructure#540]
Bonjour,
La nouvelle orthophotographie de l'Eurométropole de Strasbourg (en ECW) est disponible ici:

https://www.swisstransfer.com/d/6103b2e9-7c9e-481c-9428-fba22443f043
https://www.swisstransfer.com/d/8c4203cf-2534-4864-b7b0-ad9f6eaa0514

Elle est documentée ici : https://data.strasbourg.eu/explore/dataset/service-wms-des-orthophotographies/table/

Est-ce que quelqu'un peut la mettre à disposition sur http://wms.openstreetmap.fr ?

edit: entre temps, un jp2 à été également mis à dispo ici : https://data.strasbourg.eu/explore/dataset/orthoimage_2022/information/

**Comment by cquest** [comment]
Les ECW semblent corrompus... je lance le téléchargement du JPEG2000

**Comment by cquest** [comment]
C'est en place sur wms.openstreetmap.fr, couche WMS strasbourg_2022 et dans tous_fr (WMS+TMS) !
