### ISSUE TITLE
services HS : tuiles Cadastre et BANO (layers)

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#542]
Bonjour

Les tuiles ne sont plus accessibles (samedi 2 mars 2024) :
- tms.cadastre.openstreetmap.fr
- layers.openstreetmap.fr/bano

Bien à vous :-)

Related: #317 #318 #316

**Comment by Cyrille37** [comment]
BANO est revenu, hyper rapide :-)

**Comment by frodrigo** [comment]
Pour moi tms.cadastre.openstreetmap.fr marche aussi.

**Comment by Cyrille37** [comment]
Hello. Oui, ça fonctionne à nouveau. En plus vraiment plus rapidement que dans la semaine.
Comme si les services avaient redémarré, tout frais :-)
