### ISSUE TITLE
le forum en PLS plusieurs fois depuis ce matin

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#545]
j'ai eu plusieurs fois depuis ce matin des 429 Too Many Requests sur le forum.

plus des comportements un peu erratiques

un F5 fait tout revenir ...

**Comment by jocelynj** [comment]
Est-ce que ça le fait de nouveau ?

Je vais creuser du côté des logs du serveur.

**Comment by Cyrille37** [comment]
`claudebot`  -> https://claude.ai/  :-(

**Comment by jocelynj** [comment]
Vu que ça remarche correctement, je ferme ce ticket.
