### ISSUE TITLE
service HS : tile.openstreetmap.fr/osmfr HTTP 502

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#547]
Le style **osmfr** répond 502 Bad Gateway

https://a.tile.openstreetmap.fr/osmfr/12/2053/1433.png

**Comment by cquest** [comment]
Retour du service un peu plus tôt aujourd'hui.

**Comment by Cyrille37** [comment]
Salut @cquest 
Si je peux faire quelque chose pour relancer ces services quand ils tombent, j'ai qlqs habitudes de gestion de serveurs, je suis volontaire ;-)
