### ISSUE TITLE
plus d'accès ssh notes-heatmap (osm28)

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#548]
Hello

Ça fonctionnait et paf, à un moment sans changement sur les configs ça ne fonctionne plus... Depuis chez moi et depuis osm28 avec ssh cgiquello@notes-heatmap.vm.openstreetmap.fr

```
kex_exchange_identification: read: Connection reset by peer
Connection reset by 2001:41d0:1008:2c6b:1::194 port 22
```

À noter que le service web nginx fonctionne, c'est seulement `ssh` qui ne veut plus.

C'est aussi arrivé précédement dans la journée mais comme j'avais plusieurs consoles ouvertes j'ai pu faire un `sudo systemctl restart sshd`. Mais là n'ayant plus de console ouverte je ne sais pas comment faire :(

Je n'observce rien de particulier sur https://munin.openstreetmap.fr/osm28.openstreetmap.fr/notes-heatmap.vm.openstreetmap.fr/

**Comment by jocelynj** [comment]
J’ai redémarré ssh sur ce serveur.

**Comment by Cyrille37** [comment]
Merci @jocelynj 

Je fais quelques accès et essaye de trouver un diagnostic / une solution.
