### ISSUE TITLE
Impossible d'envoyer des images sur panoramax OSM-FR : https://panoramax.openstreetmap.fr:5173/ -- (failed)net::ERR_CONNECTION_REFUSE

### ISSUE THREAD

**Issue by cayenne17** [osm-fr/infrastructure#549]
Bonjour,

Il est impossible d'envoyer des images sur l'instance panoramax d'OSM-FR.

ça tourne en boucle 
![image](https://github.com/osm-fr/infrastructure/assets/47927025/b4b14b4f-314a-46c0-9500-e552cc0a772c)

en mode DEV, ça boucle sur : 
https://panoramax.openstreetmap.fr:5173/ : (failed)net::ERR_CONNECTION_REFUSE
![20240403_13h32_19s_vivaldi_JAiGghK63h](https://github.com/osm-fr/infrastructure/assets/47927025/608d6e03-8f70-495a-9c6a-da4b89bd59b3)

**Comment by PanierAvide** [comment]
Bonjour,

Je viens de tester de mon côté, et ça semble fonctionner, ce qui laisse présager un problème soit réseau, soit de navigateur. Quel navigateur a été utilisé et quelle version ? Y a t'il un proxy sur le réseau qui pourrait causer des blocages ?

Cordialement.

**Comment by cayenne17** [comment]
@PanierAvide 
Je suis chez moi en Fibre optique Free.
ça semble provenir de mon navigateur Vivaldi. je viens de tester sur Firefox et ça a fonctionné : https://panoramax.openstreetmap.fr/sequence/22989c21-30ef-4b4b-88a0-6bb135f247e8#background=streets&focus=pic&map=5/47/3&pic=9e2035d3-7f45-47ae-9deb-9f1fef0554a1&speed=250&xyz=36.00/0.00/30

Je vais investiguer d'où vient le problème plus tard

**Comment by cayenne17** [comment]
@PanierAvide Je viens de réessayer sur mon navigateur Vivaldi sans faire de changement et sans l'avoir fermé entre temps.

ça m'a redirigé vers la page d'authentification Oauth2 osm.org en me demandant des autorisations. Et ensuite, ça a fonctionné.

**Comment by cayenne17** [comment]
@PanierAvide Est-ce que je ferme ce issue pour en ouvrir un autre sur https://github.com/panoramax-project/panoramax-website/issues ?

**Comment by PanierAvide** [comment]
Plutôt à créer ici, et en décrivant en détail la procédure pour reproduire le souci, merci :wink: 

https://gitlab.com/geovisio/website/-/issues/?sort=created_date&state=opened&first_page_size=100

**Comment by cayenne17** [comment]
@PanierAvide : https://gitlab.com/geovisio/website/-/issues/78
