### ISSUE TITLE
proxy-ign.openstreetmap.fr en IPv6

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#55]
ino de Bonbadil sur irc : 
proxy-ign.openstreetmap.fr répond au ping en IPv4 mais pas en IPv6 et surtout pas en http

**Comment by jocelynj** [comment]
Ce hostname pointe vers une VM qu'on ne maitrise pas à 100%, et je ne pense pas qu'on puisse activer le ping en ipv6.

Est-ce qu'on peut quand même accéder au service en ipv6 ?

**Comment by Bonbadil** [comment]
Non. Un test rapide d'affichage d'une tuile dans Firefox avec une connexion IPv4 seulement ou IPv6 seulement montre qu'elle ne s'affiche qu'en IPv4. De même, désactiver l'IPv6 dans JOSM (prefer.ipv6=false dans les options avancées) a permit de contourner le problème.

À défaut de pouvoir permettre les connexions IPv6 sur cette VM, peut-être faudrait-il supprimer la résolution de proxy-ign.openstreetmap.fr en IPv6 ?
C'est à dire remplacer
```
proxy-ign.openstreetmap.fr.	CNAME	osm24.openstreetmap.fr.
osm24.openstreetmap.fr.		A	77.95.65.41
```
par
```
proxy-ign.openstreetmap.fr.	A	77.95.65.41
```
Ou si osm24.openstreetmap.fr. ne répond pas du tout en IPv6, supprimer carrément son champ AAAA.

**Comment by jocelynj** [comment]
In fact, the ipv6 configuration is incorrect. osm26 has ipv6 2a03:9180:0:100::9. I will fix this on the DNS server.

**Comment by jocelynj** [comment]
Je me suis trompé dans mon message précédent: c'est bien osm24 que j'ai changé:
```
$ host osm24.openstreetmap.fr
osm24.openstreetmap.fr has address 77.95.65.41
osm24.openstreetmap.fr has IPv6 address 2a03:9180:0:100::9
```

Est-ce que tu peux confirmer que proxy-ign marche en ipv6 ?

**Comment by Bonbadil** [comment]
Oui, avec seulement IPv6 d'activée sur ma connexion, j'ai pu afficher les tuiles dans Firefox et JOSM.
Le ticket peut être clôturé. Merci.
