### ISSUE TITLE
Osmose en erreur 503

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#553]
Bonjour

Depuis hier midi le front d'Osmose affiche une erreur 503
osmose.openstreetmap.fr/

@frodrigo

**Comment by frodrigo** [comment]
C'est relancé. Je n'ai pas regardé la cause.

Non, mais même en cours de migration ça ne peut pas rester off pendant des heures.

Ce n'est pas qq mapnip du front qui font planter le serveur, mais tout ce qu'il fait a coté.
