### ISSUE TITLE
tile.openstreetmap.fr BdTopo http 502 bad gateway

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#554]
Hello

Cette fois-ci c'est https://c.tile.openstreetmap.fr/bdtopo/19/263007/183444.png qui répond HTTP 502.

**Comment by Cyrille37** [comment]
Salut @cquest @jocelynj @Marc-marc-marc 

Est-ce un serveur en cours de migration ?

Si c'est juste des services à redémarrer, je peux être initié aux manips (*j'ai plusieurs debian/ubuntu en production pour des clients*). Ma clé ssh est déjà sur osm28, osm157 et osm-notes-heatmap.

**Comment by jocelynj** [comment]
bdtopo est hébergé sur osm13, et l'accès ssh a l'air planté. @cquest: des infos sur cette machine qui devrait être chez toi ?

D'après munin, elle n'est plus accessible depuis le 10 avril.

**Comment by Cyrille37** [comment]
BD Topo répond, je ferme le ticket
