### ISSUE TITLE
Plus de Scan 25

### ISSUE THREAD

**Issue by pyrog** [osm-fr/infrastructure#555]
https://wxs-pgie.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR.CV&STYLE=normal&FORMAT=image/jpeg&tileMatrixSet=PM&tileMatrix=19&tileRow=188508&tileCol=270224

Erreur dans le navigateur : 
```xml
<ExceptionReport xmlns="http://www.opengis.net/ows/1.1">
<Exception exceptionCode="Not Found">No data found</Exception>
</ExceptionReport>
```

Erreur dans JOSM : 599

Les tuiles s'affichent mais très lentement 😢

**Comment by frodrigo** [comment]
C'est une URL de l'IGN, c'est quoi le lien avec OSM-FR ?

**Comment by pyrog** [comment]
Ok, est-ce qu'il existe un proxy OSM FR ?

**Comment by pyrog** [comment]
Bien vu 😅

**Comment by pyrog** [comment]
Bien vu 😅

**Comment by cquest** [comment]
Toutes les URL des services IGN ont changé avec la bascule vers la géoplateforme... à mettre à jour, une fois qu'on a trouvé la nouvelle qui va bien.
