### ISSUE TITLE
QGIS : Échec de la connexion à OSM sur les ordinateurs connectés derrière un proxy après quelques minutes

### ISSUE THREAD

**Issue by wilcar** [osm-fr/infrastructure#557]
Contexte : utilisation d'OSM dans QGIS sur 15 ordinateurs connectés à mon réseau universitaire derrière un serveur proxy. OSM fonctionne bien au début pour 10 machines sur 15 (le reste = "écran blanc")  mais après quelques minutes, une bannière orange apparaît sur chaque ordinateur. Bannière orange avec le message "the network request to tile.openstreetmap has been interrupted...".

Par contre, d'autres fournisseurs comme Googlemaps ou bingMaps fonctionnent bien.

Une idée ?

Pensez-vous que le serveur OSM interrompt la connexion par sécurité  en raison d'un grand nombre de requêtes provenant de la même adresse IP ?

![image](https://github.com/osm-fr/infrastructure/assets/18226229/c938506a-c3ce-46f4-b35f-455c8378ed18)

**Comment by zorun** [comment]
D'après le screenshot, ça concerne tile.openstreetmap.org, qui n'est pas géré par l'association OSM-FR.

**Comment by zorun** [comment]
En tout cas oui le proxy est certainement la cause, en tout cas le premier point à creuser.

Pour avoir de l'aide en français tu auras sûrement plus de chances sur https://forum.openstreetmap.fr

**Comment by Cyrille37** [comment]
Bonjour @wilcar 

Comme le dit @zorun il semble que ça ne soit en rapport avec l'infrastructure OSM France. Si tel est le cas pourrais-tu fermer le ticket, et reprendre sur https://forum.openstreetmap.fr/ ;-)
