### ISSUE TITLE
Création nouvelle chaine impossible sur Peertube

### ISSUE THREAD

**Issue by tomtoom1978** [osm-fr/infrastructure#558]
Pour info, je ne peux plus créer de nouvelle chaine sur le peertube.
je vous voulais créer la chaine du SOTM fr 2024, un message m'indiquant que je ne peux pas créer 2 chaines apparait.
Je suis bien en admin pourtant.

**Comment by Jean-BaptisteC** [comment]
Il existe un paramètre pour limiter le nombre de chaines créées par utilisateur `video_channels.max_per_user`

**Comment by jocelynj** [comment]
Ah oui, merci @Jean-BaptisteC . J’ai augmenté la limite à 5.

**Comment by tomtoom1978** [comment]
> Ah oui, merci @Jean-BaptisteC . J’ai augmenté la limite à 5.

Merci c'est bien ça, car le message m'indique maintenant que je ne peux pas dépasser la création de 5 chaines ;-)
Effectivement actuellement le compte à déjà 6 chaînes actives (1 chaine / année depuis 2019)

Il faudrait augmenter cette limite à 10 pour que je vous laisse tranquil jusqu'en 2028 ;-)
Merci pas avance

**Comment by jocelynj** [comment]
Je viens de monter la limite à 10.

**Comment by tomtoom1978** [comment]
> Je viens de monter la limite à 10.

Merci, la chaîne est crée !
https://peertube.openstreetmap.fr/c/sotm_fr_2024/videos

**Comment by Jean-BaptisteC** [comment]
@tomtoom1978 est ce que le stream sur peertube peut déja être créé et mis en privé pour le moment ?

**Comment by tomtoom1978** [comment]
> @tomtoom1978 est ce que le stream sur peertube peut déja être créé et mis en privé pour le moment ?

**Salut, j'ai testé le serveur pour du direct et ça roule parfaitement !**

Un flux de direct est actif, mais il faut plutôt utiliser l'intégration de la liste de lecture 2024 pour le site web,  cela permettra de mettre une boucle d'attente, un replay, etc... et de faire la bascule pour le live sur le site directement à partir de peertube, sans toucher au site. (on avait fait ça en 2023)

Pour info si la liste de lecture contient des vidéos privés, les vidéos seront visibles. La liste de lecture 2024 actuelle est donc intégrable en l'état, car le flux du live est hors-ligne. il sera afficher une image c'est propre.

**Liens de la liste de lecture:**
https://peertube.openstreetmap.fr/w/p/tu2CjS1zmuJ1ND9Lni8EoP
https://peertube.openstreetmap.fr/video-playlists/embed/de909255-bba3-44e6-9a5d-84bb6f23dbcb

**Lien intégrationliste de lecture:**
`<div style="position: relative; padding-top: 56.25%;"><iframe title="WEB SOTM∙France₂₀₂₄" width="100%" height="100%" src="https://peertube.openstreetmap.fr/video-playlists/embed/de909255-bba3-44e6-9a5d-84bb6f23dbcb" frameborder="0" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups allow-forms" style="position: absolute; inset: 0px;"></iframe></div>`

En plus:
**Liens du direct: (opter pour la lecture, via liste de lecture)**
https://peertube.openstreetmap.fr/w/bRN4ssrVrLWoS2RAabqkYe
**intégration du direct: (opter pour la lecture, via liste de lecture)**
`<iframe title="State of the Map∙France₂₀₂₄   ≡ Direct/Live ≡" width="560" height="315" src="https://peertube.openstreetmap.fr/videos/embed/57ef3770-7812-41ef-89e0-9466b231f369" frameborder="0" allowfullscreen="" sandbox="allow-same-origin allow-scripts allow-popups allow-forms"></iframe>`

**Comment by Jean-BaptisteC** [comment]
Merci pour les infos, le sujet va être surement rediscuté car l'année dernière c'était K-prod qui hébergeait le stream sur sa propre instance Peertube

**Comment by tomtoom1978** [comment]
> Merci pour les infos, le sujet va être surement rediscuté car l'année dernière c'était K-prod qui hébergeait le stream sur sa propre instance Peertube

En fait l'année dernière, nous avions fait 4 flux vidéos simultanément, et le serveur peertube de l'association ne pouvait pas supporter la demande en charge CPU pour transcoder tous les flux, il en prenait en charge 3 (c'est déjà super bien). le dernier flux était dirigé sur le serveur de kprod.

Pour cette année, on sera donc en 100% avec le serveur de l'association.

**Comment by Jean-BaptisteC** [comment]
Donc dans le cas ou on est en multistream on a d'autres choses à faire ?
Comment les utilisateurs font pour naviguer entre les streams via une playlist ?

**Comment by tomtoom1978** [comment]
> Donc dans le cas ou on est en multistream on a d'autres choses à faire ? Comment les utilisateurs font pour naviguer entre les streams via une playlist ?

Effectivement il faudrait soit naviguer dans une liste de lecture, mais c'est pas pratique et peu voyant. Soit plutôt valider la chose dès possible au niveau du bureau et réfléchir peut être à faire une deuxième liste de lecture avec ce deuxième direct sur cette 2e liste et ajouter cela dans le site internet surtout.

Mais je crois qu'il était prévu qu'1 seul direct et une mises en ligne des replays dès la semaine suivante.
Il faut me tenir informé de l'évolution s'il y a !

**Comment by Jean-BaptisteC** [comment]
C'est bien ce que j'avais en tête un seul stream, merci pour tes réponses
