### ISSUE TITLE
Ajout token matomo sur gespot et map.infos-reseaux.com

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#560]
Hello

Il me semble que nous avons une instance de Matomo pour les services de l'asso.
Je souhaiterais suivre l'usage de gespot.fr, hébergé sur osm34.

Est-ce possible d'avoir un token s'il vous plaît ?

**Comment by jocelynj** [comment]
@maelREBOUX: il me semble que tu utilises matomo sur le rendu bzh. Est-ce que c'est partageable avec gespot ?

**Comment by Cyrille37** [comment]
Hello

Sur la [page des serveurs](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France) il est bien annoncé un Matomo sur https://stats.openstreetmap.fr avec @MaelREBOUX en contact.

Qui a un compte pour ajouter des sites ?

**Comment by Cyrille37** [comment]
#564 J'ai invité @MaelReboux pour que les notifications fonctionnent

**Comment by MaelREBOUX** [comment]
Bonjour,

> @MaelREBOUX: il me semble que tu utilises matomo sur le rendu bzh. Est-ce que c'est partageable avec gespot ?

Alors nous pas du tout.
Il y a longtemps j'ai utilisé Matomo pour analyser les logs de "mon" tuileur mais ce n'est pas pertinent.
Plus de matomo sur le serveur depuis la migration il y a qqs mois.

Par contre, j'ai installé et configuré le Matomo sur https://stats.openstreetmap.fr/ 
Et je l'upgrade de temps à autre.

Donc, pour répondre à la question : il suffit de créer un nouveau "site" sur Matomo pour les 2 sites en question et de fournir le bout de javascript à intégrer qq part.

**Comment by flacombe** [comment]
Merci @MaelREBOUX pour la réponse.

Comment puis-je avoir un compte pour le faire s'il te plaît ?

**Comment by Cyrille37** [comment]
Hello la team

@MaelREBOUX Je veux bien un compte aussi, je pourrais ainsi aider avec un peu de "faire" :-)

Avec l'email **cgiquello arobase openstreetmap.fr** stp

**Comment by flacombe** [comment]
Bonjour

Une petite relance pour @MaelREBOUX afin d'obtenir les comptes s'il te plaît

**Comment by flacombe** [comment]
Bonjour tout le monde

Je relance à nouveau @MaelREBOUX 

C'est à dire qu'on en a vraiment besoin et nous avons déjà perdu 2 mois de stats, c'est dommage :(

**Comment by flacombe** [comment]
C'est réglé pour ma part, merci @jocelynj qui a pu me créer un compte aujourd'hui.

@Cyrille37 en plus du login/mail, il faut nous dire pour quel site web tu souhaites t'en servir parce que c'est créé en même temps

**Comment by Cyrille37** [comment]
Bonjour @flacombe 
Je proposai juste de partager le pouvoir :-) C'est à dire pouvoir créer des comptes, toucher les configs, donner un coup de main en fait. Je n'ai pas besoin de stats sur osm_fr.
