### ISSUE TITLE
Plus de géocodage inverse - osmose.openstreetmap.fr

### ISSUE THREAD

**Issue by pyrog** [osm-fr/infrastructure#563]
Console javascript  : `Unhandled Promise Rejection: Error: Unhandled error. (undefined)`

**Comment by frodrigo** [comment]
De quel site tu parles ?

**Comment by pyrog** [comment]
oups, [osmose.openstreetmap.fr](https://osmose.openstreetmap.fr)

**Comment by pyrog** [comment]
C'est retombé en marche 😄 

<img width="427" alt="Capture d’écran 2024-05-26 à 23 09 35" src="https://github.com/osm-fr/infrastructure/assets/2158081/2f72627b-67a3-4d67-8098-35c23fb25907">

**Comment by frodrigo** [comment]
C'est plus corrigé que tombé en marche.

**Comment by cquest** [comment]
Géocodage "normal", pas inverse (géo > adresse / description)
