### ISSUE TITLE
Ajout @MaelReboux dans team Infrastructure

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#564]
Comme @MaelReboux est listé sur la [page des serveurs](https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France) et pour qu'on puisse le poké/assigné dans les tickets :

![image](https://github.com/osm-fr/infrastructure/assets/368965/0899f27c-dca1-42b3-adf4-6602a9572d25)

**Comment by jocelynj** [comment]
Bonne idée !

Son invitation est marqué en "Awaiting MaelREBOUX’s response" -> tu l'as déjà demandé ?

De ton côté, est-ce que tu as déjà des droits, et sinon, en veux-tu ?

**Comment by Cyrille37** [comment]
Je n'est pas contacté Mael (_que je ne connais pas_), me disant que l'invitation envoyée par github faisait le job ;-)

Et pour ma pomme, je peux gérer les tickets, c'est très bien :-)

**Comment by jocelynj** [comment]
Je ne trouvais pas non plus dans la liste, c'est pour ça que je demandais :) 

Mais tu es en fait dans les admins de l'organisation osm-fr ici: https://github.com/orgs/osm-fr/teams

**Comment by MaelREBOUX** [comment]
C'est bon : je suis là ;)
