### ISSUE TITLE
redirection HTTP 301 discourse vers forum

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#566]
Remplacer http et https discourse.openstreetmap.fr par un HTTP 301 vers https://forum.openstreetmap.fr/

**Comment by jocelynj** [comment]
Tu veux dire, une redirection plutôt que l'URL marche telle quelle ?

**Comment by Cyrille37** [comment]
Juste simplifier la compréhension et **être sûr d'être au bon endroit**.
- soit supprimer discourse.osm.fr
- soit faire une redirection 301 vers forum.osm.fr

**Comment by jocelynj** [comment]
Si je me suis pas planté, la redirection discourse -> forum est active. Est-ce que tu pourrais vérifier de ton côté ?

**Comment by Cyrille37** [comment]
Bonjour @jocelynj 
C'est parfait, https://discourse.openstreetmap.fr/ -> https://forum.openstreetmap.fr/
