### ISSUE TITLE
ajouté @vinber à l'organisation "osm-fr"

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#567]
Pour faciliter les notifications j'ai ajouté @vinber dans l'organisation `osm-fr`.
Invitation en attente.

cf. #551

**Comment by Cyrille37** [comment]
Bizare, @vinber est déjà dans "outside collaborator" et pourtant il n'y a pas completion du pseudo dans les commentaires ... On varra bien ...

**Comment by vinber** [comment]
quelle promotion :) merci @Cyrille37

**Comment by vinber** [comment]
j'aurais bien fermé l'issue mais j'ai pas le droit :)

**Comment by vinber** [comment]
je peux :)

**Comment by vinber** [comment]
merci @Cyrille37

**Comment by Cyrille37** [comment]
Je découvre la gestion des droits sur Github, c'est carrément plus complexe qu'avec gitlab :-)
Tu as donc accès avec les droits de "triage".

Mais je ne comprends toujours pas bien le fonctionnement de tout ça :-(

**Comment by vinber** [comment]
oui je ne comprends pas toujours tout non plus, chouette ce que tu fais sur le triage et les relances justement !
