### ISSUE TITLE
ajout de ROC / Taiwan

### ISSUE THREAD

**Issue by althio** [osm-fr/infrastructure#57]
Bonjour,

Nous avons reçu une demande pour ajouter Taiwan (ROC, Taipei) sur download.openstreetmap.fr

[relation/449220](https://www.openstreetmap.org/relation/449220)

**Comment by jocelynj** [comment]
Taiwan est déjà dispo chez Geofabrik: http://download.geofabrik.de/asia/taiwan.html

À moins d'avoir besoin de diff minutes, je ne vois pas l'intérêt de rajouter Taiwan sur download.openstreetmap.fr.

**Comment by ThomasG77** [comment]
@althio Suite au retour de @jocelynj, besoin de diff minutes ou on ferme cette demande?

**Comment by Supaplextw** [comment]
Hi 
I'm the one who report a the issue. Sorry I could not speak French.
Geofabrik service will meet my need.
Could close the issue.
