### ISSUE TITLE
Le serveur de tuile de BANO donne une erreur 502 permanente.

### ISSUE THREAD

**Issue by Rpnpif** [osm-fr/infrastructure#571]
Exemple : https://b.layers.openstreetmap.fr/bano/12/2034/1427.png
renvoie 502 Bad Gateway nginx/1.25.4

Sous JOSM, les demandes tournent en boucle donnant un CPU à 100 % d'activité.

**Comment by vdct** [comment]
Le souci semble plus général que le calque BANO. Retour à la normale en cours cf https://forum.openstreetmap.fr/t/fond-de-carte-qui-ne-fonctionne-plus-au-zoom-erreur-502/24425/5

Par ailleurs concernant BANO ce fond n'est plus mis à jour actuellement. Pour une vue à jour, préférer la carte Pifomap dispo (par commune) ici : https://bano.openstreetmap.fr/pifometre/pifomap.html

**Comment by Rpnpif** [comment]
Merci beaucoup, Christian a bien relancé et ça marche bien. Je ne connaissais pas Pifomètre, je vais regarder. Dommage que le fond BANO ne soit plus mis à jour car il me semble plus pratique sous JOSM et je l'utilise souvent.

**Comment by vdct** [comment]
Oui la màj n'était plus maintenable au fil des évolutions internes de BANO. Le fond de Pifomap ressemble mais je suis d'accord ça ne remplace pas le fond raster, qui n'a pour l'instant pas de remplaçant dans JOSM

**Comment by Cyrille37** [comment]
Salut @Rpnpif 
Du coup, ce ticket peut-il être fermé ? Si oui, peux tu le fermer stp ?
