### ISSUE TITLE
Matomo : problème de droits en écriture dans un répertoire

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#575]
Bonjour,

Sur la machine qui héberge Matomo, j'ai l'erreur suivante :

> An exception has been thrown during the rendering of a template ("Unable to write in the cache directory (/data/www/vhosts/stats.osm.fr/htdocs/tmp/templates_c/e0).").
> in /data/www/vhosts/stats.osm.fr/htdocs/plugins/Live/templates/getVisitList.twig line 12

Il y a visiblement un soucis de droits, pouvez-vous regarder s'il vous plaît ?

**Comment by jocelynj** [comment]
C’est corrigé avec un `chown www-data` de tous les fichiers de ce dossier. Tu peux retenter ?

**Comment by flacombe** [comment]
Ca fonctionne à nouveau, merci @jocelynj !
