### ISSUE TITLE
Migration de petitereine.openstreetmap.fr sur cluster Moji

### ISSUE THREAD

**Issue by jocelynj** [osm-fr/infrastructure#577]
La VM hébergeant petitereine devra être déplacer d’OVH à Moji.

@Cyrille37 : est-ce que tu seras dispo un de ces jours au cas où ça ne redémarre pas correctement ?

Et est-ce qu’on devrait étendre ce site à la France entière, ou au moins à la région Centre-Val-de-Loire ?

**Comment by Cyrille37** [comment]
Bonjour @jocelynj 

Pas de soucis, tu peux la migrer, je serai dans le coin.

Pour faire évoluer faudrait que je regarde le code, c'est du vieux et pas moi qui l'ai écrit... Je regarderai après l'été.

**Comment by jocelynj** [comment]
Ça marche, je regarde pour migrer mercredi.

Pareil pour notes-heatmap.vm.openstreetmap.fr ?

**Comment by jocelynj** [comment]
Les deux sites ont été migré sur le cluster moji, sans aucun souci.

À noter que j’ai enlever osm157.openstreetmap.fr, remplacé par petitereine.vm.openstreetmap.fr.

**Comment by Cyrille37** [comment]
Merci @jocelynj 

J'arrive bien à me connecter en ssh sur petitereine.vm.openstreetmap.fr en passant par osm28.openstreetmap.fr.

Puis-je remettre en place le `cron` pour la mise à jour ou bien as-tu configuré un timer systemd ?

**Comment by jocelynj** [comment]
Il faudra faire gaffe que osm28 disparaitra à terme. Tu n’as pas de connection ipv6 de ton côté ? Sinon, je peux t’ajouter un compte sur une machine rebond sur le cluster Moji.

**Comment by Cyrille37** [comment]
Bonjour @jocelynj 
Je veux bien un rebond sur le cluster Moji car je n'ai pas d'IPv6 sur tous mes lieux de connexions. Merci :-)
