### ISSUE TITLE
mise à jour de Peertube en 6.2.0

### ISSUE THREAD

**Issue by bristow** [osm-fr/infrastructure#578]
Bonjour la team !

Actuellement, Thomas envoie les vidéos du sotm et on nous demande de faire le sous-titrage avec scribe.cemea.org qui est pas mal mais qui demande beaucoup de modifications.

J'ai fait une rapide étude que je vous mets là : 
https://forum.openstreetmap.fr/t/sous-titrage-et-chapitrage-des-videos-sotmfr/25121/21?u=bristow

Avec la 6.2 RC, le sous-titrage serait automatique et ce serait hyper rapide de corriger à la marge les sous-titres.

Est-ce envisageable cette migration ?

La release note : https://github.com/Chocobozzz/PeerTube/releases/tag/v6.2.0-rc.1

Merci la team 🙏🏻

**Comment by jocelynj** [comment]
Je préférerais éviter d’installer une RC sur une instance de production. Est-ce que tu sais dans quelle mesure les RC de peertube sont fiables ?

**Comment by bristow** [comment]
D'après le développeur de PeerTube, aucun bug majeur n'a été remonté.

Je me renseigne auprès de K-Prod pour savoir ce qu'il en pense.

**Comment by jocelynj** [comment]
@bristow : on annule cette mise à jour en attendant la prochaine version de Peertube ?

**Comment by bristow** [comment]
Oui mais ce n'est qu'une question de jours, voire heures 😉

**Comment by bristow** [comment]
Ah ah, je m'en doutais. Peertube vient de passer en stable
https://github.com/Chocobozzz/PeerTube/releases/tag/v6.2.0

Vous pourrez migrer quand vous voudrez, merci !

**Comment by jocelynj** [comment]
@bristow : tu sais si les imports des vidéos et des sous-titres sont terminés pour le sotm 2024 ?

**Comment by bristow** [comment]
Thomas me dit cela 

> Il me manque encore quelques média mais cela risque d'être très long si on attend. Les sous-titrages on tous été fait également.

> Donc oui vous pouvez passer en 6.2

Donc, si tu te poses la question de la migration, on peut ☺️

Merci 🙏

**Comment by jocelynj** [comment]
J'ai mis à jour en version 6.2.1, et activé la transcription automatique. Par contre, je ne sais pas exactement comment cette transcription marche, et si il faut la lancer à la main sur les vidéos déjà envoyées.
