### ISSUE TITLE
Nextcloud ne semble pas se synchroniser

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#58]
et pas d'accès par le web https://nextcloud.openstreetmap.fr

**Comment by jocelynj** [comment]
Je n'ai pass de souci à me connecter sur https://nextcloud.openstreetmap.fr/index.php/login

Pour la synchro, je n'utilise pas ça, du coup, je ne peux pas tester :(

**Comment by vinber** [comment]
oui cela semble fonctionner pour moi aussi, désolé du bruit !

**Comment by vinber** [comment]
je n'ose plus écrire :) mais j'ai 
- du mal à ce que la synchro se fasse sur mon ordi en utilisant le logiciel desktop (cea marche bien pour trois autres serveurs nextcloud avec lesquelles je synchronise des dossiers),
- cela semble fonctionner du coté du service web jusqu'à la fenêtre d'identification, puis cela rame

**Comment by vinber** [comment]
cela semble marcher

**Comment by vinber** [comment]
Je réouvre ! cela patine ce matin

**Comment by vinber** [comment]
en fait cela semble surtout être trés long (quelques dizaine de secondes pour affichage)

**Comment by vinber** [comment]
Bonjour,
cela ne fonctionne pas, je suis désolé de faire le rabat-joie (je suis le seul à me servir de nextcloud ?).
Que cela soit à distance ou sur le web, cela prend tellement de temps que je ne sais même pas si cela fonctionne au final :(

**Comment by Marc-marc-marc** [comment]
si tu l'utilise, c'est bien normal de signaler quand cela ne va pas :)
analyse express : 
- sdd @ sature en % d'utilisation, taux d'écriture élevé, latence élevée
- la vm swap in-out ce qui est évidement mauvais pour les perfs
- le hosteur osm28 swapout de manière conséquence, ce qui est souvent signe qu'on a trop de chose inutile qu'on pourrait tweater
- le débit utilisé par nextcloud est faible... nextcloud n'est donc sans doute pas la cause du problème mais un effet collatéral d'un problème ailleurs.
"il n'y a plus qu'à" corriger ce(s) problèmes, sans oublier qu'au passage, une maj en debian 9 ne serrait pas du luxe.

**Comment by vinber** [comment]
Bonjour,
je reviens sur ce point de lenteur de nextcloud.

Cela sert principalement (du moins pour moi) sur l'orga du sotm. Dans un moment (janvier, février), nous allons rentrer dans une phase de cette orga où avoir des documents communs à jour est très pratique.

a-t-on la possibilité que cela soit plus fluide ? par possibilité je ne parle pas matériel car je suppose que l'on a cette possibilité mais plutôt du coté humains et les disponibilités de temps. Aucune pression et dire non ne me choque pas !

à plus

**Comment by cquest** [comment]
Je viens de mettre à jour nextcloud et ses plugins.
Le stockage se fait aussi désormais sur le SSD et plus sur HDD, donc ça devrait être plus rapide...

**Comment by vinber** [comment]
mon utilisation de ce matin estfluide, je ferme :)
