### ISSUE TITLE
Erreur 502 sur bano.openstreetmap.fr

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/infrastructure#580]

**Comment by vinber** [comment]
@vdct

**Comment by vdct** [comment]
@vinber je n'ai ni les compétences ni les accès pour gérer la VM derrière BANO & Pifomètre, j'invoque @jocelynj ou @cquest 
merci

**Comment by Jean-BaptisteC** [comment]
Problème corrigé

**Comment by Jean-BaptisteC** [comment]
Problème de nouveau présent ce jour

**Comment by vdct** [comment]
Merci @Jean-BaptisteC 
La machine est inaccessible vu de moi, ni en direct, ni en rebond. Ping @jocelynj ou @cquest car je n'ai pas d'accès alternatif pour diagnostiquer

**Comment by Jean-BaptisteC** [comment]
Le problème est corrigé

**Comment by Jean-BaptisteC** [comment]
Problème de nouveau présent ce jour

**Comment by Jean-BaptisteC** [comment]
De nouveau disponible
