### ISSUE TITLE
Plusieurs couches TMS ne répondent plus

### ISSUE THREAD

**Issue by pyrog** [osm-fr/infrastructure#581]
https://a.tile.openstreetmap.fr/volta/20/543694/373633.png
https://c.tile.openstreetmap.fr/bdtopo/19/271851/186813.png
https://wms.openstreetmap.fr/tms/1.0.0/bdparcellaire_histo/19/271850/186813
https://wms.openstreetmap.fr/tms/1.0.0/orthohr_2020/19/271851/186813
https://wms.openstreetmap.fr/tms/1.0.0/orthohr/19/271852/186812

https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/19/271851/186813.jpg
La page [enedis.openstreetmap.fr](https://enedis.openstreetmap.fr) affiche une erreur 302 avec Referrer Policy: strict-origin-when-cross-origin

**Comment by Jean-BaptisteC** [comment]
Les tuiles semblent fonctionner de nouveau

**Comment by cquest** [comment]
Ces flux TMS proviennent d'osm13... qui peut être parfois indisponible (vieille machine, dans ma cave, en attendant mieux).
