### ISSUE TITLE
Download - some extracts are not up-to-date

### ISSUE THREAD

**Issue by osm-ToniE** [osm-fr/infrastructure#582]
I'm trying to use europe.osm.pbf but this file is as of 2024-01-16 23:49 local server time

pyosmium-up-to-date fails, because state information is not available

See also: [Planet extracts from https://download.openstreetmap.fr/extracts/](https://community.openstreetmap.org/t/planet-extracts-from-https-download-openstreetmap-fr-extracts/116516/6) on the community.openstreetmap.org server

The use case has been described here: [PTNA: news for Public Transport Network Analysis at 122](https://community.openstreetmap.org/t/ptna-news-for-public-transport-network-analysis/8383/122) and here [PTNA: news for Public Transport Network Analysis at 124](https://community.openstreetmap.org/t/ptna-news-for-public-transport-network-analysis/8383/124)

**Comment by jocelynj** [comment]
You’re right, that it wasn’t correctly updated since January, and we have the same issue for north-america. I will remove these old extracts, and I would recommend to download Europe from Geofabrik.

**Comment by osm-ToniE** [comment]
Thanks, I'll try this.

[Jochen Topf suggest a different approach](https://community.openstreetmap.org/t/ptna-news-for-public-transport-network-analysis/8383/135) using planet file with massive filtering before splitting, ...
