### ISSUE TITLE
Ajout de cuivre.infos-reseaux.com

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#583]
Hello @jocelynj 

Je cherche à renvoyer cuivre.infos-reseaux.com vers la VM enedis:80, à l'image de gespot et map.infos-reseaux.com.
Les DNS sont déjà les bons. Aucun service ne tourne encore sur enedis, cela doit donc donner un 502.

Il me semblait qu'il y a un proxypass a mettre sur osm34 mais je ne trouve pas de nginx en route sur la VM.
Est-ce possible de l'ajouter au bon endroit s'il te plaît ?

Est-ce également possible de me créer un nouveau site sur le Matomo pour ça s'il te plaît ?
Je ne peux pas le faire non plus.

Bonne soirée

**Comment by jocelynj** [comment]
Est-ce que tu pourrais plutôt utiliser un CNAME proxy.th3.vm.openstreetmap.fr au lieu de spécifier les IPs pour tous ces domaines ? Ça nous permettra de changer plus facilement les IPs si nécessaire.

Je vais te rajouter cuivre.infos-reseaux.com sur ce proxy.

**Comment by flacombe** [comment]
Merci beaucoup !
En effet je vais mettre un CNAME (même si ce n'est pas conforme aux bonnes pratiques s'agissant de deux domaines différents)

**Comment by flacombe** [comment]
CNAME en place pour cuivre.infos-reseaux.com et map.infos-reseaux.com.
Impossible pour gespot.fr parce que c'est le domaine racine en revanche.

**Comment by jocelynj** [comment]
Je t'ai aussi ajouté le site sur matomo.

**Comment by flacombe** [comment]
Merci beaucoup @jocelynj !
