### ISSUE TITLE
tile.openstreetmap.fr/osmfr HTTP 502

### ISSUE THREAD

**Issue by StephGBFO** [osm-fr/infrastructure#584]
Bonjour,

Le service renvoyant les tiles en "tile.openstreetmap.fr/osmfr/" retourne une erreur 502 bad gateway.
exemple : https://a.tile.openstreetmap.fr/osmfr/12/2067/1425.png

Bonne journée :)

**Comment by StephGBFO** [comment]
Bonjour,
Les tiles sont bien revenus :) Un peu de lag par moment, mais plus d'erreurs.
Merci beaucoup et bonne journée.

**Comment by cquest** [comment]
Problème temporaire réglé.
