### ISSUE TITLE
Redirection https sur nos proxy

### ISSUE THREAD

**Issue by flacombe** [osm-fr/infrastructure#585]
Bonjour chers mainteneurs

Comme cela est de plus en plus le cas, l'authentification OAuth2 ne fonctionne que sur des sites https (c'est en tout cas ce qu'il se passe sur projetdumois).
Serait-ce possible d'opérer une redirection htttp => https sur les reverses proxy et sinon tous, au moins celui de osm34 / enedis s'il vous plaît ?

Pour ma part je suis ok pour les redirections suivantes :
* http://enedis.openstreetmap.fr => https://enedis.openstreetmap.fr
* http://map.infos-reseaux.com => https://map.infos-reseaux.com
* http://gespot.fr => https://gespot.fr
* http://cuivre.infos-reseaux.com => https://cuivre.infos-reseaux.com

Je laisse les autres compléter si ils ont le même besoin et je l'aurais volontiers fait directement sur les services concernés mais impossible étant déjà derrière le reverse proxy.

Bonne après-midi

**Comment by jocelynj** [comment]
Les redirections vers https sont actives pour tous les domaines liés à http://enedis.openstreetmap.fr.

**Comment by flacombe** [comment]
Et ca marche, merci @jocelynj
