### ISSUE TITLE
Ortho 2022 Anglet

### ISSUE THREAD

**Issue by Patchanka64** [osm-fr/infrastructure#588]
Bonjour 

Suite à cette discussion : https://forum.openstreetmap.fr/t/ortho-2022-anglet/27925

La ville d’Anglet a publié son orthophoto de juin 2022 en opendata : https://anglet-opendatapaysbasque.opendatasoft.com/explore/dataset/orthophoto-20220/information/?location=12,43.50835,-1.51903&basemap=jawg.light

Serait-il possible de l’avoir sur les serveurs d’OSM France pour la contribution via ID et JOSM (quand les travaux en cours sur l'infra OSM-Fr seront terminés).

Merci d'avance

**Comment by cquest** [comment]
Vu !

354 dalles de 256Mo cas sans aucune compression... donc dans les 86Go.
Je télécharge et recompresse tout ça en COG pour la mise en ligne.

**Comment by cquest** [comment]
Une dalle est corrompue... le fichier COG final fait 4Go :)

C'est ajouté sur la couche TMS "Tous FR" et dans la couche WMS anglet_2022
