### ISSUE TITLE
sympa sur osm101 qui pertube l'envoi vers osm138-liste

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#59]
@jocelynj  les headers de l'alerte monit non reçue par osm138-liste pour admin-notification@listes... montrent que osm101 t'as envoyé l'email en direct
il y a une copie de sympa sur osm101 :) sans doute un reste historique a virer ou dont le nom de domaine ne devrait pas/plus être listes

**Comment by jocelynj** [comment]
osm101 a été coupé, parce que plus utilisé maintenant. Il n'y a donc plus de problème :)
