### ISSUE TITLE
Pays manquants dans les réplications et extracts en Afrique

### ISSUE THREAD

**Issue by severinmenard** [osm-fr/infrastructure#590]
Il semble manquer a minima Maroc, Égypte et Madagascar dans https://download.openstreetmap.fr/replication/africa/ et http://download.openstreetmap.fr/extracts/africa/

**Comment by jocelynj** [comment]
Il n’y a effectivement pas tous les extracts sur ce site, pour éviter de dupliquer les extracts fournis sur http://download.geofabrik.de/. À moins que tu n’ais vraiment besoin de diff minutes au lieu de diffs journaliers ?

**Comment by severinmenard** [comment]
Mais sauf erreur de ma part, Geofabrik ne les fournit pas par pays, et justement je cherche à mettre à disposition via WFS/WMS les données OSM sur les pays francophones du Sud, Maroc et Madasgacar compris donc (Égypte non, par contre)

**Comment by severinmenard** [comment]
@jocelynj il manque aussi Haiti dans https://download.openstreetmap.fr/replication/central-america/

**Comment by jocelynj** [comment]
I’ve started the generation of diff files for all these countries.

I will generate the pbf files in a few days.

**Comment by jocelynj** [comment]
Les extraits sont maintenant dispos sur le site web.
