### ISSUE TITLE
connection au wordpress

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#593]
je n'arrive plus à me connecter au wordpress d'openstreetmap.fr

il me dit à ma première tentative You have exceeded maximum login retries Please try after 14 hour(s)

ce qui rend les essais un peu long à mener !

que puis-je faire ?

par ailleurs, le plugin Social Login ne fonctionne plus depuis longtemps, j'imagine que l'on peut le retirer ?

@nlehuby @jocelynj ?

**Comment by nlehuby** [comment]
idem ici : je n'arrive pas à me connecter non plus.

**Comment by jocelynj** [comment]
J’ai le même souci d’ici. Je vais regarder ce qu’il se passe sur la VM.

**Comment by jocelynj** [comment]
Ça remarche !

Lors de la migration d’OVH sur le cluster moji, j’avais oublié de mettre à jour la liste des IPs utilisé par le proxy. Du coup, wordpress voyait toutes les requêtes (y compris accés de bots sur la page d’admin) comme venant de la même IP. Maintenant, wordpress voit la bonne IP, et gère correctement le blocage par IP.

**Comment by jocelynj** [comment]
@vinber : tu confirmes que la connection au wordpress marche pour toi maintenant ?

**Comment by vinber** [comment]
Yep, désolé je n'avais pas retenté. Merci du ping
