### ISSUE TITLE
tile.openstreetmap.fr ne répond pas

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#595]
Bonjour

Le service [tile.openstreetmap.fr](https://tile.openstreetmap.fr/) ne répond plus :disappointed: 

Par contre on retrouve le service en tapant directement sur [a.tile.openstreetmap.fr](https://a.tile.openstreetmap.fr/).

**Comment by cquest** [comment]
Le service est de retour, déménagé d'osm12 (mort) à osm14.
