### ISSUE TITLE
download.openstreetmap.fr erreur documentation ?

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/infrastructure#597]
Hello

Sur le wiki https://wiki.openstreetmap.org/wiki/Planet.osm il est noté que download.openstreetmap.fr ne sert pas de `.osm.pbf` alors que si. Est-ce que je corrige le wiki ?

poke @cquest @jocelynj

**Comment by jocelynj** [comment]
Ça me semble correct: on n'a pas de .osm.pbf du planet complet, uniquement d'extraits.

**Comment by Cyrille37** [comment]
Ah! Merci @jocelynj :-)
J'avais mal compris la doc
