### ISSUE TITLE
plantage régulier osmose frontend

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#6]
plante régulièrement par saturation ram. plusieurs pistes : 
soupçon de surallocation mémoire dans la vn : 
- diminuer le nombre de thread apache (on est a max 19 sur la semaine) /etc/apache2/mods-enabled/mpm_worker.conf
- augmenter la ram attribuée à la vm (par exemple la moitié de ce qu'on peux récupérer sur l'ancien overpass api)
- diminuer MaxRequestWorkers à 1 ou 2 fois le nombre de coeur cpu

soupçon de fuite mémoire applicative : 
- diminuer MaxConnectionsPerChild à 100 voir moins.
- mettre un check&restart en cron

**Comment by jocelynj** [comment]
Configuration actuelle:
**/etc/apache2/mods-enabled/mpm_worker.conf**
```
        StartServers             2
        MinSpareThreads          10
        MaxSpareThreads          75
        ThreadLimit              64
        ThreadsPerChild          25
        MaxRequestWorkers        150
        MaxConnectionsPerChild   50
```

**/etc/apache2/sites-enabled/osmose.openstreetmap.fr.conf**
```
        WSGIDaemonProcess osmose processes=4 threads=5 
                          user=osmose group=osmose 
                          maximum-requests=1000 graceful-timeout=600
                          python-path=<path>
```

**Comment by Marc-marc-marc** [comment]
Pour mémoire, les modifs ont été faite il y a plusieurs mois : 
**/etc/apache2/mods-enabled/mpm_event.conf**
```
	StartServers		1
	MinSpareThreads		1
	MaxSpareThreads		7
	ThreadLimit		64
	ThreadsPerChild		8
	MaxRequestWorkers	40
	MaxConnectionsPerChild	100
	ServerLimit		40
```
et depuis plus de plantage
