### ISSUE TITLE
Osmose est down, beta et dev également

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#60]

**Comment by Marc-marc-marc** [comment]
osm153 accessible et fonctionnel
taux élevé de lock exclusif sur la db http://munin.openstreetmap.fr/munin-cgi/munin-cgi-graph/osm28.openstreetmap.fr/osm153.openstreetmap.fr/postgres_locks_ALL-day.png
j'ai redémarré postgres, osmose est à nouveau fonctionnel
@frodrigo me dit que cela se produit suivant mais j'ai pas trouvé trace d'un autre ticket récent.
je propose d'ajouter un test d'une page la plus légère possible pour être notifié lorsque le problème a lieu
PS. en passant kill de 17 sessions ssh mortes

**Comment by vinber** [comment]
cela fonctionne, merci

**Comment by vinber** [comment]
ah non !!!

**Comment by jocelynj** [comment]
D'après http://munin.openstreetmap.fr/osm28.openstreetmap.fr/osm153.openstreetmap.fr/index.html, les phases où apache n'est pas accessible est un peu corrélé avec l'autovacuum de postgresql. Je vais le désactiver pour voir ce que ça donne.

**Comment by frodrigo** [comment]
Moins de gens se plaignent, c'est peut être mieux maintenant, non ?

**Comment by Marc-marc-marc** [comment]
suite à la discussion avec @frodrigo 
ajout sur osm153:/etc/munin/plugin-conf.d/munin-node
```
[http_loadtime]
env.target http://osmose.openstreetmap.fr/fr/api/0.2/meta/tags
env.requisites false
```
+ ajout de la sonde http_loadtime avec `ln -s /usr/share/munin/plugins/http_loadtime /etc/munin/plugins/`

résultat à venir sur http://munin.openstreetmap.fr/osm28.openstreetmap.fr/osm153.openstreetmap.fr/http_loadtime.html

**Comment by frodrigo** [comment]
Ça tourne maintement plutôt bien, apres les deux grosse mise à jour.
On peut clore.

**Comment by vinber** [comment]
donc je ferme !
