### ISSUE TITLE
accès bd ortho depuis https://cadastre.openstreetmap.fr/segmented/

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#61]
signalé par baptistemm sur irc
surement du au manque de token dans l'url. token à rajouter ou referer a whitelister

**Comment by bmillemathias** [comment]
opened on my side earlier https://github.com/osm-fr/export-cadastre/issues/30

**Comment by jocelynj** [comment]
J'ai activé le referer sur proxy-ign, mais on doit avoir un autre souci parce que ça ne marche toujours pas - peut-être un souci http/https.

**Comment by jocelynj** [comment]
C'est corrigé en changeant le site https://cadastre.openstreetmap.fr/segmented/ pour utiliser https sur proxy-ign.

**Comment by ThomasG77** [comment]
En regardant OpenSolarMap (aussi dans les sites "whitelistés"), je vois que les appels font comme si chaque projet whitelisté passait sa propre clé d'API en ne passant pas par la clé du proxy indiqué côté NGinx.

En effet, sur:

* [OpenSolarMap](https://opensolarmap.org/#19/43.41472/5.02532) `https://proxy-ign.openstreetmap.fr/0p3n50l4rm4p/bdortho/19/269464/191818.jpg`
* [OpenStreetMap](https://www.openstreetmap.org/edit#map=17/47.21558/-1.55163) https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/17/64968/45987.jpg

@cquest Tu peux confirmé/infirmé ou demander à celui qui a les clés de "l'étable IGN" (Attention, une migration côté Geoportail peut affecter la résolution à court terme du problème http://professionnels.ign.fr/migration-geoportail)
