### ISSUE TITLE
Bloquer l'acces à Osmose au bot "Mozilla/5.0 (compatible; adscanner/)"

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#62]
Le user agent "Mozilla/5.0 (compatible; adscanner/)" ne respecte pas le robots.txt il demande des ressources longues à servir (liste de toutes signalements, graphe d'historique)

**Comment by Marc-marc-marc** [comment]
je n'ai pas trouvé de test HTTP_USER_AGENT sur osm153
ils sont sur le reverse proxy ou on les a perdu lors de la migration ?

**Comment by jocelynj** [comment]
J'ai modifié la config apache pour interdire les accès de ce user-agent:
```
        RewriteCond %{HTTP_USER_AGENT} "Mozilla/5\.0 \(compatible; adscanner\)" [nocase]
        RewriteRule ^.*$ - [forbidden,last]
```
