### ISSUE TITLE
Produire les extracts pour la Russie

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/infrastructure#63]
Ajouter à http://download.openstreetmap.fr/ les extracts de la Russie suivant le découpage officiel.
La Russie n'est plus mise à jour dans Osmose par manque d'extract.
https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L1154

**Comment by ThomasG77** [comment]
Je cherche Russia dans http://download.openstreetmap.fr/extracts/ et https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L1239
A fermer?
