### ISSUE TITLE
rebond ipv4<>ipv6 pour ybon sur osm28

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#64]
ybon avait besoin de faire un rebond ipv4 sur osm28 pour accéder à umap
je lui ai crée un compte à la main sur osm28
j'ouvre ce ticket ci pour reporter l'info dans la conf ansible :)

**Comment by jocelynj** [comment]
Merci, c'est ajouté sur https://github.com/osm-fr/ansible-scripts/commit/3b6207b293355cdb42ba58126c3204f4abae9313
