### ISSUE TITLE
lien xapi josm dans taginfo

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#65]
le lien josm dans taginfo ne fonctionne pas car il pointe vers https://localhost:8112/import?url=http%3A%2F%2Foapi-fr.openstreetmap.fr%2Fxapi
à voir si on peux convertir cela en overpass standard ou si on le supprime purement et simplement

**Comment by jocelynj** [comment]
Quelle url doit-on mettre à la place ?

**Comment by Marc-marc-marc** [comment]
le lien fonctionne mais cible le monde au lieu de la France #145

**Comment by Cyrille37** [comment]
il n'y a plus de `taginfo` sur openstreetmap.fr
