### ISSUE TITLE
http://live.openstreetmap.fr/ is down ?

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#66]
http://live.openstreetmap.fr/

**Comment by vinber** [comment]
effectivement, ce n'était pas clair, désolé.
le site est accessible mais rien ne s'affiche.
Ni le temps, ni le nombre d'éditions, ni le nombre d'utilisateurs ne changent.

**Comment by vinber** [comment]
cela semble fonctionner merci.
Je ferme !

**Comment by vinber** [comment]
Je réouvre, car cela "semble la même chose", cela ne se met pas à jour.
Signalé par @Cyrille37 sur framateam

**Comment by Marc-marc-marc** [comment]
le problème a-t-il entre-temps été résolu ? je ne vois pas d'anomalie particulière pour ma part.

**Comment by Cyrille37** [comment]
Ce matin ça fonctionne. Je n'ai pas testé hier. Samedi après-midi il n'y avait pas actualisation des données ou alors aucune activité sur osm, mais les autres outils remontaient de l'activité (http://osmlab.github.io/show-me-the-way/).

**Comment by vinber** [comment]
yep, cela fonctionne pour moi aussi, alors que samedi idem. hier je ne sais pas ! Je ferme
