### ISSUE TITLE
osm210 osmose-backend non documentée et sature io

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#69]
a faire :)
- rajouter dans la liste des serveurs
- rendre ses io légèrement non-prioritaire par rapport au reste ou la limiter à <100%
- ajuster le timeout sshd session morte
- problème atop au restart par cron

**Comment by Marc-marc-marc** [comment]
@frodrigo on peux faire quelque chose applicatif pour réduire les écritures sans trop dégrader les perfs ? c'est postgres qui bombarde :) si c'est des tables temporaires, on pourrait peut-être voir pour en faire tenir + en ram
sinon je pense tester un ionice pour voir si cela améliore #58

**Comment by frodrigo** [comment]
Il y a un des backends osmose non généré par osm-fr qui utilise un tmpfs (comme volume dans un docker) pour la base postgis.
C'est l'import initial qui fait des écritures, le reste c'est de la lecture et déjà des tables temporaires.

**Comment by cquest** [comment]
Au moins deux pistes:
- réduire les IO (tempfs et ramdisk sont une option)
- baisser la priorité de ces io

Pour la première je pense qu'on va vite saturer en RAM

Pour la seconde, c'est faisable via les cgroups utilisés par LXC, mais ce n'est pas directement accessible via la GUI de proxmox.

**Comment by frodrigo** [comment]
Le backend Osmose osm210 n’exécute plus de taches de puis le 6 décembre.
http://buildbot.osmose.openstreetmap.fr/buildslaves/osm210

Le 03/01/2019 à 09:35, Christian Quest a écrit :

**Comment by jocelynj** [comment]
À terme, le but est de réserver le cluster ovh aux taches non gourmandes en cpu, ou qui sont des services "externes". Les services gourmands seront plutôt sur des machines puissantes, pour éviter ces services plus critiques.

osm208, osm209 et osm210, qui sont sur le cluster OVH, sont donc à virer, ou au minimum à ne faire tourner que la nuit.

**Comment by jocelynj** [comment]
Les backends osmose du cluster OVH ont été désactivée, grâce au prêt de serveurs par PauLLA pour faire tourner des backends.
