### ISSUE TITLE
migrer les vm osm11/12 sur osm26/27/28

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#7]
tache a probablement diviser en sous-tache : 
- créer un rôle ansible pour chacune des vm
- la partie migration en elle-même entre les anciennes vm et les nouvelles (en même temps que le passage sur les nouvelles vm ou migrer indépendamment les vm si c'est portable entre openvz et proxmox)

**Comment by jocelynj** [comment]
Ce qui reste à faire:
* osm101
  * [ ] galette
  * [ ] monit - à remplacer par status.openstreetmap.fr ?
* osm102
  * [ ] umap
  * [ ] nomino
* osm103
  * [ ] api.openstreetmap.fr - on le supprime définitivement ?
  * [ ] overpass API - en cours de migration sur osm147/osm148
* osm109
  * [ ] backup - on a un backup sur osm134, mais ça serait mieux d'avoir deux backups séparés sur deux sites différents.
* osm117
  * [ ] osmose frontend

**Comment by Marc-marc-marc** [comment]
pour ex- api.openstreetmap.fr : à voir si on veux migrer l'analyseur de relation basé sur overpass qui existait ou si on le drop vu que personne n'a dit le moindre mot pendant ces très nombreux mois de coupure

**Comment by jocelynj** [comment]
Vu que personne n'a l'air d'en avoir besoin, autant supprimer api.openstreetmap.fr

**Comment by Marc-marc-marc** [comment]
J'ai édité https://github.com/osm-fr/infrastructure/issues/7#issuecomment-342306212

**Comment by Marc-marc-marc** [comment]
pour analyser, c'est sur quelle page que tu as vu le hors service ?
il y a avait une typo sur la page des serveurs.
il semble en plus y avoir un bug https://github.com/osm-fr/relation-analyser/issues/1
mais pour 50Mo, ne nous embêtons pas et embarquons le avec garmin pour voir cela + tard, non ?

**Comment by cquest** [comment]
osm101 a été migrée sur osm12...

Au tour des suivantes... osm102 et osm103

**Comment by jocelynj** [comment]
Super !

Tu as migré le DNS aussi du coup ?

Je vais de mon côté juste préparer un role ansible pour installer nomino/analyser, ce qui clarifiera les choses.

**Comment by cquest** [comment]
osm102 et osm103 sont maintenant aussi sur osm12 et "UP"... ne reste plus qu'osm109 (backuppc)

**Comment by cquest** [comment]
Planning de suite:
- [ ] mise à niveau hard d'osm11 et passage à proxmox5
- [ ] test de migration des petites VM d'openvz vers proxmox5 (à faire chez moi)

puis

- [ ] migration des VM d'osm12 sur osm11 remis à neuf

osm109 (backuppc) et osm104 (imagery+bano) sont très grosses... migrations délicate et à ne faire qu'en local sur les serveurs free.

**Comment by jocelynj** [comment]
osm11 a été mis à jour, et est maintenant utilisé.

Je propose de fermer ce ticket, et d'en ré-ouvrir un pour gérer osm12.

**Comment by Marc-marc-marc** [comment]
je n'ai pas d'avis sur 1 ticket <> 2 tickets, mais il reste aussi à faire 
 * [ ]  maj de la doc du wiki, entre autre pour les nouvelles vm d'osm11

**Comment by jocelynj** [comment]
Les VMs sont normalement listés dans le tableau de https://wiki.openstreetmap.org/wiki/FR:Serveurs_OpenStreetMap_France#VMs (ça serait d'ailleurs bien de pouvoir trier la liste par défaut par Host)

**Comment by frodrigo** [comment]
On peut fermer ?

**Comment by Marc-marc-marc** [comment]
il reste osm103 osm104 osm105 osm108 osm124 à migrer

**Comment by cquest** [comment]
Test de migration d'osm103 qui est sur osm12 en openvz sous centos6.
Le grand saut openvz/centos6 vers proxmox6 ne passe pas en direct.
J'ai donc tenté un saut intermédiaire par proxmox3 (j'ai ça dans un VM sur mon proxmox6 à la maison).
C'est bon, le restore se passe normalement, je refais un backup depuis proxmox3 en espérant que proxmox6 l'accepte.

Migrer osm103 n'a pas d'intérêt en soit vu qu'il n'y a qu'un bête apache qui tourne dessus, c'est juste pour test le chemin d'upgrade pour osm104/105/108.

**Comment by cquest** [comment]
Bon... le restore proxmox3 sur proxmox6 ça le fait pô :(
Un proxmox4 alors ?
