### ISSUE TITLE
certif https osm2pgsql-monde.openstreetmap.fr

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#72]
il serrait utile pour récupérer en https 
https://osm2pgsql-monde.openstreetmap.fr/~osm2pgsql/state.txt
utilisé par ex depuis https://layers.openstreetmap.fr/

**Comment by jocelynj** [comment]
C'est fait, même si je ne suis pas sûr que cette URL soit utilisée :)
