### ISSUE TITLE
monit backuppc

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#77]
ajouter surveillance backuppc dans monit osm109 et osm134

**Comment by jocelynj** [comment]
Merci pour l'information, c'est effectivement une bonne idée. Je l'ajouterais sous peu.

**Comment by psampont** [comment]
"Sous peu", effectivement, j'ai même pas eu le temps de préparer mon P.R. ;)
Ben tant pis, je me pencherai sur un autre problème après Noël.

Bonne fête à tous.

**Comment by jocelynj** [comment]
En fait, backuppc ne tournait pas sur osm134, et je l'ai démarré à la main.
Du coup, on aurait besoin d'une surveillance via monit, qui aurait aussi l'avantage de redémarrer backuppc automatiquement. @psampont: tu veux regarder ça ?

**Comment by psampont** [comment]
Je ne connais pas monit mais ça m’intéresse.

**Comment by jocelynj** [comment]
Monit et Munin a été configuré pour backuppc.
