### ISSUE TITLE
Clé d'accès API Geoportail plus valide dans uMap

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/infrastructure#78]
Problème signalé sur le forum osm-fr : https://forum.openstreetmap.fr/viewtopic.php?f=3&t=6974

À première vue, la clé API Geoportail pour l'accès à l'ortho IGN dans uMap n'a peut-être pas été renouvelée.

`<ExceptionReport><Exception exceptionCode="MissingParameter">Key does not exist or has expired</Exception></ExceptionReport>`

![image](https://user-images.githubusercontent.com/677071/49139569-74c6e780-f2f2-11e8-93ec-1895986ecec8.png)

**Comment by ThomasG77** [comment]
A fermer. La clé marche à nouveau ou a été remplacée (je constate mais je ne suis poas intervenu). 
A tester de votre côté sur https://umap.openstreetmap.fr pour confirmer
Capture d'écran de ce jour à l'appui.

![selection_907](https://user-images.githubusercontent.com/642120/50227389-ebad4880-03a5-11e9-8b35-2eedb3a80997.png)

**Comment by cquest** [comment]
La clé a été mise à jour
