### ISSUE TITLE
osm25 oom tous les samedis pendant la nuit

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#80]
[nov. 3 02:03] renderd invoked oom-killer
[nov.10 02:03] renderd invoked oom-killer
[nov.17 03:11] apache2 invoked oom-killer
[nov.24 02:03] renderd invoked oom-killer
[déc. 1 02:04] renderd invoked oom-killer

**Comment by cquest** [comment]
C'est le cron qui lance la recalcul des tuiles des premiers niveaux de zoom... je regarde ça

**Comment by cquest** [comment]
Pas d'oom ce samedi... c'était bien ça, je ferme.
