### ISSUE TITLE
wms.openstreetmap.fr : couches à corriger

### ISSUE THREAD

**Issue by cquest** [osm-fr/infrastructure#83]
Certaines orthos ne fonctionnent plus correctement en WMS:

- [x] Auvergne Craig 2013 : config proxy ?
- [x] Auvergne Craig 2009 : config proxy ?
- [x] CG93 2013 : config proxy ?
- [x] ortholittorale 2002
- [x] ortholittorale v2 (2011-2014) : données récupérées
- [ ] La Rochelle 2013 : config proxy ?
- [ ] La Rochelle 2007 : config proxy ?
- [x] Nancy 2002 : données manquantes
- [x] Nancy 2005 : données manquantes
- [x] Nancy 2008 : données manquantes
- [x] PACA 06 - 2009 : données manquantes
- [x] PACA 13 - 2009 : données manquantes
- [x] PPIGE Nord-Pas de Calais 2013 : 404 sur WMS distant
- [x] Toulouse 2011
- [x] Toulouse 2013
- [x] Toulouse 2015
- [x] Toulouse 2017

**Comment by cquest** [comment]
Toulouse 2017 de retour :)

**Comment by don-vip** [comment]
Pour les autres couches de Toulouse tu peux trouver le WMS [ici ](https://wms.plan.toulouse.fr/geocache/wms?VERSION=1.1.1&SERVICE=WMS&REQUEST=GetCapabilities) et les tuiles brutes ici:
- [2015](https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2015/information/)
- [2013](https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2013/information/)
- [2011](https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2011/information/)
- [2007](https://data.toulouse-metropole.fr/explore/dataset/orthophotoplan-2007/information/)

Attention l'ortho 2010 n'est pas sous licence libre car la ville n'en possède pas les droits ! (sic).

Tu peux aussi jeter un coup d’œil à la [page JOSM](https://josm.openstreetmap.de/wiki/Maps/France) qui est à jour (toutes les URLs listées là-bas fonctionnent, on a un test automatique qui vérifie toutes les 6h).

**Comment by cquest** [comment]
Ajouts sur Nancy:
- 1994 (40cm)
- 1999 (50cm)
- 2001 (25cm)
- 2002 (25cm noir et blanc)
- 2005 (15cm)

**Comment by cquest** [comment]
l'Ortho Littorale de 2002 est de retour :)

**Comment by cquest** [comment]
Toulouse: 2011, 2013, 2015 désormais disponibles.

**Comment by cquest** [comment]
Impossible de trouver le service WMS actuel de La Rochelle, tout les reste est à nouveau OK.
