### ISSUE TITLE
Umap est en mode 502

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#88]
de manière assez aléatoire, j'arrive à la page d'accueil, parfois 502.
L'accès à une page utilisateur http://umap.openstreetmap.fr/fr/user/vinber/ ne marche jamais.

**Comment by Marc-marc-marc** [comment]
load average: 56.55, 54.36, 50.47 (en français : ultra chargé)
en cours d'investigation (mais c'est tellement lent qu’investiguer est lent)

**Comment by Marc-marc-marc** [comment]
monit+nginx coupé une minute, pas de changement de charge visible

**Comment by Marc-marc-marc** [comment]
nginx coupé pendant 10 min sans effet.

trouvé 2 causes :

- 24 rsync qui se margent dessus... cquest va etre content et va pouvoir promouvoir zfs :) de manière moins frontale, suffit de mettre un semaphore pour s'exécuter qu'une fois au max

- non configuration d'une valeur raisonnable aux nombre de connexion simultanée dans nginx qui fait que si le serveur ralenti, on finit par avoir de + en + de connexions simultanées ce qui ralenti de plus en plus le serveur

**Comment by cquest** [comment]
En attendant, j'ai basculé le rsync en daily et oui, il faut passer à la réplication ZFS et le dégager ;)

**Comment by Marc-marc-marc** [comment]
à rajouter aussi : une alerte via monit si le temps de chargement de la page est déraisonnable

**Comment by vinber** [comment]
bonjour,
merci cela marche, je ferme et j'ai ouvert 2 issues, c'est comme cela ?

**Comment by jocelynj** [comment]
Yep, merci pour avoir ouvert les tickets.
