### ISSUE TITLE
Umap / passer à la réplication ZFS

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#90]
_Originally posted by @cquest in https://github.com/osm-fr/infrastructure/issues/88#issuecomment-453592692_

**Comment by jocelynj** [comment]
@yohanboniface, @cquest. Normalement tout est en place côté infra. la seule chose manquante est de quoi passer umap en read-only, pour pouvoir migrer sur osm159 après rsync final.

osm159 est déjà en réplication zfs de osm28 vers osm27

**Comment by jocelynj** [comment]
Doublon avec #86.
