### ISSUE TITLE
ajouter sotm2019.openstreetmap.fr dans le certificat

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#91]
Quand on veut aller sur https://sotm2019.openstreetmap.fr, on obtiend que : 

sotm2019.openstreetmap.fr utilise un certificat de sécurité invalide.

Le certificat n’est valide que pour les noms suivants : api-pic4carto.openstreetmap.fr, api.openstreetmap.fr, backup.umap.openstreetmap.fr, bato.openstreetmap.fr, beta.osmose.openstreetmap.fr, dev.forum.openstreetmap.fr, dev.taginfo.openstreetmap.fr, dev.tile.openstreetmap.ma, dev.umap.openstreetmap.fr, forum.openstreetmap.fr, fr.osm.social, josm-dev.openstreetmap.fr, layers.openstreetmap.fr, live.openstreetmap.fr, maposmatic.openstreetmap.fr, monitor.openstreetmap.fr, munin.openstreetmap.fr, next.openstreetmap.fr, nextcloud.openstreetmap.fr, opendata.osmose.openstreetmap.fr, openstreetmap.fr, osmma.openstreetmap.fr, osmose.openstreetmap.fr, overpass.openstreetmap.fr, peertube.openstreetmap.fr, petitereine.openstreetmap.fr, prev.openstreetmap.fr, sotm2018.openstreetmap.fr, taginfo.openstreetmap.fr, tile.openstreetmap.ma, umap.openstreetmap.fr, www.openstreetmap.fr

**Comment by jocelynj** [comment]
Effectivement, je ne l'ai pas ajouté. Je viens de lancer les rôles ansibles proxycache et letsencrypt pour mettre à jour

**Comment by jocelynj** [comment]
C'est corrigé, merci.
