### ISSUE TITLE
forum : passer en https

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/infrastructure#92]
redirect http -> https

**Comment by Cormoran96** [comment]
Je veux bien prendre l'issue. J'ai du temps. Par contre juste mettre ma clé ssh sur osm27

**Comment by jocelynj** [comment]
Pourquoi osm27, et pas osm139 ?

**Comment by jocelynj** [comment]
Et pour info, la config apache est dans ansible, sur https://github.com/osm-fr/ansible-scripts/blob/master/roles/phpbb/files/apache.site

**Comment by Cormoran96** [comment]
Heu oui je voulais dire osm139. ça marche je modifie la conf sur le github

**Comment by jocelynj** [comment]
@Cormoran96: Est-ce que tu as pu avancer sur le sujet ?

**Comment by jocelynj** [comment]
Le forum est maintenant redirigé en https, via https://github.com/osm-fr/ansible-scripts/commit/6f01b9961533aa98e33cee3e8f60bfa6acde3eea
