### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by vinber** [osm-fr/infrastructure#97]
Peut-on faire une redirection de soutien@openstreetmap.fr sur soutien@listes.openstreetmap.fr ?

C'est plus joli !!!

et je crois que des soutien@openstreetmap.fr ont été diffusés dans la nature !

Par avance merci :)

**Comment by jocelynj** [comment]
La redirection est ajoutée - est-ce que tu peux tester que ça marche correctement ?

**Comment by vinber** [comment]
tu es parfait :) merci, test parfaitement réussi !!! Si vous lisez ceci et que vous voulez soutenir le sptm-fr, vous pouvez donc écrire à soutien@openstreetmap.fr !
