### ISSUE TITLE
Plus de munin pour VM bzh202

### ISSUE THREAD

**Issue by MaelREBOUX** [osm-fr/infrastructure#98]
Tout est dans le titre.

Avant il y avait cette url :http://munin.openstreetmap.fr/osm25.openstreetmap.fr/bzh202.osm25/index.html

Je constate que pour osm25 c'est devenu : http://munin.openstreetmap.fr/openstreetmap.fr/osm25.openstreetmap.fr/

Mais du coup : je ne retrouve pas la VM bzh202.

**Comment by jocelynj** [comment]
C'est revenu sur http://munin.openstreetmap.fr/osm25.openstreetmap.fr/bzh202.osm25/index.html

En fait, bzh202 est configuré à la main dans munin, et j'avais regénéré le fichier complet. Il faudrait que je trouve un bon moyen de le configurer...

**Comment by MaelREBOUX** [comment]
Merci @jocelynj 

De mon côté faut que je termine la mise en place de monit. S'il avait été fini de configurer j'aurais reçu une alerte pour l'espace disque…

**Comment by MaelREBOUX** [comment]
Du coup il y a une interruption depuis mi-janvier.

Mais on voit bien une sacré augmentation de trafic. Cool.

![Capture d’écran 2019-03-18 à 08 05 45](https://user-images.githubusercontent.com/6370443/54512490-ab357a80-4954-11e9-9fa1-29dc4d204bf5.png)
